### ISSUE TITLE
We should not be asking for "First name" and "Last name"

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#1110]
We are using django.contrib.auth which asks for "First name" and "Last name" which is bad and unfortunately not that easy to solve. The best place to track this issue upstream seems to be here:
http://code.djangoproject.com/ticket/5638

We might want to look into workarounds to fix this, since it really makes us look bad.

I'm putting in the 1.3 milestone while being hopeful. Let's see what we can do about this one.

**Comment by unho** [comment]
This is gone in new master since we only have now "Full name". See https://github.com/translate/pootle/blob/ba74f868/pootle/models/user.py#L78.
