### ISSUE TITLE
Review correct use of E-tag

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#1244]
Ideally we should serve our exported translations files with the correct E-tag. This way tools like Virtaal or crawlers of open-tran would be able to avoid downloading files entirely. We might already be doing the right thing. We might want to do this for ZIP files as well. Any other pages/files?

**Comment by dwaynebailey** [comment]
Downloads of ZIPs and files is now behind the Download button unlike previous Pootle versions.  Closing this, we can address any such info at a later date if it is still relevant.
