### ISSUE TITLE
Add support for validating translations (syntax checks)

### ISSUE THREAD

**Issue by sayamindu** [translate/pootle#1326]
*Version: 2.0.x*

One of the main problems for developers is that often translators commit PO files with syntax errors (not all translation team does rigorous checking with the built in Pootle checks).

It may make sense to have some form of validation being done when an unit is updated, something in the lines of http://people.sugarlabs.org/sayamindu/pootle_gettext_check.png

**Comment by julen** [comment]
This is already implemented in master, not specific to gettext but critical failing checks are mandatory to be reviewed after submitting. We also prominently display the number of critical failing checks everywhere in the overview pages.
