### ISSUE TITLE
add news-manage-page to admin-screen

### ISSUE THREAD

**Issue by JohannesAhlers** [translate/pootle#1336]
I'd like to have the ability to delete old news-entries. This functionality should be added as a separate page on admin-screen.

My current problem with the news: I added a test-project some days ago. This created a news-entry which appears on pootle main-page. Now I deleted this project again. The news-entry is still visible and clicking the link will result in a "Page not found" error.

**Comment by julen** [comment]
The news feature is gone, closing.
