### ISSUE TITLE
Consider doing load testing on Hudson for Pootle

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#1475]
It would be great if we could actually see performance graphs on Hudson as things change.  I don't know if such plugins are available, but it would be great if we can make this work out. Dwayne, you know you want to do this.

Some possible building blocks:
 - ab - Apache Bench
 - http://curl-loader.sourceforge.net/
 - http://www.joedog.org/%20index/siege-home

**Comment by jleclanche** [comment]
@dwaynebailey closing this because we use Travis now and it's just as good.
