### ISSUE TITLE
Make translation-files markable as "online" / "offline"

### ISSUE THREAD

**Issue by JohannesAhlers** [translate/pootle#1485]
Sometimes our translators want to translate offline with a tool like Virtaal. The upload-options helps preventing loss of translations made online meanwhile. But it would be a nice feature, if the translator can mark the downloaded file as "offline". So other translators know they should better not touch the file now.  
Currently we use the news-entries for this.

Perhaps an additional permission could be developed, with which a file can be blocked really. So the file with status "offline" could not be changed on Pootle temporarily until it returned to "online" status.

**Comment by julen** [comment]
We have some ideas we want to explore in terms of *locking*, and will definitely get our hands dirty with that at some mid-term point. I'm closing this for the time being, and will open a new ticket when we get with a more specific plan.
