### ISSUE TITLE
Ability to restrict view permissions for a project for nobody and default users

### ISSUE THREAD

**Issue by Cecilia-Albertsson** [translate/pootle#1494]
I would like to be able to hide selected projects from users who are
not logged in and from users who are logged in with default permissions.

The idea is to keep one project (say, project1) open for viewing and editing
by general users, while keeping a related project (say, project1dev) visible
only to users with admin permissions, containing files to be used only by
admins/developers, for instance to update the source language strings of the
files in project1, or to perform tests on PO-files in Pootle.

**Comment by dwaynebailey** [comment]
We can currently do this.
