### ISSUE TITLE
Make translation edit rows clickable

### ISSUE THREAD

**Issue by terinjokes** [translate/pootle#1510]
*Version: 2.0.x*

Right now now when editing a project in Pootle, one can change the active row by clicking on the row number way on the left hand side of the table.

It seems more logical to us that the whole row be clickable.

**Comment by unho** [comment]
@julen Is this still valid?

**Comment by iafan** [comment]
This is no longer valid. We have rows clickable now. Preventing data loss on navigating away from the unit now has a separate issue #3724
