### ISSUE TITLE
Unified Activation Workflow

### ISSUE THREAD

**Issue by terinjokes** [translate/pootle#1511]
*Version: 2.0.x*

I think the activation workflow should be unified and made more end-user friendly.

Here's the idea I have in mind:

1) User registers in the same manor as current.
2) After clicking the link in the activation email, the user automatically logged in, and shown a page or two tutorial on how to use the Pootle system, basic guidelines to follow, where to go for help, while at the same time setting up some settings (interface language, projects and languages that would be added to the dashboard). Similar to how Gmail acts when you first activate.

**Comment by julen** [comment]
Now there's allauth and the user is automatically signed in upon confirming the email (note this works immediately after signing up).

**Comment by terinjokes** [comment]
@julen Although the company i was working for at the time no longer exists, I'm glad to finally see this be resolved. :+1:
