### ISSUE TITLE
Implement (visual) inheritance from parent languages

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#1526]
Not sure about other OS's, but Haiku has a nice feature: an incomplete locale will inherit missing strings from its parent.

This means that e.g. pt_BR localizer can only translate those strings that are different between pt_BR and pt, and the system will automatically inherit everything else from  pt.

For this to work well, however, this inheritance should be made more visible.

In particular, Haiku encourages localizers to only translate those strings that should NOT be inherited, so all other strings should be properly shown as inherited until the localiser decides they want to change them. Also, those inherited strings should not be exported when generating catkeys files (bug translate/translate#1515).

A very good example of what I'm talking about can be seen here:
http://hta.polytect.org/catalogs/view/19/pt_BR

**Comment by dwaynebailey** [comment]
I think this is out of scope for what Pootle should be doing.  Optimising of exports to only contain what is different should I think be the responsibility of serialisation or code building.
