### ISSUE TITLE
save authors and times, and for some translations original author/source, of all translation variants

### ISSUE THREAD

**Issue by qdinar** [translate/pootle#1549]
feature requests:
1. save authors and times of all submitted translation variants.
2. there should be field to link to original author or source, where from submitter has got that, for case that he has not translated it himself, he is not author of translation.
3. make these saveable to file.

**Comment by dwaynebailey** [comment]
We already do parts of these:
1. Done - see timeline
2. Hard to do and I'm not 100% sure of the value or copyright related issues
3. Can't do, I think the timeline is enough.
