### ISSUE TITLE
Lengthy processes need some visual feedback

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#1571]
*Version: 2.1.x*

After waiting for more than 10 minutes for a new project to be added, I pressed Ctrl+C in the terminal to interrupt Pootle's process. I thought that something was definately going wrong, but apparently, nothing was. There were simply quite a lot of files to index.

The point is: some visual feedback is definately needed for situations like this. If something takes more than a few seconds to finish, it should allow the user to see the process of the task, be it some raw log (names of files being processed, like during installation) or a progress bar...

**Comment by jleclanche** [comment]
@julen i think this can be closed now, yes?

**Comment by julen** [comment]
Yeah, stats don't block the main Pootle process (and therefore the UI) anymore. Visual feedback is also provided when stats are being calculated in the background and the current overview page contains stale data.
