### ISSUE TITLE
SELinux will prevent Pootle from using memcached

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#1644]
*Version: 2.1.x*

On Fedora if we set localsetting.py to use memcached we can't use it as Apache running under SELinux enforcing policy prevents httpd from using the network.

If we are in a situation where memcached is enabled in localsettings.py and we can't access it then it might be an issue with SELinux.

The condition would be this:
memcached is configured AND running under Apache:
"SELinuc may be preventing Apache from accessing memcached.  Check by running 'getsebool httpd_can_network_connect' and enable by running 'setsebool -P httpd_can_network_connect 1'

**Comment by dwaynebailey** [comment]
memcached is dropped for ``2.7.0`` might be relevant for Redis but lets deal with that then

**Comment by unho** [comment]
@dwaynebailey I wasn't aware of that. Does Redis completely replace memcache? I still see references to memcache in master.

**Comment by iafan** [comment]
While memcached can technically be used for some parts of the cache, Redis now is a hard dependency, and it can handle all the caching needs in the same way or even better, so there's no need to mention memcached anywhere in the docs/code now.
