### ISSUE TITLE
Project administration has an empty "project" column

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#1660]
A page such as the one in the URL field has an empty column because the rows in the tbody has an extra column there for which there isn't an entry in thead:
<td class="project"><input name="form-0-project" value="8" id="id_form-0-project" type="hidden"></td>

This causes extra sorting arrows for that column which is confusing (and obviously unnecessary).

**Comment by unho** [comment]
@julen Is this still open with latest new admin changes done in core (new master)?

**Comment by julen** [comment]
No longer relevant.
