### ISSUE TITLE
Snapshot for statistics

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1668]
*Originally posted by Manal Hassan:*

Dear all,

I'm managing many (10+) language teams who are localising many projects (5 or more), and I want to monitor their work.

Weekly I have to visit the pages for every team for each application, they are working on two now ==> 20 pages, and then I need to copy the statistics in a spreadsheet to be able to compare it with the new statistics the following week.

This is such a time consuming task, I was wondering if you can frequently (daily/weekly) -or on request- save the stats, to be able to browse them and compare them (or generate diffs) any time.

I'm concerned with project per language, not per user basis.

**Comment by julen** [comment]
We already have reports for such a use-case, closing.
