### ISSUE TITLE
Allow translators to let the admins know about typos in the original .po

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1673]
Depends on:
* [x] #2168 Report errors and improvements in source text

*Originally posted by Ivan Garcia:*

It will be good if the translators could have some button or any way to let the creators of the original .po that some paragraphs contain some typos or errors.

In our case we've told the users to use the comment field to add 
TYPO: 'what is wrong' => 'how should be' 
syntax and with an easy script we are able to export all those typos into an html for revision. But that's not a clean solution, just fast for the moment.

In a clean way for example I'm thinking in a 'Suggest' button also under the original text field.

**Comment by julen** [comment]
This has already been implemented.
