### ISSUE TITLE
Add an API for adding new strings

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1700]
*Originally posted by Sylvain Zimmer:*

We'd love to be able to programmatically add a new string to a po/pot file.

Even if for a time being it's just a web form on pootle, we can script that easily.

I guess it could look like

AddNewString(lang,filepath,basestring,translationstring)

Thanks!

**Comment by dwaynebailey** [comment]
Closing all API related issues to implement them as needed for ``ptl`` with spinoff API development rather than leaving these open.
