### ISSUE TITLE
Add a button or link next to the user row to change his lang/proj selections

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1703]
*Originally posted by Ivan Garcia:*

Sometimes the admin of Pootle would like to change the selections made by an user about his langs or projects.

What about if in the users list that the admin can see, we add a button or link in the user row (it could be called 'More Options' for example) and it would lead to a form page , like 'accounts/edit/' for the admin to change those options.

Maybe the final url could be something like 'admin/users/<nameuser>/edit/'

What do you think?

**Comment by julen** [comment]
Users do not have assigned languages anymore, closing.
