### ISSUE TITLE
File names should be considered case insensitive (in GNU style projects)

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#1708]
*Version: 2.1.x*

I had a bunch of files named pt_br.catkeys (instead of pt_BR.catkeys), and Pootle didn't recognize this language as Portuguese Brazilian, but instead assigned those files to the Templates language. Could the file names perhaps be case insensitive? Or maybe that should just be considered as another project "style", along with GNU?

**Comment by phlax** [comment]
i believe that case-sensitivity has now been fixed
