### ISSUE TITLE
Sync_stores generate are not escaping new lines in properties files

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1715]
*Originally posted by Branko Kokanovic:*

When using properties files project setup, and if we have "\n" as values in properties files, sync_stores command (and commit to VCS) generates properties file that is not escaping new lines, and instead generate real new line character.

Example:
FOO=bar1\nbar2

is transformed to:
FOO=bar1
bar2

which is not proper properties file according to specs

**Comment by dwaynebailey** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle.  Closing
