### ISSUE TITLE
Incorrect filename for downloads

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#1732]
*Version: 2.1.x*

I download a file from Pootle with this URL using wget:
http://pootle.locamotion.org/templates/foss_manual/pootle-terminology.tmx/download/

The file is saved with the name "index.html".  Firefox suggests the correct filename on save, probably because it guesses the name from the redirect URL instead of the original.

Anything we can easily so about this? I don't consider it a major issue.

**Comment by jleclanche** [comment]
This isnt really fixable, nor should we care.
