### ISSUE TITLE
Locale-dependent number formatting doesn't work under Windows

### ISSUE THREAD

**Issue by iafan** [translate/pootle#1749]
Summary: Pootle runs on Windows 7, locale is ru_RU with codepage cp1251. The number delimiter is a non-breakable space symbol which is returned by Windows in cp1251 codepage. There seems to be no way to tell Windows to use UTF-8 codepage instead via setlocale().

Commenting out this line fixes the problem:

  #'pootle.middleware.setlocale.SetLocale', # sets Python's locale based on request's locale for sorting, etc.

From the IRC chat log:

(1:44:50 AM) dwaynebailey: locale.setlocale(locale.LC_ALL, ('en_US', 'UTF-8'))
(1:46:29 AM) afan: dwaynebailey: locale.Error: unsupported locale setting 
(1:46:56 AM) dwaynebailey: And this:
(1:46:56 AM) dwaynebailey: locale.setlocale(locale.LC_ALL, ('enu', 'UTF-8'))
(2:01:23 AM) afan: dwaynebailey: ('enu', 'UTF-8') won't work. ('enu') will. Seems like you can't set codepage to UTF-8 on Windows. Instead, you need to treat the string according to current codepage (cp1251 in my case) and do the conversion. I'd suggest just not to use locale-specific formatting under Windows if that's easier.

**Comment by dwaynebailey** [comment]
Closing, not a target for deployments and we have some workarounds in the code already for Windows devs.
