### ISSUE TITLE
Add custom templates for Contact and Login form the way we do for other forms

### ISSUE THREAD

**Issue by iafan** [translate/pootle#1756]
Most our forms use custom templates. For example, this is how the File upload form is rendered:

```html
{% for field in upload.form %}
<p {% if field.help_text %}title="{{ field.help_text }}"{% endif %}>
{{ field.label_tag }} {{ field }}
{{ field.errors }}
</p>
{% endfor %}
```

This allows us to place error messages below the form field for better readability.

However, two forms -- Contact and Login -- use default form rendering:

```
{{ form.as_p }}
```

Which renders errors at the top.

Can we adjust these two forms the same way we do for e.g File upload form (or for Registration form)?

This would ensure the consistency of how the form errors are rendered across the entire application.

**Comment by julen** [comment]
Form errors are displayed consistently from what I can tell, closing.
