### ISSUE TITLE
it should be able to update_from_templates without copying target language strings from templates

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#1763]
currently, if I run manage.py update_from_templates, all the TARGET strings in template are copied to the target store. While it's possible to avoid that in bilingual formats, it seems imposible with monolingual ones (e.g. properties).

I suggest to make this copying of target text during update_from_templates optional by introducing a new option (e.g. --copy-target-text or --strip-target-text or something like that).

**Comment by dwaynebailey** [comment]
``update_against_templates`` has been removed from Pootle 2.7.0, we'll approach monolingual files differently in future.
