### ISSUE TITLE
Open all units in the page for editing at once

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#1782]
One of the feature of Rosetta that I like is that all units in the page are open for editing at once and all get submitted once while switching to next page. IMO this makes translating online a bit faster requiring less clicks and page reload times.

**Comment by jleclanche** [comment]
@julen do you think this can still be considered relevant?

**Comment by julen** [comment]
Closing, as the ajax editor already addressed the original issue.

**Comment by khaledhosny** [comment]
I think the original issue still stands, currently the time between finishing the current unit and moving to the next one is rather long (compared to Virtaal, for example). So the suggestion of making all units in the page editable at once was just to be able to concentrate on translation rather than waiting for the next unit to show up.
