### ISSUE TITLE
getting org.apache.lucene.queryParser.ParseException error when I search a keyword with double quotations

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1784]
*Version: 2.1.x*

*Originally posted by Naoya Makino:*

getting org.apache.lucene.queryParser.ParseException error when I search a keyword with double quotations.
for example, http://pootle.locamotion.org/ach/abiword/abiword.po/translate/ 
when you do a search with double quotation, http://pootle.locamotion.org/ach/abiword/abiword.po/translate/?search=%22Auto+Update%22&sfields=source&sfields=target

im getting this exception error: g.apache.lucene.queryParser.ParseException: Cannot parse '"Auto*': Lexical error at line 1, column 7. Encountered: after : "\"Auto*"

I searched with "Auto Update" but in error says Cannot parse '"Auto*' somewhere it changes the query from "Auto Update" to '"Auto*' and gives me an error.

here is an apache error log:

Wed Dec 01 23:34:16 2010] [error] Traceback (most recent call last):
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 92, in get_response
[Wed Dec 01 23:34:16 2010] [error]     response = callback(request, *callback_args, **callback_kwargs)
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/lib/pymodules/python2.6/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[Wed Dec 01 23:34:16 2010] [error]     response = view_func(request, *args, **kwargs)
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/local/pootle/local_apps/pootle_store/views.py", line 459, in translate
[Wed Dec 01 23:34:16 2010] [error]     return translate_page(request, store.units, store=store)
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/local/pootle/local_apps/pootle_store/views.py", line 315, in translate_page
[Wed Dec 01 23:34:16 2010] [error]     step_queryset = get_search_step_query(request.translation_project, search_form, units_queryset)
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/local/pootle/local_apps/pootle_store/views.py", line 158, in get_search_step_query
[Wed Dec 01 23:34:16 2010] [error]     textquery = translation_project.indexer.make_query(word_querylist, False)
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/local/lib/python2.6/dist-packages/translate/search/indexing/PyLuceneIndexer.py", line 181, in make_query
[Wed Dec 01 23:34:16 2010] [error]     return super(PyLuceneDatabase, self).make_query(*args, **kwargs)
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/local/lib/python2.6/dist-packages/translate/search/indexing/CommonIndexer.py", line 176, in make_query
[Wed Dec 01 23:34:16 2010] [error]     analyzer=analyzer))
[Wed Dec 01 23:34:16 2010] [error]   File "/usr/local/lib/python2.6/dist-packages/translate/search/indexing/PyLuceneIndexer.py", line 270, in _create_query_for_field
[Wed Dec 01 23:34:16 2010] [error]     return qp.parse(value)
[Wed Dec 01 23:34:16 2010] [error] JavaError: org.apache.lucene.queryParser.ParseException: Cannot parse '"Auto*': Lexical error at line 1, column 7.  Encountered: <EOF> after : "\\"Auto*"

but this search with double quotation works fine on dev server which just runs pootle straight on python 8080 server. only difference with production and dev is whether runs on apache with wsgi or python 8080.

here is Java version on production server:
java version "1.6.0_18" OpenJDK Runtime Environment (IcedTea6 1.8) (6b18-1.8-0ubuntu1) OpenJDK 64-Bit Server VM (build 14.0-b16, mixed mode)

and this is on dev:
java version "1.5.0" gij (GNU libgcj) version 4.4.1

thank you

**Comment by julen** [comment]
Lucence has been phased out for a while, closing.
