### ISSUE TITLE
Pootle repeat header lines en po files

### ISSUE THREAD

**Issue by godiard** [translate/pootle#1821]
*Version: 2.0.x*

In our pootle  instalation, pootle generate po files with the header lines repeated many times. This not happen every time, there are many files without problems.
Example of bad file: 
http://git.sugarlabs.org/memorize/mainline/commit/d8720afb4fc57341fe40722d82aae20894a0fd88

Our pootle instalation is in pootle.sugarlabs.org, version 2.0.3 packaged in ubuntu 9.10

**Comment by dwaynebailey** [comment]
Closing, we haven't seen this in any of our instance and not sure if its deployment specific or specic to for e.g. file uploads.
