### ISSUE TITLE
fuzzy check not getting written to .po file

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1864]
*Version: 2.1.x*

*Originally posted by (unknown user):*

I have a fuzzy text, and when I try to untick the fuzzy box and save the string it does not get written to the .po file. 
But when altering the text and saving it, the file gets updated with the new string and the fuzzyness is removed.

Pootle 2.1.5 is powered by Translate Toolkit 1.9.0-beta1

**Comment by julen** [comment]
`AUTOSYNC` was phased out a while ago, closing.
