### ISSUE TITLE
IntegrityError while translating

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1876]
*Version: 2.1.x*

*Originally posted by Branko Kokanovic:*

I am using .properties files. Upon initial import, every (already) translated string that was identical to english version was charactized by pootle as untranslated (example: REGION=Region (en), REGION=Region (sr)). When I copy/pasted translation from english, Pootle got that correctly as translated (.properties files was later unchanged). After next VCS update of template files, Pootle again started to "see" this strings as untranslated. When I again tried to copy/paste exact strings again, I got this: http://pastebin.com/x68ye0GA.

So, there are kind of two problems, but maybe underlying cause is the same (that's why only one bug report) - first is not correctly identifying translated, but exactly same strings as translated and second is this exception that is blocker (IMHO).

Please tell me if you need anything else to identify problem.

Pootle 2.1.1
Translate Toolkit 1.8.0
Django 1.1.1
Python 2.4

**Comment by julen** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
