### ISSUE TITLE
tooltip for terminology suggestion is missing

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1878]
*Version: 2.1.x*

*Originally posted by André Schnabel:*

current pootle version (2.1.5) does not a tooltip for terminology suggestions.
(The translator comment should be displayed if it is in ther terminology file).

The problem is visible at:
http://pootle.locamotion.org/de/vlc/translate.html?search=bar&sfields=source&sfields=target

there should be a tooltip for "bar", as visible in
http://pootle.locamotion.org/de/terminology/translate.html?unit=114653

**Comment by julen** [comment]
Closing in favor of #3026.
