### ISSUE TITLE
The strings pager seems to skip some strings when paginating

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1889]
*Version: 2.1.x*

*Originally posted by Mario Domenech Goulart:*

Here I have a file with 22 out 25 strings translated.  The first page lists strings from 0 to 8.  The second page lists strings from 5 to 13.  The third page lists strings from 16 to 24.

I cannot access string 14, for example.

I expected the pagination to be like:

0 - 8
9 - 18
19 - 25

Or some slicing that allows me to see all the strings.

What I currently get is:

0 - 8
5 - 13
16 - 24

I've placed some screenshots of the issue I'm facing at http://arquivos.ossystems.com.br/~mario/misc/pootle-pagination/
so we can see the behavior in question even if something changes.

My setup is:

- Debian 6.0
- Django 1.2.5
- Translate Toolkit 1.8.1
- Pootle 2.1.5
- Python 2.6

**Comment by julen** [comment]
We don't use pages anymore, closing.
