### ISSUE TITLE
When quick translating, allow to skip strings with suggestions

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#1900]
Here's the email I got today:

> I was just looking for some magic undocumented URL-parameter
> that would allow me to tell pootle to step only to untranslated AND
> nosuggestions.
> 
> Pootle's havigation is really poor, you can only go from the very
> start and iterate one by one.
> 
> So when person A starts translating, user B will first have to click
> "next" over all the suggestions user A did already until user B will
> get to something that really is untouched.
> 
> This is very annoying, so I was hoping there was some "unitstates"
> parameter for "nosuggestion"...

Would it be possible to introduce a possibility to skip strings with suggestions? I think it would be really helpful in cases where multiple people are adding suggestions to the same project/folder.

**Comment by ta2-1** [comment]
I'm closing this issue because it will be addressed in #4628 where some implementation details can be discussed.
