### ISSUE TITLE
Java properties projects are all UTF-8?

### ISSUE THREAD

**Issue by kristofferpeterhansel** [translate/pootle#1918]
*Version: 2.1.x*

It seems that 2.1.6 might now treat all Java Properties projects as being UTF-8. And indeed it seems that the same value is used for 'localfiletype' in the database ('properties') making it hard to distinguish what it is supposed to be.

The problem is that Java by default loads properties files as ISO 8859-1. So it is rather important it is preserved.

**Comment by dwaynebailey** [comment]
We've take out monolingual support on 2.7.0 and will bring back better support for monolingual going forward.
