### ISSUE TITLE
Pootle is unable to export files on Windows

### ISSUE THREAD

**Issue by kristofferpeterhansel** [translate/pootle#1919]
*Version: 2.1.x*

It seems that Pootle does not like Windows paths. At least when you try any export option it ends up creating urls like this:
http://webdev01:10080/pootle/export/ds%5Cbranding-da.properties

Where the %5C (i.e. backslash) should have been a forward slash.

I am doing with with Pootle 2.1.6 and Translate Toolkit 1.9.0 and under Python 2.5.4.

I should also mention that I have set the PODIRETORY to an absolute Windows path (J:\Storage\Pootle). If that makes any difference.

**Comment by julen** [comment]
Export has been rebuilt from the ground up, and besides Windows is not supported on production environments anymore.
