### ISSUE TITLE
Provide meaningful message for invalid term being added to terminology

### ISSUE THREAD

**Issue by madkinder** [translate/pootle#1942]
As of now (pootle rev 17490) whenever one tries to add a term that is already present in ``pootle-terminology.po`` the following message is displayed above the field: "Please correct the error below.".

Since the terms aren't sorted (which would be great if they were) it is not obvious what error is user supposed to correct. It would be better if the error message stated something like "This term is already present in terminology".

**Comment by dwaynebailey** [comment]
This is fixed in Pootle.
