### ISSUE TITLE
Java properties project doesn't get updated from templates properly

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1949]
*Version: 2.1.x*

*Originally posted by Phil:*

Hi,
1. ( http://www.philiplb.de/misc/pootle/1.png )
First, I create a Java properties project, UTF8, with gnu style project tree and en as default language.
2. ( http://www.philiplb.de/misc/pootle/2.png )
Now I add en and de as languages.
3. ( http://www.philiplb.de/misc/pootle/3.png )
Here I upload the first version of the en.properties to the english language.
4. ( http://www.philiplb.de/misc/pootle/4.png )
I update german from the templates so I can start translating.
5. ( http://www.philiplb.de/misc/pootle/5.png )
Here I translated the only unit of the test project.
6. ( http://www.philiplb.de/misc/pootle/6.png )
I overwrite the en.properties with a new version
7. ( http://www.philiplb.de/misc/pootle/7.png )
As you can see, the english file is updated correctly, the string changed from "Hello" to "Hello world"
8. ( http://www.philiplb.de/misc/pootle/8.png )
I update the german file again from the templates
9. ( http://www.philiplb.de/misc/pootle/9.png )
There is the error: In the german file, the english string didn't update, the old translation is lost and replaced by the new english string.

You can find the en.properties here: http://www.philiplb.de/misc/pootle/en.zip
In the zip are two folders with an en.properties each:
1: Used as old en.properties
2: Used as new, changed en.properties

**Comment by julen** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
