### ISSUE TITLE
Privileges problem

### ISSUE THREAD

**Issue by goetas** [translate/pootle#1959]
*Version: 2.1.x*

some months ago i created a bug ticket #1833.
the solution for the ticket was:
> what I did in r17167 (which will be part of 2.1.5) is hide the project field in
> user profile entirely if user doesn't have server wide view permissions.

My pootle config is:
I have very restrictive server wide permissions (no one can view/translate projects).
I have per user  and project translate/view permissions.

In 2.1.6, without the "project field" in user profile i can't show user projects with low privileges (without server wide view permissions).

Can you restore the "project field" in user profile, or make it configurable?

**Comment by dwaynebailey** [comment]
Closing as this is a 2.1.x version, if it presists in 2.7.0 please reopen
