### ISSUE TITLE
Add commit status flag on each PO

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1988]
*Originally posted by Chris Leonard:*

Sayamindu Dasgupta had made some modification to our local Pootle instance back in 2009 starting from a baseline of Pootle 1.2.1 and TranslateToolkit-1.3.0, although it was later upgraded to Pootle 2.0 and TranslateToolkit-1.5.1

He recorded his patches here:

http://git.sugarlabs.org/pootle

He made one very nice hack as shown here:

http://git.sugarlabs.org/pootle/mainline/commit/b7dbad4e48e8c6779e05a56cae5a83b3c3bfec40

As modified by this correction commit:

http://git.sugarlabs.org/pootle/mainline/commit/473847808819b259f9e2c2d7a9df077aa42b2245

The idea is very good, but I cannot vouch for the implemetnation 100%, so some experiementation and changes t omake it more of a general case (instead of Suagr Labs git specific would be needed.

I cannot guarantee that the hack performs exactly as expected, I seem to remember some cases where it didn't produce correct results, but we no longer use this patched version.  This method seems to compare the PO in Pootle with the PO in git to determine how to set the status flag.

In an alternative state-maintaining method that does not look at the repo it might do something like this:

TRUE meaning a commit is required to synch up Pootle and git.

Set status flag to TRUE at start, when a PO file is committed, set it's status flag to FALSE, if a change is made to a string in the PO file, then set status flag to TRUE. 

Lather, rinse, repeat.

Having status on whether a PO has been committed (without rummaging through the repo) would be a very nice enhancement.

**Comment by dwaynebailey** [comment]
We're redoing the whole approach to VCS and likely this means not exposing VCS to users but having Pootle do the right thing. So closing.
