### ISSUE TITLE
Template language changed when adding new language in project

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1998]
*Version: 2.1.x*

*Originally posted by Anders Mark:*

This bug is about Pootle mixing up the template language and new languages added. When editing the new added language the left column shows values in the template language. This is correct. The right column is however not displaying anything at all. If select the template language and edit the file I see the added language in the left column and nothing in the right column.    

Below the order I do the things:

1. Create the project. Code: tariff32, Full Name: tariff32, Quality checks: standard, File Type: Java Properties (UTF-8), Project Tree Style: Non-Gnu, Source Language: en
 Click on "Save changes"

2. Click on the newly created project (tariff32) and create language "Templates - templates".
    Click on "Save Changes".

3. In the file system in the Pootle structure. Add a file for template language. 
    root@pootle:/var/db/pootle/po/tariff32/templates>
    
    cp ../../tariff32.copy/templates/common_messages.properties.sorted.short common_messages.properties

    As you see I add a file and call it common_messages.properties. It's in English and contains 10 rows. I have a set of testfiles which I use for recreation of the problem. 

4. Now it's time to tell Pootle there are new files in language templates. This can be done in two ways as I see it. Either you can do it in the web interface and rescan project files for templates. The other way is to run the command line utility which I use in this example.

   django-admin.py update_stores --settings=pootle.settings --project=tariff32

5. Now I add the new language. I choose Denish "da". 
    I go to Admin / Projects and select tariff32. In the list which for now only shows "Templates - template" I select "Danish - da". Then click "Save Changes".

    Now Pootle automatically has created a copy of the template file common_messages.properties in the Danish subdirectory. Of course I have my own Danish translation and will use that instead. 

6. Replace the automatically created file in the "da" directory which the one written in Danish.
    cp ../../tariff32.copy/da/common_messages.properties.sorted.short common_messages.properties

7. To inform Pootle that there has been changes on disk I run the command line tool:
    django-admin.py update_stores --settings=pootle.settings --project=tariff32

   The changes made to the Danish property file should now be reflected in Pootle web interface as I see it. 

8. In the Home page I click on project "tariff32", and then select "Danish" language. The only file in this language "common_messages.properties" are shown, I click on this one. I now see the English language which is the template in the left column. There are no values at all in the right column. If I however select the template and the same file I see the Danish language in the left column and nothing in the right. 

Something seems to be mixed up with template language and added languages. I have also experienced a scenario where when I've imported the new language file and select it for editing I get this language in the left column and the template in the right column. I guess it should be the other way around?

**Comment by dwaynebailey** [comment]
Closing as this is monolingual related and in 2.7.0 we've taken out monolingual support so that we can bring it back in a much better way.
