### ISSUE TITLE
po file may add more plural forms than language has

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2016]
_Version: 2.1.x_

_Originally posted by Richlv:_

pootle 2.1.4

if an uploaded po file has more plural forms than the language has configured in pootle, they will still be added. as a result pootle will have them, will detect them with "nplurals" check - but provide no way to fix the issue. saved po file will also have this issue.

issue currently can be seen at https://www.zabbix.org/pootle/ja/Zabbix-2.0/translate.html?unit=120312, although most likely will be fixed soon :)

for the record, broken file was produced with omegat

**Comment by comradekingu** [comment]
@transl8bzimport Is this still the case?

**Comment by phlax** [comment]
i think this was open by a bot posing as @dwaynebailey 8/

lets close such old issues that dont have any activity
