### ISSUE TITLE
Specify db/table/column encoding with mysql

### ISSUE THREAD

**Issue by llimeht** [translate/pootle#2047]
Many mysql installations use the upstream default encoding for databases of latin1_swedish_ci. If neither pootle nor user manually specify that pootle should use utf-8 with mysql, the data either gets corrupted in the round-trip or the database refuses to import the data.

Pootle instructions currently tell the user to manually specify utf-8 when creating the mysql db:

http://translate.sourceforge.net/wiki/pootle/mysql

```sql
CREATE DATABASE pootle CHARACTER SET = 'utf8';
```

but looking at discussions on mailing lists etc, this step is evidently forgotten often enough.

Given that pootle will create the tables within the database, pootle could first ensure that the db has the correct encoding. There is presumably some way of telling django ORM what the encoding of the data should be (and one would assume that django would then tell the database to create the tables accordingly).

Failing that, pootle could be slightly more crude by executing raw sql prior to table creation if mysql is in use. e.g.:

```sql
ALTER DATABASE `pootle` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
```

through a django hook

https://docs.djangoproject.com/en/dev/topics/db/sql/#executing-custom-sql-directly

Django documentation indicates that this is a common problem and the django developers seem to want the database administrator to configure things properly rather than django doing things magically in the background. One way of doing that is of course to add to my.conf

```ini
[mysqld]
character-set-server=utf8
default-collation=utf8_general_ci
```

although such a requirement doesn't make pootle any more robust (as tempting as that is!)

There is also the suggestion that

```python
DATABASE_OPTIONS = {
    "charset": "utf8",
}
```

might work in django although it's not obvious to me whether that's changing the charset of the db or the charset of the db connection.

http://stackoverflow.com/questions/2267242/django-legacy-database-encoding

https://docs.djangoproject.com/en/dev/ref/databases/#creating-your-database

**Comment by dwaynebailey** [comment]
Added supported DB etup instructions in 8ac4e5fe0c5d97937d0d88f142acf04607c8e518

We can't protect sysadmins from all encoding issues.  We could add a check in Pootle to detect bad DB encoding.  But I think the docs are enough.
