### ISSUE TITLE
Add "changed" filter

### ISSUE THREAD

**Issue by JohannesAhlers** [translate/pootle#2051]
*Version: 2.1.x*

A further filter, which is a negation of "unchanged" filter should be implemented, to review all already translated entries.

Our developers create the message texts in German. Now the quality management department is doing a translation "Developer-German" to "Customer-German". Normally the texts matches, but sometimes not. Such a "changed" filter will help us to review the entries which were changed by QM.

**Comment by dwaynebailey** [comment]
This is such a corner case that its probably best to create a custom check in the Translate Toolkit to fullfill this role. The problem with this as a general check is that its mostly not useful for anyone and rather confusing alongside ``changed``
