### ISSUE TITLE
uploading srt files in a subtitle srt project does not find any strings

### ISSUE THREAD

**Issue by ichernev** [translate/pootle#2060]
*Version: 2.1.x*

Description of problem:
In a project with File Type: "subtitle: srt" uploading srt files is not working properly -- no strings are found for translation inside.

Steps to Reproduce:
1. Download pootle 2.1.6 and translate-toolkit-1.9.0 source code
2. $ ./PootleServer
3. create a new project with File Type: "subtitles: srt" (you need to have aeidon installed)
4. add a language to the project
5. select that project-language and upload a srt file

Actual results:
The uploaded srt file is marked as Completed, i.e there are no strings for translation found inside.

Expected results:
The subtitle strings from the srt file should be collected and the system should enable their translation.

Additional info:
Actually, if the project File Type is "Gettext PO" then uploading srt files converts them to *.po files (using sub2po), but then exporting the translations returns the *.po file.

**Comment by julen** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
