### ISSUE TITLE
Space indication

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#2065]
I was asked to suggest to indicate spaces like text editors do – by using a middle dot. Not sure if that's possible, but consider it a feature request. :)

**Comment by jleclanche** [comment]
@dwaynebailey can we take a hard stance on this bug? Id like to say it's not needed.

**Comment by dwaynebailey** [comment]
@jleclanche can you give a reason why its not needed? I can think of why it is: double spaces, indent with spaces, space based layout.

**Comment by comradekingu** [comment]
@rimas-kudelis This is fixed in the latest version.
