### ISSUE TITLE
(CSS) Background rules that only specify a gradient should use background-image instead of background.

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#2068]
In http://test.locamotion.org/html/translate.css, at the bottom of div#toolbar block, there are these two lines:

    background: -webkit-gradient(linear, left top, left bottom, from(#e5f3f8), to(#cde7f1));
    background: -moz-linear-gradient(top,  #e5f3f8,  #cde7f1);

There is a small problem with them, I'm not sure how many browsers are affected though. I noticed it while using Webkit-based WebPositive on Haiku OS.

The problem in my browser is that the toolbar is rendered transparent, which is rather undesired. Since these lines only specify the gradient and nothing else, my suggestion is to use background-image rules to specify it instead:

    background-image: -webkit-gradient(linear, left top, left bottom, from(#e5f3f8), to(#cde7f1));
    background-image: -moz-linear-gradient(top,  #e5f3f8,  #cde7f1);

I haven't tested, but I suspect this may solve the issue I am (and others might be) having.

While at it, why not also add a few rules for other browsers, and a generic one (without prefix)? So, the result would be something like this:

    background-image: linear-gradient(top, #e5f3f8, #cde7f1);
    background-image: -o-linear-gradient(top, #e5f3f8, #cde7f1);
    background-image: -moz-linear-gradient(top, #e5f3f8, #cde7f1);
    background-image: -webkit-linear-gradient(top, #e5f3f8, #cde7f1);
    background-image: -ms-linear-gradient(top, #e5f3f8, #cde7f1);
    background-image: -webkit-gradient(linear, left top, left bottom, from(#e5f3f8), to(#cde7f1));

note: this is adapted from what I got by using http://gradients.glrzad.com/

**Comment by julen** [comment]
Wherever gradients are being used, `brackground-image` is used (applies just to *select2*'s CSS), hence closing.
