### ISSUE TITLE
Suggestions look clickable even when they aren't

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2092]
When users have no suggest or translate permission, they are able to see suggestions. The suggestions are styled with the cursor pointer, so look clickable. When they click, nothing happens (since r17955), but ideally we shouldn't even make them look clickable.

**Comment by unho** [comment]
Suggestions are now clickable and it opens the suggestion dialog where you can edit it or accept/reject with a comment. So closing this.
