### ISSUE TITLE
Java properties with a = symbol in the value are split

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#2095]
*Version: 2.1.x*

Reference
http://docs.oracle.com/javase/6/docs/api/java/util/Properties.html

"The key contains all of the characters in the line starting with the first non-white space character and up to, but not including, the first unescaped '=', ':', or white space character other than a line terminator."

After issuing a update_stores command to update the Pootle database from source code, I see this in the diff

-greater_than_or_equal_to=>
+greater_than_or_equal_to=>=

The original value is '>=' but it is overwritten by '>' automatically by update_stores. It seems that a split occurs after each '=' symbol, when in fact it should only occur after the first '=' on a line.

**Comment by julen** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
