### ISSUE TITLE
Cannot export pootle-terminology.po after creation with "Manage Glossary"

### ISSUE THREAD

**Issue by llimeht** [translate/pootle#2096]
*Version: 2.1.x*

After creating a glossary for a language in a project, there is a "pootle-terminology.po" file listed against that language. I went through that file and fixed up a few terms that it had picked to make the terminology more universal etc.

I then wanted to copy that work around to the other languages in the project so that they can have the same set of terms to base their terminology off. I'd also quite like to check that file into the VCS as it seems to be a useful part of the project at this stage.

However, I can't find a way of extracting the pootle-terminology.po for that language at all. It's not in the zip file when I download it and it's not created when running sync_stores.

(In the end, I created a new pootle-terminology.po using poterminology on the templates and have copied that file around. All seems happy now.)

**Comment by julen** [comment]
Closing based on the fact that terminology extraction isn't present in Pootle anymore.
