### ISSUE TITLE
Exported/updated files should retain the structure of original files (or that of the template, if there is no original file)

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#2099]
I don't know if it's possible, but it would be nice if, when exporting, Pootle would do something similar to what po2xxx does with -t parameter instead of simply outputting the "default" (or whatever we may call it) structure. The reason why this would be nice is simple: many of the supported file formats allow having more information in them than just the translated strings.

For example, in a PHP file there may be a little bit of PHP code before and/or after the array is initialized. ResX files might contain even more information, such as window sizes, icons etc., in them.

Ideally, all that arbitrary code/information/whatever would be left intact in the exported file, but right now this is not happening (at least in case of PHP files). At the moment, it seems easier to work on PHP files like by simply converting them to .po(t) and working with that format instead, and later using po2php to convert the translation back to .php, because something as simple as updating the PHP project from causes loss of all arbitrary code in the file. Ideally, this wouldn't be needed.

I'm not sure it's actually possible without touching at least some stores themselves, so consider this of wishlist severity.

**Comment by julen** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
