### ISSUE TITLE
Integrate ESLint with Travis

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2103]
Since Pootle is now partly a JavaScript application, JSLint seems like a useful utility to consult. If integrated with Hudson/Jenkins, this might help us maintain quality in our JavaScript. More information here:
http://projects.mikewest.org/jslint_utils/

**Comment by unho** [comment]
@dwaynebailey Is this still relevant?

**Comment by julen** [comment]
Yes, but changing actors: ESLint and Travis.
