### ISSUE TITLE
conflicting keys in .po

### ISSUE THREAD

**Issue by glensc** [translate/pootle#2135]
*Version: 2.1.x*

Situation:

I had singular keyword in project (.pot file), which later was converted to plural (also in .pot). Pootle (Update from templates calling msgmerge or similiar) moved the old singular translation into comment and added plural as active. This later resulted conflict with msgfmt:

msgfmt --statistics lt.po -o lt.mo.tmp && mv lt.mo.tmp lt.mo
lt.po:346: duplicate message definition...
lt.po:323: ...this is the location of the first definition
msgfmt: found 1 fatal error

.po file context:

319 #: tpl/default/list_latest.php:71 tpl/default/list_latest.php:96
320 #, php-format
321 msgid "there is # reply"
322 msgid_plural "there are # replies"
323 msgstr[0] ""
324 msgstr[1] ""
325 msgstr[2] ""
326 

345 
346 #~ msgid "there is # reply"
347 #~ msgstr "yra # atsakymas"
348

**Comment by dwaynebailey** [comment]
Closing this for now, can't replicate as I no longer have these files.
