### ISSUE TITLE
Some breadcrumbs are repeated

### ISSUE THREAD

**Issue by julen** [translate/pootle#2150]
Depends on:
* [x] #2766 Reorder breadcrumbs to adapt to translator's common use-case

In some pages the breadcrumbs are more than obvious and they add too much text to the pages.

For example, when we are in '/accounts/personal/edit/', 'Pootle » My Account » Profile' is displayed, but the last part in the breadcrumb is obvious can be omitted since 'Profile' is already highlighted in the tab. That applies to most of the pages in Pootle.

**Comment by unho** [comment]
@julen Is this still relevant?

**Comment by julen** [comment]
Let's close it.
