### ISSUE TITLE
Superuser accounts should see account information from Admin panel in user profile

### ISSUE THREAD

**Issue by ChrisOelmueller** [translate/pootle#2156]
1) With superuser rights, visit http://test.locamotion.org/accounts/ (or the account overview of any other pootle instance)

2) Click on a user profile on that page

What I would like to see on this page is data like the email address (for which I'd otherwise need to head over to the Admin panel).

Navigating between several pages in the admin overview is tiresome at a certain threshold of users.
Also, we subscribe to the user registration feed for projects. This feed links the user profile page, so it would improve the workflow if you plan to e.g. subscribe new users to certain services or mailing lists.

**Comment by unho** [comment]
@julen Is this still relevant with new UI?

**Comment by julen** [comment]
The point being *navigating between several pages in the admin overview is tiresome*, this is not applicable anymore.
