### ISSUE TITLE
Show RSS icon in relevant pages

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2166]
*Version: 2.1.x*

We have RSS feeds on several pages in Pootle, but don't advertise the RSS feed anywhere except for having it in the link tag. Since Firefox (and maybe other browsers) don't show the RSS icon in the presence of the link tag, we should show something in the page to make it easier for people to realise that something is available.

**Comment by jleclanche** [comment]
-1 on this, browsers will show it automatically if they are rss-enabled anyway.
