### ISSUE TITLE
Pootle should take one sentence as a segment for translation instead of whole string

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2185]
*Originally posted by Rajesh Ranjan:*

I am using Pootle at different places and it would be better if Pootle should take one sentence as a segment/unit for translation instead of whole string. This is a major problem of all the editors based on .po format. All editors show a translator the whole string, sometimes it might be of several sentences. Here difficulty starts. It hampers:
1. Editor's Usability
2. Translation Memory and its utilization
3. Translation Speed

The editor's approach to show translation unit should be changed and show the translator sentence by sentence to translate instead of whole string.

**Comment by julen** [comment]
Segmentation is out of the scope of Pootle, therefore closing this bug — if needed, external tools can provide such functionality.
