### ISSUE TITLE
Deleting a project does not create a news feed entry

### ISSUE THREAD

**Issue by ChrisOelmueller** [translate/pootle#2187]
*Version: 2.1.x*

In the admin interface, select Projects and
* Create a new language project with arbitrary name (using Foo here), save changes
* Tick deletion box of the new project, save changes

Now the "News" section on the main page -- and the feed generated from it -- show the creation of Foo but not the deletion.
Thus clicking on the project name leads to an invalid page without a reason obvious to users.

**Comment by julen** [comment]
The news feature is gone, closing.
