### ISSUE TITLE
Failing checks wrap under submit button

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2214]
Depends on:
* [ ] #2213 Empty source string does not display well

In this unit http://mozilla.locamotion.org/af/firefox/translate.html#filter=incomplete&unit=1543747 you can see failing checks wrapping under the submit button.

This condition is caused by the lack of source text as reported in 2213.  This causes loss of vertical space to cause this problem.

Not sure if it is possible to get this results in a unit with many failures but with a single line source text.

In any case this really should not wrap under the button.

Solutions:
1) Wrap around the button. Would work, but might look messy with failure next to submit.
2) Elipsise the failures.  Would work best if we have Julen's classification work in place.
3) Move the button down when there are more failures.  Could look nasty.
4) Ignore it as it is rare.
5) Add some false positive catching to reduce the number of errors.  Seems like a temporary solutions

4 seems a good option :)

**Comment by julen** [comment]
Closing in favor of #3220.
