### ISSUE TITLE
Filter admin tables when we can't fit everything on one page

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2233]
When you have a large number of projects, users and languages it is hard to admin them as you can't quickly find them:

While you can step through them the pootle.lm.org server has 147 pages of users.  The same issue occurs in languages.  Less of an issue with projects.

We should be able to type in some text and filter the table. Ideal would be some nice ajaxy query of the total table.  But a search and retrieve would be OK.

**Comment by julen** [comment]
We have a new admin UI covering all these cases :tada:
