### ISSUE TITLE
Drilling down into directories in overview page causes file list columns to change size

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2243]
When you drill down into a directory the column widths change.

While this is normal since I guess the table is proportionally spaced, it makes the UI experience odd since the olumns move and related upload widgets shift position.

Solution:
1) Fix the column widths so that we don't get these jiggles
2) Make it possible to adjust the width of a column and remember that width

Problems with proposed soln:
Test is hidden - this is probably solved by 2) above.  But most like we'd need to use ... in cases of directory and file names that are too long.

**Comment by unho** [comment]
@julen @dwaynebailey @jleclanche  I think this is gone with new UI.

**Comment by julen** [comment]
The column widths still change but that's normal since they're proportionally spaced. The table doesn't misplace any other elements though — they're not there anymore.
