### ISSUE TITLE
Combining characters are cutoff in new Pootle interface

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2250]
If you type Ñ in Wolof (e.g. http://mozilla.locamotion.org/wo/firefox/config1/translate.html#filter=incomplete where it is listed as a special character) in the first line then it looks like a normal N.

We seem to not allow enough row height to show the ~ diacritic.

Not sure if this is a Firefox issue or a layout issue, but I guess it is quite confusing for translators as they can't see if it is correct or not.

**Comment by julen** [comment]
Not valid anymore, closing.
