### ISSUE TITLE
Selecting 'Checks' in translation UI shows ----- and selects no checks

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2286]
If you manually select 'Checks' in the Pootle translation UI then we by default select -----.

This does not occur if you are coming from the overview page as we've already preselect the test.  It only comes if you are in the translation page and manually change the selector to checks.

Problem:
When you first select checks it add the sub-selector with ----, meaning no select checks:
1) ----- - is not clear what it means and it doesn't select anything.  So you need to do two steps but it isn't immediately obvious that there is a second step.  If you just select checks and didn't do the second step the UI is in a state that doesn't show failures and doesn't respond.
2) There is no way to select all checks so that you can step through all errors.

Solution:
* Drop ----- and add 'All'
* By default if we didn't select the type of test we should select All.

I'm not sure what the load implications are of by default selecting All.  But this I think massively reduces the potential user confusion as they would always enter into checks in a way that allows them to begin taking action.

**Comment by unho** [comment]
Closing since this no longer applies.
