### ISSUE TITLE
Checks in the translation UI should be sorted and coloured according to severity

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2287]
Bug #2149 added classification to the check selector.

But in the actual translation UI where checks are displayed in the top right they are all displayed in red.  We are using red in the overview page to indicate critical errors.  

Problem:
* We are communicating that all errors are now critical.
* We don't order or classify to indicate severity

Solution:
* Use red only for critical errors.  Use another colour for other errors e.g. various shades for the other errors and maybe green for selectors i.e. not an error.
* Place errors in the order that we have with Critical, Functional, etc

Possible problems with the above proposal:
* Error don't leap out on the page - but maybe we only want critical ones to leap anyway.

**Comment by unho** [comment]
Closing since this is now fixed.
