### ISSUE TITLE
Move check descriptions off the wiki into applications

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2288]
Currently the UI descriptions of the checks are in the translate wiki.  In Virtaal we do have nice names and human readable one liner.  But the full description remains on the wiki.

Problem:
* Means leaving Pootle to get the descriptions of the error.

Solution:
This might be part of bug #1758 but lets let that one deal with the natural names only.
* On hover shows the short description
* Click takes you to either:
  * The wiki (probably want to put each test on its own page but not critical)
  * The wiki data is part of the app. So displayed in a lightbox and using markdown to then easily format the description of the error.

The onhover is easy as we have those descriptions already
The full description would add a lot of text to translate.  But it would make it easier to actually translate the text.  It might be worth putting that into a different domain.

**Comment by unho** [comment]
@dwaynebailey Is this replaced by #3604?

**Comment by unho** [comment]
Quality checks descriptions are now in http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/pofilter_tests.html and are being moved within Pootle as part of #3604 so closing this.
