### ISSUE TITLE
Investigate how we get "Problem reading N files" so that we can make it have an actionable purpose

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2303]
I'm not sure how to recreate, but sometime you will see a: (x) (circles in red with x inside) next to a directory.  Tooltip say "Problem reading N files".

Problem:
a) What are you meant to do with them, if anything
b) How do you make them go away

Solution:
a) Remove them if they serve no purpose
b) Have some clear action that must be taken by the user, the admin or some ability to rescan or something.
c) If it really is borken then prevent someone from drilling down there
d) If it needs action by an admin expose that action here.  i.e. the rescan files button should be with the error message.

**Comment by julen** [comment]
These messages were removed long time ago, closing.
