### ISSUE TITLE
Filter by options should not be present if there are no items of that type

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2304]
Filter by offers a number of filters.  These should not be present if there is no item of that type:

Thus if there are no suggestions then "Suggestions" should be removed from the list.

Problem:
You select the items and only then are you told that there are no units of that type.

Solution:
Only show what actually have data.
This covers also Translate, Untranslated, Incomplete, etc.

Issues:
This might be a problem on items such as checks where we delay finding the data.  But at least lets get this right for the ones where we do have checks.

**Comment by unho** [comment]
Closing since I don't think this applies anymore.
