### ISSUE TITLE
Remove ability to update file-by-file from VCS

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2312]
At the moment we still have the ability to update file-by file in a VCS. There is no GUI for it any more, but constructing the right URL will work.

We should remove this, since we only want to support full project updates.

I think the relevant code is:
pootle_app/views/language/urls.py-31 ....update_file
pootle_app/views/language/view.py:119:def update_file(
pootle_translationproject/models.py:404:    def update_file(

**Comment by dwaynebailey** [comment]
We're looking at VCS differently post 2.7.0 Pootle, so closing.
