### ISSUE TITLE
Provide update code to initialise separate VCS checkout

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2319]
Depends on:
* [x] #2314 Separate version control checkouts

With the separate VCS clones/checkouts (bug #2314), we should provide a way to help users upgrade their existing systems when we detect that we run on the new version of Pootle for the first time (or the management command is run. This could mean creating the necessary file structures, and moving files/symlinks across and resetting things for a clean checkout/clone as required by our new code.

**Comment by dwaynebailey** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
