### ISSUE TITLE
Look in separate repo when adding language or project

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2320]
Depends on:
* [x] #2314 Separate version control checkouts

Until now, Pootle automatically imports existing files on the file system when you add a project or language in a project if it finds something relevant at the right path.

With separate checkouts/clones (bug #2314), existing files might already exist in the existing checkout/clone, but won't be in the po directory when scanning, and won't show up. It should.

**Comment by dwaynebailey** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
