### ISSUE TITLE
Reconsider handling of existing files

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2321]
Depends on:
* [x] #2314 Separate version control checkouts

When adding a language to a project, we scan the file system to see if there are existing files to add (see also bug #2320). When we remove the language, we don't remove the files, which will make it easy to add them again.

We need to review this interaction with the file system, especially in the face of the new separate checkout (bug #2314). If something existing is already there, it won't get updated to templates, and won't be added to version control, which is probably the best behaviour (it is easy to do it after the fact), but we don't currently provide a way to add files to version control through any other means than updating from templates in a versioned project. It might be as simple as a bug for UI+ability to add unversioned files to the version control system.

**Comment by dwaynebailey** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
