### ISSUE TITLE
Look into performance of version control functionality

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2322]
Our interaction with version control systems are slow. It isn't necessarily a huge problem, but is likely to create issues with large projects, or on a busy server. The user experience is also not great.

We need to evaluate which kind of projects we want to be able to support, and what level of user experience we consider adequate. Some issues that might warrant attention:

 - We do lots of file system activity, like traversing directories and copying files.

 - Update several files in one go (now relatively easy with separate checkouts (bug #2314)

 - Commit several files in one go (we don't have UI or backend code).

 - Cache times of last update from upstream to avoid unnecessary pulling (maybe even just a few minutes or something like that).

 - Check which files actually changed, and do fast merges (if only one side changed)

 - 3 way merges where possible (maybe not a performance issue)

 - for new files (when bug #2255) don't parse if we can avoid it. Might be impossible with the new overview page needing statistics.

 - check for repeated calls to the --version of the VCS commandline

 - caching for things like .hasversioning()

 - check for unnecessary calls to .hasversioning() I used this simple patch in the toolkit to see what is being called:
```diff
diff --git translate/storage/versioncontrol/__init__.py translate/storage/versioncontrol/__init__.py
index c344871..bd3eb29 100644
--- translate/storage/versioncontrol/__init__.py
+++ translate/storage/versioncontrol/__init__.py
@@ -80,6 +80,7 @@ def run_command(command, cwd=None):
     """
     # ok - we use "subprocess"
     try:
+        print " ".join(command)
         proc = subprocess.Popen(args=command,
                 stdout=subprocess.PIPE,
                 stderr=subprocess.PIPE,
```

**Comment by dwaynebailey** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
