### ISSUE TITLE
Long delay in availability of legal pages when your first create them

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2328]
Note: This bug comes out of a review of the work to solve bug #2134

I can't seem to replicate this now.  But I initially, on a clean slate did the following:

1) Created a URL based legal page
2) Created a page based one

I struggle to get any of them to display.  After about 5 minutes and various fiddling they displayed.  I'm concerned that I created some problem that forced them not to display or that too much aggressive caching prevented their display

**Comment by julen** [comment]
Not applicable anymore.
