### ISSUE TITLE
Identify the source of TM suggestions

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2349]
Depends on:
* [ ] translate/amagama#2348 Store project metadata

Use case: When I'm translating and see suggestions from TM I want to know where it came from some that I can make an evaluation of the quality of the suggestion. There are certain sources that I trust more then others.

Problem:
At the moment we simply have a list of TM results from Amagama.

Solution:
Show an icon to the right of the TM suggestion that tells us where the suggestion came from.

**Comment by julen** [comment]
Closing this as we already have the source in local TM matches. If 3rd party services ever provide the source, it'll be added at its due time.
