### ISSUE TITLE
Comment is lost if you submit unit instead of comment

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2357]
If you begin to add a comment and then click submit for unit instead of for he comment you will lose the comment.

Problem:
You can lose data unexpectedly

Possible Solutions:
1) Submit any open comment on submitting a translation. This seems like the least obtrusive.
2) Block unit submission or disable unit submission when comments are open.  Safest in terms of discovering intention but most disruptive and could be confusing if you are blocked with unit submission and you can't work out why.

**Comment by julen** [comment]
Closing per the last comment.
