### ISSUE TITLE
New comment does not appear immediately

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2364]
When you add a comment to a unit that has no comment it does not appear immediately.

Problem:
Because the comment does not appear you think you messed up and try again.  We need to see the comment so that we know what we did worked.

To reproduce:
1) Go to a unit with no comment
2) Click 'Add comment'
3) Add some text and submit
4) Comment does not appear
5) Refresh unit, comment appear

**Comment by julen** [comment]
Not valid anymore, closing.
