### ISSUE TITLE
Once you have added a comment you can't add another

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2365]
If you add a comment you lose the 'Add comment' link.  So you can't add another comment or correct the one you've just made.

While being able to add many comments could cause some sort of comment pollution, the fact that you lose the ability is rather confusing.

Solution:
1) Don't ever remove the 'Add comment' link.
2) Or, allow someone to edit their just submitted comment.

**Comment by julen** [comment]
Not valid anymore.
