### ISSUE TITLE
inconsistent handling of newlines

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2370]
*See also:*
 * http://bugs.locamotion.org/show_bug.cgi?id=2659

When newlines are entered in the online editor with the enter key, the unit is shown with \n and newlines) when the unit is shown above. However, on the next visit, the newlines are gone, so it wasn't truly stored in the database with newlines.

In other words if you enter
koei
koei
koei

it will show after submit as
koei\n
koei\n
koei\n

but on the next visit to the unit will show as
koeikoeikoei

Before we've wanted users to type '\n' to signify a newline, so I think this is a bug in the JS highlighting code that populates the unit as you submit (that doesn't come from the server, as far as I remember).

**Comment by doerler** [comment]
Is there any progress on this. From my point of view handling line breaks should be a basic feature of such a tool - or am I wrong. We would love to use pootle for some projects but the missing support for linebreaks is a real show stopper.

+1 for correct newline/linebreak handling

**Comment by julen** [comment]
Thank you for your input @doerler. This is indeed being handled as part of the work in #3941, which obsoletes this bug request basically. I suggest you subscribe there if you wanna get the latest updates.
