### ISSUE TITLE
Unfortunate icon/text placement

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2428]
*See also:*
 * http://bugs.locamotion.org/show_bug.cgi?id=2268

*Created [attachment 856](http://bugs.locamotion.org/attachment.cgi?id=856)*

Screenshot

We have some unfortunate layout at times with regards to how text is shown relative to their icons. In the attachment, you can see how the filename is displayed underneath the file icon, and the sorting icons in the table headings is not consistently next to the heading. It seems like this would always happen on both my 13" and 15" screens, unless the browser is running full screen, or I reduce the font size to really small.

**Comment by unho** [comment]
No longer relevant.
