### ISSUE TITLE
Little indication if suggestion was successful

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2461]
When giving a suggestion for the last/only unit, we show the message at the bottom "You finished with everything". Even when this disappears, the new suggestion isn't shown in the list. This might give the impression that nothing happened.

We might want to reload the suggestions with AJAX (I don't think any current view exists) or manually enter it with JavaScript (sounds harder). Doing a refresh of the page (or just the editing unit) is maybe slightly inelegant solution, but might be easiest and quite ok.

Another possibility is to "disable" the editing unit after having finished going through things, to enforce the idea that it is finished. Doesn't sound very attractive immediately.

**Comment by julen** [comment]
We now return to the previous screen prior to entering the editor, therefore closing.
