### ISSUE TITLE
Special handling of the templates directory

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2490]
We need special handling of the templates directory.  The new overview page is optimised for things that need translations, not the reference templates.
# Action

We might want to wait and deal with this together with how we handle other abstract ideas e.g. goals, terminology.

My ideal would be that we treat templates apart from languages, in that way there is no confusion and it doesn't even need to be displayed to non-admin users.  It would also allow a slightly different overview view for templates.

**Comment by jleclanche** [comment]
@dwaynebailey whats this?

**Comment by phlax** [comment]
fixed in #5813
