### ISSUE TITLE
Facility to lock strings for further editing in tool

### ISSUE THREAD

**Issue by aalam** [translate/pootle#2494]
Following is copy of bug filed for gettext [http://savannah.gnu.org/bugs/?37236] to add facitility.
--
There is a great need to provide facility in .po file to lock the strings for further editing. It is always very difficult for a coordinator or commmitter of any project to track change of all the translation again. So there should always be a facility so that a coordinator or a community can lock the strings so that file can be translated/editable only for new or fuzzy strings.

The benefit of this facility is great. Assume, if one community thinks that present translation of 'gedit' is fine for their locale, the community can lock all the strings or some strings where they are having consensus that these are fine. In this process the usability will be increased much and review will become very easier. 
----
 Same time it is possible to add faciility in Tool, which can be good feature.

This feature may be possible to add in translate-toolkit, but filing for pootle as web-tool to start with

**Comment by julen** [comment]
We're gonna address this as part of implementing further export functionalities, therefore closing this for the time being.

**Comment by aalam** [comment]
thanks for update. I will look forward once fixed.
