### ISSUE TITLE
Users need instructions on how to remove themselves from Pootle notifications

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2505]
Users who get email based on their settings to join a Pootle project are not able to easily unsubscribe.

As the following email demonstrates:

```
On 7 September 2012 23:44, Kyrié Humphrey <kyrie.humphrey@gmail.com> wrote:

    Hi,
    can i be removed from this mailing list?
    Thanks
    2012/9/7 <pootle-registration-noreply@pootle.locamotion.org>

        Hi,

        Quick reminder that 10 September is our first cut-off where we will produce language packs and push translations to Mozilla.  If you haven't already please focus on making sure all the critical translations are up-to-date for your language.

        Have fun,
        Dwayne
```

While my first response is you signed up for this, it does present a problem of admin overhead.

Problems:
1) Email address looks odd and maybe we need to look at that cause it isn't registration
2) Don't explain to people why they are receiving this
3) Don't allow people to opt-out
4) Don't tell people how to unsubscribe

Solution:
=========
The quick solution is probably to address 2) and 4) just by adding the needed text such as:

"You are receiving this email because you selected Mozilla Firefox - Afrikaans as a project that you wish to watch.  If you no longer wish to receive these email then please change your settings to exclude this project."

**Comment by julen** [comment]
Such notifications are gone, closing.
