### ISSUE TITLE
Overview actions that take a long time have no busy indicator

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2507]
Both Rescan project folder and Update against template can take a long time yet there is no busy indicator.

Since we know how many files are impacted it would be great if this was actually a progress bar. But just the normal busy indicator would be helpful.

**Comment by unho** [comment]
@julen @jleclanche @dwaynebailey Is this still relevant now that we use RQ?

**Comment by jleclanche** [comment]
No

**Comment by dwaynebailey** [comment]
@jleclanche @unho RQ only removes the stats bottleneck from any long running tasks.  It doesn't remove uploads of ZIPs or any actions that are long running.  So no this isn't really fixed and I think needs a relook based on the impact of long tasks on 2.7.0 era Pootle.  I'll leave this closed as our long running tasks will hit us again with things like uploads and downloads and we can address them there by using RQ and we'll address others by using RQ and by making them work more independently of Pootle
