### ISSUE TITLE
Add project wide developer comments within Pootle

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2529]
Developer comments are a way to communicate information to all teams.  But in PO files these are extracted from the source.  Yet the experts who need to define them are most likely translating the strings and have no access to the code.  With the ability to add a developer comment certain enabled translators or editors can improve the ease of translation by adding more meta information for a string.

Implementation
==============
Allow someone with the correct rights to add a developer comment within Pootle.  These comments are to be saved to the DB as well as exported with the PO file.  The comment should be marked as special (so that we can track and handle it).  A change of the comment in Pootle should overwrite any existing comments for that unit so that when it is exported we use the new comment.

To investigate
==============
Using #. will protect the field from translators but would eliminate it with any gettext tools.  So need to chose which makes the most sense.

The rights could be a new right or an extension of some existing right.  New rights make things cluttered without any rights groupings.  While overloading makes it unclear what each right brings.

**Comment by julen** [comment]
Closing, will re-create when needed.
