### ISSUE TITLE
Attach screenshots to a unit

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2530]
A screenshot allows a translator to see how their unit will appear in the final product making it easier to implement a translation that works for a given language.

### Implementation
Someone with correct rights should be able to upload a file to be associated with a unit.  The image should be stored on the Pootle server and accessible online.  The link to the image should be added as a developer comment so that it can be displayed and behave like a thumbnail image.  The image should be stored using some sort of hash which would then allow the same image to be uploaded and used for other units.

### Concerns
We need to check that the file format is correct and file size is within some reasonable limits.

**Comment by julen** [comment]
Closing, will re-create when needed.
