### ISSUE TITLE
Disabled textarea is not informative enough

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#2552]
Bug #1785 fixed the problem where editable textareas were displayed for Pootle users without Submit or Suggest permissions. As a result, these are disabled now.

However, I don't think that this makes the situation clear enough, because when empty, a disabled textarea looks confusingly similar to an enabled one. I have two ideas about this:
a) explain in the disabled textarea that the user lacks permissions. E.g. set its contents to something like:
You don't have the permissions necessary to submit or suggest translations.
b) simply hide both the textarea and the fuzzy checkbox. This could also be accompanied by an explanation in a separate div, for example.

**Comment by unho** [comment]
@julen I think is fixed on new master, isn't it?

**Comment by julen** [comment]
We don't display any buttons or fuzzy checkboxes, but no explanation is given as to why the user cannot contribute.

**Comment by unho** [comment]
I think current status is enough to consider this as fixed, so closing it.
