### ISSUE TITLE
Reuse merging logic for update_stores

### ISSUE THREAD

**Issue by julen** [translate/pootle#2564]
Depends on:
* [ ] #2563 Factor out merging logic

Currently update_stores doesn't have proper merging logic the same way as uploads or VCS updates have. Once the merging logic has been factored out in bug #2563, we need to reuse that work for update_stores.

**Comment by dwaynebailey** [comment]
@phlax @julen is this still relevant with changes to Store.update() and Diff code?

**Comment by phlax** [comment]
no i would say this has been addressed
