### ISSUE TITLE
Exported PO files use only the firstname field

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2588]
Its seems that exported PO files use only the first name field and not first name + last name.

This was reported on IRC:

ChrisOelmueller

something i *really* would love to understand for a while:
pootle offers a profile with first and last name
yet when writing authors in .po files, only the first name is considered
cf. http://git.io/rp9giQ

Solution
========
First need to check if the above is in fact true
Probably just concatenate the two even if it doesn't work for everyone
Or
Hide last_name and relabel first_name so that we can use that as the only field.

See https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/models.py#L1501

**Comment by unho** [comment]
@julen @dwaynebailey @jleclanche I think this should be fixed now we merged "First name" and "Last name" into "Full name", isn't it?

**Comment by jleclanche** [comment]
It should be, yes, but either way I don't think this was ever actually an issue.

**Comment by dwaynebailey** [comment]
@unho @jleclanche was testing not an option?

**Comment by julen** [comment]
FTR: the exported header uses the value of the `User.display_name` property, which in turn returns the full name if available, username otherwise.
