### ISSUE TITLE
Empty project/language rows can be selected for actions in admin pages

### ISSUE THREAD

**Issue by ChrisOelmueller** [translate/pootle#2592]
1) Enter admin panel
2) Click on any project in Projects
3) Select the box saying "Update from templates"
=> Notice that it highlights all projects on this page and additionally the empty line on the bottom that's supposed to help adding projects
4) "Save Changes" now yields

Cannot assign None: "TranslationProject.language" does not allow null values.

I didn't test much with the delete buttons for projects or languages but suppose that similar issues also happen there.

Since users can still manually select the box belonging to the empty rows even if the select-all functionality is fixed, it might be reasonable to hide the boxes entirely for that row.

**Comment by julen** [comment]
Not applicable anymore with the new admin UI.
