### ISSUE TITLE
User suggestions should contain a date

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2595]
Depends on:
* [x] #2712 Make use of a single Suggestion model

Currently there is no date and time for a user contributed suggestion.  We should use the same approach that we used in bug #2361 to show date and time in the timeline.

**Comment by unho** [comment]
This is now fixed on new master. See https://github.com/translate/pootle/blob/ba74f868/pootle/apps/pootle_store/models.py#L166-L167.
