### ISSUE TITLE
Filter by strings which are untranslated and have no suggestions

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2604]
*Originally posted by Ben Hearsum:*

My normal workflow for translating is to go through all of the strings that have absolutely no translations. The project I work on (Tagalog Firefox) tends to go through suggestions in a batch, so many strings have many suggestions (but no accepted one yte), but some strings have no suggestions at all. Currently, it's not possible in Pootle to go through just the latter set. This isn't the end of the world, but it's a pain for any project that prefers to approve strings in a batch rather than approving them as they come in. This probably only comes into play for new localizations on big projects -- small projects don't have enough strings to where it matters, and existing localizations of large projects have few new strings to translate.

**Comment by julen** [comment]
Closing in favor of #1900.
