### ISSUE TITLE
User can review own suggestions

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2631]
*Version: 2.1.x*

*Originally posted by Zeki Bildirici:*

Hello,

I am contributing LibreOffice translations. We are using Pootle 2.5.0-beta1.

While translating, i figured out a user can review its own sugestions. Which makes nosense.

In previous versions Pootle has no history info for string. But in this version, it is availbale, so it will be very good to restirct users reviewing their own suggestions.

Best regards,
Zeki

**Comment by dwaynebailey** [comment]
Closing.  In suggestions we can accept/reject. It isn't really a review process.  If it is the team should manage that themselves.
