### ISSUE TITLE
Markdown can't parse URLs like https://wiki.mozilla.org/L10n:Teams:shn

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2649]
See http://mozilla.locamotion.org/shn/firefox/

Where there is a link to the Shan team page entered in Markown as:

`[Shan team](https://wiki.mozilla.org/L10n:Teams:shn)`

While this is an upstream bug in markdown itself, just adding it here as this directly impacts us when hosting Mozilla files.

**Comment by jleclanche** [comment]
@dwaynebailey is this relevant still? news are gone, anything else in markdown left?

**Comment by unho** [comment]
@jleclanche Staticpages still use a field that allows to use markdown: https://github.com/translate/pootle/blob/master/pootle/apps/staticpages/models.py#L54

**Comment by dwaynebailey** [comment]
We can't and shouldn't solve probems with external libraries here.
