### ISSUE TITLE
Allow adding of 'developers' comments to share across a project

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2658]
Original request from Igor:
"Add an ability to change the 'developer comment' (controlled by a separate permission). When such a developer comment is added, it is saved to both Pootle database and synchronized to the .po file as a special comment (#.pootle: Text goes here). If such special comment was added to Pootle for a particular unit, it should overwrite any exisitng comments starting with '#.pootle:' on update_stores."

Problem:
You want to easily improve the quality of information shared with translators.  This could be correction of a developer comment or addition of a developer comment.

Requirements:
1) This would need to work within existing Gettext workings

**Comment by julen** [comment]
Closing, will re-create when needed.
