### ISSUE TITLE
End of filter message offscreen when units are large

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2664]
If you reach the end of filter message and you have large units you will find that:

1) The screen goes into modal mode
2) You don't see any message
3) If you scroll up the message is available higher up the screen

Problem:
Most users won't know to scroll

Solution:
Make the modal dialogue centred on the currently viewable part of the screen as opposed to the virtual screen.

**Comment by julen** [comment]
This message is not displayed in the editor anymore.
