### ISSUE TITLE
Server name and description not localised

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2665]
In Pootle 2.1, the default server name and description could be localised for a more fully localised experience on first run. This also enables people to translate their own descriptions if they want to bother regenerating the .mo files, etc. We seem to have lost this somewhere. The strings are marked in the .conf files but not extracted.

I guess this is not high enough priority now, but would be nice to fix the regression at some stage, so I'm adding this hear so it doesn't go forgotten.

**Comment by unho** [comment]
@julen Do we still have server description on master. I know it has been removed, but I am not sure if somehow you recovered it back in a new way.

**Comment by julen** [comment]
Nope.

**Comment by dwaynebailey** [comment]
This is a bit outdated, there are parts of this that need addressing but it becomes site specific and we need to rather work out a better way to allow localisation for an installation e.g. site name, static pages, etc.  Thus closing.
