### ISSUE TITLE
Update X-POOTLE-MTIME format timezone

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2669]
As part of solving the timezone issues, we assume that the uploaded files with `X-POOTLE-MTIME` header had this time generated in Africa/Johannesburg time (the default with Pootle 2.1). We need to generate this in a new format (maybe similar to the PO-Revision-Date header) to be able to identify files originally downloaded from Pootle 2.5. Otherwise we'll from now on always be two hours out in this calculation.

The relevant code is in `pootle/apps/pootle_store/models.py`

**Comment by julen** [comment]
We now use a django utility function which in turn takes into account the server timezone setting when creating the unix epoque timestamp.

**Comment by julen** [comment]
We now use a django utility function which in turn takes into account the server timezone setting when creating the unix epoque timestamp.
