### ISSUE TITLE
Incorrect URLs rendered for user profiles in the 'News' section

### ISSUE THREAD

**Issue by iafan** [translate/pootle#2671]
See http://translate2.evernote.com/pootle/ -> Latest News block -> New user _xxxxxx_ registered. Profile links there are missing the root /pootle/ part (e.g. they are rendered as http://translate2.evernote.com/accounts/xxxxxx/ instead of http://translate2.evernote.com/pootle/accounts/motionthings/

**Comment by julen** [comment]
Not applicable anymore.
