### ISSUE TITLE
Duplicate "flags" comment lines end up getting stripped by PoEdit

### ISSUE THREAD

**Issue by jake** [translate/pootle#2687]
*Version: 2.1.x*

*Created [attachment 884](http://bugs.locamotion.org/attachment.cgi?id=884)*

File as generated by Pootle, with duplicate flags.

We have an automated script that runs the following every 5 minutes:

```
header "Exporting database changes to disk"
django-admin sync_stores --project=tumblr-web --settings=pootle.settings

header "Rebuilding template file"
[xgettext script to update template file]

header "Committing changes to repo"
django-admin commit_to_vcs --project=tumblr-web --user=jacob --settings=pootle.settings

header "Updating files on disk with changes from repo"
django-admin update_from_vcs --project=tumblr-web --settings=pootle.settings

header "Updating files from templates"
django-admin update_from_templates --project=tumblr-web --settings=pootle.settings

header "Committing changes to repo"
django-admin commit_to_vcs --project=tumblr-web --user=jacob --settings=pootle.settings
```

When pootle guesses a translation match, it adds a new entry similar to this.

```
 # 85%
 #: app/[...].php:514
 #, fuzzy, php-format
 msgid "Posted to %1$s"
 msgstr "Publié le %1$s"
```

The next time the above build script runs, it updates the entry with a duplicate flag comment, rather than merging with the existing comment (or rather, failing to realize the exiting comment already has "php-format" defined). Example:

```
 # 85%
 #: app/[...].php:514
+#, php-format
 #, fuzzy, php-format
 msgid "Posted to %1$s"
 msgstr "Publié le %1$s"
```

When the file containing the duplicate flag is opened in PoEdit, it ends up stripping the second line, effectively marking the string as un-fuzzy.

```
 # 85%
 #: app/[...].php:514
 #, php-format
-#, fuzzy, php-format
 msgid "Posted to %1$s"
 msgstr "Publié le %1$s"
```

Sadly we can't upgrade to the latest Pootle until it's stable. I searched but I couldn't tell if this has been fixed in the most recent version. Sorry if this has already been patched.

**Comment by dwaynebailey** [comment]
Unclear exactly which step is causing this.  We've also dropped update_against_templates so likely the problem goes away in a new automated apporach outside of Pootle.
