### ISSUE TITLE
Error Checks (Expand) takes too much time

### ISSUE THREAD

**Issue by arky** [translate/pootle#2707]
When you click the error checks 'expand' link for the first time it takes a lot of time (almost to 2.7mins) load.

(Logged with Firefox Web Console devtools)
[10:25:31.920] GET http://mozilla.locamotion.org/bn_BD/firefox/summary/ [HTTP/1.1 200 OK 166688ms]

**Comment by julen** [comment]
Stats are calculated and cached on bg jobs now, so this is not an issue anymore.
