### ISSUE TITLE
Pootle does not update the languages against a template changed in upstream VCS

### ISSUE THREAD

**Issue by unho** [translate/pootle#2756]
If you have a project which is integrated in a VCS, when the template is updated in upstream, if you tell Pootle to sync its local VCS copy (located in VCS_DIRECTORY) and then tell Pootle to update any language against the template, that language is not updated.

This is because the new template is not copied to PODIRECTORY and Pootle only works against PODIRECTORY, so the template Pootle sees has no changes and therefore the languages don't have to be updated. But in VCS_DIRECTORY the template is up-to-date and has changes that require the languages to be updated against this template.

**Comment by dwaynebailey** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
