### ISSUE TITLE
Stale statistics when making changes in the file-system

### ISSUE THREAD

**Issue by julen** [translate/pootle#2776]
It seems that the statistics cache is not properly invalidated when there have been modifications in the file-system.

Let's consider the following actions:

1) Delete/modify/add files directly in the filesystem
2) Run manage.py update_stores

At this point you are able to see the newly added files from the web UI (and removed files are not visible anymore)

If you browse the files and directories of a translation project, the stats have been updated, that's what the table displays. But in the root of the translation project, the summary still displays the old stats.

So it looks like the stats cache for the root folder hasn't been invalidated.

After running `refresh_stats --project=foo --language=bar`, there's no mismatch between the stats displayed in the summary and in the tables

**Comment by unho** [comment]
@julen Is this still relevant?
