### ISSUE TITLE
Provide the template to render for pootle_notifications app "view" view instead of having one template with a lot of ifs

### ISSUE THREAD

**Issue by unho** [translate/pootle#2823]
The template notices.html in pootle_notifications app is used for rendering three different scenarios: news for project, news for language, and news for translation project. Having a simpler template for each scenario will be better.

Julen suggests:
> Ideally one should be able to use that view ("view" view in
> pootle_notifications) by passing a custom template — that way you avoid
> having such if-else blocks in the template.
> 
> You could route the same view (the one in pootle_notifications) from
> pootle_project, pootle_translationproject and pootle_language URLs. Having
> the url patterns included in each of the apps (since it's specific to that
> app) but providing a custom template on each app. If you realize it's
> matching a generic ?<pootle_path>.

**Comment by julen** [comment]
This template is gone.
