### ISSUE TITLE
Implement versioning for static pages

### ISSUE THREAD

**Issue by julen** [translate/pootle#2830]
Static pages should be able to support multiple versions of the same page. For example, you could have different versions of the same ToS page that has been evolving over time.

Implementation-wise, there are third-party Django apps that add this functionality already; while some of them seem to be overkill, other options look like abandoned projects. We need to evaluate which option/approach better fits the use-case we have in mind and act accordingly.

**Comment by jleclanche** [comment]
So is this really something we want then?

**Comment by julen** [comment]
Overkill for Pootle, let's close it.
