### ISSUE TITLE
Per Locale/Project Contributor Metrics

### ISSUE THREAD

**Issue by arky** [translate/pootle#2833]
I would like to know all the contributors stats for a particular project/locale. At the moment we get only recent contribution stats. 

This would help us measure, credit and reward contributions made all individuals in the project.

**Comment by julen** [comment]
Code-wise this is possible with `User.top_scorers()` and the `top_scorers` template tag, it's just not exposed for every single scenario. Any deployment can adjust this to its needs, therefore closing.
