### ISSUE TITLE
Filter translations and suggestions by user

### ISSUE THREAD

**Issue by gueroJeff** [translate/pootle#2840]
Currently users with advanced permissions over a particular language are unable search for, retrieve, view, and edit submissions for a single user. This would be beneficial in evaluating a single user's contributions and translation skill. It would also be useful to identify users who are struggling to make accurate contributions and others who might be purposefully corrupting a project with their submissions.

**Comment by julen** [comment]
The end goal being checking user's specific contributions and translation skill over time, reports already offer that feature set. Closing.
