### ISSUE TITLE
Preview before submitting news

### ISSUE THREAD

**Issue by unho** [translate/pootle#2848]
Depends on:
* [ ] #2378 Use markup filters for news input

Add support for previewing the news before submitting.

This bug is splitted from bug http://bugs.locamotion.org/show_bug.cgi?id=2378

The original text is:

> 1) The ability to preview before posting, so that you can see what you are
> about to post.  Probably having a [Preview] button instead of submit.  This
> changes to [Submit][Change] when in preview mode.  Text entered is replaced
> by the preview text in Preview mode.

Perhaps this can be changed to having a [Preview] button, and when previewing show the buttons [Publish] and [Preview].

If a JavaScript preview is used perhaps the preview can be achieved by using a tab like in Github comments forms and just have a [Publish] button.

**Comment by julen** [comment]
The news feature is gone, closing.

**Comment by julen** [comment]
The news feature is gone, closing.
