### ISSUE TITLE
Commit all files to VCS from UI

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2863]
*Version: 2.5.0*

*Originally posted by Florent:*

Scenario:

-let's say you have 100 languages in your project.
-You have changed values for ALL theses languages and you are happy with it
-You want to commit all your languages in a raw.

=> As far as i know, you can't, you need to go on each language and click on 'Commit all to VCS'. This is quite time consuming.

It would be really nice to implement a "Commit all languages to VCS" at the root of the project.

Any suggestion ?

Florent Valdelievre

**Comment by julen** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
