### ISSUE TITLE
Permissions page not fitting well on screens 1024px wide

### ISSUE THREAD

**Issue by unho** [translate/pootle#2875]
There are some "issues" with elements not fitting well on screens 1024px wide.

See original comment in https://github.com/translate/pootle/pull/38#issuecomment-17057894

**Comment by unho** [comment]
I am now feeling the effects of not being descriptive enough when I created the issue. I think I was talking about the formsets with too much columns in the admin interface.

With the new admin UI this is mostly gone, except for the permissions pages.

**Comment by julen** [comment]
Scrolling is fine in this case, the permissions page needs a whole revamp anyway.
