### ISSUE TITLE
Styling of different input/form elements is totally inconsistent

### ISSUE THREAD

**Issue by unho** [translate/pootle#2876]
This later point raises the issue that now the styling of different input/form elements is totally inconsistent, and now it draws even more attention (compare the paddings and sizes of the elements).

See bug #2875

See original comment in https://github.com/translate/pootle/pull/38#issuecomment-17057894

**Comment by unho** [comment]
@iafan Is this still relevant?

**Comment by iafan** [comment]
@unho, the nav toolbar is styled properly now, closing
