### ISSUE TITLE
Running Pootle on Windows - symlink issues

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#2903]
@X-Cray wrote (in #63):
> I'm trying to set up Pootle on Windows. Obviously, when trying to set up VCS
> integration with Git I faced a problem with symlinks which Python 2 does not
> handle here. So, I've installed jaraco.windows and added the following
> sitecustomize.py to my env

Also modified  pootle/apps/pootle_store/models.py and replaced call to mtime.strftime('%s') with int(time.mktime(mtime.timetuple())

As I noted, there is another bug there, where "%s.%d" should be "%s.%06d" to correctly format microseconds.

**Comment by julen** [comment]
We don't support Windows on production, closing.
