### ISSUE TITLE
Custom commit message templates for commits to VCS

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#2906]
Chris Oelmuller (https://github.com/ChrisOelmueller) wrote
(in https://github.com/translate/pootle/pull/13):
> This PR deals with committing changes and with the commits caused by
> initializing new files from templates.
> The fallback message in python is supposed to be mostly failsafe and thus only
> replaces one variable. Most projects would probably still pick it over the
> current message, but the default message in 60-translation.conf aims to improve
> messages even more.

> For git folks: A first iteration of this included Reviewed-by: %(user)s lines
> for the default settings.
> I figured to omit it after some discussion, projects can still easily add the
> line if they are interested.

> Anything else that commitdata should hold?

Note that although the PR was closed by Chris, it wasn't because it was resolved - just that it had been in the PR queue so long that rebasing it onto the 2.5.+ master was more than he was interested in doing.  The issue still remains.

**Comment by julen** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
