### ISSUE TITLE
Java properties don't import properly

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2908]
*Version: 2.5.0*

*Originally posted by Florent:*

*Created [attachment 917](http://bugs.locamotion.org/attachment.cgi?id=917)*

Template and english translation

1) Project creation
-Create a new project 
  -File type = Java Properties ( UTF-8 )
-Quality check = standard
-Project tree Style
  -Non-GNU : Each language in its own directory
-Source language English - en

2) Add new language(en) and Templates

3) Upload a new template file ( attached : template/diabetes.properties )

=> First of all, we will notice that need "need translation" column = 0
I was expecting to have a number >0 as we did not provide any translation

4) Go in english click "Update against template"
=> I was expecting to have to have "need translation" column > 0

5) Try to upload en/diabetes.properties which contains the english translation
=> I was expecting to have to have "Total" column > 0, and "need translation" column = 0

The only solution i have found is to stick with po file on pootle and use prop2po + po2prop which i find cumbersome.
If a developer need to add a key which needs to be propagated to the languages files, he needs to

- Add his key into his template.propertie
- Prop2po
- Upload into pootle
- Update against template
- Translate 
- Download the latest localization
- Po2prop

If pootle managed to handle Java properties file, he would avoid doing prop2po + po2prop each time he changes a key.

Any suggestion ?

**Comment by dwaynebailey** [comment]
Monolingual files are being reworked post 2.7.0 so closing for now.
