### ISSUE TITLE
Regenerate URL is broken

### ISSUE THREAD

**Issue by arky** [translate/pootle#2915]
Always call terminology_extract.html from the app baseurl 

1. Change language (here: Vi)
2. Go into terminology subdirectory (vi/terminology/essential.po/terminology_manage.html) 
3. Click on  "You can regenerate the glossary from scratch" link 
4. You'll get a 404 (vi/terminology/essential.po/terminology_extract.html)

**Comment by julen** [comment]
Not reproducible anymore, closing.
