### ISSUE TITLE
Legal Agreement: Display content in text area

### ISSUE THREAD

**Issue by arky** [translate/pootle#2916]
*Created [attachment 920](http://bugs.locamotion.org/attachment.cgi?id=920)*

Legal Agreement

Please show the legal agreement content in a text area. 

Here a mockup:

		    +--------------------------------------+
		    |  Action Required      	       	   |
		    |                          	       	   |
		    |   +-------------------------------+  |
		    |   |                               |  |
		    |   |                               |  |
		    |   |                               |  |
		    |   |                               |  |
		    |   |                               |  |
		    |   |                               |  |
		    |   |                               |  |
		    |   +-------------------------------+  |
		    |	I have read and accept+-------+	   |
		    |                         +-------+	   |
		    +--------------------------------------+

**Comment by unho** [comment]
@iafan @julen @arky @dwaynebailey @jleclanche Should we close this issue then?

**Comment by julen** [comment]
Yes, the agreements are displayed in a lightbox and are scrollable there, we won't display them in a textarea especially because of the reasons outlined above.
