### ISSUE TITLE
Report a problem with source string feature for mozilla projects

### ISSUE THREAD

**Issue by arky** [translate/pootle#2917]
It would be nice to have 'Report a problem with source string' option for mozilla projects. 

Use-Case: There were instances where we found the source strings had typos or were badly broken. 

When a user clicks the we pick the store string and redirects the user to bugzilla.mozilla.org bug report form with <project_name> component selected.

You can see this (non-working) icon here:
http://staging.locamotion.org/zh_CN/birdfont/translate.html

**Comment by unho** [comment]
@arky Can you please provide the required input?

**Comment by arky** [comment]
@julen Definitely duplicate of bug #2168
