### ISSUE TITLE
Improve extension action download handling with redirects

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#2918]
In the work for bug #2868, I tried to use HttpResponseRedirect and redirect calls to immediately take the user to a just-generated download file.  However, any and all attempts to use either kind of redirect left the user at a failure screen that started with something like this:

Server Error

An error has occurred. Thank you for your patience.

Failed lookup for key [directory] in u'[{}, {\'csrf_token\': <django.utils.functional.__proxy__ object at 0x7f1c96bd1390>}, {\'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f1c96bd1410>, \'user\': <django.utils.functional.SimpleLazyObject object at 0x7f1c94d4d5d0>}, {\'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f1c96880510>}, {\'LANGUAGES\': [(\'ach\', \'ach\'), (\'af\', u\'Afrikaans\'), (\'ak\', u\'Akan\'), (\'am\', u\'Amharic\'), (\'ar\', u\'Arabic\'),
...

This is with the extension action commits on the test/extension-actions branch based off of stable/2.5.0 - I haven't been able to test the feature/extension-actions branch off of master.

I will close bug #2868 since it is possible to get download files without these (currently commented out) redirects - you just have to click on the Download link two (or more commonly three) times, which is very annoying, but can be lived with for now.  However, it would be very nice to eliminate this problem.

**Comment by julen** [comment]
Not applicable anymore.
