### ISSUE TITLE
Flush cache admin feature

### ISSUE THREAD

**Issue by iafan** [translate/pootle#2927]
Would be nice to have a 'Flush Cache' button on 'Administration / Info' tab (provided caching is enabled), which would do the following:

```py
from django.core.cache import cache
cache._cache.flush_all()

This is to avoid restarting memcached or any other possible cache backend, because a) Pootle admin might have no rights to restart the service and b) restarting caching backend as a whole might invalidate data unrelated to Pootle or not invalidate nothing.

**Comment by unho** [comment]
@iafan I see a `flush_cache` command in https://github.com/translate/pootle/tree/ba74f868/pootle/apps/pootle_app/management/commands, so is this still not fixed?
