### ISSUE TITLE
Pootle Admin lacks the ability to post entries to latest news.

### ISSUE THREAD

**Issue by hbayindir** [translate/pootle#2962]
[Note: This bug is related to standalone installation of Pootle]
Pootle has an RSS feed feature which shows developments on the web page. This feed is also useful for site administrators for announcing some improvements over the site, maybe upcoming maintenance announcements and such.

However, Pootle administration panel lacks the ability to insert new entries to the latest news feed. While this can be done via inserting rows into the table inside the database, the fact that not every Pootle admin is a system admin and has access to internals makes this choice infeasible.

Implementation of a small panel for adding entries to news feed or administering them will be a great improvement.

**Comment by julen** [comment]
The news feature is gone, closing.
