### ISSUE TITLE
Punctuation highlighting

### ISSUE THREAD

**Issue by arky** [translate/pootle#2965]
*Created [attachment 928](http://bugs.locamotion.org/attachment.cgi?id=928)*

Highlighting '...'

The vietnamese localizers reported they were confused by doted border of punctuation highlight. (see attached screenshot)

http://mozilla.locamotion.org/vi/firefox/user1/translate.html#filter=suggestions&unit=2508065

**Comment by dwaynebailey** [comment]
I think the current UI is fine for this.  So closing unless its highlighted again.
