### ISSUE TITLE
Command-line client for Pootle API

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#2968]
Depends on:
* [ ] #2874 Add basic API to Pootle

*Version: 2.5.0*

This requires:

    The CLI should allow easy non-shell access to Pootle projects via web API

        Examples: create and delete a project, create users, add them to a project

        Upload and download files

        Get stats

        So very much mirrors what the API would provide

    CLI commands most likely map closely to the resource

        ptl user create dwayne

        ptl project create firefox

    Trickier for translation project / store / unit, embedded in hierarchy

        use ‘create’ for independent objects (language, project)

        use ‘add’ for objects embedded in hierarchy

**Comment by dwaynebailey** [comment]
Closing in favour of bugs opened against planned ptl tool
