### ISSUE TITLE
Unified multi-format Download action for stores

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#2974]
*Version: 2.5.0*

In bug #2966, Dwayne Bailey wrote (in ```BZ-IMPORT::comment #2```):
> The idea I've always thought would work would be if there was a single URL
> and icon. The icon shows a dropdown menu of other download formats and
> initiates a download.  Not sure how hard that is to code though.

The intention of this is to unify the "Download" and "Download XLIFF" actions in the "Translate offline" category (as well as provide other format options, such as PO and possibly others)

As part of the purpose of this ticket is to "simplify" the interface for translators, we surely do not want to offer all possible formats.  XLIFF and PO may well be the only ones, although there might be one or two others (perhaps configurable by an administrator - either globally or on a per-project basis).

For monolingual formats, we might want to offer a .zip containing the source and target files (this would be new functionality).

Of course, we want the first (and default) format option to be the actual source format (or perhaps .zip for monolingual formats).

It is unclear whether it would make sense to provide this type of drop-down choice functionality for translation project / directory, or whether it would be restricted to stores.  The discussion in bug #2415 may be relevant to that decision.

**Comment by dwaynebailey** [comment]
Closing in favout of planned features around export interaction.
