### ISSUE TITLE
commandline updating from templates does not add a news entry

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2977]
*Version: 2.5.0*

*Originally posted by Michiel Dethmers:*

when you run "Update from templates" in the interface it adds a news entry saying "Updated from templates" with some stats on terms.

When you run the same command on commandline, this entry is not added. It is quite useful to see this, just to have a language history.

I have a regular cron to automatically do this, as I think there is no need to manually do it on the interface.

**Comment by julen** [comment]
The news feature is gone, closing.
