### ISSUE TITLE
Make translation toolbar fit to device width

### ISSUE THREAD

**Issue by arky** [translate/pootle#2979]
Let us try to get bottom toolbar in translation pages to fit the full device width. The toolbar elements search, filters inherits too much min-width and padding causing the toolbar to wrap. 

To reproduce this bug, Please use the Firefox responsive view mode or resize your window.

**Comment by unho** [comment]
@iafan @julen I think this is fixed in new master, isn't it?

**Comment by julen** [comment]
Yeah, closing.
