### ISSUE TITLE
ascii error while updating a UTF-8 file against template

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2980]
*Version: 2.5.0*

*Originally posted by Samual Lenks:*

*Created [attachment 930](http://bugs.locamotion.org/attachment.cgi?id=930)*

Spanish translation file that errors

If I try to update against template against the Spanish game menu translation in my project, I get this error:

Server Error

An error has occurred. Thank you for your patience.
'ascii' codec can't encode character u'\xf3' in position 9: ordinal not in range(128)

However, I'm pretty sure that the file IS encoded in UTF-8, the exact same as all the other translation files in my project, and I have no idea why this error occurs only on this file.

I've attached the file that errors.

**Comment by julen** [comment]
Update against templates is gone, closing.
