### ISSUE TITLE
Users suggestions not shown on user page

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2984]
A hindi user made this recent contribution:

http://mozilla.locamotion.org/hi_IN/firefox/translate.html#filter=suggestions&unit=1551354

Yet this is not reflected on their user page:
http://mozilla.locamotion.org/accounts/Shweta/

There are some possible reasons:
1) Some suggestions where made in April, though the one above was made within the last week.  So the missing suggestions in the user page could be because these happened before our upgrade.

2) This might relate to the two suggestion models

3) Some other reason, e.g. capitals in username that prevent us seeing things

However, we have other users with submissions that are far earlier that appear correctly.  It is hard to see when suggestions where submitted as there is no date.

**Comment by unho** [comment]
@translate/core This seems to still be valid. If a user send a suggestion on its statistics the number of translated and reviewed doesn't increase, but its score does.

**Comment by dwaynebailey** [comment]
That page doesn't exist anymore and the data is migrated (as best as we can) to the new scoring stuff.  The comment by @unho sounds more like the issue that accepted suggestions don't change counts.
