### ISSUE TITLE
Editing site title or description in admin UI makes impossible to set them via config file

### ISSUE THREAD

**Issue by jaywink** [translate/pootle#3001]
*Created [attachment 931](http://bugs.locamotion.org/attachment.cgi?id=931)*

IRC log

In settings/90-local.conf (or any other of the settings files) if I add TITLE and DESCRIPTION it should populate to be visible in the site.

This happens except if the user sets a title or description form the admin menu after which the config file changes have no effect any more. The values can now only be edited via the admin menu and they are saved in the db in table siteconfig_sitesettings.

Expected (as an admin): To have config file changes update in site (and thus in DB settings as well) OR (better) be warned in the config file that I cannot edit the values via config files if they have been set via Admin UI.

What happens: No mention in documentation or config file about issue.

Added IRC log if issue is not clear.

**Comment by unho** [comment]
No longer relevant.
