### ISSUE TITLE
Make Submission use a larger set of submission types

### ISSUE THREAD

**Issue by unho** [translate/pootle#3011]
_See also:_ #3104

Making pootle_statistics.models.Submission use a richer set of submission types would help keeping track of each single change made by a user.

Right now it is impossible to tell if a submission involves sending a new translation for a unit or marking it as 'needs work', unless the related unit is queried.

Another example is that it is impossible to tell if the submission was to suggest a possible translation without checking if there is a relationship to a Suggestion.

**Comment by julen** [comment]
This is not applicable anymore.

**Comment by julen** [comment]
Came across [some comment in the source code referencing this issue](https://github.com/translate/pootle/blob/e71a3e0427848d8b2f8a7ec386f7b7aa3aee2fbc/pootle/apps/pootle_statistics/models.py#L237-L272), so reopening until that's addressed.

**Comment by phlax** [comment]
closing this as the target is too broad, submissions have changed since it was opened, and we are currently refactoring them
