### ISSUE TITLE
Put models on pootle_store on separate files

### ISSUE THREAD

**Issue by unho** [translate/pootle#3012]
Putting models on pootle_store on separate files will ease developers look at their code.

Splitting in several files shouldn't be a problem if they are put on the same module named models and making the relevant elements available at module level using `__all__` on  `__init__.py` like in https://github.com/translate/pootle/blob/master/pootle/apps/pootle_app/models/__init__.py

**Comment by julen** [comment]
Closing in favor of #3656.
