### ISSUE TITLE
New language is lost when added http://mozilla.locamotion.org/ky/

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3025]
I added ky to the Firefox project on http://mozilla.locamotion.org/

The breadcrumb dropdowns started behaving oddly.  If you go to http://mozilla.locamotion.org/ky/ then the dropdown says "All languages" since somehow ky is not available. 

My guess is that it is because of translate/lang/data.py::_fix_names which rewrites the language names.

**Comment by julen** [comment]
This was already fixed in #3320.
