### ISSUE TITLE
Error when importing .xlf file with alt-trans element

### ISSUE THREAD

**Issue by andreaswolf** [translate/pootle#3027]
*Version: 2.5.0*

*Created [attachment 934](http://bugs.locamotion.org/attachment.cgi?id=934)*

Backtrace when opening the project after the import went wrong

When importing XLIFF files from my VCS repository, I get an error (and subsequently the project is broken) when there is a alt-trans element in a file.

The file has been generated as is by a Pootle 2.1.6 instance I hosted locally, and now while trying to connect the VCS repository (Git) to a new 2.5.0 instance, I get the attached backtrace. Sorry that it's partly in German, I did not manage to get a fully english trace even when starting Pootle with LANG=C set on my command line.

**Comment by dwaynebailey** [comment]
Closing, needed more feedback
