### ISSUE TITLE
Continuous unit loading

### ISSUE THREAD

**Issue by julen** [translate/pootle#3029]
Pootle loads units on-demand, but it always keeps the same number of units on screen. It would be nice to have a continuous unit loading, therefore being able to quickly jump to specific units without going through pages (this would consequently remove the notion of pages).

Since units can be arbitrarily loaded, the infinite scrolling must work vertically in both directions.

**Comment by unho** [comment]
@julen Isn't this already fixed in new master?

**Comment by julen** [comment]
Not yet.

**Comment by phlax** [comment]
i believe this functionality is now available
