### ISSUE TITLE
Tagging: Enhance tag editing interface for TranslationProject with Select2 component

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#3040]
Depends on:
* [x] #3035 Tagging: Add interface for managing TranslationProject tags from TP page
* [x] #3036 Tagging: Add interface for managing TranslationProject tags from Project view

While it will be desirable for users without JavaScript (or perhaps with visual impairment that makes JavaScript-based UI less usable) to be able to add and remove tags, it is expected that most users would prefer a Select2 AJAX interface for adding to and removing the tags for a Translation Project.

This ticket is for enhancing the basic tag filtering functionality in bug #3035 and bug #3036 with Select2 for a more dynamic user interface, including the ability to create new tags when adding them to a particular Translation Project.

**Comment by unho** [comment]
Tags have been dropped and might be reimplemented, so this is no longer applicable.
