### ISSUE TITLE
Tagging: Add admin interface for deleting/renaming tags

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#3041]
Depends on:
* [x] #3034 Tagging: Add initial version of core tagging functionality

As users create tags dynamically, they can always simply remove the tags from objects and add new tags with a different name, so it is not necessary to have the ability to edit the names of tags or to remove them from the global tag namespace.  However, over time, old or unused tags may accumulate and will clutter the selection options displayed via Select2.

This ticket is for the work to create an admin interface to the tagging namespace, allowing tags to be deleted (and possibly renamed as well).

Tags that are not used must be deletable; allowing deletion of tags that are in use would be nice, but is not a requirement.

Renaming of tags is not a requirement either, but if not too difficult, could be allowed here as well.  Note that renaming a tag to a name already in use as a tag should not be allowed.

Finally, a manage.py command for deleting all tags that are not in use would be nice to have (for automatic cleanup from a daily cron file) but this is not a requirement either.

**Comment by unho** [comment]
Tags have been dropped and might be reimplemented, so this is no longer applicable.
