### ISSUE TITLE
Tagging: Enhance tag editing interface for TPs on Project page to allow (un)tagging multiple TPs at once

### ISSUE THREAD

**Issue by dupuy** [translate/pootle#3042]
Depends on:
* [x] #3036 Tagging: Add interface for managing TranslationProject tags from Project view

This ticket is for enhancing the basic tag adding/removing functionality in bug bug #3036 to allow tags to be added to or removed from multiple translation projects at once.

**Comment by unho** [comment]
Tags have been dropped and might be reimplemented, so this is no longer applicable.
