### ISSUE TITLE
Unknown language code imported to existing language

### ISSUE THREAD

**Issue by brother** [translate/pootle#3049]
*Version: 2.5.0*

The git repositories hooked to the Pootle server had tt_RU.po files in them but no language was configured to read those files. We had tt for Tatar and ru for Russian as one would suspect.
The effect this had was that Russian dropped from 100% complete to 74% complete, the same as the value for the tt_RU.po files. Somehow somewhere Pootle found the tt_RU files and read them into the Russian language project.

After discussion at the IRC channel we added a secondary Tatar language code for tt_RU (named it Tatar (Cyrillic)) and it picked up all the tt_RU files. After that was done we updated all the projects for Russian from VCS and it got back to 100% translated.

I could imagine this being a big problem if you would add pt_BR into pt or something like that. There are probably worse examples out there.

**Comment by jleclanche** [comment]
@julen do you know if this is still valid in core?

**Comment by julen** [comment]
FWIW there's no VCS support.

**Comment by julen** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
