### ISSUE TITLE
update_against_templates overwrites files instead of merging

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3052]
*Originally posted by Armin Besirovic:*

If the templates file has translations, update_against_templates will overwrite the translated files from other language. To reproduce:

- make a new csv-based project with english and german
- add en/test.csv:
```
source,target
"First","First"
"Time","Time"
```
- add de/test.csv
```
source,target
"First","Erste"
"Time","Zeit"
```
- do update_stores
- add new line to en/test.csv:
`"Third","Third"`
- run `update_stores --keep` then run `update_against_templates`
- the de/test.csv file is overwritten with the en/test.csv file

IMHO, when importing against templates there must be no overwrite and additional to that any new target string should be empty. I made a fork on github and added some changes which make this work but I'm not a python developer.

The changes I did can be seen here: https://github.com/adioe3/pootle/commit/7eaf7b17129fcfd0ec146027539718ba6b5d8671

If the devs think this is ok I will make a pull request.

**Comment by julen** [comment]
Update against templates is gone, closing.
