### ISSUE TITLE
[Android Resources] Update from templates overwrites translations

### ISSUE THREAD

**Issue by chhitz** [translate/pootle#3082]
*Created [attachment 949](http://bugs.locamotion.org/attachment.cgi?id=949)*

test files for android resource translation

I have enabled the Android Resource file translations with attached patch.

The project I add is correctly recognized and parsed into the database.
I selected English to be the source language.

When I "Update against templates" in a specific language all
translations (also the ones not made through Pootle) are overwritten
with the strings from the source language (English).

Steps to reproduce:
1) apply patch to pootle 
2) Configure English (en_US) and German (de_DE)
3) add files from attachment to PO_DIRECTORY (android_test)
4) configure new project 'android_test': File type: Android Resources'; Project Tree Style: 'Non-GNU'; Source Language: 'en_US'
5) verify that the string in de_DE is "AKTIVITÄTEN"
6) in de_DE: update from templates
7) string in de_DE is now "ACTIVITIES"

expected:
7) string in de_DE is not changed

**Comment by julen** [comment]
Update against templates is gone, closing.
