### ISSUE TITLE
Pootle has no way of calculating number of words translated

### ISSUE THREAD

**Issue by multiwebinc** [translate/pootle#3101]
*Version: 2.5.0*

Most translators charge per word and therefore it would be great to be able to have a way to display the number of words translated by each user, not just the number of strings. How it is now, it's impossible to have several translators working on the same language simultaneously because you can't keep track of the number of words each user translates.

**Comment by unho** [comment]
@translate/evernote This is fixed on master, isn't it?

**Comment by julen** [comment]
Yep, closing.
