### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'user'

### ISSUE THREAD

**Issue by unho** [translate/pootle#3102]
Depends on:
* [x] #2712 Make use of a single Suggestion model

See http://sourceforge.net/mailarchive/message.php?msg_id=31382974 and https://errormill.mozilla.org/verbatim/verbatim-prod/group/57279/

In the mozilla install we're hitting errors in 
https://github.com/translate/pootle/blob/2cce45820d/pootle/apps/pootle_store/models.py#L1627

```python
if submit.submitter.user.username != 'nobody':
```

where submitter is None.

Looking at the model, https://github.com/translate/pootle/blob/2cce45820d/pootle/apps/pootle_statistics/models.py#L67, that seems to be OK datawise, but I'm surprised we're the only folks hitting.

Sadly, we're hitting it in frequent code paths like commiting to VCS or downloading zips.

Since the error is reported by Mozilla, their use of LDAP Authentication method might be important.

After initial research it seems that in all the places where Submission is instantiated the profile is passed, but due to all the different possible cases it was not possible to verify if the profile passed was actually a real profile.

Also legacy data (from previous Pootle versions where the submission might have been created without a profile) might be the root of the issue as well.

A patch to avoid this issue is on commit https://github.com/translate/pootle/commit/64e2128b8e but this doesn't actually fix the root of the problem.

**Comment by jleclanche** [comment]
Fixed
