### ISSUE TITLE
Wording of last action block is incorrect for suggestions

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3104]
*See also:* #3011 #2712

I uploaded files as suggestions into Walllon
http://mozilla.locamotion.org/wa/firefox/

These have been slowly accepted by the main translator

The current message for last action says:
_dwayne_ accepted suggestion for string _The following passwords match your search:_ 2 days ago

While I technically made the suggestion, I definitely didn't accept it.  This needs to be reworded to show the correct data. I'm not sure if we know who the acceptor is, I assume yes in which case:

_fridel_ accepted _dwayne_'s suggestion for string _XXX_

would work better

**Comment by julen** [comment]
This is not applicable anymore.
