### ISSUE TITLE
SVN updates to template strings appear as translated language suggestions

### ISSUE THREAD

**Issue by evfool** [translate/pootle#3115]
*Version: 2.5.0*

*Created [attachment 954](http://bugs.locamotion.org/attachment.cgi?id=954)*

Updated english string shown as translation suggestion to the German string

Setup information:
Pootle 2.5.0
Translate Toolkit 1.10.0
Django 1.4.5
Java properties projects set up with backing SVN repository
two languages: Templates (English) and German

The problem: the templates language strings shown in pootle are never updated
Steps:
1. Update a string in the templates file, and commit to the SVN repository
2. pootle update_from_vcs --language templates from commandline
3. check the templates string on Pootle (e.g. by searching for the translation key)
What happens:
The string to translate is still the old one, it did not get updated. Instead, I can see that there is a new suggestion for the German translation, which is the updated English translation from SVN
What should happen instead:
The new string should appear in templates, and the German string should be marked as needs work, I guess

**Comment by julen** [comment]
VCS support has been dropped, closing.
