### ISSUE TITLE
Pootle does not seem to like _ in email addresses

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3120]
A user registered on mozilla.locamotion.org with the email address f_akad@hotmail.com.

He got no activation email.  Also if you went to the registration page and asked for a password reset it said that that email did not exist.

I suspect the issue is the _ (underscore) in the email address which is somehoew rejected as a valid email address.  The address is in the database and listed for the user.

**Comment by jleclanche** [comment]
Fixed, just tested.
