### ISSUE TITLE
Continue translation use untranslated filter by default

### ISSUE THREAD

**Issue by arky** [translate/pootle#3123]
*Version: 2.5.0*

Clicking on 'Continue translation' link on project page should show only untranslated strings instead of 'incomplete' strings. 

During translation sprints I found that new translators preferred 'untranslated' strings. 

Use-Case:
1. Go to Firefox Project page http://mozilla.locamotion.org/tl/firefox
2. Click on Continue translation (XX) link: http://mozilla.locamotion.org/tl/firefox/translate.html#filter=incomplete
3. You will be redirected to translation page with incomplete filter.

Suggested Behavior: Use untranslated filter.

**Comment by julen** [comment]
Not the case anymore.
