### ISSUE TITLE
quicker workflow for dealing with multiple duplicate strings

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3125]
*Originally posted by Ben Hearsum:*

A few weeks ago I was speaking with the lead for Mozilla's Tagalog localization about the move from Narro -> Pootle. He mentioned that when we were still using Narro, he was able to approve a single string and have all strings that were exactly the same be translated and approved at the same time. This may not be useful for smaller projects, but it seems like a useful thing for a project like Mozilla that has so many duplicate strings in it.

Is this something that could be implemented in Pootle? Given a little guidance I could try to take a stab at it myself.

**Comment by julen** [comment]
Translating always needs context, the suggestion while has good intentions it cause more harm than good, therefore closing.
