### ISSUE TITLE
Extend docs for project-related management commands

### ISSUE THREAD

**Issue by unho** [translate/pootle#3144]
Docs for project-related management commands, like `update_from_vcs`, don't specify the steps performed and in which places they change stuff.

For example it is not clear if `update_from_vcs` actually changes `PODIRECTORY` to make it be in sync with `VCS_DIRECTORY` after syncing with remote repository, or in which state is the Pootle DB after running it (is the DB synced with `PODIRECTORY` and `VCS_DIRECTORY`?).

It is necessary to provide such information to make it a good reference when providing support.

**Comment by dwaynebailey** [comment]
Since VCS is not in Pootle 2.7.0 and we'll be rewriting VCS support I'm closing this
