### ISSUE TITLE
OS X Strings: No update when source language changes

### ISSUE THREAD

**Issue by chhitz** [translate/pootle#3149]
*Created [attachment 966](http://bugs.locamotion.org/attachment.cgi?id=966)*

testcase files

When the strings in the source language change, the target language is not updated.

Translator can not see the changes in the original and adapt the translations.

Steps to reproduce:

1. create new project (File Type: OSX Strings, Source Language: English)
2. add English and a second language
3. upload strings_testcase/original/Localizable.strings into English --> shows total 2 words
4. update second language against templates --> shows total 2 words, 2 to translate
5. translate second language --> no words left to translate
6. upload strings_testcase/updated/Localizable.strings into English with overwriting --> shows 3 words
7. update second language against templates --> expected: total 3 words, 3 need translation; actual: total 2 words, 0 to translate

**Comment by julen** [comment]
Update against template feature has been dropped, closing.
