### ISSUE TITLE
Allow quick jump in translate mode

### ISSUE THREAD

**Issue by abelcheung** [translate/pootle#315]
*Version: 0.6.3*

Currently pootle expects translators to translate sequentially, from entry 1 to
the last one. However, translators may not always work in such manner; for
example, if first part of strings are difficult to understand, translators may
choose to translate latter part, then revisit first part again later. It would
be much more convenient to allow jumping to anywhere in translate mode, which is
partially implemented in view mode.

In view mode, people are permitted to jump to previous page, next page or last
page. If same can be implemented in translate mode, and even bigger jump is
allowed, including allowing translator to enter page number manually, that
would be more convenient, like:

================================================================
Start | Previous ?? | Items ?? to ?? of ??? | Next ?? | End
                                              +---------+
Jump to entry: 100 | 200 | 300 | 400 | 500    |         |
                                              +---------+
================================================================

The text entry field is for entering entry number manually.

**Comment by dwaynebailey** [comment]
This doesn't apply anymore as the whole UI has changed and its easy to get to work that needs to be done based on folders, files and even goals
