### ISSUE TITLE
New install fails with PostgreSQL

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3160]
_Version: 2.5.1-rc1_

_Originally posted by (unknown user):_

I'm running Ubuntu 13.04, using pyenv and Python 2.7.6 build from sources in a dedicated virtualenv.

Note that i've already downgraded django-taggit in this virtual env: http://pastie.org/8571671

pootle setup fail when using PostgreSQL database. I went on IRC, and @dwaynebailey asked me to perform the 3 following steps: 

(env-name) $ python manage.py syncdb --noinput => OK
(env-name) $ python manage.py migrate => Fails
(env-name) $ python manage.py initdb

output: http://pastie.org/8571534.

It works with MySQL and SQLite in the same environment: http://pastie.org/8571583 & http://pastie.org/8571601

**Comment by markshep** [comment]
I'm getting this error when setting up an instance of Pootle 2.5.1.3 (as downloaded from http://pootle.translatehouse.org/download.html).  Is it possible to get this fix applied to the "stable/2.5.1" branch too for the next bugfix release, or will I have to go to 2.6.0-rc2 to be able to use PostgreSQL with Pootle?

**Comment by jleclanche** [comment]
@markshep We're releasing Pootle 2.7 very soon (within a couple of weeks). Please don't use the 2.6 line, it's a transitional release for upgrades.

If you need postgresql support right now, you can install Pootle from git as the current master is pretty stable as it is. Or you can wait until we release 2.7 :)
