### ISSUE TITLE
Integrate django-statici18n in Pootle

### ISSUE THREAD

**Issue by arky** [translate/pootle#3161]
Django's default i18n has performance overhead. Perhaps we could use django-statici18n in pootle to pre-generate and serve the catalog from static webserver.

django-statici18n is for:

    Collecting JavaScript catalogs from each of your Django apps (and any other place you specify) into a single location that can easily be served in production.

https://github.com/zyegfryed/django-statici18n

**Comment by julen** [comment]
Let's not do premature optimization and address things like these when there's a real issue.
