### ISSUE TITLE
Check for pending user agreement if any legal page exists

### ISSUE THREAD

**Issue by arky** [translate/pootle#3164]
Pootle checks for pending user agreement even when no legal pages are enabled. This creates extra db queries:

QUERY = u'SELECT (1) AS "a" FROM "staticpages_legalpage" LEFT OUTER JOIN "staticpages_agreement" ON ( "staticpages_legalpage"."id" = "staticpages_agreement"."document_id" ) WHERE ("staticpages_legalpage"."active" = %s AND (("staticpages_agreement"."user_id" = %s AND "staticpages_legalpage"."modified_on" > "staticpages_agreement"."agreed_on") OR NOT ("staticpages_legalpage"."id" IN (SELECT U1."document_id" FROM "staticpages_agreement" U1 WHERE U1."user_id" = %s )))) LIMIT 1' - PARAMS = (u'True', u'1', u'1')

Connection: default

/usr/lib/python2.7/cProfile.py in runcall(149)
  return func(_args, *_kw)
/home/arky/src/pootle-dev/pootle/core/decorators.py in wrapped(87)
  return func(request, path_obj, _args, *_kwargs)
/home/arky/src/pootle-dev/pootle/core/decorators.py in _wrapped(180)
  return func(request, _args, *_kwargs)
/home/arky/src/pootle-dev/pootle/core/decorators.py in wrapped(139)
  return func(request, path_obj, dir_path, filename, _args, *_kwargs)
/home/arky/src/pootle-dev/pootle/apps/pootle_translationproject/views.py in translate(658)
  context_instance=RequestContext(request))
/home/arky/src/pootle-dev/pootle/apps/pootle_misc/context_processors.py in pootle_context(90)
  context.update(_agreement_context(request))
/home/arky/src/pootle-dev/pootle/apps/pootle_misc/context_processors.py in _agreement_context(62)
  LegalPage.objects.pending_user_agreement(request.user).exists()):

**Comment by phlax** [comment]
legalpages has been removed - we will bring back this functionality with notifications and/or web sockets

**Comment by unho** [comment]
Legalpages is still there. But this won't be fixed as we expect to completely replace this.
