### ISSUE TITLE
Pootle does not run in subdirectory

### ISSUE THREAD

**Issue by astehlik** [translate/pootle#3169]
*Version: 2.5.1-rc1*

**Comment by astehlik** [comment]
Sorry, I totally forgot about this because we endet up using a dedicated domain for pootle.

Thank you for all your help! :smiley:

**Comment by julen** [comment]
No worries, closed this since we merged back our fork, which dealt with those situations (even if we run it from a root endpoint nowadays)

**Comment by zalexua** [comment]
Hi all !

I want to confirm the bug reported by astehlik, I mean links to languages like "https://www.zabbix.org/pootle/pootle/bg/Zabbix-trunk/" generated from a project.
You can see that yourself here: https://www.zabbix.org/pootle/projects/Zabbix-trunk/

I've used a workaround on that site to resolve the problem:
 
```
WSGIScriptAlias /pootle /opt/pootle/wsgi.py
<Directory /opt/pootle>
Options FollowSymLinks
Require all granted
RewriteEngine On
RewriteBase /pootle/
RewriteRule ^wsgi.py/pootle/(.*)$ $1 [R]
</Directory>
```

Note - the double "pootle/pootle/" comes from WSGIScriptAlias' value, which is "pootle" in current example.

If WSGIScriptAlias is just / (i.e. root of site) then those links are generated correctly, without duplicated value.

That pootle installation was running using v 2.5.0 and this issue didn't exists on the version.
I was able to reproduce it on 2.5.1 and on currently running  2.5.1.3

Does it make any sense to reopen this bug report on fill new one?

**Comment by unho** [comment]
@zalexua No need to reopen or create new issue since this is fixed on the newer versions as told in the [comment](https://github.com/translate/pootle/issues/3169#issuecomment-69887709) before yours.
