### ISSUE TITLE
Feature request: add ability to remove many(all?) suggestions at once

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3172]
_Originally posted by Pere Pujal i Carabantes:_

Currently to remove suggestions you should reject the suggestions one by one, this is good for valid suggestions, but when it comes to reject suggestions putted there by a spammer or a troll who abuses the server you need a way to remove many of them at once.

Ideally one should be able to remove:
1. All suggestions made by a user(a spammer)
2. All suggestions made by a user in a date interval(a legit user whose account has been hacked by a spammer)
3. All suggestions

**Comment by phlax** [comment]
i believe the suggestions ui handles the functionality suggested here, altho it doesnt allow to delete iirc
