### ISSUE TITLE
data lost when deleting languages

### ISSUE THREAD

**Issue by akoscomp** [translate/pootle#3173]
*Version: 2.5.1*

You can reproduce if:
1. Go Admin - Languages
2. With Delete checkbox select all languages.
3. Deselect Austrian
4. Push Save Changes
5. With Delete checkbox select all languages.
6. Deselect Austrian and German
7. Push Save Changes

After this step the Pootle delete Austrian language too.

**Comment by dwaynebailey** [comment]
The new admin UI does not allow you to select multiple languages.  So closing this.
