### ISSUE TITLE
Percent sign is not separated from number in Spanish

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3176]
*Version: 2.5.1*

*Originally posted by Adolfo Jayme:*

I actually fixed this in translations, but it seems it was not applied in 2.5.1. The percent sign must be separated with a thin, non-break space (U+202F) or a normal-width non-break space, according to our Ortografía ruling from 2010.

**Comment by dwaynebailey** [comment]
Pootle translations have been imported for 2.7.0 so they are most likely now correct.
