### ISSUE TITLE
Language dropdown not showing template languages

### ISSUE THREAD

**Issue by chhitz** [translate/pootle#3192]
*Version: 2.5.1*

The language dropdown menu is only displaying languages that are _not_ specified as source language in any project.

Deactivating this filter shows all possible languages and does not seem to have any undesirable side effects:

```diff
diff --git a/pootle/apps/pootle_language/models.py b/pootle/apps/pootle_language/models.py
index 03dbd96..9611602 100644
--- a/pootle/apps/pootle_language/models.py
+++ b/pootle/apps/pootle_language/models.py
@@ -56,7 +56,6 @@ class LiveLanguageManager(models.Manager):
         return super(LiveLanguageManager, self).get_query_set().filter(
                 ~models.Q(code='templates'),
                 translationproject__isnull=False,
-                project__isnull=True,
             ).distinct()
```

**Comment by jleclanche** [comment]
@julen is that what you guys just fixed?

**Comment by julen** [comment]
We removed the explicit check for `templates`, this talks about source languages in general. Feel free to check it out and close if it doesn't apply anymore.

**Comment by julen** [comment]
`project__isnull=True` was there to avoid routing users to the English source language, which leads to a misleading empty page in our case and the vast majority of deployments, but it's not always the desired behavior as shown by the OP.

In any case the actual fix is not *just* taking that line out, but taking out languages with no live TPs. As described in the manager's docstring: *A live language is any language containing at least a project with translatable files.* The pushed commit is a regression in this aspect, hence reopening.

**Comment by unho** [comment]
Just for the record, commit 21b59033 has been reverted in 9387c920. So this issue is still not fixed as told in the previous commit.

**Comment by unho** [comment]
There is agreement on including any template language on the dropdown, but instead hide any language without visible TPs.
