### ISSUE TITLE
wrong links generated to access project/language page

### ISSUE THREAD

**Issue by tasso85** [translate/pootle#3193]
*Version: 2.5.1*

I have noticed the following bug in version 2.5.1, which was already there in version 2.5.0 at least.

I have just made a fresh install of Pootle 2.5.1 on a clean CentOS machine, using the 32bit installer from bitnami.

After the installation, the server starts fine, but if I click on a project on the right, then I choose a language on the left in the following page, it tries to access a link like http://MY_SERVER_IP/pootle/pootle/it/terminology

Notice here the double "/pootle" part, there should be only one, in fact if I manually delete one, it loads the page correctly.

If I access the language in the project by clicking on the total number of words instead the link is correct, with only one "/pootle" part.

**Comment by julen** [comment]
We at Evernote were using a deployment in a non-root location and can assure such links have been correct. If there's anything similar going on please create a new issue.
