### ISSUE TITLE
Java properties plural forms

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3195]
*Originally posted by Diorcet Yann:*

Some framework use plural forms in java .properties files

For example:
http://blog.vityuk.com/2013/03/easy-localization-in-java.html
http://www.gwtproject.org/doc/latest/DevGuideI18nPluralForms.html

It's not handle by Pootle currently.
Where (in the code) is stuff is handled? (i will work on a patch)

**Comment by julen** [comment]
Support for monolingual files is gone, closing.
