### ISSUE TITLE
Requesting verbose errors access while "Uploading from templates"

### ISSUE THREAD

**Issue by mautematico** [translate/pootle#3198]
*Created [attachment 974](http://bugs.locamotion.org/attachment.cgi?id=974)*

Errors are not verbose

Hello there!

I feel lost. Sorry if this is not the appropriate place to file this bug. :S

As you can see on attachment, I was trying to "Upload from templates" and I get this "Error while uploading from templates" thing. Now I have no idea what did happen and worst: I have no idea what should I do.

I'm requesting access to more verbose errors so I can know what to do to solve them.

I don't know if this is an account/access update. If that's the case: Do I need someone to vouch me?

Or maybe is this a feature request?

As you can see, yes. I feel lost.

By the way: I'm working on Firefox es-MX localization, at:
http://mozilla.locamotion.org/es_MX/firefox/
There is where the "Error while uploading from templates" thing happened.

I have HG access to mozilla's repos, if that helps.

Thank you!

**Comment by julen** [comment]
Update from templates feature is gone, closing.
