### ISSUE TITLE
user dashboard - 1 Suggestions Pending - No results

### ISSUE THREAD

**Issue by qdinar** [translate/pootle#3204]
i see in
http://pootle.locamotion.org/accounts/qdb
:
Suggestions Pending
Pootle 2.5.1 	1
i click on "1" and go to
http://pootle.locamotion.org/tt/pootle/translate/#filter=user-suggestions&user=qdb
and see:
No results.

**Comment by unho** [comment]
The user public profile has been completely rewritten, so this is no longer applicable.
