### ISSUE TITLE
user join is not shown in language news page

### ISSUE THREAD

**Issue by qdinar** [translate/pootle#3205]
i see several users are shown in "Latest News"
http://pootle.locamotion.org/tt/notices
like:

Thu 12 Sep 2013 10:13:42 UTC
User translate joined language Tatar

but i do not see me - "qdb" there though
seems there is even the oldest event shown in this page and there are no "2nd page" link:

hu 06 May 2010 17:16:47 UTC
New project Pootle added to language Tatar.

maybe it is because i joined it even before that, i do not remember whether it is so.

**Comment by julen** [comment]
The news feature is gone, closing.
