### ISSUE TITLE
Translate-tab for projects broken

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3207]
*Version: 2.5.1*

*Originally posted by Maik Glatki:*

Overview
Set up a new pootle installation

Steps to reproduce
 1. Install pootle on debian 7 server using this official documentation: http://pootle.readthedocs.org/en/latest/server/installation.html - used pip install Pootle=2.5.1
 2. Used MySQL as database.
 3. Run pootle as an apache passenger
 4. Navigate to the main page.
 5. Navigate to any project in the side bar (i.e. "Tutorial"
 6. Click on the tab "Translate" on the top bar.

Actual Result

* Translate page opens without content, no results shown.

Expected Result

* Translate page opens with content

Additional notes:

* Chromium console indicates that the script xhr/units/?page=1&path=%2Fprojects%2Ftutorial%2F&pager=true returns Status Code 500.
* navigating to the respective script manually returns an empty page with: "This must be an AJAX request."
* After setting DEBUG = True and TEMPLATE_DEBUG = True in the settings.conf, directly navigating to the script returns a Database Error: '(1054, "Unknown column 'pootle_store_store.pootle_path' in 'where clause'")'. Log exempt from apache2 error log is attached.
* I confirmed that the database, table and column exists.
* Tested with Chromium and Firefox (version 30)
* After encountering this problem, I reinstalled pootle from scratch with the same result
* Using the translate tab on a projects with a specific language selected (i.e. /af/tutorial/translate/) works fine (although interestingly, there is a 500 Request to https://amagama-live.translatehouse.org/api/v1/en/af/unit/?source=Welcome&jsoncallback=_jsonp1158).

**Comment by julen** [comment]
Not applicable anymore.
