### ISSUE TITLE
Pootle Settings not persistent.

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3208]
*Version: 2.5.1*

*Originally posted by Maik Glatki:*

Steps to reproduce:

* Installed Pootle, 2.5.1, passenger in apache2
* Changed general settings in the Admin interface. Saved
* Restarted apache2

Actual Results:

* The main page still randomly shows the default settings ("This is a demo installation of Pootle.").
* After some navigation, the real configuration seems to be loaded.
* Another Apache restart resets the shown text again.

Additional notes:

* Seemingly similar to #1389, but not the same.

**Comment by unho** [comment]
This is gone in new master
