### ISSUE TITLE
Error building mlo language pack

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3211]
*Reported by Akmal Khushvakov (uzbadmin)*

I am trying build new Uzbek language pack. But it doesn’t work. It says: 
```
Error: Requested content 'mozilla.locamotion.org/uz/firefox/?ext_actions=Build+language+pack' cannot be resolved.
```

Can you make for me this work?

**Comment by julen** [comment]
MLO removed the option to build any language packs, closing.
