### ISSUE TITLE
Miscounts after refresh_stats in check and suggestions

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3218]
See http://custom-mlo.testing.locamotion.org/af/firefox/

Notice that the navbar has a check failure count of 12 while the total for the directories as 13+1+5=19

![screen shot 2014-08-01 at 14 34 11](https://cloud.githubusercontent.com/assets/647438/3779320/9980e77e-1980-11e4-956f-aaf2f73cdf90.png)

Also the suggestion count is not present in the navbar.  Plus also note that the total count is missing showing only "Next goal" not "Continue translation".  Also missing is "View all"

![screen shot 2014-08-01 at 14 46 44](https://cloud.githubusercontent.com/assets/647438/3779479/7e88674c-1982-11e4-8bfa-e85e739a5bee.png)

**Comment by unho** [comment]
Closing this as this applies to stats on 2.6.0. If it appears again in new master a new issue can be filed.
