### ISSUE TITLE
Language dropdown has weird order

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3219]
The language picker is perfectly ordered in alphabetical order [except for Northern Ndebele](http://custom-mlo.testing.locamotion.org/ak/firefox/)?

![screen shot 2014-08-01 at 14 40 42](https://cloud.githubusercontent.com/assets/647438/3779424/d28ad97a-1981-11e4-8849-4b5b94c16e18.png)

**Comment by julen** [comment]
This is weird as I can still see it on the testing mlo site.

Could you try to check the output of this snippet in a Django shell?
```python
import locale
from pootle.i18n.gettext import tr_lang
from pootle_language.models import Language

sorted([(lang[0], tr_lang(lang[1]))
       for lang in Language.live.values_list('code', 'fullname')],
       cmp=locale.strcoll, key=lambda x: x[1])
```

**Comment by dwaynebailey** [comment]
Tested and the source of the problem is now very clear.  Leading spaces in the language names.

```py
[(u'nd', u' Northern Ndebele'),
 (u'kj', u' Oshiwambo '),
 (u'pbb', u' P\xe1ez'),
 (u'ach', u'Acoli'),
 (u'af', u'Afrikaans'),
 (u'ak', u'Akan'),
 (u'am', u'Amharic'),
```

I guess that we either want to block the inclusion of leading spaces in the language names.  Or we want to ``.strip()`` the values before we populate the listbox.

**Comment by unho** [comment]
``.strip()`` looks like the best approach.

**Comment by julen** [comment]
With the commit above languages are guaranteed not to contain any leading/trailing whitespace upon any save. If anyone feels like this should also be done at display time, that's a bug in TTK's `tr_lang()` function.

@dwaynebailey for these 3 languages that you have issues with, I'd suggest to manually modify them.
