### ISSUE TITLE
Sidebar does not remember that it has been closed when you are in goals

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3225]
The sidebar will remember if it has been set to closed or open when in the file overview. But if you filter on a goal then the sidebar will open.  If you close it then it will not remember that it was closed.  This mean that every directory that you enter will reopen the sidebar.  It also means that every time you return from the editor the sidebar will open.

**Comment by unho** [comment]
Closing this as goals were dropped and will be reimplemented on new master.
