### ISSUE TITLE
django-taggit not recognized with Pootle 2.5.1.1

### ISSUE THREAD

**Issue by olivernb** [translate/pootle#3233]
Installed Pootle 2.5.1.1 with pip in a virtualenv.

launched "pootle --version" and I obtain:

      File "/var/www/pootle/env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: django-taggit>=0.10,<0.11.2

although I have django-taggit 0.11.1 properly installed in pip virtualenv, (installed by pip install pootle) 

    (env)/v/w/p/env # pip freeze|grep taggit
    django-taggit==0.11.1

with pip install pootle==2.5.1 => same problem
with pip install pootle==2.5.0 => OK, pootle working properly.

FYI: bug already reported here http://sourceforge.net/p/translate/mailman/message/32477565/

**Comment by emezeta** [comment]
same problem here but Pootle==2.6.0 rc2
2.5.0 is working fine

**Comment by emezeta** [comment]
I restart from scratch. v2.5.1.1 is working ok.

I follow http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/server/installation.html steps

The only thing I needed to do it was to create the assets folder before run: 
     $ pootle collectstatic --noinput 

I try the installation from zero several times. All of the times manually create assets was a must. 
Debian 6, 7 and 8. Ubuntu 12.04

**Comment by adamtaylor** [comment]
@emezeta how did you run the collectstatic command with the arg parsing problem? If I try that I simply get the same exception as running `pootle --version` (the same as shown above).

I'm not sure if this a pootle or virtualenv problem?

**Comment by julen** [comment]
This is a Pootle problem, I just checked the contents of the PyPI download and the *assets* directory is empty. The build should include the [built files](https://github.com/translate/pootle/blob/stable/2.5.1/Makefile#L17).

From the time being, the workaround is building the assets yourself, `pootle collectstatic --noinput && pootle assets build`.
cc @dwaynebailey, uploading a new package/version with actual contents would prevent people from hitting this.

**Comment by unho** [comment]
Closing since this should be fixed with the last 2.5.1.3.

**Comment by marksweb** [comment]
I'm running pootle 2.6 RC2 and when running `pootle check` I get `pkg_resources.DistributionNotFound: django-taggit>=0.10,<0.11.2`

**Comment by unho** [comment]
Please do not run that version. I am afraid we are not going to provide support for that version.

There is already 2.7.0 stable version and we are about to release 2.7.1 with several bugfixes to it. So please upgrade!

**Comment by marksweb** [comment]
@unho yeah I was trying to upgrade to 2.7 but then got a load of errors about packages not being found so I got impatient & dropped back to RC2. Now I've got an error coming from the assets `There is no manifest which knows the version` in the apache log & a permission denied when I try to build the assets.

It's not gone well :(

**Comment by unho** [comment]
@marksweb Hopefully we will release 2.7.1 today. If we do, perhaps we can try to help you to upgrade to 2.7.1 next week.
