### ISSUE TITLE
Crowd-sourced dev funding

### ISSUE THREAD

**Issue by taoeffect** [translate/pootle#3234]
Please start a kickstarter/indiegogo campaign. I pledge to contribute and [tweet](https://twitter.com/taoeffect) about it if you do this within 4 months of this issue (after that, possible I'd've switched to an alternative!).

Bug #3232 is really bugging me and want it fixed!

**Comment by comradekingu** [comment]
@taoeffect Clearing up some old issues here.
https://liberapay.com/Pootle
Bountysource is proprietary.
