### ISSUE TITLE
create_local_tm: multiple warnings

### ISSUE THREAD

**Issue by Mixaill** [translate/pootle#3242]
After update from 2.5.1.1 to 2.6.0-rc1

<pre>2014-08-11 20:11:37,373 WARNING /var/www/translation/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py:124: Warning: Incorrect string value: '\xD0\xA0\xD1\x8B\xD1\x86...' for column 'target_f' at row 1
  return self.cursor.execute(query, args)</pre>

**Comment by unho** [comment]
The new master (core) no longer uses this local TM, so the bug is no longer relevant.
