### ISSUE TITLE
Pootle demo site?

### ISSUE THREAD

**Issue by edpichler** [translate/pootle#3265]
Is there any Pootle demo site? Where can I find this information?

**Comment by m-aciek** [comment]
The site [seems to be down](http://downforeveryoneorjustme.com/pootle.locamotion.org) for now. Is there another demo site?

**Comment by dwaynebailey** [comment]
@m-aciek our demo site is backup if you want to have a look

**Comment by jampy** [comment]
Looks like the demo site has email issues. I tried to sign up twice, but never got the activation mail (tried two addresses, including Gmail)

**Comment by phlax** [comment]
yep @jampy you are right - leave it with me and ill ping you when its fixed

**Comment by cbenhagen** [comment]
@phlax I am having the same issues. Is it down again?

**Comment by t1gor** [comment]
Not sure that is was mentioned, but https://pootle.locamotion.org/ has problems with SSL certificate :/

**Comment by Vadorequest** [comment]
Seems like it's down.

**Comment by Vadorequest** [comment]
This seems to be okay, not sure if it's a demo: https://pootle.linguisticteam.org/

**Comment by LTIOfficial** [comment]
Hi @Vadorequest,
That is not one of the Pootle developer's sites, demo or otherwise.  It's LTI's (Linguistic Team Int'l) long-running working instance, which I just migrated to a new server (same URL, though).

**Comment by Vadorequest** [comment]
Okay, thanks for letting me know!
