### ISSUE TITLE
Login after verification gives odd items in "dialog"

### ISSUE THREAD

**Issue by silpol** [translate/pootle#3269]
Pootle 2.5.0 is powered by Translate Toolkit 1.11.0
http://translate.eliademy.com/

I made myself registered, has seen dialog
"Registration Complete
Please check your email to activate your account."

then I went through email verification - clicked link from mail, it asked to login, then on completion
"Account Activated
The account has been activated for username "False". You can now proceed to log in."

I expected at least something real there instead of "False.", be it user name or email or full name.

can it be a tip of bigger problem in authentication?

**Comment by PriscillaAlcalde** [comment]
I've just received this message: 

"Account Activated
The account has been activated for username "False". You can now proceed to log in."

And it seems weird. What does "False" mean in this context?
