### ISSUE TITLE
Project admin page hides some content

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3278]
Reported by @akerbeltz on tech-team mailing list.

On [the Project Admin page](http://custom-mlo.testing.locamotion.org/admin/projects/) the right side of the screen is cut off, I can just about see the triangle of the dropdown and there's no horizontal scrollbar so if there's anything off to the right, I can't see/access it.

![image](https://cloud.githubusercontent.com/assets/647438/4473732/d2327a5a-4956-11e4-9699-3c94439ad7b3.png)

**Comment by unho** [comment]
@julen I think this is no longer applicable, isn't it?

**Comment by julen** [comment]
Nope, closing.
