### ISSUE TITLE
(Regression) Account Activation: Check for Activation Code has expired

### ISSUE THREAD

**Issue by arky** [translate/pootle#3281]
During recent Mozilla Thai L10N sprint, I have noticed  that the activation page shows username as 'false'. Regression of bug #3060 ?

Testcase:
1. Register a new account, click the link in activation email 
2. You'll be redirected activation page on pootle. It will show your username as 'false'

**Comment by unho** [comment]
We have dropped django-registration, so this is no longer applicable.
