### ISSUE TITLE
Move dependency check to their own app

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3289]
@julen @iafan We were discussing our differences in dependency checks (pootle/depcheck.py) and we found that we could do one of two things:

 - Decentralize dependency checking, and having a pootle_depcheck.py file in every app with a determined function  which would run and return a list of installed/missing optional dependencies
 - Move dependency checking to its own app. This may be a better idea as it's more relevant to packaged pootle installs.

Option 1 is easier to implement. I'm in favour of option 2 and currently working on a prototype. This would most likely move the depcheck part of the admin UI to its own page.

**Comment by dwaynebailey** [comment]
Rather lets do what is proposed in #3594
