### ISSUE TITLE
Cherry-pick 63e9555fa423734bf14aac77540f3d4c944a0d63

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3298]
Need to fix travis and cherry pick 63e9555fa423734bf14aac77540f3d4c944a0d63 for 2.6

**Comment by julen** [comment]
As mentioned on IRC this change only hides an error, and it's not a fix for the real problem that it tried to solve in the first place (#3286). Check #3485 for the real thing.

This changeset won't make to core.
