### ISSUE TITLE
Figure out the state of monolingual formats

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3303]
If we prioritize moving towards database-based stores, monolingual support will naturally come back to us. Would it be worth dropping monolingual support until we get there?

See 727187c71b3df6178e3c8739f5ada42d8e288ecf

**Comment by dwaynebailey** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
