### ISSUE TITLE
Let us configure the dashboard

### ISSUE THREAD

**Issue by princeofnaxos** [translate/pootle#3328]
The 'nobody' user doesn't have any permissions set. So at 'not logged in' state, why are we presented with an "Overview" with (empty) "Languages" and "Projects"? Without permissions for 'nobody', the login form should appear.

At 'logged in' state, we would want to be able to determine which information is shown on the Overview. E.g. we find 'Top contributors' totally nonsense, and don't it on the dashboard.

Regards,
Edwin Boersma

**Comment by dwaynebailey** [comment]
You can do any of these by [customising Pootle](http://docs.translatehouse.org/projects/pootle/en/latest/developers/customization.html)
