### ISSUE TITLE
What language is translated in the Translate tab on the dashboard?

### ISSUE THREAD

**Issue by princeofnaxos** [translate/pootle#3329]
Hi, 

When I have logged in, I see two tabs: "Overview" and "Translate". Having permissions on multiple projects and multiple languages, I would choose a project and language to translate.

But when I click "Translate" tab, I come to a translation view, where it says "All projects / All languages" in the header. It is now unclear to me where I am? Which project is it, and which language? From the source text and the suggested translation, I can see it is the first language in the first project as listed in the Overview.

This is apparently a bug.

Regards,
Edwin Boersma

**Comment by julen** [comment]
This UI is not exposed at `/` anymore, hence closing.
