### ISSUE TITLE
What is the state of your own translations?

### ISSUE THREAD

**Issue by princeofnaxos** [translate/pootle#3330]
When I choose Dutch as the interface language, I see only few words that are actually in Dutch. Most of the language names are translated (but not Dutch ;-( ), and in the translation view, only the tab Permissions is translated.

Similar situation with e.g. German and French.

With so few words translated, you should actually not offer interface languages. It makes a translation website look a bit silly.

Regards,
Edwin Boersma

Using 2.5.1.1.

**Comment by unho** [comment]
Closing this since no additional data has been provided.
