### ISSUE TITLE
Recover: Re-introduce version control support

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3341]
cc @julen @iafan @ta2-1 

So we want VCS support available out of the box. We discussed it wouldn't be in pootle "core", but it should be available as a pootle app.

I have moved what can immediately be moved to `pootle.apps.versioncontrol` on master. What now remains on master is as follows:
- `TranslationProject.scan_files()` has a vcs_sync argument which seems completely out of place
- `TranslationProject.update_against_templates()` contains some versioncontrol logic, adding files if `self.scan_files(vcs_sync=False)` has new files (?)
- `TranslationProject.update_file` is tightly bound to vcs, but is also only called from `pootle_translationproject.views.vcs_update` so go figure. 
- `pootle_translationproject.views` has a bunch of VCS actions, those are pretty inconsequential

So I'd like to do an actual pass together on what is actually still relevant in all that, how can we clean it up, and how can we move it out of where it currently is. I also need to know what the EN requirements regarding the code is (since you don't use pootle's vcs integration - could it be improved so EN can use it as well, or does it just need to stay out of the way?). Whatever remains afterwards will land in the core branch.

[Specification](https://docs.google.com/document/d/1e_0lX5jHf7hB79QIYppa8xQ1-09u6YRzMZixMLFdE7w/edit?usp=sharing)

**Comment by phlax** [comment]
pootle_fs has recovered this functionality, altho its still somewhat unstable
