### ISSUE TITLE
Add syntax highlighting editor to our static pages

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3346]
Our static pages are HTML, and it would be nice to have HTML syntax highlight in there.

My personal strong preference is http://codemirror.net/ since it is very solid, has a great API, and allows to easily write custom highlighters, which we can make the use of in other places in the app.

**Comment by julen** [comment]
Note the end result is always HTML, however the source text can either be HTML, Markdown or reStructuredText, as configured by server admins.

**Comment by iafan** [comment]
1. Technically, Codemirror has support for both [Markdown](http://codemirror.net/mode/markdown/) and [reStructuredText](http://codemirror.net/mode/rst/) in case someone wants to support that.
2. I explained in #3766 why having anything but HTML is a bad idea. Having to support multiple syntax highlighters is another reason against non-HTML formatters.

**Comment by julen** [comment]
I'm fully aware CodeMirror supports the afore-mentioned formats as well as many more — I was commenting on the topic for the sake of completeness, as the original message was leaving behind the fact that other markup formats are currently supported by Pootle.
