### ISSUE TITLE
User "nobody" can remove other's rights

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#335]
_Version: 0.6.3_

If someone gives the user "nobody" admin rights for a project in Pootle, any
anonymous user can remove all rights from any other user (nobody, default, or
any specific user). With "assign" rights a similar situation can result.

Suggested improvement: remove "assign" and "administrate" rights for the user
"nobody" under all circumstances so that it can never be assigned to "nobody".

**Comment by linuxjackto1** [comment]
thanks www.movied.org
