### ISSUE TITLE
Set sane defaults for `SESSION_CACHE_ALIAS`

### ISSUE THREAD

**Issue by julen** [translate/pootle#3356]
Django 1.7 introduces the [`SESSION_CACHE_ALIAS` setting](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-SESSION_CACHE_ALIAS) which allows to separate cached session data from the `default` cache backend. Let's make sure that we provide sane settings to make this separation straightforward.

**Comment by julen** [comment]
Looking at this it's basically a matter of configuration (just a new possibility) and something *up to deployments*, so there doesn't seem to be anything to be done actually. Thoughts @jleclanche?

**Comment by jleclanche** [comment]
Yes, I don't think there's anything to be done, but the [`CACHES`](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-CACHES) setting needs to be a proper dict (did they change it?)

**Comment by julen** [comment]
They changed that [ages ago (1.3)](https://docs.djangoproject.com/en/1.3/ref/settings/#std:setting-CACHES).

Closing this as irrelevant for a general use-case.
