### ISSUE TITLE
 Use reviewers name in last action messages 

### ISSUE THREAD

**Issue by arky** [translate/pootle#3362]
The project overview page notification uses submitters name instead of reviewers name. 

 "submitters_name" accepted suggestion for string "string" A minute ago.

(instead of) 

"reviewer_name" accepted suggestion for string "string" A minute ago. 

In this screenshot 'Arky' is reviewer and 'Denomain' is submitter of the translation. 

![last-action](https://cloud.githubusercontent.com/assets/808895/5104002/143805ac-7010-11e4-8dc9-8c5b7d08ca3c.png)

**Comment by julen** [comment]
Not applicable to master, closing.
