### ISSUE TITLE
Switch revision counter storage to Redis

### ISSUE THREAD

**Issue by julen** [translate/pootle#3364]
The current version of revision counter is supported by MyISAM engine only. Since we have Redis as a hard dependency let's move it there.

**Comment by julen** [comment]
The revision number will be stored as a counter in Redis without any timeout values and will be kept forever, but accidental clears of the Redis DB (via blind `cache.clear()` calls for instance) can leave deployments without this information.

While the `clear_cache` command proposed in #3500 would allow clearing the cache while preserving this data, as a second safety measure I'll extend the `revision` command to accept a `--restore` flag which will get the highest revision number from the DB (a simple SQL query) and save it as the current value for the revision counter.

**Comment by ta2-1** [comment]
I mentioned in #3500  that I didn't expect to see revision counter as a cached value.
As far as I know any cache has `get` and `set` methods. They don't suite for revision counter.
I think it's necessary to use `incr` (http://redis.io/commands/incr) call only.

**Comment by julen** [comment]
Yes, using `incr` is the point of this whole thing, but you're missing that Django's caching API also offers `incr`/`decr` methods, which in turn are implemented by the Redis cache backends, and this applies to  both [django-redis-cache](https://github.com/sebleier/django-redis-cache/blob/8e9d345a81ef2154e164d3b969728ba892c2bc29/redis_cache/cache.py#L308-L322) and [django-redis](https://github.com/niwibe/django-redis/blob/9f4bad13a2b80706d70117089bdec5c5c14ae960/django_redis/cache.py#L103-L105) too.
