### ISSUE TITLE
Java property files are not always recognized depending on the name of the file

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#3368]
Our project (bzr branch lp:dhis to get the source code) uses monolingual Java property files. They basically follow the pattern of 
1) The template file (in English) is always one of the following file
i18n_module.properties
i18n_app.properties
i18n_global.properties

2) The translation file is always located in the same directory as the template file and looks like

i18n_module_ar.properties

which would correspond to the Arabic translation of this file. 

Files with "module" and "global" are recognized as templates, but files with "app" are not recognized as templates. 

Pootle 2.5.0
Translate Toolkit 1.11.0
Django 1.4.13

**Comment by dwaynebailey** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
