### ISSUE TITLE
Translations without a key in the template appear 

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#3369]
Our project (bzr branch lp:dhis2 to get the source code) uses Java property files. All files are located in a directory, with the template file being named something like "i18n_module.properties" and the corresponding translation being something like "i18n_modules_ar.properties". In some cases, a key/value pair is deleted from the template file by the developers, but not deleted in the translation (as this is a workflow handled by the translators and not the devs). When these are imported into Pootle, the translation appears without a corresponding template value. 

The expected behaviour would be that Pootle would ignore all keys/value pairs which may be present in the translation file, but absent in the template itself. 

As an example, see below
![pootle](https://cloud.githubusercontent.com/assets/2968061/5124951/a1db62d8-70be-11e4-971b-8bad8fad9945.png)

**Comment by dwaynebailey** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
