### ISSUE TITLE
Pootle sync_stores fails when a Java property for a given language does not exist

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#3370]
We have a project based on Java property files. In certain cases, the property files themselves do not exist in the actual source code, when they are translated. The basic workflow is, when a new language needs to be translated, we will create a new language in Pootle, and the translation will take place. We will then perform a sync_stores command to flush the translations to the database. What should happen ( I think) should be that for a given new language (zz), if the template is named "i18n_global.properties" a new file "i18n_global_zz.properties" should be written to disk. We would then add this to our VCS. However, Pootle throws an error when this situation occurs with "file does not exist....".

**Comment by dwaynebailey** [comment]
We're going to manage monolingual differently in Pootle post 2.7.0 and we've dropped monolingual support in Pootle 2.7.0 with the idea of managing this outside of Pootle. Closing
