### ISSUE TITLE
Can't add user by admin interface

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#339]
_Version: 0.6.3_

_Originally posted by Oscar Manuel Gómez Senovilla:_

When adding a user through the admin interface, and using the upper box, no
matter what I do, I always get "ValueError: Please set the users full name or
leave it blank", and the user is not added.

If I use the lower box, no error, but the user is not added.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
