### ISSUE TITLE
Travis: use wheels to speedup Travis builds

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3393]
Installation of dependencies on Travis builds takes on average 154s (50% of the build time).  With the changes to remove C optimisations in lxml (see #3389) we reduce that to 57s (better, but still about 25% of build time).

Other Travis users have used various methods to build wheels for their dependencies so that installs are in the seconds range.  We should probably look at that also if we want Travis build failures to arrive closely after a broken landing.

**Comment by julen** [comment]
This is somehow addressed by using container-based builds and caching in Travis, so I wonder if it's still worth exploring this option.

**Comment by unho** [comment]
If it is easy to implement and saves time, I think we should consider do it.

**Comment by julen** [comment]
Just checked out options here, and this will basically become a non-issue once Travis-CI upgrades its build environment with [pip 7](https://lincolnloop.com/blog/fast-immutable-python-deployments/).

**Comment by dwaynebailey** [comment]
It might be worth making our builds use pip7 like such http://stackoverflow.com/a/30425598
