### ISSUE TITLE
Change localize() calls with var substitution to calls that pass vars to jToolkit

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#340]
_Version: 0.7a1_

jToolkit has been patched to allow us to fallback to English if the localised
string has the incorrect variable count (bug #28)

We now need to change all instance of localize() that involve variable
substitution to the form that passes the variables to jToolkit.

Probably best to do this after the templating work.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
