### ISSUE TITLE
Organize cache timeout settings

### ISSUE THREAD

**Issue by julen** [translate/pootle#3402]
Currently there's a mess with respect to settings that control caching timeout.

There's the `OBJECT_CACHE_TIMEOUT` setting, which is very vague and it's not clear what it affects to. The docs say *Time in seconds the Pootle's statistics cache will last.* but this affects to anything but stats, which currently have no timeout setting associated with it. This setting is used for project/language lists or user permissions, for example.

Then there's the template fragment cache, which currently is only used for caching editing widgets (both for translation and terminology modes). The timeout for this is fixed, set at `0`, and it will never expire. Not everyone will be happy with this.

What I propose is to have a separate setting for each concern. Something like:

```python
POOTLE_TEMPLATES_CACHE_TIMEOUT = 987654
POOTLE_XXX_CACHE_TIMEOUT = 0
```

or even,
```python
POOTLE_CACHE_TIMEOUT = {
  'templates': 0,
  'xxx': 0,
}
```
Then we need to make sure the code is using the correct setting in the relevant location.

I understand these names might be way too verbose, any naming suggestions welcome.

**Comment by jleclanche** [comment]
@julen We're moving this to mstone-future. If you want it to land in 2.7, you'll have to act quick :)
