### ISSUE TITLE
Reduce memory load on search operations (and unit selection in general)

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3405]
Search operations use much memory on large data sets (for example, when searching across all projects/languages). On our particular database, the server process can easily take entire free memory (10-15 GB) and crash.

We need to find a way to run a search in a way that is DB size-independent. One potential solution to explore would be to always perform the search on one translation project at a time, get its results, then go onto another project. Same applies to simply selecting all units for translation.

In the simplest case, when no sorting is required, we can go through one translation project to another and stop searching immediately after we have enough units to be displayed. Once the user goes through the units and we need to load another portion of units, we can re-issue the search starting with the last known translation project / store / unit and gather the next set of data.

When we need to select units and sort them, we can scan through all translation projects (again, one TP at a time), gather and cache the list of matched units along with their attribute to sort by, then sort the resulting set and use it to display paginated data to the user. The storing of that sorted set can happen in .e.g Redis, and in this case we can leverage its sorted sets feature and automated key expiration mechanism to clean up data from past searches. Or we can store the data in in SQL database tied to user session + unique search identifier within that session, but then we will need to clean up the stale data periodically on our own.

**Comment by julen** [comment]
> Search operations use much memory on large data sets (for example, when searching across all projects/languages). On our particular database, the server process can easily take entire free memory (10-15 GB) and crash.

From the tests I've done and the patterns I've observed in our deployment, these operations don't eat memory as they did before; they are CPU-bound now. So this is not true anymore with the fixes done by @ta2-1 in 0d63e479e.

**Comment by julen** [comment]
Closing issue per the comment above. I have filed #3537 to address the speed concerns.
