### ISSUE TITLE
Add locale aware formatting to numbers

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3410]
On some of our pages numbers are reaching into the thousand and million count which makes the numbers harder to read without locale specific formatting, as can be seen in this navbar on the front page of the staging server:

![screen shot 2014-12-06 at 04 07 20](https://cloud.githubusercontent.com/assets/647438/5327301/9ed014c6-7cfd-11e4-9db8-5fbd043d7b82.png)

We should add locale aware formatting that would change e.g.

1000 -> 1,000 or 1 000 or 1.000
1000000 -> 1,000,000 or 1 000 000 or 1.000.000

In a locale aware away so that it is easy to read.

**Comment by unho** [comment]
Using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString in the JS code might be an option, but support varies from browser to browser and not all locales might be supported in a given browser.

**Comment by unho** [comment]
Another possible way to deal with this is using https://docs.djangoproject.com/es/1.9/ref/contrib/humanize/#intcomma
