### ISSUE TITLE
Add minimum Python-pip version requirement

### ISSUE THREAD

**Issue by arky** [translate/pootle#3412]
It would be a good idea to document that we now need Pip version 1.5.6 to run Pootle.  See bug https://github.com/translate/pootle/issues/3411

@dwaynebailey  Not sure which docs needs to be updated.

**Comment by dwaynebailey** [comment]
Our installation instructions for ``virtualenv`` based installation add a ``pip install --upgrade pip`` step so we are always on the latest ``pip``
