### ISSUE TITLE
Add default project descriptions

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3416]
In order to get ``initdb`` running on ``core`` we had to drop the project [descriptions] since these move to staticpages on core.  This bug is to add those back.

To achieve that initdb should create static pages for these default projects that contain the content previously held in the [descriptions](https://github.com/translate/pootle/blob/96edf539/pootle/core/initdb.py#L300-L306).

**Comment by unho** [comment]
Commit where description were dropped on initdb: https://github.com/translate/pootle/commit/078457ab#diff-7f8c84076d131103c0e7ea24c457f1b4R274
