### ISSUE TITLE
Improve check calculation speed in refresh_stats process

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3419]
We use `refresh_stats` command with `--calculate-checks` option to make the recalculation. It calls `Unit.update_qualitychecks()` method for every non obsolete unit in `pootle_store_unit` table.
The main issue is that every `Unit` object should be created.
The for loop in `Unit.objects.all().iterator()` works forever comparing to the loop in `Unit.objects.values('source_f', 'target_f', 'id')`.
I suggest to make possible using of `ENChecker` filters for string values not as method of `Unit` object only.

**Comment by unho** [comment]
Closed since stats infrastructure has been refactored and this no longer applies.
