### ISSUE TITLE
Rename regex variables for ENChecker filters

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3426]
We use regular expressions in quality check filters ( in `pootle_misc/checks.py`).
All regex variables defined in the beginning of module to have precompiled regular expressions on runtime.
This  `<filter_name>_regex_<index>` is variable name format.
Instead of meaningless indexes, let's use appropriate name suffixes for better readability

**Comment by jleclanche** [comment]
@ta2-1 status?

**Comment by ta2-1** [comment]
@jleclanche It haven't yet been done.

**Comment by dwaynebailey** [comment]
We don't have ENChecker anymore
