### ISSUE TITLE
Enable reporting to specific email address per project

### ISSUE THREAD

**Issue by unho** [translate/pootle#3440]
This is porting https://github.com/translate/pootle/commit/85bec12c  to core.

**Comment by jleclanche** [comment]
@unho looks like a typo in db8a0eb caused this to autoclose

**Comment by unho** [comment]
@jleclanche No, this is ok to be closed. In fact it seems like I forgot to close this when I landed those commits.

**Comment by jleclanche** [comment]
@unho db8a0eb is from january 2014, this bug is from last week.. you sure about that?

**Comment by unho** [comment]
@jleclanche I am completely sure. The commits fixing this were landed in core, which is current master. So this issue is fixed.
