### ISSUE TITLE
Issues with taggit migrations in stable/2.6.0

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3444]
Migrations from ``2.5.1`` to ``2.6.0`` are [failing in the migration tests](https://travis-ci.org/translate/pootle/jobs/45989213#L8386) for taggit, which is dropped, and thus potentially masking other migration issues. Can we fix these so that we can try to get back to green on that branch.

**Comment by unho** [comment]
A dirty hack that might work is to remove all references to taggit app in south_migrationhistory DB table.

**Comment by unho** [comment]
Fixed with https://github.com/translate/pootle/commit/3816e55c4cd593fb534ed3caea120dbe27a3d2b3 and https://github.com/translate/pootle/commit/5d5e9f6baf484ed32eab1e592058ca4cfc5320ff.
