### ISSUE TITLE
Translator submissions aren't being credited on the users page

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3445]
User [rat](http://mozilla.locamotion.org/accounts/rat) has no submissions shown on their user page:

![screen shot 2015-01-06 at 09 46 58](https://cloud.githubusercontent.com/assets/647438/5626914/9dbf4076-9589-11e4-8def-f2af24146068.png)

They are however credited on the [contributors](http://mozilla.locamotion.org/about/contributors/) page under Tamil, indicating that there is tracking of these contributions:

![screen shot 2015-01-06 at 09 47 24](https://cloud.githubusercontent.com/assets/647438/5626875/278652f0-9589-11e4-8cae-17a9b1a5353b.png)

I don't think that investigating this on current mozilla.locamotion.org code base is valuable as we might need to fix it again in core.  We do need to check this in core to ensure that this user does get credited on the new user page in core.  Also we should check this when we migrate mlo to core that the data migrates correctly.

**Comment by Rat-S** [comment]
Thanks for considering this issue.

**Comment by dwaynebailey** [comment]
The way we credit translators has massively changed in 2.7.0 so we'll close this
