### ISSUE TITLE
With no EMAIL_* users are still able to attempt to register

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3448]
If no `EMAIL_*` settings are set then password reset will fail with a traceback.  Pootle should not issue a traceback, it should at least report on the admin interface that users can't register/reset passwords because no `EMAIL` is setup (though I thought it did this previously).

Reset password should be disabled if there is no `EMAIL_*` setup.

**Comment by jleclanche** [comment]
Does this happen in the allauth branch?

**Comment by unho** [comment]
To my understanding having email settings is a hard requirement since otherwise users can't register and there is no way to contact admins, so adding a check that ensures the email settings are configured feels the right approach.

**Comment by unho** [comment]
After a second review that actually doesn't fix anything.

**Comment by unho** [comment]
Actually ensuring a working server is available we can avoid this situation. See PR #4011.
