### ISSUE TITLE
allauth: Settings CAN_REGISTER needs review with allauth changes

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3449]
CAN_REGISTER is present in pootle/templates/account/password_reset.html on core but not documented.  It is present and documented on master.  So either it must go on core or be ported from master, I suspect the later.

**Comment by jleclanche** [comment]
I noticed that the entire doc page was gone from core so I didn't look into it further, I just assumed EN dropped support for it. @julen thoughts?

**Comment by julen** [comment]
There's no such template in core and [`CAN_REGISTER` was wiped out](https://github.com/translate/pootle/commit/37fc8ed) because we no longer offer model-backed user signups (they must use their EN accounts to log in), which was offered via django-registration at the time.

**Comment by dwaynebailey** [comment]
Ah @jleclanche CAN_REGISTER came back to pootle/templates/account/password_reset.html in 701c687da125a01c7c2dbe23130aaffd1b6d9c3b so the errors is on the allauth branch.

**Comment by julen** [comment]
Just added this to the allauth tracker — we need to be able to completely forbid user registration. Can you please look at this sooner than later @jleclanche?
