### ISSUE TITLE
Follow-up on report string errors setting

### ISSUE THREAD

**Issue by julen** [translate/pootle#3453]
Now that #3442 has been merged, I was integrating the required setting changes on our deployments and was thinking that...

1. A sane default value for `POOTLE_REPORT_STRING_ERRORS_EMAIL` could be `CONTACT_EMAIL` itself. This way small deployments won't need to adjust this most of the time.
2. `POOTLE_REPORT_STRING_ERRORS_EMAIL` is a super long setting name. What about aligning with the other contact settings and using something like `POOTLE_CONTACT_REPORT_EMAIL`? (yes I know `CAN_CONTACT` and `CONTACT_EMAIL` are still missing the `POOTLE_` prefix). I see this change is safe to make without affecting anybody since it's been only included in 2.6.0-rcX, and that's an *unreleased* version.
3. `POOTLE_REPORT_STRING_ERRORS_EMAIL` is missing the `.. versionadded::` directive in the docs.

Thoughts?

**Comment by unho** [comment]
@julen My thoughts below:

1. I am not against this, despite current status emphasizes that it is not necessary to use the same email address.
2. Yes, it is a really looooong name :). I was trying to make it really explicit to avoid people asking what was its purpose. But I suppose people is stupid enough to ask that even with the really long name. Anyway the proposed name is still long and I don't like it. What about `POOTLE_STRING_ERRORS_EMAIL` which is one character shorter?
3. Obviously I forgot about this. I am fixing this.

**Comment by unho** [comment]
Fixed 3 in https://github.com/translate/pootle/commit/a70354cf.

**Comment by julen** [comment]
1. You can still keep emphasizing it's possible to use a different email address in the sample configuration file (no change needed) and let the default be `CONTACT_EMAIL` at the same time.
2. I used the `POOTLE_CONTACT_` prefix for grouping purposes so contact-related settings can be easily identified. Keeping that in mind can you think of something you like and is <30 chars?

**Comment by julen** [comment]
So which name are you happy with? Any other opinions around?

**Comment by unho** [comment]
@julen The one you proposed, `POOTLE_CONTACT_REPORT_EMAIL` if I am not wrong. Go ahead with the rename.

**Comment by unho** [comment]
@julen And as I told, I am ok with using `CONTACT_EMAIL` as the default value, as long as the comments for `POOTLE_CONTACT_REPORT_EMAIL` (this is the new name) clearly state that it can be set to be any email, providing the current example https://github.com/translate/pootle/blob/e4fafa85/pootle/settings/30-site.conf#L33.
