### ISSUE TITLE
Align on core the User model to match stable/2.6.0

### ISSUE THREAD

**Issue by unho** [translate/pootle#3456]
This probably depends on porting core to allauth (see PR https://github.com/translate/pootle/pull/3447).

Have in mind that we are not talking about where the code lives, but about the DB schema, because that is what matters to allow a clean upgrade from the transitional 2.6.0 release.

**Comment by unho** [comment]
Have in mind that User models is in accounts app in stable/2.6.0 branch and in pootle/models/user.py in core branch.

**Comment by unho** [comment]
After a quick check I noticed that several fields have to be added on stable to the user model, particularly all the score related ones https://github.com/translate/pootle/blob/55c25f92/pootle/models/user.py#L96-L108.

**Comment by unho** [comment]
Also note minor changes required by some other fields!

**Comment by jleclanche** [comment]
I actually disagree with several of those new fields. All of them except score, in fact. An argument can be made for website at best.

**Comment by unho** [comment]
@jleclanche It is easier to just pick them. We can figure out later what we do about those fields.

**Comment by jleclanche** [comment]
@julen do you have any specific plans for those fields? long term, they don't belong in core anyway.

**Comment by unho** [comment]
I posted it up, but stating it again: I added a new issue for picking `core` branch User fields to `stable` branch User, while this stays for adjusting core fields to what is in `stable` branch.

**Comment by unho** [comment]
@jleclanche Just to clarify a bit more the scope of this specific issue, the changes between stable and core User models that need to be addressed in this issue are:

```diff
--- /core_pootle/pootle/models/user.py
+++ /stable_pootle/pootle/apps/accounts/models.py
@@ -74,18 +74,13 @@
         help_text=_('Designates whether this user should be treated as '
                     'active. Unselect this instead of deleting accounts.'),
     )
-    is_superuser = models.BooleanField(
-        _('Superuser Status'),
-        default=False,
-        help_text=_('Designates that this user has all permissions without '
-                    'explicitly assigning them.'),
-    )
 
     date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
 
     # Translation setting fields
-    unit_rows = models.SmallIntegerField(
+    _unit_rows = models.SmallIntegerField(
         default=9,
+        db_column="unit_rows",
         verbose_name=_("Number of Rows"),
     )
     alt_src_langs = models.ManyToManyField(
@@ -93,22 +88,9 @@
         blank=True,
         db_index=True,
         limit_choices_to=~Q(code='templates'),
+        related_name='user_alt_src_langs',
         verbose_name=_("Alternative Source Languages"),
     )
 
     USERNAME_FIELD = 'username'
     REQUIRED_FIELDS = ['email']
```

**Comment by unho** [comment]
Issue https://github.com/translate/pootle/issues/3298 is part of this.

**Comment by jleclanche** [comment]
All done it seems
