### ISSUE TITLE
Rename pootle_profile app to accounts

### ISSUE THREAD

**Issue by unho** [translate/pootle#3460]
Probably related with moving core to allauth (see PR https://github.com/translate/pootle/pull/3447).

**Comment by jleclanche** [comment]
There's no reason to do that, accounts and profiles are handled separately. There's arguably some bits to be moved to the (existing) accounts app but no reason to rename pootle_profile to anything else than `profiles`.

**Comment by unho** [comment]
@jleclanche The idea behind this is that if we drop the `PootleProfile` model and merge it with `User`, then we can drop the specific app for it and it becomes the `accounts` app, like in master branch.

**Comment by jleclanche** [comment]
PootleProfile is already dropped in core.

**Comment by julen** [comment]
@unho the assumptions of this issue are incorrect — `PootleProfile` model is long gone as @jleclanche said.

About 6 months ago we refrained from moving the views out of `pootle_profile` not to misalign directory layouts even more without reaching an agreement first.

**Comment by jleclanche** [comment]
@julen Where would you personally like to see the profile views go?

**Comment by julen** [comment]
This depends on what we agree upon as a general directory layout.

**Comment by unho** [comment]
@julen @jleclanche Yes, I knew that `PootleProfile` had already been dropped. I clearly need to start thinking on english instead of galician to avoid this kind of confusions. I apologize for the time wasted.

Let me restate. Since we already dropped the `PootleProfile` model by merging it with `User` (both on core and stable branches), I think it is a good idea to move the rest of the code in `pootle_profile` app to a new `accounts` app like in stable branch (which actually would be renaming the app).

**Comment by julen** [comment]
Closing in favor of #3656.
