### ISSUE TITLE
Improve per product language support

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#347]
_Version: 0.7a1_

_Originally posted by Oscar Manuel Gómez Senovilla:_

In the language page for a product, there isn't option for deleting a language.
Also, the rest of the options in the same aren't clear, and I'm still not sure
of what the checkbox does, along with the "update from templates" link. Maybe a
"title" tag in the link or a more verbose text could help (since I don't know
the function of each link).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
