### ISSUE TITLE
Add docs on how to setup background jobs

### ISSUE THREAD

**Issue by julen** [translate/pootle#3473]
Docs for rqworker and friends is very lacking. The installation guide should include minimal instructions on how to set it up.

**Comment by julen** [comment]
Related: #3351

**Comment by unho** [comment]
Not sure if 4fca2562 tackles this.

**Comment by dwaynebailey** [comment]
Both 98511c416accfc334df02d388a96ff833160b696 and 4fca256 provide documentation to address this issue.
