### ISSUE TITLE
API authorization is broken

### ISSUE THREAD

**Issue by julen** [translate/pootle#3485]
The API shipped in current stable (2.5.1) [claims that](http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/api/using.html#authorization) *in order to avoid all users access or alter data they are not meant to, the Pootle API checks if the visitor has enough permissions to perform the requested actions on the resources. The permissions used for these checks are the same permissions used in Pootle for regular users.*

The API resources in Pootle are using [Tastypie's own `DjangoAuthorization` class](http://django-tastypie.readthedocs.org/en/latest/authorization.html#djangoauthorization) for authorization purposes, [`ProjectResource` for instance](https://github.com/translate/pootle/blob/27b031894e412496d70cc0679daacb073e469fbd/pootle/apps/pootle_project/api.py#L60). This class in turns integrates with Django's built-in permissions, but the problem is Pootle uses custom authorization mechanisms, and permissions are not handled the same way as in Django. Therefore any API resource using `DjangoAuthorization` as an authorization class is broken.

To fix this it's necessary to create and use an authorization class that truly checks Pootle's permission system.

**Comment by jleclanche** [comment]
Whatever comes out of this will probably need to be cherry-picked to stable/2.6.0

**Comment by dwaynebailey** [comment]
> Whatever comes out of this will probably need to be cherry-picked to stable/2.6.0

Likely not, its off by default and I doubt any real users have activated it.

**Comment by julen** [comment]
It'll save you a migration. The commit that was proposed to be cherry-picked needs to be reverted though.

**Comment by unho** [comment]
This is only relevant if we ship a 2.5.1.2 or if we want to port the API to new master.

**Comment by jleclanche** [comment]
Who are our API users?

**Comment by x-cray** [comment]
@jleclanche I'm implementing CI with translation templates automatically updated in Pootle on every build.

**Comment by jleclanche** [comment]
@x-cray This is a use case we want to support but the API is gone in 2.7. If you hop on irc, `#pootle-dev` on freenode, we can discuss it because we have alternatives.

**Comment by jleclanche** [comment]
Closing, API is gone.
