### ISSUE TITLE
"nobody" and "default" should not be valid usernames

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#349]
_Version: 0.7a1_

Users can be created with the names "nobody" or "default" which can interfere
with rights management in a project. 

For example, if the user "nobody" is created, and admin rights (say) are
assigned to him, the anonymous user (any user not logged in) receives admin
rights for that project. Such a user will perhaps also not receive the rights of
the default user.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
