### ISSUE TITLE
Perform RTL review of core

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3498]
With the number of changes on core we're no longer sure of our RTL status.  We need to do an RTL review of the new features and land any fixes for RTL.

**Comment by dwaynebailey** [comment]
@khaledhosny would you be willing to have a look at this for us?

**Comment by khaledhosny** [comment]
I’d love to, but I’m not sure when I’ll have enough time to setup a Pootle instance to test this (there seem to have been many changes lately and I’m not following things closely).

**Comment by jleclanche** [comment]
We should be setting up a proper staging 2.7 server at some point soon.

**Comment by khaledhosny** [comment]
That should make things simpler.

**Comment by dwaynebailey** [comment]
Note to self: we'd need localisation recovered for this to be most useful and language switcher which we did on ``<2.7.0`` but which EN dropped.

**Comment by SafaAlfulaij** [comment]
@khaledhosny There are currently two servers using the master version, translate.evernote.com and pootle.lxde.org. I think that they can be used to check RTL layout ;)

**Comment by dwaynebailey** [comment]
We've been doing a review for the 2.8.0 release.  This has been superceded by #4925 which covers RTL issues still to be resolved.
