### ISSUE TITLE
When segments does not exist, return errorstr in non-debuging mode

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#350]
_Version: 0.7a1k_

_Originally posted by Alberto Escudero:_

I am not sure if consider this a bug but a "debugging" code :)
# Write an error out, in case this is a real problem instead of an absence of an

index
errorstr = str(e).strip() + "\n" + self.errorhandler.traceback_str()

What other kind of errors are expected? 

Make it a debug option

2006-04-01 18:09:13: could not open index, so going to create, error follows:
java.io.FileNotFoundException:
/home/aep/test4/po/ooo/sw/.poindex-ooo-sw/segments (No such file or directory)
Traceback (most recent call last):
  File "/usr/local/lib/python2.4/site-packages/jToolkit/data/indexer.py", line
304, in **init**
    tempreader = indexer.IndexReader.open(self.storeDir)
JavaError: java.io.FileNotFoundException:
/home/aep/test4/po/ooo/sw/.poindex-ooo-sw/segments (No such file or directory)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
