### ISSUE TITLE
Document clear_stats command

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3500]
``flush_cache`` was added in 98241580063576d3ed06b01248e955af54b210c5 but not documented.  See also #2927 for description and rationale that could help documentation.

**Comment by ta2-1** [comment]
Current implementation of `flush_cache` command has no sense now. Filled Redis stats cache is a requirement and if we need to refresh stats we use `refresh_stats` command.
I see two options:
- Drop this command;
- Change it for flushing something like Django templates cache.

@julen?

**Comment by julen** [comment]
Now that more named caches are in use, I wouldn't mind adjusting the command to run `cache.clear()` for a given named cache. I'd also be in favor of renaming the command to `clear_cache` (`flush` might result ambiguous).

These would be valid cases:

```python
$ python manage.py clear_cache stats
$ python manage.py clear_cache template_fragments
```

Although the command is pretty simple and anyone can implement it, the point of having it would be being an utility when upgrading deployments.

**Comment by julen** [comment]
Actually as I'm working on #3364, what I was proposing in the previous point cannot be done blindly, because we want to have some data always available on Redis (the revision counter this time), and clearing a cache would wipe out all the existing data.

Having said that, blindly clearing **most** of the caches is fine, but not all of them.

For convenience, the keys that need to be **preserved at any time** will need to go to the same cache (let's say `default`), and we'd need to keep these keys in a whitelist so we'd be able to save-restore them at the time of doing the clear.

Does this make sense @ta2-1? Any other thoughts?

**Comment by julen** [comment]
As a side note and for the specific case of the revision counter, I'm thinking about providing a way to restore it from the DB too.

**Comment by ta2-1** [comment]
Hmm... I thought revision counter shouldn't be saved via django redis cache API.
And can I ask one more time?
Why do we need to keep `clear_cache` command for stats cache?

**Comment by julen** [comment]
> Hmm... I thought revision counter shouldn't be saved via django redis cache API.

Please move any revision-related discussion into its relevant issue.

> And can I ask one more time?

I'm missing any questions in your previous comment.

> Why do we need to keep clear_cache command for stats cache?

I see your point on `clear_cache` being useless for stats as it's a requirement to have it filled in with values (even if they are zero) — what I wrote was just meant to be an example on the use of `clear_cache`, so disregard any actual cache names.

**Comment by dwaynebailey** [comment]
Busy reviewing documentation.  Was about to add doc for this but based on the discussion I won't do that.

**Comment by unho** [comment]
Just a note from a discussion me and @ta2-1 had these days: it might be worth renaming the command to `flush_stats` or similar in the meantime, so it aligns with `refresh_stats`.

**Comment by unho** [comment]
The command has been renamed to `clear_stats` in d731fd3f.
