### ISSUE TITLE
Adjust Evernote auth backend to the allauth branch

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3515]
We need to take the Evernote auth backend out of core and integrate it in the allauth branch. The natural way for doing so would be to write an allauth social provider, but the steps to do so are unclear (no docs, just some provider examples) and have other effects.

Implement the backend as an allauth provider
---

Pros:
+ It uses the same mechanisms as core, better integration

Cons:
- Allauth uses its own models/DB tables for keeping the link between social providers and users
- Need for data migrations 

Keep evernote auth backend
---
Pros:
+ Already implemented, tested and deployed
+ No need for data migrations

Cons:
- It *might* distance itself a little bit from the auth approach core has taken
- Need to hijack URL patterns.

**Comment by julen** [comment]
Also note that whatever approach we decide to take, we need to take the existing code away from the master branch, as well as adjust the requirements that this has imposed until now.

**Comment by unho** [comment]
@julen Can't your code stay? I mean, is it not possible to alter the build scripts to exclude that code and get clean packages?

**Comment by julen** [comment]
@unho I don't see much value in keeping our code there as it's only valid for us.

**Comment by julen** [comment]
We had an attempt to enable our auth backend side-by-side with allauth, and it works, but measuring the risks and potential issues we have decided to take the way to implement an allauth provider.

In any case, the documentation in allauth in this regards is basically null, and since our backend is not similar to any available out there, we'd appreciate any type of help to move this forwards.

**Comment by jleclanche** [comment]
@julen Keep in mind that when I originally suggested allauth, I thought your evernote auth was oauth2-based.

I was having this discussion the other day actually and I don't understand what the benefit for you is not to use the public evernote oauth system.

**Comment by ta2-1** [comment]
@jleclanche, is there ready allauth provider for Evernote?

**Comment by jleclanche** [comment]
@ta2-1 Not unless they added one recently, but seeing as EN uses oauth2 as a provider, it would be a mere few lines of code to write one (basically just settings).

**Comment by ta2-1** [comment]
I haven't got (added or not). 
We found this issue https://github.com/pennersr/django-allauth/issues/556
It's closed and there no Evernote provider here https://github.com/pennersr/django-allauth/tree/master/allauth/socialaccount/providers.

**Comment by julen** [comment]
Sorry hit the button accidentally.

**Comment by dwaynebailey** [comment]
Have we made any direct contact with the authors of allauth? I could imagine that there is limited/no docs on the backends as they are one off creations and there aren't a ton of them to justify extensive documentation.

Maybe touching base with them on their channel would be the quickest way to clarify things and maybe even to get assistance with the implementation.  I doubt that they would push away someone wanting to implement a backend.

**Comment by jleclanche** [comment]
Yes, I filed pennersr/django-allauth#814 with no answer yet, though it's more specific than the general lack of documentation.

But to be honest, I had a look through some of the code today and I didn't find it specifically difficult to follow through. Creating a new backend seems fairly straightforward with everything happening in authenticate().

**Comment by julen** [comment]
Seeing the state of things, from our side finally we'll keep our existing backend, and simply ignore allauth's social provider capabilities, thus continuing the route @ta2-1 already took.

**Comment by jleclanche** [comment]
Ok, great.

Does that mean the allauth branch can land soon? Or are we still looking for UI changes?

**Comment by julen** [comment]
As mentioned since the very beginning #3343 will be merged once it has been fully implemented.

**Comment by julen** [comment]
This is done on our side, closing.
