### ISSUE TITLE
Implement new authentication workflow

### ISSUE THREAD

**Issue by julen** [translate/pootle#3517]
UI aside, we need to be able to support the following login, registration and password reset workflow:

![sign-in-flow-v2_gh](https://cloud.githubusercontent.com/assets/16768/5070768/8bf8305a-6e6a-11e4-8673-08968bf6be20.png)
![sign-in-flow-v2_gh_2](https://cloud.githubusercontent.com/assets/16768/5070770/8f25765c-6e6a-11e4-9b87-26b4418ebe2c.png)

It's unclear if allauth supports the following, which are needed:
* Linking and unlinking of social providers from users. We currently provide the option to link/unlink a user from an EN account in the user settings page, and this needs to be kept. (not covered in the mockups @iafan, it probably should).
* Talking to the backend via XHR requests ([it doesn't seem to be supported](http://stackoverflow.com/questions/16162108/implementing-ajax-requests-response-with-django-allauth)).

**Comment by jleclanche** [comment]
I filed an issue on django-allauth asking for confirmation on how to unlink social accounts. i suspect it's a matter of deleting the SocialAccount row but there may be more to it.

**Comment by julen** [comment]
Just checked again the state of XHR and [according to the tests](https://github.com/pennersr/django-allauth/blob/master/allauth/account/tests.py) they implemented this in some views (this happened after the previously-linked SO question), so let's make sure all the workflow can be covered.

**Comment by julen** [comment]
There are more workflow-related questions to be answered though.

On the one hand, when someone tries to log in with a social service for the **first time**, it's not clear if it needs to:
1. Display an error if there's no user linked to the social account. This involves first creating a user, then manually linking to it.
2. Automatically create a new user based on the social service data. I wonder if some providers may not be suitable for this step as they might not offer all of the necessary information to create a Pootle user?
3. Offer to link the social service to an existing user

The current approach at EN is a combination of 3 & 2: we want actual EN users to be the translators, so they can only register using EN, and on the first login we *offer* them to link the social service to an actual Pootle user (3). If this step is skipped, a new Pootle user is created automatically using the data provided by the social service (2).

On the other hand, the mockups don't describe how the interaction with the external auth will happen. This always implies visiting an external page to perform authentication, and it can either redirect the current page to the social service or it can open a popup with the auth request of the social service. An example of a clean and non-disruptive workflow of the latter can be experienced at stampsy.com.

**Comment by iafan** [comment]
I'd prefer creating the user automatically — or linking it automatically to an existing user — by his email. In this case, providers must only authenticate users when they have their email verified (in other words, we should be able to trust an email that comes from the social service). I believe that email is one and only information a provider should report to Pootle. Based on the email address, we can auto-generate the username. Everything else, like full name, is optional, and can be filled in by the user himself. Of course, we can be smart here and pre-fill the username, and try the preferred username if this information is provided by the auth plugin.

**Comment by julen** [comment]
After discussing this, we'll make a change both in our workflow and in our SSO provider, therefore automatically create a user upon first login, without any prompts.

This way linking and unlinking is left behind in this workflow, and since it's not a critical feature on our side (again, we require all of our translators to be EN users), we can address that at a later stage.

**Comment by julen** [comment]
Any progress on enabling the XHR endpoints?

**Comment by jleclanche** [comment]
No, I'm on exports right now - allauth had to take a backseat to it since it's not a blocker anymore.

**Comment by julen** [comment]
This does block having a functional UI and our work on it.

**Comment by iafan** [comment]
@jleclanche, would be great if you could help Julen with this allauth/XHR stuff when he asks to do so. After all, allauth-related work is not anywhere near the completion, as it requires major UI overhaul (which Julen kindly put on his plate), not to mention extensive testing. Without that, we won't be able to merge that chunk of work into master, and this might affect your release plans.

**Comment by julen** [comment]
@jleclanche I'm using your current work on this and works fine, but can we also get rid of the annoying messages, please? As I see it'd be straightforward, just reimplement the `add_message` method in our adapter to a no-op `pass`.

**Comment by julen** [comment]
As I see when signing up for a new account, allauth automatically logs the user in even if the email address hasn't been confirmed. This is not in par with the workflow that we want to achieve here (see screens 5 and 8). @jleclanche can you address this please?

**Comment by jleclanche** [comment]
I'm confused as to why it would do that. That's why confirmation is there in the first place...

**Comment by julen** [comment]
Reasoning aside, the fact is that it currently behaves like that.

**Comment by iafan** [comment]
I added a new screen and comments on account linking:

![sign-in-flow-account-linking](https://cloud.githubusercontent.com/assets/1728158/6233498/25054aca-b688-11e4-9105-ca008f2722b3.png)

**Comment by jleclanche** [comment]
@julen allauth seems to have gained a LOT of settings since i first played with it:
http://django-allauth.readthedocs.org/en/latest/configuration.html

email confirmation was just allauth defaulting to "optional" rather than "mandatory". I've changed that now.

Do take a look through those options. Some stuff is relevant to what we're doing here.

**Comment by julen** [comment]
Thanks @jleclanche!

**Comment by julen** [comment]
@iafan I'm not sure the second part of your mockup makes complete sense to me.

First it says that it will create a user account automatically (fine), but then requests users to create (and then input) a password if they don't have one yet. IMO the second proposed screen defeats the purpose of having social sign in, and looks completely unnecessary unless I'm missing some detail.

**Comment by julen** [comment]
@jleclanche please also set `ACCOUNT_CONFIRM_EMAIL_ON_GET = True`, otherwise there's an extra confirmation step involved — clicking the link from the email should be enough.

**Comment by julen** [comment]
@iafan the *Resend Email* action from step 8. is not necessary, because [allauth will automatically resend the confirmation email](https://github.com/pennersr/django-allauth/issues/218) if a user tries to log into an inactive account. So we only need to display screen 8. upon a login attempt on an inactive account. 

@jleclanche in this context, when a user tries to log in, we need to let the client know the account is inactive as part of the XHR response — currently it redirects to `/accounts/confirm-email/` and displays a template. Can you please have a look at this as soon as it's possible?

**Comment by jleclanche** [comment]
@julen Im not entirely sure what you mean. On the `/accounts/confirm-email/` page, do you have access to that user account? if you do, it's a simple matter of checking whether the account is inactive, no?

**Comment by julen** [comment]
This is about the `/accounts/login/` view: instead of [being interrupted by a redirect](https://github.com/pennersr/django-allauth/blob/0a9b326d629b922cec73c3c205467af42895d275/allauth/account/utils.py#L118-L119) in the middle of the XHR request, it's necessary to return a response indicating teh account is inactive.

**Comment by jleclanche** [comment]
@julen Does that `reverse('account_email_verification_sent')` remember the fact you queried with XHR? I'm guessing not.

A thought occurs that if not, we could fix that, and reimplement xhr-specific functionality for that view.

**Comment by julen** [comment]
Nope, it blindly redirects the browser to `'account_email_verification_sent' in the middle of the request.

**Comment by jleclanche** [comment]
@julen Looking deeper at how the code is structured I don't think there is a way to really fix this without rewriting a large portion of it. Can we hack this one and catch the redirect from js? In the mean time one can file an issue on django-allauth and see what they say about supporting xhr there somehow.

**Comment by julen** [comment]
There's no way to do such a hack, [by XHR's design](http://www.w3.org/TR/XMLHttpRequest/#infrastructure-for-the-send%28%29-method).

Note this is a blocker to implement the auth workflow: it's necessary to get a response with relevant data, not an abrupt redirect.

**Comment by jleclanche** [comment]
Darn, I was hoping this was possible. Ill file a bug.

**Comment by julen** [comment]
@jleclanche one small detail. It'd be great if we can make the `uidb36` and `key` URL params from the `account_reset_password_from_key` view available to the *password_reset_from_key.html* template. For the time being I'm using `window.location.pathname`, but I strongly dislike the idea of coupling the `window` object to the API module — this needs to deal with the auth backend, no more.

**Comment by julen** [comment]
Found another two blockers @jleclanche, which are very likely related one with each other:

1. When successfully resetting the password via the form you reach after clicking the link received in the email, the response returns a template (`Content-Type: text/html`), not JSON.  
It's worth noting that requests to this endpoint ending up in error (because of validation errors, for example) do return JSON.
2. When the password has been reset, the template that it returns displays a message providing a link to users so they can log in as a separate step. In other words, users are still logged out after successfully resetting their passwords.  
As displayed in the 9th mockup, a successful password reset should perform a login with no need for extra steps.

**Comment by julen** [comment]
> 1. When successfully resetting the password via the form you reach after clicking the link received in the email, the response returns a template (Content-Type: text/html), not JSON.

Hmmm now I'm able to get JSON with a `location` field as expected. It was very likely an artifact of continuous testing.

The other issue still remains true though: it needs to log the user in after successfully resetting the password.

**Comment by iafan** [comment]
@julen,

> but then requests users to create (and then input) a password if they don't have one yet

No, we're not asking users to create a password. The user only needs a password to link existing Pootle account with the social service. This will also happen if the users try to use multiple social services to log in. But for as long as they use the single social service, they will not need to care about the passwords.

**Comment by julen** [comment]
FTR: the blind redirect to `'account_email_verification_sent'` has been addressed.

Automatically signing in after password reset is still awaiting input from upstream.

**Comment by jleclanche** [comment]
> Automatically signing in after password reset is still awaiting input from upstream.

I realize this is good UX but it's not a blocker for this to land. It can be addressed later.

**Comment by julen** [comment]
This was already implemented.
