### ISSUE TITLE
Implement UI for new authentication workflow

### ISSUE THREAD

**Issue by julen** [translate/pootle#3518]
We need to implement the UI to make the new authentication workflow (#3517) a breeze to use. See the attached mockups for a detailed overview of where we want to reach.

![sign-in-flow-v2_gh](https://cloud.githubusercontent.com/assets/16768/5070768/8bf8305a-6e6a-11e4-8673-08968bf6be20.png)
![sign-in-flow-v2_gh_2](https://cloud.githubusercontent.com/assets/16768/5070770/8f25765c-6e6a-11e4-9b87-26b4418ebe2c.png)

**Comment by julen** [comment]
As we see in the mockups, the new UI can be triggered from any page, so it's not tied to an specific context. At the same time, it's a requirement being able to trigger the UI from external URLs, because:

1. they will be present in verification/password reset emails, and
2. in any situation it allows to point users in the right direction

For these scenarios where someone is navigating into Pootle using an externally-provided URL, I'd propose using the welcome page as a context.

The caveat would be if someone closes the popup when accessing one of the auth-specific URLs, the user is left off with a URL in the `/accounts/` namespace but the displayed content refers to `/`, the welcome page.
In the ideal situation, this can be addressed by wrapping auth URLs in a client-side router, so for example with a router mounted at `/`, a URL such as `/signup/` would trigger the UI and it would be a façade that knows how to talk to `/accounts/signup/` behind the scenes, and also knows it needs to restore the URL to `/` when the view has been unmounted.

The ideal situation provides the best UX but at the current state of things it would take longer to implement too. Having said this, personally I'd live with the caveat for now and propose the ideal scenario as a future improvement.

Any other suggestions or thoughts on the matter? @iafan @dwaynebailey

**Comment by iafan** [comment]
What I was envisioning here is to use hash for that, since sign-in popups are shown by the client code. So if you are on any page, for example, `https://translate.evernote.com/ru/kb_evernote/translate/articles/#filter=incomplete` and you click on 'Sign In', the popup will appear and the URL (it's hash part) will be rewritten like this: `https://translate.evernote.com/ru/kb_evernote/translate/articles/#filter=incomplete&sign-in`

Similarly, if one goes to the above URL from any external link, they will see the page underneath + the sign-in popup. This will allow us to send out account activation links pointing to the same URL the user was on, so that the flow is not interrupted.

This means that we won't need any real auth-specific URLs. If the sign-in UI can be triggered from any page, why do we need any dedicated URLs?

**Comment by julen** [comment]
I'm not convinced with the approach you propose, and here's why: due to the nature of our client-side code, it requires to have the trigger implemented for different scenarios differently — the editor or overview pages would need different code in order to support this, besides the fact there's no client-side "routing" in some pages.

It would also require complicated logic handling to delay loading any contents that might potentially be restricted to the user that is about to log in. Or, in its case, it would require to load unnecessary contents because the page would need to be reloaded after a successful login anyways.

This is not very DRY and it's easy to miss out details when creating new or modifying existing code.

Besides, there's the fact that it's 2015 and I have a strong -1 on keeping using hashes for app URL routing unless it's strictly necessary to support non-modern browsers, which fortunately enough is not our case.

Passing any sign in URL with a `next` query parameter will already take care of redirecting users back to where they were. Also, in any context and you'll need to reload the page to display the updated contents, so a redirect is not any different from that.

> This means that we won't need any real auth-specific URLs. If the sign-in UI can be triggered from any page, why do we need any dedicated URLs?

Because they are shared as links that are part of reset & activation emails.

**Comment by iafan** [comment]
Ok, after discussion I tend to leave this up to you and have special URLs for password reset / account verification flow. Let's use that and see if it gives the proper final user experience.
