### ISSUE TITLE
Use `trimmed` flag for `{% blocktrans %}`

### ISSUE THREAD

**Issue by julen** [translate/pootle#3528]
[Django 1.7 introduced](https://docs.djangoproject.com/en/1.7/releases/1.7/#internationalization) the `trimmed` flag for the [`{% blocktrans %}`](https://docs.djangoproject.com/en/1.7/topics/i18n/translation/#std:templatetag-blocktrans) template tag. This removes whitespace from the beginning and end of the block, therefore allowing to indent such translatable texts without accounting the whitespace as translatable content. Several Pootle templates can benefit from this and we'll gain readability.

**Comment by unho** [comment]
I have been waiting for this since I started using Django.

**Comment by julen** [comment]
I intentionally left out some templates which will be imminently gone, and also some blocks affecting inline elements.
