### ISSUE TITLE
VFolders: Alter VirtualFolder.save() to to append `-virtual` to the name if necessary

### ISSUE THREAD

**Issue by unho** [translate/pootle#3534]
If the vfolder name conflicts with any the name for any existing directory or file in the vfolder location it is necessary to rename it. Have in mind that the location can use any combination of `{LANG}` and `{PROJ}` placeholders, so it would be necessary to check all the matching TPs.

**Comment by unho** [comment]
@iafan What about raising an error when we try to add a vfolder named like a regular folder?

**Comment by iafan** [comment]
@unho, I'm not opposed to this approach. How will we cover the situation when the physical folder is added on update_stores, and such a virtual folder already exists? Also raise an exception? How will one rename the virtual folder to resolve the conflict?

**Comment by dwaynebailey** [comment]
@iafan My view is this:

1. If there is a name clash we disable the vfolder (even if that clash happens by the appearance of a new folder that matches the vfolder)
2. Report this as part of update_stores
3. I'd like Pootle to run fine even with an unresolved clash so no exception raising that would disable anything.  An exception might be useful for someone doing some remote monitoring.
4. To be able to rename the vfolder we'd need to have the ability to delete vfolders
5.  I'd style a clashing vfolder differently on the admin view of the vfolders and disable all information.

**Comment by iafan** [comment]
Thanks, @dwaynebailey. I agree with your vision here. It might be easier to simply disable the vfolder than to implicitly rename it (this would change its URL and break inbound links, if any).

As for item 4, I think at some point I shared an idea to replace all the vfolders based on the vfolder description .json file. So deleting or renaming the vfodler would mean adjusting the same master .json file that contains all the descriptions and running the `add_vfolders` command (also it might make sense to rename this command to `update_vfolders` for clarity). Such a command would complain on any folder naming conflicts.

**Comment by unho** [comment]
Related #3809.

**Comment by unho** [comment]
See #3905 for temporary workaround.

**Comment by phlax** [comment]
this was fixed by #5221
