### ISSUE TITLE
RQ job fails if multiple obsolete items comes in one update

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3535]
I got "cache miss" error in RQ job when multiple stores or directories for one parent item should be made obsolete during `update_stores` command.
RQ job for the first item starts before the second or third or ... items are set as obsolete and it waits for valid cached values for them.

**Comment by iafan** [comment]
Does this error makes RQ jobs fail?

**Comment by ta2-1** [comment]
@iafan, stats cache must be filled. if it is not we are not able to calculate the right values.
