### ISSUE TITLE
VCS using Git: deal with merge conflicts

### ISSUE THREAD

**Issue by wthielen** [translate/pootle#3536]
**Test case**
- In Pootle, update some text in a PO file
- In the code, add a new string, put it in the PO file, commit and push to repository
- In Pootle, trying to commit the updates results in a merge conflict

**Suggestion for resolution**
Since it is less of a deal to add new strings in the PO file from the source code (this is an automatic process, using POedit here), when commiting changes from Pootle to VCS, my opinion is to do the following:
- Changes are in the `/po` directory
- Pull latest version from the VCS first in `/repos/<project>`
- Copy the files from the `/po` to the `/repos/<project>`, thereby overwriting the string addition (not a huge deal)
- Commit and push to repository

This way, the translator's work is preserved, and the programmer only needs to pull and re-source from code in POEdit.

Thoughts welcome.

**Comment by julen** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.

**Comment by wthielen** [comment]
Oh? Since when? I see we are using 2.5.1.1 with our project.
In any case, looking forward to the new implementation of VCS support!

**Comment by julen** [comment]
There are several worlds of difference between 2.5.1.x and current master, where the VCS feature has been dropped. The general suggestion is to handle VCS processes out of Pootle, then use update/sync with Pootle in a timely fashion.
