### ISSUE TITLE
Improve unit retrieval time

### ISSUE THREAD

**Issue by julen** [translate/pootle#3537]
In #3405 we vastly reduced the unit retrieval memory footprint, but there are still some bottlenecks that make the data slow to load on relatively big data sets.

Note that when we're talking about unit retrieval, we're mostly referring to fetching units from the editor via the internal API. Keeping that context in mind, it's important to realize of the querying needs:

* Units can be **filter**ed by state or other attributes, or a combination of them: untranslated, needs work, untranslated + needs work, suggestions etc.
* Units can be **sort**ed
* Unit fields can be **search**ed. (Note that this is currently orthogonal to filtering and sorting, i.e. filters and sort order has no effect over searches).
* When units are filtered, the query is of a **dynamic nature**: there might be concurrent edits/updates that would change the result set.

Current implementation
-------------------------------

The current implementation works as follows:

1. The editor requests units to the internal API and specifies the `path` where it should get units from.
    * If it's an initial request (or a filter, search, sorting criterion changed), we signal the fact by also passing the `initial` parameter to the backend.
    * If it's *not* an initial request, the client explicitly requests the `uids` it should retrieve. This is known by the client because of 2.3.
    * Any filters to be applied are passed as query string parameters too.
    * Only `count` units will be retrieved at a time. This value is retrieved from the user's `unit_rows` preference.

2. The backend retrieves the set of requested units.
    * It fetches a queryset of all `Unit`s available for the current user in the requested `path`. It only considers units from user-accessible projects.
    * Narrows down the queryset and applies more filters based on the requested criteria on 1.3.
    * In case it's an initial request:
        1. All matching `uids` are retrieved for sending it to the client. This ensures the dynamic nature of the queryset won't screw the client's behavior (see 1cf9cb70a and evernote/pootle#48 for background details)
        2. The queryset is limited to `count` units.
    * In case it's not an initial request and `uids` have been provided, the queryset is narrowed down to the given `uids`.
    * Units are grouped by their `pootle_path` in Python.
    * Unit groups are serialized to JSON and returned to the client.

Caveats
------------

* When there are concurrent edits, users can go through units that don't match the filtering criteria anymore (the uid list is static once retrieved in the client), thus this can end up in being wasted translator time.

Existing bottlenecks
---------------------------

I have measured  in simple terms the amount of time spent in the steps of the current implementation and watched the resulting SQL queries. Here are my findings.

*  In all types of requests, when building the data dictionary for every unit, a query is performed [every single time `source_language` is accessed](https://github.com/translate/pootle/blob/7b5d35d52b901b1912b01a8ac22c29237829e032/pootle/apps/pootle_store/views.py#L372).
  * There should only be one query per project, and not N queries where N is the number of units to be returned (`count`). This doesn't consume much time, but it incurs in lots of useless requests.

* The unit retrieval execution time is badly affected on the **initial request** in two places:
  1. Retrieving the `uids` for the whole result set.
  2. Grouping the whole result set. I just found a way to avoid this long-running query on the initial request so fortunately we can ignore it :)

Retrieving `uids` is the real bottleneck here. It produces the following SQL query (note I've put `<pootle-path>` and `<user-accessible-projects>` as placeholders):
  ```sql
SELECT `pootle_store_unit`.`id`
FROM `pootle_store_unit`
INNER JOIN `pootle_store_store` ON (`pootle_store_unit`.`store_id` = `pootle_store_store`.`id`)
INNER JOIN `pootle_app_translationproject` ON (`pootle_store_store`.`translation_project_id` = `pootle_app_translationproject`.`id`)
INNER JOIN `pootle_app_project` ON (`pootle_app_translationproject`.`project_id` = `pootle_app_project`.`id`)
INNER JOIN `pootle_app_language` ON (`pootle_app_translationproject`.`language_id` = `pootle_app_language`.`id`)
WHERE (`pootle_store_unit`.`state` > -100
       AND `pootle_app_project`.`disabled` = 0
       AND `pootle_app_translationproject`.`disabled` = 0
       AND (`pootle_store_store`.`pootle_path` LIKE '`<pootle-path>`')
       AND (`pootle_store_store`.`pootle_path` NOT LIKE '/templates/%')
       AND `pootle_app_project`.`code` IN (`<user-accessible-projects>`)
       AND (`pootle_store_unit`.`state` = 0
            OR `pootle_store_unit`.`state` = 50))
ORDER BY `pootle_store_store`.`pootle_path` ASC,
         `pootle_store_unit`.`index` ASC
  ```

**Comment by iafan** [comment]
In #3405, I suggested splitting the massive query into smaller ones, which, in most common scenarios, would greatly improve the speed, I believe. Would be nice to do some speed tests for this approach. Basically, I would like to see the delay between getting results when searching for some term or filter through e.g. the entire database, or through one translation project

**Comment by julen** [comment]
@phlax and I have been [discussing on IRC](https://botbot.me/freenode/pootle-dev/2015-12-14/?msg=56099662&page=1) the bottleneck of `get_units` raised on this issue, and while we don't have a definite answer on how to efficiently tackle it, it might help to summarize what use-cases we want the editor to support and which ones cause trouble and why:

* Loading units based on a *filter* (state, has suggestions, search text, checks, etc.)
* Sorting the current (filtered) result set
* Displaying the total count of units, and the position of the current unit in the result set
* Navigating to previous/next units, or going to unit `u` in the screen by clicking on it
* Going directly to unit with index `i` in the result set
* Given a specific `uid` (and optional filter), load the unit in the context of the entire result set
* In filtered result sets, expanding the context units of the current unit

**Comment by julen** [comment]
Implementation-wise, we definitely want to **get rid of** the list of `uids` the current approach makes use of, as it's the real bottleneck and it can cause major server overload and sending down the wire and clients storing way more data than actually needed.

While pagination looks like the natural fit for this, as mentioned in the original report, it's necessary to take into account that data has a dynamic nature: the result set can (and very likely will) change while working on it. This already caused [other type of trouble in the past](https://github.com/evernote/pootle/issues/48).

**Comment by phlax** [comment]
So in terms of slow/complex queries:

> Given a specific uid (and optional filter), load the unit in the context of the entire result set

This is undoubtably the most expensive query to make. If you do not know the offset of the unit within the result set there really is no other way than iterating the result set to find it.

As the result set can be very large this means pulling a very large SQL result (or any type of result for that matter - ie cached/indexed) into memory and the processing these rows one-by-one.

This is extremely taxing for the application server and fairly taxing for whatever persistence is providing the result set.

> Displaying the total count of units, and the position of the current unit in the result set

This is a fairly expensive query, at least with mysql (particularly so for innodb - see https://www.percona.com/blog/2006/12/01/count-for-innodb-tables/)

I am just priming an Elasticsearch cache to see how it performs giving counts of large filtered result sets - but im pretty sure this is not such an issue in this context.

If getting counts is difficult to make performant - then this is something we could consider caching - but in the context of a contributor editing units - it might not really help much

This is certainly something we can

**Comment by phlax** [comment]
> Implementation-wise, we definitely want to get rid of the list of uids

yep, for sure - i think this is the one thing we have to do.

I dont really see any other approach than some form of pagination/keeping track of the offset, as this allows you to quickly splice the result set and never work with more objects in memory than you actually need.

As i understand the problem - its that the offset needs to change as the result set changes due to contributor activity.

Essentially i think the solution lies in keeping track in the client of which units are no longer in the result set and decrementing the offset accordingly.

I can see 2 possible approaches to implementing this:

- after/during unit edit the server is queried to ascertain whether the unit is still in the current result set
- the client uses the available data about the unit and the active filters and ascertains whether the unit still meets the criteria

**Comment by phlax** [comment]
some quick thoughts on these...

>    after/during unit edit the server is queried to ascertain whether the unit is still in the current result set
- in some ways this is more reliable as its asking the server what would you give me now
- this is not the most efficient approach
- i have a niggling concern about using eg Elasticsearch and there being a lag in the unit's index being updated - and still appearing in the list 

>  the client uses the available data about the unit and the active filters and ascertains whether the unit still meets the criteria

- this is the faster approach, minimizes network overhead, and distributes the workload
- this might be complex tho particularly if you are trying to ascertain eg if the unit is still in the total result set or just that its order and therefore offset has changed

**Comment by phlax** [comment]
@julen i think i have a solution that should work in terms of paginating but taking account of edited units.


initial request
---------------

- client sends request with optional `offset`
- server sends:
  - "results": 1st 10 uids from `offset` or 0
  - "offset": (`offset` or 0) + 10


subsequent request
------------------

- client sends `offset`
- client sends list of current `uids`
- server does following algo:

```
remaining_units = result_set[offset-10:offset].filter(uid__in=uids).count()
units_removed = 10 - remaining_units
new_offset = (offset - units_removed) + 10

return {
    "offset": new_offset,
    "results": result_set[new_offset - 10:new_offset]}

```

**Comment by phlax** [comment]
this was resolved by https://github.com/translate/pootle/pull/4560
