### ISSUE TITLE
refresh_stats should fail for non-existent projects and languages

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3538]
Currently with RQ based ``refresh_stats`` if you use either ``--language`` or ``--project`` and give it a non-existent project or language then it won't fail.

Try: ``./manage.py refresh_stats --project=xxxxxx`` or ``./manage.py refresh_stats --language=zzz``

The command gives the false impression that it is correctly counting those projects when it should actually give immediate feedback that those do not actually exist.

**Comment by ta2-1** [comment]
This issue should be applied to PootleCommand.

**Comment by unho** [comment]
No longer applies since this command has been removed.
