### ISSUE TITLE
Make resource list work on sqlite and Postgres (SUBSTRING_INDEX)

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3539]
In https://github.com/translate/pootle/blob/master/pootle/apps/pootle_project/models.py#L329 we make use of SUBSTRING_INDEX.  [SUBSTRING_INDEX](http://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_substring-index) is not available on sqlite or on Postgress so we'll need to have custom SQL there for those databases.

**Comment by dwaynebailey** [comment]
Possible solutions:

*  [Postgres](http://www.postgresql.org/message-id/469833CE.1020409@alteeve.com)

**Comment by jleclanche** [comment]
Also see [SO16177969](https://stackoverflow.com/questions/16177969/converting-mysql-query-to-sqlite-substring-index) for sqlite
