### ISSUE TITLE
Local TM UI doesn't work for amaGama results

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3541]
We should integrate local TM and amaGama results. Local TM has access to other information such as the project name and person who translated the suggestion since it has access to the data from Pootle.

When using amaGama results the string in the UI is confusing: 

*Translated by someone in project ""*

![screen shot 2015-01-23 at 17 55 13](https://cloud.githubusercontent.com/assets/647438/5879690/43cd8c32-a329-11e4-863f-8804b54e9730.png)

We should either:

1. Include some of that information in amaGama results e.g. the project name
2. Use a different comment when we have results from amaGama e.g. just remove it

**Comment by jleclanche** [comment]
This happens in `templates/editor/units/xhr_tm.html`. I suppose a check for whether `sugg.project` exists before outputting the string is enough. I don't know how to do that in that weird template language though :p
@julen thoughts?

**Comment by julen** [comment]
@jleclanche did the PR which was quicker. Please test that and report back.
