### ISSUE TITLE
Use `collections.OrderedDict` instead of `django.utils.datastructures.SortedDict`

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3544]
In Django 1.9 [`django.utils.datastructures.SortedDict`](https://docs.djangoproject.com/en/1.7/ref/utils/#django.utils.datastructures.SortedDict) will be removed, it is deprecated in Django 1.7.  Use [`collections.OrderedDict `](https://docs.python.org/3/library/collections.html#collections.OrderedDict) from the Python standard library instead.

The use of ``OrderedDict`` requires Python 3 compatibility.

**Comment by jleclanche** [comment]
> The use of OrderedDict requires Python 3 compatibility.

It doesn't, it was backported to 2.7.

**Comment by dwaynebailey** [comment]
> > The use of OrderedDict requires Python 3 compatibility.

> It doesn't, it was backported to 2.7.

Indeed, [collections.OrderedDict](https://docs.python.org/2/library/collections.html#collections.OrderedDict) on Python 2.7
