### ISSUE TITLE
Projects initialisation does not make stores and stats available

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3547]
In the following conditions:
1. You have a project folder with various PO files in non-GNU layout
2. You create the project within Pootle
3. Pootle initialises the project

Result
1. All TPs exist and all of the directory structure and files exist
2. There are no stats for the stores
3. Running `refresh_stats` across the stores does not create the stats.  You can only create them by running `update_stores`

Expected
- The stores are initialised and all word counts are correct

**Comment by jleclanche** [comment]
@ta2-1 status ping

**Comment by ta2-1** [comment]
@jleclanche it will be fixed in #3583.

**Comment by jleclanche** [comment]
@ta2-1 Are you planning to land #3583 any time soon?

**Comment by phlax** [comment]
i think this is fixed - @ta2-1 any thoughts?

**Comment by unho** [comment]
Reopened so @dwaynebailey can confirm which is the expected behavior. From my reading it is that translations should be automatically pulled in after project is created.

**Comment by dwaynebailey** [comment]
Think I see now why @unho reopened, did an initdb on master and we're in an odd state

**Comment by phlax** [comment]
this was related to old refresh_stats mechanism
