### ISSUE TITLE
RQ status indicator on Admin->Info page only works for one worker

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3552]
If you have more than one worker running then the status line will show "Stopped".  It only shows the correct status of "Running" if there is only one worker running.

**Comment by julen** [comment]
Relevant code: https://github.com/translate/pootle/blob/5bd61ce37f656a9ead3c5be598836d4a9cb4a41d/pootle/apps/pootle_app/views/admin/dashboard.py#L296-L298

Not sure what's the point of it, @ta2-1?
