### ISSUE TITLE
FileSystemStorage must generate its location dynamically

### ISSUE THREAD

**Issue by julen** [translate/pootle#3557]
The `FileSystemStorage` class used as part of `Store.file` [sets the `location` kwarg by directly assigning `settings.PODIRECTORY`](https://github.com/translate/pootle/blob/df037a939f3b8646589317b331a74236c0ed3792/pootle/apps/pootle_store/models.py#L1301). This is troublesome with Django 1.7 migrations, because it serializes **the value at the time of running makemigrations** so that it's available for frozen models in `RunPython` operations.

The side-effects of this are visible:
* The initial migrations have [the value of my `settings.PODIRECTORY`](https://github.com/translate/pootle/blob/df037a939f3b8646589317b331a74236c0ed3792/pootle/apps/pootle_store/migrations/0001_initial.py#L40).
* Having `settings.PODIRECTORY` other than that will make Django think there has been a change in the models, thus it will alarm about it:
```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

In order to fix this:

1. the value of `location` must be set via a module-level function, and
2. the initial migration must be fixed so it doesn't serialize a fixed value.

**Comment by julen** [comment]
> 1. the value of location must be set via a module-level function, and

The suggested workaround could be applied to `FileField`'s `upload_to` but it doesn't work on our case since the `location` parameter cannot be a callable. I'll go for subclassing the storage class and assign `settings.PODIRECTORY` there.

**Comment by asier5** [comment]
This is a very good idea of solving the problem of dynamic paths out of MEDIA_ROOT. Many thanks for the comments.
