### ISSUE TITLE
Error in navigation when submitting and going to next

### ISSUE THREAD

**Issue by tasso85** [translate/pootle#3561]
Sometimes, when using pootle to translate, I just click on "continue translation" and then go on translating, however, sometimes the interface will send me back to the summary page even if there are still untranslated entries, like it "thinks" that I'm done when actually I'm not.

**Comment by julen** [comment]
Thanks for the report @tasso85. I'm not sure which version you are referring to but this was surely fixed in d6608b5cfa.

**Comment by tasso85** [comment]
I am using version 2.5.1.1 right now

**Comment by julen** [comment]
Good, it's already fixed as said before, thanks for confirming the version!
