### ISSUE TITLE
Drop __version__.py and instead follow PEP 440 and expose git version hash

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3569]
Following [PEP 440](https://www.python.org/dev/peps/pep-0440/) was highlighted by @julen as a good improvement to Pootle version info in #3565 and repeated below:

> Can we use the occasion to be more (*de facto*) "standard" and put the version information in `pootle.__init__`? `__version__` should be a module/package attribute as specified by PEP8, not a module.
> 
> Also ensuring the version scheme matches [PEP 440](https://www.python.org/dev/peps/pep-0440/) wouldn't hurt. Defining the version information in the tuple should be enough, then the string can be generated from there ([see how Django does it](https://github.com/django/django/blob/stable/1.7.x/django/utils/version.py)).
> 
> ...[W]e'd very likely start using this module if we can directly get the git revision/branch information from there ([see example](https://github.com/getsentry/sentry/blob/master/src/sentry/__init__.py)). We currently do some deployment hackery to get this information for our staging server (see the ribbon on the upper-right corner).

**Comment by unho** [comment]
I think this is the right time to perform this change.

**Comment by julen** [comment]
Just raising that this non-standard practice fails to provide the version information for software such as [Django-Debug-Toolbar](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/69aec0133496c9a3fb9b0a6a69b6ebf81077607d/debug_toolbar/panels/versions.py#L56) or [Sentry](https://github.com/getsentry/raven-python/blob/133fcdb74869bb270f75642889b17b0752bf0b6e/raven/utils/__init__.py#L58), which have heuristics to determine the version of a Python package — Pootle always end up with a ` 	<module 'pootle.__version__' from '/path/to/pootle/pootle/__version__.pyc'>` as a version number :disappointed:

**Comment by jleclanche** [comment]
Moving to 2.7, this is definitely the right time to do it yes.

**Comment by dwaynebailey** [comment]
@julen @jleclanche I've had this one at the back of my mind for a bit and will likely give it a go in the next few days.
