### ISSUE TITLE
All filesystem → DB syncing and DB  → filesystem tasks should go the queue

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3577]
Thinking about #3547, #3542 we are faced with a problem:
- every action in admin UI (for a instance, new project creation) should be processed instantly;
- parsing dirs/files/units takes a lot of time.

So we come up with solution to move all filesystem → DB syncing tasks to the queue processed in a separate RQ worker.

**Comment by dwaynebailey** [comment]
@ta2-1 this will be a very cool change, but can we please make sure that we're on the same page in terms of queues and RQ going forward.

**Comment by julen** [comment]
@dwaynebailey yeah we are discussing queues on our side, will get back to you guys afterwards.

**Comment by ta2-1** [comment]
It's impossible to run `filesystem → DB` and `DB → filesystem` task for the same `TranslationProject` object in the same moment. Therefore if we move `filesystem → DB` tasks to the queue we must move `DB → filesystem` tasks there too.
Also I suggest to use the same approach as in #3615 to avoid running of two same sync jobs for the same `TranslationProject` object.

**Comment by ta2-1** [comment]
As it was mentioned in https://github.com/translate/pootle/issues/3727#issuecomment-275032936 this is relevant to old RQ refresh_stats mechanism. And question of concurrent `update_stores` is a separate question which won't be resolved as suggested in this issue.
