### ISSUE TITLE
Get rid of `directory` and `path-prefix` parameters from PootleCommand

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3578]
These parameters limited its action to a path relative to PODIRECTORY or to TP.

From IRC chat
@dwaynebailey: 
>--directory should go, it assumes too much about knowing the structure.

@julen:
> TP would be the smallest scope you could select, and this in turn is optimized (with revision counters) to avoid unneeded syncs.

**Comment by julen** [comment]
Also note that `--directory` has been pending deprecation for a long while, as noted by @alaaosh in 7a6cbcc7dd.
