### ISSUE TITLE
Telling translator about which format to use

### ISSUE THREAD

**Issue by abelcheung** [translate/pootle#358]
*Version: 0.9*

When displaying some c-format-like strings like "%d in %s", there is no way to
tell whether it is really c-format, or python-format, or using any other
language at all. It is suggested to show which language it is using, just like
showing comments. It's probably even better if some links can be provided as
well to educate translator how to handle such formats in various languages.

**Comment by dwaynebailey** [comment]
Our goals in Pootle is to educate users about things like variables but not to make it too technical.  The issues isn't about knowing if something is a C style variable but rather allowing things like placeables and variable highlighting rather than trying to turn translators into coders.
