### ISSUE TITLE
Setup default stats cache

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3585]
Pootle now requires a ``stats`` cache with infinite timeout.  We need to change the default that has only one cache to include a separate stats cache.  This cache needs infinite timeout.  We need to also change the code that allows fallback to ``default`` cache as that won't work with the current stats setup.

**Comment by julen** [comment]
So is it being suggested here that if no cache named `stats` exists with `'TIMEOUT': 0` then `raise ImproperlyConfigured`?

If so, besides adding relevant docs, also ensuring a Redis caching backend is being used would be wise, as `LocalMemoryCache` is volatile, works per-process and cannot be shared, plus people might start wondering where the `refresh_stats` data has gone or why numbers are 0 all the time. Also, for the correct operation of stats (and other bits) we're strongly advocating for a Redis cache backend anyway.

**Comment by julen** [comment]
Re. the Redis cache backend, we're currently using [django-redis-cache](https://github.com/sebleier/django-redis-cache/tree/master) but it's not as maintained as [django-redis](https://github.com/niwibe/django-redis/), plus the latter also offers nice helpers to ease working with the Redis server directly, which we'll have the need to use sooner or later. So I'd suggest to add django-redis to the set of base requirements too.

**Comment by dwaynebailey** [comment]
Fixed in d15acafcb2a13da8015b8a31c4f611e017ca47fc
