### ISSUE TITLE
Drop the Revision model in 2.6.0

### ISSUE THREAD

**Issue by unho** [translate/pootle#3586]
It has been dropped on master in https://github.com/translate/pootle/commit/bc9eb0e8#diff-ce6a659043fccc6e0887ef6ad8c9083f

Note that Revision has been backported from 2.7 for compatibility, so the cleaner way is to locate and remove the migration in 2.6.0 to avoid people creating and removing the DB table.

Also undo the other changes performed in https://github.com/translate/pootle/commit/d2052cd5

**Comment by jleclanche** [comment]
This doesn't matter, we'll wipe the migrations before 2.7.

**Comment by unho** [comment]
@jleclanche Yes, you are right. And I just realized that those migrations need to be backported to stable/2.6.0.

**Comment by jleclanche** [comment]
Taking this.

**Comment by jleclanche** [comment]
Finished it in 0de4f4b.
