### ISSUE TITLE
REGEXP not present in PostgreSQL

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3587]
Postgres [fails on Travis tests](https://travis-ci.org/dwaynebailey/pootle/jobs/50400894#L2516) because of the use of [NOT REGEXP](http://dev.mysql.com/doc/refman/5.1/en/regexp.html#operator_not-regexp)

The equivalent in Postgres is to use [POSIX Regular Expressions](http://www.postgresql.org/docs/9.3/static/functions-matching.html#FUNCTIONS-POSIX-REGEXP)

**Comment by jleclanche** [comment]
Taking this, though travis is blank...
