### ISSUE TITLE
Move from django-redis-cache to django-redis

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3590]
From https://github.com/translate/pootle/issues/3585#issuecomment-73847522: 
We're currently using [django-redis-cache](https://github.com/sebleier/django-redis-cache) but it's not as maintained as [django-redis](http://niwibe.github.io/django-redis/), plus the latter also offers nice helpers to ease working with the Redis server directly, which we'll have the need to use sooner or later. So I'd suggest to add django-redis to the set of base requirements too.

**Comment by julen** [comment]
There's no need to make any actual moves but only ensure django-redis is listed as a requirement and it's properly referenced in the settings.

We'll make sure to test this out on our side though and report back.

**Comment by julen** [comment]
Tested this and all is fine. For the future I would appreciate if you could wait until I report back before merging as requested in the previous comment.
