### ISSUE TITLE
Mitigate the risk of revision counter also being in 'default' Redis cache

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3592]
The revision counter goes into the 'default' cache.  This adds the risk of people clearing the default cache and also wiping out the revision counter — even if there's a way to restore it, we might want to prevent removal in the first place. This concern was raised in https://github.com/translate/pootle/issues/3500#issuecomment-73204160

**Comment by julen** [comment]
When I first raised the situation in https://github.com/translate/pootle/issues/3500#issuecomment-73204160 I was proposing to whitelist the keys that need to be preserved when running the `clear_cache` command. On a second thought, this doesn't scale well and is error-prone.

I'd instead have a reserved `redis` named entry in `CACHES`, which would use a `DB` number different from any other named caches. This named entry would be used anywhere in the app code for persistent Redis storage. Not sure if we could/should put this in the same `DB` number as `RQ_QUEUES`, which also needs persistent storage — would love your input here @ta2-1.

At the same time, the `clear_cache` command would refuse to run [`cache.clear()`](https://docs.djangoproject.com/en/1.7/topics/cache/#basic-usage) (which uses [`flushdb()`](http://redis.io/commands/flushdb) behind the scenes) for the cache named as `redis`, thus explicitly preventing the data living there from accidental wipe outs.

**Comment by jleclanche** [comment]
@julen why do we use redis through the cache framework instead of using it directly for this?

**Comment by jleclanche** [comment]
It seems like a lot of our problems here are caused by the inherent design of the cache framework which is meant to behave *as a cache*. It has a timeout, it has automatic culling, it has clearing and flushing and wiping and killing and what not... so yeah.

**Comment by julen** [comment]
Currently we have no direct way of reusing the existing Redis connection, while the caching framework provides that for free. Hint: with django-redis we'll be able to gain easy [direct client access](http://niwibe.github.io/django-redis/#_why_use_django_redis).

**Comment by jleclanche** [comment]
Let's do it then.

**Comment by julen** [comment]
From my side, a more than desirable outcome for this issue would be to reduce the duplication across RQ and Redis cache backend configuration. Good news is [django-rq have us covered](https://github.com/ui/django-rq#support-for-django-redis-and-django-redis-cache) and it'll be cheap to be DRY :)

**Comment by ta2-1** [comment]
+1 for the redis DB inited as CACHE, and reusing that settings for RQ.

**Comment by jleclanche** [comment]
+1 here too.

**Comment by julen** [comment]
Taking over this to ensure it'll be ready for our next release.
