### ISSUE TITLE
Use Django's System check framework to get rid of depcheck

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3594]
Django 1.7 introduces the [System check framework](https://docs.djangoproject.com/en/1.7/topics/checks/), this would allow us to elegantly get rid of depcheck.

The Django checks are run with runserver and manage.py commands and would allow us to prevent Pootle running in cases where there is no Redis server, no caching or no rqworker running.  Thus our 'required' dependencies could actually raise real Errors.

**Comment by jleclanche** [comment]
Moved redis version check to this as well.

**Comment by jleclanche** [comment]
Ok well I got bored and ported most remaining checks too.

**Comment by julen** [comment]
This was done in the linked PR.
