### ISSUE TITLE
Drop south_migrationhistory DB table after upgrading to 2.6.0

### ISSUE THREAD

**Issue by unho** [translate/pootle#3597]
Like those already being dropped in https://github.com/translate/pootle/blob/stable/2.6.0/pootle/apps/pootle_app/management/commands/upgrade.py#L141-L149

South migration history is no longer necessary after upgrading to 2.6.0, since in Pootle 2.7.0 South is dropped in favor of Django migrations.

**Comment by unho** [comment]
It was decided to postpone the South migration history removal in order to ensure we can recover from failing upgrades. See the discussion on https://github.com/unho/pootle/commit/0650f4f0#comments for more information.

**Comment by jleclanche** [comment]
This was done.

**Comment by dwaynebailey** [comment]
@jleclanche could you please link to commits that achieve this, its a PITA to later find these type of comments but no link to the commit.

**Comment by jleclanche** [comment]
I don't really know when it was done, but it was part of our 2.6/2.7 db wipe.

**Comment by unho** [comment]
@dwaynebailey @jleclanche After final upgrade to 2.7 the `south_migrationhistory` DB table is still present. It was considered to drop it as the last step of the upgrade, but it was deemed helpful to keep it for further reference after upgrade.

So reopening.

**Comment by jleclanche** [comment]
Huh.

**Comment by julen** [comment]
I wonder what's the real benefit of this. The same way as no tables have been cleaned up for other scenarios (registration, django-taggit etc.), I don't think Pootle should be doing anything here. Just let the DBA do this if needed, otherwise it doesn't hurt.
