### ISSUE TITLE
Backport saving revision on Redis on 2.6.0

### ISSUE THREAD

**Issue by unho** [translate/pootle#3598]
Basically backport most of https://github.com/translate/pootle/commit/bc9eb0e8

Check if any later change has been done to those files since we replaced django-redis-cache with django-redis.

Note that it is necessary to add Redis to 2.6.0 requirements.

Depends on https://github.com/translate/pootle/issues/3586

**Comment by unho** [comment]
This has been discussed, and adding the Redis dependency on 2.6.0 was considered undesirable.

Instead it was suggested to drop the migrations to add `Revision` model on 2.6.0 and add the logic to populate the revision in Redis in 2.7.0. This can be done either by using a migration or by getting back the `setup` management command.

**Comment by jleclanche** [comment]
When was this discussed? Because this isn't what I remember.

**Comment by unho** [comment]
@jleclanche It has been discussed a few days ago. Can you share what you remember?

**Comment by unho** [comment]
Related #3586

**Comment by unho** [comment]
This has evolved into something different, so opened a new issue for this: #3627

Closing this.
