### ISSUE TITLE
Local TM: Pootle fails to start if elasticsearch isn't available

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3610]
Pootle will fail to run if Local TM is setup and it can't connect to elasticsearch.

This needs:

1. Softer failing - Pootle should still run
2. Django checks to report this issues
3. Dashboard check - to report non available local TM

**Comment by julen** [comment]
Related evernote/pootle#285

**Comment by unho** [comment]
Related issue: #3297
