### ISSUE TITLE
Stats: add multiple workers support

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3615]
Currently stats are calculated in background jobs, but due to the way they were architected, they **require having a single worker**. We want to remove this limitation so that,

1. Stats calculation can benefit from running in multiple workers.
2. This architecture doesn’t leak to other jobs that can potentially use background jobs.

## Current Architecture

Every node identified by `pootle_path` has a value for every `CachedMethods` stored in Redis (8 methods in total).

The current architecture works from the bottom up in the tree structure (`Store` → `Directory` → `TranslationProject` → `Project`). Note that `Language` objects have no cached stats data and `Project` objects are the only parent for `TranslationProject` objects:

1. Write operations affecting any node in the tree will request themselves and their parent to update its cache for a specific combination of `CachedMethods`.  
*Example*: when a `Unit` has been translated, stats for the specific cached methods such as `TRANSLATED, LAST_ACTION, MTIME` should be updated.
2. The node will be **invalidated** by marking itself with a dirty bit. It will also invalidate **all the pootle paths reaching to it**, i.e. all the other nodes in the path from the project.  
At the technical level this means that all the pootle path members in the `pootle:dirty:treeitems` sorted set in Redis will be incremented by 1. No real data is removed, and `pootle:dirty:treeitems` keeps track of what nodes have ongoing updates, regardless of their `CachedMethods`.
3. A new job to recalculate stats for the specific combination of `CachedMethods` for **all the paths registered as dirty** will be created.
4. After stats have been recalculated, the counter in `pootle:dirty:treeitems` for each path in the trail will be decremented by 1.

This is problematic with multiple workers because there can be race conditions where different leaves of the same parent request to update the cache and:

1. The parent reads different data from leaves, because a worker has updated the leaf’s data, and the other worker reads stale data.
2. As an effect of reading stale data, write operations will result in incorrect data.

### A simple illustration of the problem
One unit has been added to the `Store` *A* and another unit has been added to the `Store` *B*. Suppose that we have two workers running and jobs triggered for `Store` *A* and `Store` *B* are executed in parallel.

![a simple illustration of the problem](https://cloud.githubusercontent.com/assets/682845/6442021/a3413852-c0fd-11e4-8e66-c11213e966ab.png)

`C.TOTAL` will have incorrect value after both jobs are finished.

## Proposed Solution
1. Split jobs and perform one job per node.  
   *Example*: jobs “/C/A”, “/C/B”  will be split as: [“/C/A” → “A”, “C”] and 
[“/C/B”  →  “B”, “C”].*
2. Taking into an account that [RQ doesn’t support multi-job dependencies yet](https://github.com/nvie/rq/issues/260), enqueue a job for a `Store` only after it has been invalidated. Create and enqueue a parent job only after a child job has been finished.  
   *Example*: `Job` *A* should be enqueued after `Store` *A* has been invalidated and `Job` *C* only after `Job` *A* has been finished.

Therefore we get the following list of jobs in our example:
<table>
  <tbody>
    <tr><th>Job A</th><th>Job B</th></tr>
    <tr>
      <td>
<pre>
A.calc_TOTAL
A.set_TOTAL
get C
add job C (TOTAL)
</pre>
      </td>

      <td>
<pre>
B.calc_TOTAL
B.set_TOTAL
get C
add job C (TOTAL)
</pre>
      </td>
    </tr>
    <tr><th>Job C</th><th>Job C</th></tr>
    <tr>
      <td>
<pre>
get A.TOTAL
get B.TOTAL
C.TOTAL = A.TOTAL + B.TOTAL
</pre>
      </td>

      <td>
<pre>
get A.TOTAL
get B.TOTAL
C.TOTAL = A.TOTAL + B.TOTAL
</pre>
      </td>
    </tr>
  </tbody>
</table>

Jobs “A” and “B” can be run in parallel. But it’s not possible to do the same for jobs affecting the same node.

![ More than one of the same jobs can't be run in parallel](https://cloud.githubusercontent.com/assets/682845/6442438/c1b70a5c-c100-11e4-9f64-3be58e2f6e28.png)
This example is valid for any node despite of its position in the tree. 

It’s possible to prevent enqueuing jobs affecting the same node in parallel. Instead of blindly enqueuing jobs, they can be [added as a dependency](http://python-rq.org/docs/) of the last added job for the node or skipped ([see explanation in RQ’s source code](https://github.com/nvie/rq/blob/30b21ef06ef692788e6905631fc110b117c94d7e/rq/queue.py#L190-L193)).
Technically this means adding a new last:job:<pootle_path> key to the Redis DB.

![possible problems with multiple workers 2](https://cloud.githubusercontent.com/assets/682845/6442596/11c2b414-c102-11e4-93d3-716e19f5c618.png)

The proposed solution avoids any kind of race conditions.

**Comment by julen** [comment]
@translate/house it'd be great if any of you guys review the whole approach proposed here, as well as the PR @ta2-1 opened some time ago — it's an important-enough topic that deserves everyone's attention.

**Comment by ta2-1** [comment]
Guys from @translate/house, could you please give your feedback about this approach (and PR #3621). I spent a lot of time trying to avoid any kind of race conditions. And I hope we are close to merge that PR.

**Comment by jleclanche** [comment]
Ive reviewed the approach and gone through the PR.

I think the idea is correct but you are taking things too far with one job per `Store`. Why not have the leaves be the `Directory` object? It would, in large projects, massively reduce the amount of individual redis queries and job setup you are doing and should yield significant performance improvements, if I'm trusting the numbers @julen posted.

**Comment by ta2-1** [comment]
@jleclanche, if we make a query either for `Directory` or `TranslationProject` we need to block calculating for all its childs. This is an issue and the whole algorithm becomes more complicated.
