### ISSUE TITLE
Please add Last Position as Quick Link

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#362]
*Version: 0.9.2*

*Originally posted by Clytie Siddall:*

[Note: Bugzilla only goes up to Pootle 0,9,2, so we can't select the later versions.]

Especially with a large project like OOo, we're unlikely to get it  
finished in one login session. But when you log in again, you loses  
your place in the translation.

I was inside Vietnamese/OOo/basic/source/app.po, but when I logged  
in, I went back to Vietnamese.

How about having, as one of our Quick Links, the place we were when  
we last logged out? Just use the path as the link name.

Can we do this fairly easily?

Clytie

**Comment by dwaynebailey** [comment]
Since the big 2.7.0 UI changes we don't think this is needed anymore.  Users can easily get back to large bodies of work and continue.
