### ISSUE TITLE
Customize `CSRF_FAILURE_VIEW` for XHR

### ISSUE THREAD

**Issue by julen** [translate/pootle#3620]
When a request fails due to CSRF protection kicking in, `settings.CSRF_FAILURE_VIEW` is returned, which defaults to [`django.views.csrf.csrf_failure`](https://github.com/django/django/blob/stable/1.7.x/django/views/csrf.py). This always returns a basic HTML template.

The obvious caveat is that this doesn't play well with XHR views. It would be possible to catch the `HttpResponseForbidden` exception in `pootle.middleware.errorpages`, but that would still return HTML, and retrieving the reason why the CSRF middleware failed is unnecessarily hard. More importantly, since the scenario cannot be dealt gracefully, it gives a sense of brokenness. 

It'd be possible to create a custom view to handle CSRF failures, and when the request comes via XHR, no template is returned; for any other scenario it'd fall back to the default `django.views.csrf.csrf_failure` view.

**Comment by jleclanche** [comment]
Hm, is this something we really care about? CSRF failure should never happen non-maliciously.

**Comment by julen** [comment]
It can happen when the token the client has is not valid anymore; sign in/out actions affect this.

This shouldn't be a problem per-se, but people tend to have multiple tabs open at the same time, and invalidating the token in one tab will make the remaining tabs unaware of the change. Any action attempt in the remaining tabs will trigger the CSRF protection, and by consequence the UX is terrible because there's no clue what happened.

**Comment by jleclanche** [comment]
There's additional concern though then, because then you're not refreshing the CSRF token, so if the user tries to log in again, the same error will happen. Can you confirm?

**Comment by julen** [comment]
Reviewed the topic and we won't need this — closing in favor of #3622.
