### ISSUE TITLE
Simultaneous runs of "Update against templates" overwrites other languages

### ISSUE THREAD

**Issue by keverets** [translate/pootle#3623]
From the web interface of 2.5.1.1: A user uploads a new template file, then goes through each language clicking on "Update against templates".  If they don't wait for the update to complete before moving on to another file (in the latest case, performing the update for Italian, then before completion performing the update for Japanese), the resulting file (Japanese in this case) is corrupted with many translations from the initial file (Italian).

It seems there's some race to this operation which isn't prevented by the interface.

The project uses:
* Quality Checks: standard
* File Type: Gettext PO
* Project Tree Sytle: GNU style: files named by language code
* Source Language: English - en
with no "Ignore Files"

If there's any other information required, please let me know.

**Comment by artyom** [comment]
We're having the same issue on the same pootle version (2.5.1.1) with similar setup but we're using [management command][1] `update_against_templates`, so this is not just the web UI problem.

[1]: http://pootle.readthedocs.org/en/stable-2.5.1/server/commands.html?highlight=update_from_vcs#update-against-templates

**Comment by julen** [comment]
Update against templates is gone in the new upcoming version, closing.

**Comment by amix** [comment]
So what is the new way of doing `update_against_templates` @julen ?

**Comment by julen** [comment]
We have taken this responsibility out of Pootle in 2.7, so it needs to be offloaded to some external process.

In the case of a continuous l10n cycle (which I guess you might be interested in), you would first `sync_stores` to retrieve the latest translations, then update offline your files to your latest templates (this really depends on the format(s) and tools you already/plan to use), and finally bring everything back using `update_stores`.

(@iafan you might wanna chime in to give extra insights if necessary.)

**Comment by Mixaill** [comment]
@julen, any plans to reintroduce this feature in Pootle 2.7.x?

>his really depends on the format(s) and tools you already/plan to use
OK. I, like many others Pootle users, use GNU Gettext. What should I do with my .po files to update them against .pot?

**Comment by iafan** [comment]
@amix, at Evernote we use our own toolkit that implements continuous localization on top of Pootle. It fully automates the process by pulling source files in various formats from version control, parsing them, generating .po files and sending them into Pootle, then gathering translations back, generating localized files and pushing them back to VCS. So in our case, this process replaces the need for `update_against_templates` altogether. We're planning to open-source this tool in the next few months. If you want to play with it sooner (under NDA), feel free to PM me at afan at evernote dot com.

**Comment by iafan** [comment]
@Mixaill, In GNU gettext toolchain there's a tool called `msgmerge` that is supposed to do just that. See http://www.gnu.org/software/gettext/manual/gettext.html#Updating

**Comment by amix** [comment]
@iafan We would love to get access to this! Will send you an email
