### ISSUE TITLE
Restore Revision number on upgrade to 2.7 or later

### ISSUE THREAD

**Issue by unho** [translate/pootle#3627]
In #3586 we are dropping the old DB-based `Revision` model on 2.6, but we are not adding the new `Revision` model because it would require adding the Redis dependency to 2.6.

So it is necessary to restore in the upgrade machinery (possibly with a data migration) the last revision (actually we are initializing it) by using the following snippet from https://github.com/translate/pootle/commit/bc9eb0e8#diff-60c1c0a61f2a39914dec4b805a6e2940R41

```diff
+from pootle.core.models import Revision
+from pootle_store.models import Unit
+
+
+Revision.set(Unit.max_revision())
```

**Comment by julen** [comment]
That is a data migration which was already present in master (pre wipe-out) as you point out. Alternatively, you can request users to run `pootle revision --reset` as an extra step part of the upgrade process.

**Comment by unho** [comment]
@julen I was unaware of such migration. Maybe it is a good idea to get it back since it seems harmless for you.

And we are trying to simplify as much as possible the upgrade procedure so users don't get confused. Using a migration for this looks like a good way to achieve that.

**Comment by julen** [comment]
The migration is in the link you provided.

**Comment by unho** [comment]
As pointed out by @julen actually we want this migration back: https://github.com/translate/pootle/commit/bc9eb0e8#diff-a4eb26d2ca01e615173f2c3e41d40f70

**Comment by jleclanche** [comment]
We're setting this to a non-issue.

**Comment by unho** [comment]
Reason to close this: The revision stuff has been added in 2.6, which is now a transitional upgrade, so there is no chance that any revision will have a revision number greater than the default 0. Code in master is able to deal with this "revision set" scenario since it returns the `INITIAL` value if there is any problem: https://github.com/translate/pootle/blob/1930c5a9/pootle/core/models.py#L18-L74
