### ISSUE TITLE
How to cancel the removing repeated function of text with Po format text？

### ISSUE THREAD

**Issue by shouhuanxiaoji** [translate/pootle#3633]
when I translate a .po format text.There has some repeated text, but the pootle only display the repeated text once. And after finish translating the text, I found that the repeated text has only translated for one place, other repeated text were not translated.I need to retain the repeated text,so how can I cancel this function?
thanks.

like this
<pre>
msgid "Successfully deleted %(count)d %(items)s."
msgstr ""

msgid "Successfully deleted %(count)d %(items)s."
msgstr ""

msgid "Successfully deleted %(count)d %(items)s."
msgstr ""
</pre>
This is a demo of what I want to translate.

In the pootle editor, I only find one line text.And after I finish translating, it display the translating of all program has been over.But when I download the po file,I find what as follow:
<pre>
msgid "Successfully deleted %(count)d %(items)s."
msgstr ""

msgid "Successfully deleted %(count)d %(items)s."
msgstr ""

msgid "Successfully deleted %(count)d %(items)s."
msgstr "你好."
</pre>
 
and there have another function which I dont need.If the source text is null or some blank,pootle will delete.How can I cancel this function?

tks very much

**Comment by dwaynebailey** [comment]
@shouhuanxiaoji your PO file is broken.  The PO format uses ``msgid`` as its unique ID, so you can't have non-unique entries.  Use ``msgctxt`` to disambiguate if needed.
