### ISSUE TITLE
Sidebar layout screwed with imports_exports

### ISSUE THREAD

**Issue by julen** [translate/pootle#3640]
The imports_exports app makes some visual customizations, which break the sidebar's layout:
* the sidebar's height is not adjusted to the height of the content
* an empty sidebar being displayed has been observed under some circumstances too, although I'm not able to trigger it right now.

Check out https://core-translate.stage.evernote.com/ru/clearly_evernote/ as an example of such layout.

**Comment by dwaynebailey** [comment]
@julen in point 1) in your initial bug comment is the white space at the bottom, under the gray import/export section, what you mean when you say "the sidebar's height is not adjusted to the height of the content"?

![screen shot 2015-03-17 at 14 08 19](https://cloud.githubusercontent.com/assets/647438/6688953/22eb747a-ccaf-11e4-9d24-8e91cb91f42b.png)

**Comment by julen** [comment]
It should fit the whole page area, not be trimmed after the sidebar content. Check https://translate.stage.evernote.com/ru/web_evernote/ for the expected layout.

**Comment by unho** [comment]
Picked from an email. Indented comments are from @iafan and the replies are from @dwaynebailey.

> I gave a first look at import/export UI — here are my impressions (I
> might be reiterating something that Julen or you already pointed out):
>
> 1) Side bar should take the full height of the content area despite the
> absence of the project description.
> Example: https://translate.stage.evernote.com/ru/web_evernote/ — here the
> sidebar is rendered correctly, probably because it has extra content
> And here: https://translate.stage.evernote.com/ru/clearly_evernote/ the
> sidebar doesn't take the full height, thus looking odd.

I think that's the item already highlighted in this issue.

> 2) Let's not use any background color in the sidebar. The background
> should always be white.

I thought some separation of purpose might be a good thing here.  But
happy to do white.

> 3) The padding on `#import-export-sidebar` should be 2em (basically, we
> want actions and arbitrary descriptions underneath share the same padding).
>
> So the CSS to fix (2) and (3) will be like this:
>
> ```css
> #import-export-sidebar {
>   padding: 2em;
> }
> ```
>
> 4) I'd recommend being more verbose on the actions, since we seem to have
> plenty of space there. Instead of 'Download', I'd go for 'Download contents
> for offline translation'

Verbose +1.  Though ''Download for offline translation' maybe is better.

> 5) the current upload action UI definitely looks odd. A text input which
> allows you to type something in (?!), but which simply hides the file upload
> form for no good reason, since it looks and behaves even worse than the
> original file input control. One can definitely replace this with the
> similarly looking action link, named something like "Upload translations",
> which, when clicked, will open the file selection dialog, and will do a form
> submit in `onchange` event, to save an extra click.

I like that its much cleaner.

**Comment by unho** [comment]
>> 5) the current upload action UI definitely looks odd. A text input which
>> allows you to type something in (?!), but which simply hides the file upload
>> form for no good reason, since it looks and behaves even worse than the
>> original file input control. One can definitely replace this with the
>> similarly looking action link, named something like "Upload translations",
>> which, when clicked, will open the file selection dialog, and will do a form
>> submit in `onchange` event, to save an extra click.
>
> I like that its much cleaner.

@iafan @dwaynebailey The reason to use a fake input to hide the file input is that this way we can get a consistent look and behavior across all browsers. Added some changes on https://github.com/translate/pootle/pull/3663 to avoid users typing on it.

Please let me know if you still consider that it is necessary to remove the form from the sidebar and replace it with a link that opens a popup dialog holding the upload form (like in old Pootles).

**Comment by julen** [comment]
Aligning with @iafan's reasoning, the current upload widget is definitely odd, and his proposal would work fine besides being simpler and less confusing for users.

**Comment by julen** [comment]
Some quick live editing:
![screenshot](https://cloud.githubusercontent.com/assets/16768/7063050/7f54fc80-dea3-11e4-9573-663b2ed72fb5.png)

**Comment by unho** [comment]
> 5) the current upload action UI definitely looks odd. A text input which
> allows you to type something in (?!), but which simply hides the file upload
> form for no good reason, since it looks and behaves even worse than the
> original file input control. One can definitely replace this with the
> similarly looking action link, named something like "Upload translations",
> which, when clicked, will open the file selection dialog, and will do a form
> submit in `onchange` event, to save an extra click.

@julen @iafan @dwaynebailey We can try that way. Obviously once a file is chosen the user won't be able to change it.

**Comment by dwaynebailey** [comment]
@unho just to be clear, there is no intermediary upload form.  The user clicks the link gets the system file selection dialog and once selected to upload starts.  The user has to double click, click on Open (or Cancel on the form).  The user already has a myriad of options to bail out.  Having them pause to examine the name of the file that they've already selected to upload really doesn't prevent an error.  More likely a user will learn to quickly click past the upload form and make the same error anyway.  The pause and form really do not prevent what you are worried about here.
