### ISSUE TITLE
Absence of `log_action` logging handler breaks manage.py

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3644]
Got this during lxde upgrade:

```pytb
Traceback (most recent call last):
  File "./manage.py", line 32, in <module>
    cmd_log(*sys.argv)
  File "/var/www/pootle/git/pootle/pootle/core/log.py", line 72, in cmd_log
    fn = settings.LOGGING.get('handlers').get('log_action').get('filename')
AttributeError: 'NoneType' object has no attribute 'get'
```

Obviously that line is wrong, it should be something like `.get("handlers", {}).get("log_action", {}).get("filename")`. But I'm not sure what the code is trying to do.

CC @ta2-1 since that's your code

**Comment by julen** [comment]
@jleclanche you seem to be missing the `log_action` handler, see #3366 for reference.

If the presence of that handler is critical, it should be loudly raised somewhere else, and not break manage.py mysteriously.

At the same time, the main issue seems to be that that code assumes certain logging settings, and it looks like it sort of re-implements logging to some extent. @ta2-1 would appreciate some clarity here.
