### ISSUE TITLE
pootle webpack can't find webpack command

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3645]
I have webpack installed in /usr/local/bin but it's not finding it.

Some debugging reveals it's calling `['/var/www/pootle/env/local/lib/python2.7/site-packages/Pootle-2.7.0a1-py2.7.egg/pootle/static/js/node_modules/.bin/webpack', '--config=/var/www/pootle/env/local/lib/python2.7/site-packages/Pootle-2.7.0a1-py2.7.egg/pootle/static/js/webpack.config.js', '--progress', '--colors']`

The code in `pootle/apps/pootle_app/management/commands/webpack.py` does not try to find `webpack` in `$PATH` at all.

cc @julen

**Comment by julen** [comment]
Frontend-related commands are only needed when developing or building Pootle. Having said that, Webpack needs to be [installed locally, not system-wide](http://docs.translatehouse.org/projects/pootle/en/latest/developers/frontend.html). You should never have to deal with this command on installations via pip, as you should be getting the assets already built.

**Comment by jleclanche** [comment]
The error needs to be clearer then. Especially since the docs are fairly obscure as to what should be used between pootle assets build and webpack.

**Comment by julen** [comment]
The error message [cannot be clearer](https://github.com/translate/pootle/blob/master/pootle/apps/pootle_app/management/commands/webpack.py#L74-L78). Feel free to suggest any specific improvements.
