### ISSUE TITLE
Popup hint (Tipsy) prevents preview links from being clicked

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3648]
1. Open https://translate.evernote.com/ru/marketing2_evernote/translate/release-notes/ios/7.6.6/release-notes.html.po#unit=4534772

2. Hover the link next to 'Preview:'. The hint will show before you click the link, and it will prevent the link from working. The same popup will prevent the comment text from being selected correctly.

**Comment by julen** [comment]
Confirming this is an issue (reproduced in Webkit).
