### ISSUE TITLE
Priority sorting shouldn't always be available

### ISSUE THREAD

**Issue by julen** [translate/pootle#3652]
It's very confusing the fact that the *Decreasing priority* sorting option is offered in the editor even for installations with the virtual folders app disabled. At the same time, an installation with virtual folders enabled but no actual `VirtualFolder`s also exhibits this behavior.

**Comment by julen** [comment]
This can be considered a regression @unho.

**Comment by unho** [comment]
@julen It might confuse users, but even if it is chosen (independently of vfolders being there) it doesn't fail because we are assuming units have by default a priority of ``1``. I would like to push this post-2.7.0 unless you think this is an important issue.

**Comment by julen** [comment]
Although not immediately visible it's important as it's very confusing. Also note this is not about failure but about exposing irrelevant UI.
