### ISSUE TITLE
Allow specifying multiple files via POOTLE_SETTINGS

### ISSUE THREAD

**Issue by julen** [translate/pootle#3653]
Currently `POOTLE_SETTINGS` accepts the path to an extra settings file that will be loaded along with the defaults. This is used by the `pootle` runner for instance, but any type of deployment can use it.

In some cases, some deployments might have the need to define settings in multiple locations though: because they keep extras in an external repo, because multiple servers are running off the same codebase etc.

So `POOTLE_SETTINGS` should be able to read settings files from multiple locations; accepting `:` as a separator and loading the setting files in order is enough.

**Comment by jleclanche** [comment]
-1. If this sort of functionality is necessary, a settings loader can be written inside the POOTLE_SETTINGS file itself...

**Comment by julen** [comment]
For our specific need I'm going to use some other approach and I'm going to close this for the time being. In any case I still believe this is a simple yet non-harmful way to make `POOTLE_SETTINGS` work for more potential scenarios.
