### ISSUE TITLE
Date is rendered incorrectly in the popup hint

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3654]
1. Open https://translate.evernote.com/ja/ios7_evernote/translate/Localizable.strings.po#unit=4572599

2. Open the timeline and hover the time of  the last change:
![screenclip 3](https://cloud.githubusercontent.com/assets/1728158/6902923/c8ada704-d6cb-11e4-8a1d-65b1913a950a.png)

Now it is 10:57am (PDT).

The unit was changed at around 10:20am (slightly more than 30 minutes ago). It shows that the last change happened "An hour ago" (which is correct to the extent our 'smart' date plugin renders something that happened '> 30 minutes ago'). The HTML attribute says: `datetime="2015-03-30T17:20:49+00:00"`

However, the tooltip shows that the change happened at 5:20pm, which is misleading.

For example, the date can be always formatted using the local (browser) time, or using the server time (in ISO or other format). We need to make sure that: (a) date are rendered using the same time zone, (b) people can understand which timezone this time is in.

**Comment by ta2-1** [comment]
@iafan note that we use different date format in overview pages https://translate.evernote.com/ja/ios7_evernote/Localizable.strings.po. Should it be addressed too?

**Comment by iafan** [comment]
Thanks for spotting this! Yes, we need to use a consistent way of rendering dates. I'm not sure which one is correct, though. I guess date rendering format needs to be taken from the browser locale?

**Comment by julen** [comment]
Note there was some relevant discussion in #3664.

**Comment by ta2-1** [comment]
We don't have an existing code to get the timezone information from a client.
After discussion with @julen and @iafan a chosen way of rendering dates is to show dates for default server timezone with added timezone information.

**Comment by iafan** [comment]
@julen, @ta2-1, I updated the issue description (last paragraph) to emphasize that the issue is about consistency, not about specific datetime format or using browser or server time zones.
