### ISSUE TITLE
RQ job shouldn't fail on uninitialized cached data

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3658]
Previous requirements:
Every existing object (Store, Directory, TP, Project) should have initialized cached stats.
Before any object is saved for the first time, the stats should be initialized.
If stats updating process meets any missed data in the cache this process fails and RQ job move to the set of failed jobs.

@iafan  suggested to adjust new `refresh_stats` algorithm to use it on uninitialized cached data.
Let’s assume that we can have uninitialized cached data for some objects during stats updating. That means there are unfinished RQ jobs in the queue. If cache missed data happens then RQ jobs shouldn’t fail and all dirty flags should be unregistered but no jobs for parent objects should be created. These parents should be dirty still at the moment but they will be updated later within next jobs.

It will allow us to see a real stats data instead of zeros that are shown for a new (just added) items which has not yet been updated.

**Comment by julen** [comment]
> It will allow us to see a real stats data instead of zeros that are shown for a new (just added) items which has not yet been updated.

@ta2-1 wondering if this relates to some extent to #3547.

**Comment by ta2-1** [comment]
@julen, it's different thing. #3547 is about calculation stats for new (just added) projects. It relates to `update_stores` specific: should it be called when project added etc. And this issue is about rendering and calculation of stats. In other words what we do if we need to count or show uninitialized stats.
