### ISSUE TITLE
Stats: handling of empty directories

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3660]
Stats for  empty directories won't be set after we merge #3621 and switch to the new refreshing stats process which starts from every Store object if we try to fill empty cache. 
Hence there are questions:
- Should we show directories and translation projects if they are empty?
- How to initialize zero stats for empty directories?

**Comment by iafan** [comment]
There shouldn't be empty directories in the UI

**Comment by ta2-1** [comment]
Since we have `obsolete` field for `Directory` object we can adjust `update_stores` command to mark empty directories (or directories containing obsolete directories only) as obsolete. Then we can get rid of `disabled` field of `TranslationProject` (#3674).
