### ISSUE TITLE
CSV file size

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#3668]
I tried to upload a .csv today. Basically this CSV is 55.7MB with almost 715000 lines. I tried to split the file in multiple files with 100000 lines each one, same way i get internal error and "Premature end of script headers: wsgi.py, referer: http://my.website.com/it/project/"- So i want to ask, what is the optimal csv file size to load on the server? with how many lines?
If i need to load more than 700K lines, how do i do?

**Comment by unho** [comment]
@JohnnyKing94 Can you please provide a much more detailed output for the error?

I would say that a CSV of 1MB is already too big. What are you using CSV for?

**Comment by JohnnyKing94** [comment]
I resolved in an other way, i explained this in the other issue ticket :D
