### ISSUE TITLE
Double submissions with pootle

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#3673]
I just saw this bug in this application and i wanted to report it. When someone submit a translation, the countributor stats show doubled submissions. If i translated 2 strings, the stats shows 4, so i checked on the database and i found this: https://dl.dropboxusercontent.com/u/89718989/Pootle/bandicam%202015-04-14%2013-17-11-753.jpg
As you can see, the pootle server stores the real submission and this string value "200", why??

Then checking around the internet, i found out even your pootle demo has this problem:
look, this user has 4 submissions: http://pootle.locamotion.org/accounts/bokar/
but when you click on "4", you see only 2 submissions made by him: http://pootle.locamotion.org/ach/pootle/translate/#filter=user-submissions&user=bokar

There's an error in the application, please address this issue

Thx in advance

**Comment by dwaynebailey** [comment]
@JohnnyKing94 submission != translations.  The PO file can have 2 translations that have been submitted 4 times.  The stats track contributions over time.

**Comment by JohnnyKing94** [comment]
But i just submitted ONCE and translated ONE string... why double stat when i make Accept?? :|

**Comment by julen** [comment]
Hi @JohnnyKing94, thanks for taking your time to report this!

The submissions look good to me: one refers to accepting a suggestion (`field=3`), whereas the other one refers to a string being stored as a translation (`field=2`).

Also I wouldn't trust the locamotion server for bug reports, as it's running a very old version of Pootle. Better to test and check behavior in current master; development efforts are put there, after all.

**Comment by JohnnyKing94** [comment]
But i didn't suggest, why storing a line (200) just to fill the field 3 as an empty suggestion? just remove it, it's wrong, If i translate one string, i TRANSLATED ONE STRING, why having TWO IN THE STATS if I didn't suggest?????
