### ISSUE TITLE
Breadcrumbs misplaced when zoom is adjusted in Chrome

### ISSUE THREAD

**Issue by julen** [translate/pootle#3691]
When the zoom level is adjusted, the breadcrumbs' position gets messed up in Chrome. The issue only happens in this browser.

![screenshot](https://cloud.githubusercontent.com/assets/16768/7364201/06e01c04-ed84-11e4-9885-f2f2663ed241.png)

**Comment by iafan** [comment]
Is this supposed to be live already? I still see this issue in Chrome

**Comment by julen** [comment]
It's fixed yeah, confirmed via IM.
