### ISSUE TITLE
Stats: increase efficiency of `refresh_stats` command (with multiple workers)

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3693]
We have two `refresh_stats` commands since #3615 has been closed. 
- The old `refresh_stats` command that requires single rqworker. It calculates stats for all `Store` objects in `O(1)` DB-queries. Then, starting on every `Project`, it updates stats recursively for the entire tree structure.
- The new `refresh_stats_rq` command uses the same approach from #3615 and creates **one RQ job for every `Store` object**. When a RQ job for a `Store` object finishes it creates a new RQ job for its parent. 
As we know from [previous testing](https://github.com/translate/pootle/pull/3621#issuecomment-79028033), the old command (with a single rqworker) is twice as fast compared tothe new one (with 6 rqworkers).

The main achievement of #3615 is the absence of race conditions: it's impossible to run two RQ jobs for the same object at the same point in time. But the new command's efficiency needs to be improved.

I see two ways how we can increase the efficiency of the new `refresh_stats` command:
- Try to **avoid long queries** for getting `last_action`, `last_updated` and `last_mtime` values for every `Store` object. (For instance, we can save the last submission id as a field of the `Store` object).
- Try to **create jobs for objects higher up in the tree hierarchy** (`TranslationProject` or `Directory`, instead of `Store`), as already suggested by @julen and @jleclanche. This means that in order to add this *bigger* RQ job we need to make sure that no jobs are already running, queued or deferred for any TP child object. At the same time we need to ensure no jobs are created for any children objects of a TP while the *"bigger"* TP job is not finished.

My personal feeling is that blocking mechanism will make things more complicated here. But I'll be glad if I'm wrong.

**Comment by unho** [comment]
Command is gone, thus the closing.
