### ISSUE TITLE
This project must die

### ISSUE THREAD

**Issue by Nekmo** [translate/pootle#3703]
I am Django developer, and know that Pootle is programmed in this language made me very happy. However, trying to install Pootle saw it was a little weird. Looking Pootle saw many things that reinvented the wheel. There are many things that are not as Django.

I tried to install Pootle in my dedicated server. My server is dead.

I could not even see the homepage of Pootle. I could only look on as devouring all the resources of the machine.

4 cores, 2 GB of RAM. They are not enough to install Pootle.

THOUSANDS of lines like this at the console:
WARNING Data integrity error while importing unit back-end:
(1062, "Duplicate entry '27-a115a25065b29adfe4c0b73391cd5b3a' for key 
'store_id'")

Now my MySQL database is CORRUPTED. All thanks be to Pootle.

You are a bad example for Django.

Please learn to do things right.

Thanks.

**Comment by unho** [comment]
@Nekmo If you can provide more details, like for example which version are you using, which settings are using and which specific steps did you follow to setup it, it would be easier for us to try to figure out what went wrong and fix it.

**Comment by Nekmo** [comment]
Pip freeze:

    (pootle)[pootle@shizune pootle]$ pip freeze
    You are using pip version 6.0.8, however version 6.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    cssmin==0.2.0
    diff-match-patch==20121119
    Django==1.4.20
    django-assets==0.10
    django-taggit==0.11.1
    django-voting==0.1
    lxml==3.4.4
    MySQL-python==1.2.5
    Pootle==2.5.1.1
    six==1.9.0
    South==0.7.6
    translate-toolkit==1.12.0
    webassets==0.10
    (pootle)[pootle@shizune pootle]$ 

Maria db version:

    (pootle)[pootle@shizune pootle]$ pacman -Qi mariadb
    Name           : mariadb
    Version        : 10.0.17-2
    Description    : Fast SQL database server, drop-in replacement for MySQL

CPU:

    (pootle)[pootle@shizune pootle]$ cat /proc/cpuinfo | grep model
    model           : 54
    model name      : Intel(R) Atom(TM) CPU N2800   @ 1.86GHz

Sorry, but I do not intend to try installing again. Certainly never in MySQL. I still repairing the damage.

**Comment by jleclanche** [comment]
Pootle can't just "corrupt a db". Django in general can't do that. If your mysql db got corrupted, it's either mysql's fault or you have hardware issues.

With that said, this is absolutely not how you'll ever get help. You should probably think about that...
