### ISSUE TITLE
Navbar is misplaced after dropdown is closed

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3707]
Steps to reproduce:
1. Open https://translate.evernote.com/ru/ (can be reproduced in Chrome/Win and Chrome/Mac)
2. Click on 'All Projects' dropdown.
3. Click outside the dropdown or press Esc to dismiss it.

The entire contents of the navbar will be scrolled up as depicted on this screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1728158/7462200/a00b4608-f264-11e4-9875-0ca31e71830f.png)

An additional and probably related minor issue that for the 'All Projects' button the right edge gets clipped, which is also visible on this screenshot.

**Comment by julen** [comment]
No way to reproduce it I'm afraid (Safari/Chrome/Firefox, OS X).

**Comment by iafan** [comment]
The main issue is reproducible only in Chrome, but for me/Pavel we can see this in 100% cases and on all pages. Do you have the latest stable Chrome installed?

**Comment by julen** [comment]
Chrome 42 stable, no way to reproduce it, and cannot reproduce the *right edge* issue in Firefox either.

**Comment by dwaynebailey** [comment]
Same issues was report on LO testing server also with chrome
https://goo.gl/photos/vjhS6J6bzusJydeQA

**Comment by jihuichoi** [comment]
above screenshot came from Chrome 44.0.2398.0, Windows 8.1
but no problems on Firefox 38.0.1 and IE 11, Windows 8.1

**Comment by iafan** [comment]
Can someone try to reproduce this again on latest Chrome? I previously could reproduce this problem consistently, but now, in Chrome 49 under Windows, it's gone.

**Comment by iafan** [comment]
Pavel also confirmed that it is not reproducible in his Chrome 49/Mac. Closing for now.
