### ISSUE TITLE
File overview requires using the picker to get back to the folder

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3712]
If you browse into a file overview:

![screen shot 2015-05-06 at 14 13 31](https://cloud.githubusercontent.com/assets/647438/7493588/2c9fc044-f3fa-11e4-8cdb-0c6e981bf627.png)

Then you lose the ![screen shot 2015-05-06 at 14 13 59](https://cloud.githubusercontent.com/assets/647438/7493593/38dec756-f3fa-11e4-84a0-68f5342bd9c7.png) link.  This can be very confusing as you either need to use the back button or work the file picker.

**Comment by iafan** [comment]
I agree we can add this link for consistency. I would also recommend moving the `<- Back to parent folder` link above the table, as depicted below:

![screenclip 4](https://cloud.githubusercontent.com/assets/1728158/7503083/5c273306-f3f5-11e4-888e-a2d7768ea14e.png)

(and for file overview, we will display just this link, with no extra table).

Also, speaking of consistency: now we don't display this link when we are in the root translation project folder. I think we can add such a link that would lead to the language overview.

**Comment by iafan** [comment]
And one more thing: let's add a `Ctrl+\` (or similar) shortcut that would activate this link, and "Go back to parent folder (Ctrl+\)" title to it.
