### ISSUE TITLE
Traceback on rqworker when refreshing stats

### ISSUE THREAD

**Issue by unho** [translate/pootle#3713]
```pytb
Traceback (most recent call last):
  File "/home/leo/Escritorio/core_pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 54, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/home/leo/Escritorio/core_pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 89, in handle_all_stores
    translation_project.update_parent_cache()
  File "/home/leo/Escritorio/core_pootle/pootle/core/mixins/treeitem.py", line 550, in update_parent_cache
    create_update_cache_job(p, all_cache_methods)
  File "/home/leo/Escritorio/core_pootle/pootle/core/mixins/treeitem.py", line 727, in create_update_cache_job
    pipeline=pipe)
  File "/home/leo/Escritorio/core_pootle/pootle/core/mixins/treeitem.py", line 631, in merge_job_params
    new_params = (keys | old_keys, decrement + old_decrement)
TypeError: unsupported operand type(s) for |: 'list' and 'list'
```

**Comment by julen** [comment]
You are using a single worker right? In case you are able to reproduce it, any chance you could inspect the actual values of `keys` and `old_keys`?

**Comment by unho** [comment]
@julen Just checked again on latest master. Before checking I removed all *.pyc files and ensured I am not introducing problematic customizations in my dev settings. I am not sure if I am using one or multiple workers, but I am using default settings. I have put some prints and this is what I get:

```
old_keys:
['get_checks', 'get_last_action', 'get_last_updated', 'get_mtime',
 'get_suggestion_count', 'get_wordcount_stats']

keys:
['get_checks', 'get_last_action', 'get_last_updated', 'get_mtime',
 'get_suggestion_count', 'get_wordcount_stats']

type(old_keys):  <type 'list'>
type(keys):  <type 'list'>
```

I am guessing the problem is using `|` with lists where it probably expects sets.

**Comment by ta2-1** [comment]
> I am guessing the problem is using | with lists where it probably expects sets.

@unho, you are right.

There is a bug in `TreeItem.update_parent_cache` which is called if you are using old `refresh_stats` command with `--project` or `--language` options. I'll fix it now.

**Comment by ta2-1** [comment]
@unho, before testing make sure please, that RQ Redis DB is clear of jobs with wrong content (`list` instead of `set`).

**Comment by unho** [comment]
@ta2-1 Seems to be gone. Thanks!
