### ISSUE TITLE
MT plugins don't correctly attribute results

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3717]
Both [Google](https://cloud.google.com/translate/v2/attribution#translation-results) and [Yandex](https://tech.yandex.com/translate/doc/dg/concepts/design-requirements-docpage/) require some sort of attribution for MT results.

Thus when the MT engines are enabled Pootle won't comply with these requirements.

They both basically want attributions that:
1. Mention the service by its correct name:
  - Powered by Yandex.Translate
  - translate by Google
2. Link back to the service i.e. http://translate.google.com/ and http://translate.yandex.com/
3. Include and icon, only Google seems to reqiure that.

The way we currently get results, i.e. user presses button and then we insert it into the editor doesn't make any of these options easy.

Some ideas:
1. Include the attribution in the tooltip - I don't think that really complies
2. Insert the results into the TM results - that would allow the attribution to be inserted as we do credits for TM results.  The insertion into the results could be:
  - **Manual**, i.e. by the button press (e.g. for a paid service like Google).  Perhaps also including the results in the editor as in current behaviour.
  - **Automatic**, for a free service

**Comment by iafan** [comment]
From https://cloud.google.com/translate/v2/faq#attribution

> Q: If I’m post-editing the translation results, do I need to display attribution?
> A: No. If you are post-editing the machine translation, no attribution is required.

**Comment by iafan** [comment]
From https://tech.yandex.com/translate/doc/dg/concepts/design-requirements-docpage/

> Each page that uses data from the Yandex.Translate service must display the text "Powered by Yandex.Translate" with an active hyperlink to the page http://translate.yandex.com/.

I believe this is not technically possible The results of the translation are not displayed directly to the end user (here I mean the user of the localized product). They are post-edited by the translator, and then appear in multiple contexts, not just web pages, where putting arbitrary banner/link is either not possible, or is a deal-breaker. Looks like these terms were designed with only one use case in mind — live translation of the web pages or parts thereof, and the main idea behind these rules is to indemnify both the user of the translation service and the translation service itself from any legal claims that may arise due to incorrect translation, which are not verified by humans.

So before allowing users to use Yandex.Translate as a part of Pootle, and even making Yandex.Translate plugin a part of the core, I would strongly recommend clarifying with Yandex if such a use is legal, and whether/how it should be attributed.

**Comment by dwaynebailey** [comment]
@iafan I think both these cases show a situation that the terms didn't foresee, even the Google one.  They both foresee attribution being present when MT id displayed to an end user.  In our case on Pootle the we have end users however they're intermediaries in the cases outlined above in that they will post edit and then the results will be used by a real end user.  I've been reading this in terms of our translators being end-users, which I think is actually true here.

I'm honestly not concerned about Yandex being part of core as it is off by default and requires the site admin to actually create a key and agree to the terms.

I think honestly we need to clarify attribution with both providers for things to be watertight.

**Comment by dwaynebailey** [comment]
@iafan I've send a Feedback request to Yandex to ask for clarity on the attribution in our case.

To be honest I feel we have the same issue with Google.  While Google is clear on post-editing not needing attribution.  We are actually publishing these results when we are in the Pootle editor and we don't attribute there at all at the moment.

**Comment by julen** [comment]
> We are actually publishing these results when we are in the Pootle editor and we don't attribute there at all at the moment.

How come? The results are not available via any URL. The only related thing published here is a post-edition of the results, no more.

**Comment by dwaynebailey** [comment]
Customer query result
-----------------------------

Dear Dwayne,

Yandex has an attitude similar to Google in the case that you've described in your question. You have to attribute Yandex only where Yandex translation is being shown, i.e. at http://pootle.translatehouse.org/ . There's no need to attribute Yandex in final products as the translation will be reviewed by the editors if I understand you correctly.

--
Sincerely yours, Platon
Yandex customer support
http://company.yandex.com/

> Hi,
>
> In reading the attribution requirements both here https://tech.yandex.com/translate/doc/dg/concepts/design-requirements-docpage/ and http://legal.yandex.com/translate_api/ 2.7 we have a question that we hope can be clarified.
>
> Our product, Pootle (http://pootle.translatehouse.org/) is a community translation sever.  When we use Yandex.Translate we are getting results from the server and providing them as possible translation alternatives, along with other Translation Memory results.  Almost all of these will be post-edited by the translators.  The MT results may or may not actually appear in the final product.  The final products in our case could include anything including: software, documentation, websites, presentations.  It would become impossible to attribute correctly in each especially considering that MT results might actually not be included in the products.
>
> Google provides a little more clarity for their situation: https://cloud.google.com/translate/v2/faq#attribution
> They only require attribution when the results are published, but not if they are post-edited.
>
> Hope you can provide more clarity here.

**Comment by dwaynebailey** [comment]
We had some discussion in a thread outside of this issue:

Concerns raised where, what exactly constitutes publishing and do we require attribution when the translator is actually post-editing as apposed to the post-editing results.

Our conclusions were as follows:

- The MT suggestions are initiated by the user.  Thus they are never exposed without their explicit request.  Since we have tooltips it is clear where the results are coming from.
- The way we use the results, i.e. for a small moment in post editing, doesn't allow us to display the required attribution when the attribution is already clear to the translator
- The MT results are only ever used for post-editing they cannot ever be used raw as at the very least the translator needs to validate and uncheck a fuzzy marker to be able to use the translation.
- The FAQs in general don't deal with our specific use case and it's unclear if they thought about use case or understand it completely as we present them.
- We don't display or store the results within the TM results in which case we might rethink the need for attribution
- We're happy to include the features in the product as they have to be explicitly enabled by a Pootle sysadmin.

So we're going to leave it as is for now both for Yandex and Google Translate.  If the respective parties provide further clarity in their FAQ we can revisit this and if we modify the operation to not require user initiation we may want to revisit this decision.
