### ISSUE TITLE
Verify previously-existing email when using a social account

### ISSUE THREAD

**Issue by julen** [translate/pootle#3728]
(Branching from #3517)

We enforce users to have a valid email address in order to sign up. When users try to sign up/in using a social provider, there might already be in the system a user with the same email address which the social provider is reporting.

In such scenarios, and since we cannot blindly rely on the email being verified, we'll prompt the user for the Pootle's user account password. When this verification succeeds, the user will be signed in and the local user will be linked with the social account.

![25054aca-b688-11e4-9105-ca008f2722b3](https://cloud.githubusercontent.com/assets/16768/7607154/703ce510-f95f-11e4-8296-6ec7c0fbe9ed.png)

**Comment by julen** [comment]
Note: we discarded the right hand side of the mockup because there's no actual way to know if a user has ever set a password or not, as allauth already sets an unusable password for users created when signing in using a social provider.

**Comment by julen** [comment]
Just realized there would be a way to know if a user doesn't have a password yet (technically it has a password, but Django provides a helper to know if it's been set by the user or not), which would make the situation on the RHS possible. Should we reconsider this @iafan?

**Comment by ta2-1** [comment]
Hmm... In our (EN) case it's almost impossible. It can happen if user signed in with one EN account and then moved email from that account to the second EN account and tried to login with the second account.
Speaking about general case when more than one social service is supported I'd prefer to have social login link to proper service than resetting a password that was unused before. Input field makes no sense in this case too.

**Comment by ta2-1** [comment]
`UNIQUE_EMAIL=True` becomes a hard requirement. Let's write about it somewhere.

**Comment by julen** [comment]
Added some docs in the PR mentioning that and more.
