### ISSUE TITLE
Projects codes with _ or with similar names cause stats to not rollup to project level

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3729]
In mlo we have projects with codes ``firefoxos`` and ``firefoxos_2.1``.

After clearing all stats we did the following:

1. ``./manage.py refresh_stats_rq --project=firefoxos --language=eu``
2. ``./manage.py refresh_stats_rq --project=firefoxos_2.1 --language=eu``

We observed that at the TP level in both of these projects the stats counts were correct (``/eu/firefoxos/`` and ``/eu/firefoxos_2.1/``).  Inspection of Redis cache showed the same.

But at the project level we observed:

1.  Firefox 2.2 (firefoxos) has stats for Basque (eu) - ``/projects/firefoxos/``
2.  Firefox 2.1 (firefoxos_2.0) **does not have** stats for Basque (eu) - ``/projects/firefoxos_2.1/``

So we have a problem that we don't like:

1. Names that are similar
2. Some character - likely ``_`` but possibly ``.``

**Comment by dwaynebailey** [comment]
The same issue seems to occur when refreshing stats in the default Terminology TP for Akan - ``/ak/terminology/Glossmaster_ak.po``.  Here we have an underscore in ``Glossmaster_ak.po``

**Comment by ta2-1** [comment]
I found that we set `id` for `div` elements adding `{{ item.code }}` in template.
https://github.com/translate/pootle/blob/20c06e89d7c09e997b283eb518f217b5bc135b82/pootle/templates/browser/_table.html#L52
But then we replace `.` or `@` with `-` in 
https://github.com/translate/pootle/blob/20c06e89d7c09e997b283eb518f217b5bc135b82/pootle/static/js/stats.js#L201

**Comment by ta2-1** [comment]
what is preferable way:
- add filter in template as `{{ item.code|htmlid}}`;
- don't use `id` attribute of `div`;
- use specific method as `_get_code` for `TreeItem` avoiding unexpectable symbols?

**Comment by julen** [comment]
For the time being and for the purpose of this issue you might wanna rescue a3cc6338 which we used in the past.

The preferable way is not to use the DOM as a data store, but only as a representation of the data. In other words, you don't need to construct these selectors to query the DOM.

**Comment by dwaynebailey** [comment]
Verified this on a test deployment for mlo and it is fixed.
