### ISSUE TITLE
Empty dirs cause stats to not roll up

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3730]
In the default Terminology project for Amharic we have this directory ``/am/terminology/gnome/CVS/`` in the TP.  Sure the dir should be dropped.  But the net result is that at the TP level ``/am/terminology/`` we don't have full TP stats.  And at the project level ``/projects/terminology/`` Amharic stats do not roll up.

**Comment by dwaynebailey** [comment]
Note to self.  On mlo we can likely correct this by manually removing such empty folders, the ``CVS`` files don't exist in Pootle repo anymore.

@jleclanche I think you'll be impacted by this on LXDE as IIRC there are lots of empty dirs in your repos.

**Comment by dwaynebailey** [comment]
Running ``refresh_stats`` over these projects resulted in full counts so its definitely and issues with ``refresh_stats_rq``

**Comment by unho** [comment]
@ta2-1 Perhaps this is related to #3660?

**Comment by ta2-1** [comment]
@unho, yes this is related issue.
@dwaynebailey, does `update_stores` fix this issue?

**Comment by julen** [comment]
@ta2-1 what are the effects for this issue of the referenced data migration?

**Comment by ta2-1** [comment]
@julen, migration fixed this issue.
