### ISSUE TITLE
Files with spaces or maybe brackers (, ) do not display their stats

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3731]
In the default Terminology for Urdu there is a file ``/ur/terminology/Localization Terminology Glossary (ur-PK).po``.

Observations:

1.  At the files level - stats are correct - ``/ur/terminology/Localization Terminology Glossary (ur-PK).po``.
2. At the TP level - the file is shown as uncounted but navbar stats include the file - ``/ur/terminology/``
3. At the project level - the counts are correct and include the file - ``/projects/terminology/``

**Comment by julen** [comment]
We already fixed this some time ago, feel free to reopen if you still see it is an issue.
