### ISSUE TITLE
Navbar dropdowns shift when pressing escape

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3732]
0. Before
![screen shot 2015-05-13 at 16 30 31](https://cloud.githubusercontent.com/assets/647438/7614244/72c66576-f98d-11e4-9046-4f01a811f95c.png)

1. Click on a dropdown to open it
![screen shot 2015-05-13 at 16 30 09](https://cloud.githubusercontent.com/assets/647438/7614249/7a5ba6d4-f98d-11e4-9c3f-dae95040114a.png)

2. Navbar shifts up
![screen shot 2015-05-13 at 16 30 21](https://cloud.githubusercontent.com/assets/647438/7614255/86efce3e-f98d-11e4-8a9a-c5ce029df669.png)

**Comment by julen** [comment]
Dupe #3707.
