### ISSUE TITLE
Pootle is tightly coupled to ENChecker() even if settings.QUALITY_CHECKER is unset

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3733]
My guess is that the default install should default to TTK checks.  At the moment its unclear what checks are used if the setting is left blank as suggested.

**Comment by unho** [comment]
Answer is in https://github.com/translate/pootle/blob/master/pootle/apps/pootle_misc/checks.py#L222-L227 and  https://github.com/translate/pootle/blob/master/pootle/apps/pootle_translationproject/models.py#L190-L200.

What confuses me a bit is what is `Project.checkstyle` used for, besides checking if it is a terminology project: https://github.com/translate/pootle/blob/master/pootle/apps/pootle_project/models.py#L154-L156

**Comment by dwaynebailey** [comment]
PR #3753 fixed this issue
