### ISSUE TITLE
 Awkward URL for accessing multiple failing checks

### ISSUE THREAD

**Issue by julen** [translate/pootle#3735]
*(Original report: evernote/pootle#95)*

When clicking on the number of critical failing checks to access the editor from overview pages, a long and awkward URL is used which takes the following form: `http://server.tld/path/to/ctx/translate/#filter=checks&checks=java_format,template_format,percent_sign_closure_placeholders,non_printable,changed_attributes,mustache_placeholder_pairs,whitespace,unbalanced_tag_braces,uppercase_placeholders,mustache_placeholders,dollar_sign_placeholders,broken_entities,unescaped_ampersands,unbalanced_curly_braces,c_format,test_check,unbalanced_tags,objective_c_format,javaencoded_unicode,date_format,android_format,percent_sign_placeholders,accelerators`.

This is insane. We should rather aim at using named aliases in URLs, resulting in URLs like `http://server.tld/path/to/ctx/translate/#filter=checks&category=critical`.

Since we already name quality check failure categories (*critical*, *functional*, etc.), the natural thing would be reusing those names. In the end, the above-mentioned long URL is just a list of checks contained within the *critical* category.
(*Note: We can keep the ability to specify multiple individual checks in the long form, but using the named categories should already cover our main use-case*).

Apart from that, currently the UI doesn't reflect the multiple checks that are being displayed for the current view. When switching to named categories, the category should be selected in the drop-down. This should also ensure users are able to select check categories from the drop-down.

**Comment by julen** [comment]
Considering this a bug because it couples the critical check links with the project checker, and [the generated URLs are `ENChecker`-specific](https://botbot.me/freenode/pootle-dev/2015-05-14/?msg=39165660&page=2).

**Comment by unho** [comment]
Agreed that it is insane. Filtering by categories is saner, or pointing to a specific check.
