### ISSUE TITLE
Sync-up email addresses when editing users

### ISSUE THREAD

**Issue by julen** [translate/pootle#3737]
Allauth keeps track of user email addresses in its own `EmailAddress` model, which allows having multiple addresses for each user. This is separate from the `User` model's `email` field, but [Allauth does its best to keep these in sync](https://github.com/pennersr/django-allauth/blob/fe8c28e1c37ab17cef52ede1a46bdb1a2a717c48/allauth/account/utils.py#L313-L332) when new emails are added to the system (when signing up via social providers, for instance).

On the other hand, Pootle's admin UI for users also allows to modify *the* email address for the `User` model, but it has no clue about the mirroring that exists with the `EmailAddress` model. So we need to make sure emails remain on sync upon saving `User` instances.

**Comment by ta2-1** [comment]
I think we need to keep track of user email addresses in `EmailAddress` models in all cases. Now it's allowed to create a new user via admin UI without syncing with `EmailAddress` model.

**Comment by julen** [comment]
Yeah you are right: we should sync-up email addresses no matter what the action is. This includes rejecting an address when it already exists in the `EmailAddress` object's table for another user. Kinda relevant is here [how Allauth syncs up email addresses](https://github.com/pennersr/django-allauth/blob/9e5b85f30b411ad7aedba3985ae486e803657189/allauth/account/utils.py#L317-L336).

**Comment by julen** [comment]
Already implemented so in the PR, it'd be great if you could confirm the behavior now aligns with what we expect.
