### ISSUE TITLE
Translation navbar rendering issue (regression)

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3738]
If one goes to https://translate.evernote.com/ru/blackberry10_evernote/translate/Evernote.ts.po#unit=2997156 (at least in Chrome) they will see this:

![screenclip 3](https://cloud.githubusercontent.com/assets/1728158/7640629/3038945c-fa39-11e4-9d8a-0d3ad30566f0.png)

There should be no wrapping between search box and filter selector. Looks like a recent regression.

**Comment by julen** [comment]
This was fixed yesterday (051fb72b).
