### ISSUE TITLE
How can I restore languages?

### ISSUE THREAD

**Issue by DarioZ86** [translate/pootle#3742]
I deleted by error the languages, is there any way to restore them?

**Comment by jleclanche** [comment]
If they're still on disk, you can restore things by adding the language back and doing `pootle update_stores --lang=<lang>`

**Comment by DarioZ86** [comment]
Do I have to force a reload to see updated languages?

Also for projects I loaded files from pootle webpage, but can't see them even thouh they are indeed in the folder on server.
