### ISSUE TITLE
Upload attributes an upload to the system user, it should credit the user who uploads

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3744]
If you have a simple file that you want to upload the user given credit for any changes is the system user, thus an offline translators won't get the credit for their work.

**Comment by julen** [comment]
For admin users it should allow to choose the user to attribute credit to.

**Comment by dwaynebailey** [comment]
The only risk I can see is that I'm not an admin and thus I don't want credit.  Perhaps we should be correctly attributing the person we find in the header.  And/or blanking that when we download so that we at least know if it has been altered.

**Comment by julen** [comment]
If you have rights to import files you should be able to set attribute to a user, not sure what's the risk.

**Comment by iafan** [comment]
@dwaynebailey, I'm not sure if Julen already mentioned this to you, but I'm currently working on a better export-import design, and this feature is also covered there (when an admin uploads a file, he can choose which user he uploads this on behalf of; regular users don't have this option, and upload on behalf of themselves only). Will share the design doc soon.
