### ISSUE TITLE
Upload changes appear in the timeline but you aren't aware that they came via an upload

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3745]
There is no distinction between a translation on Pootle and an upload.  So now we have a system user (and with #3744 some correct user) who made changes but we don't know why/how.  Was this from a update_store, from an upload or via Pootle UI.  Its hard to track down issues and know how they might have originated if it was a bad upload but you can't tell if it was an upload or an editor submission.

**Comment by julen** [comment]
The [submission type for uploads exists](https://github.com/translate/pootle/blob/4887b2e01d7e29d435758f4eb022131ad89ffd10/pootle/apps/pootle_statistics/models.py#L38), not leveraging it is a pure attribution bug.

**Comment by ta2-1** [comment]
We allow to add new units into a store via upload for all users who has `translate` permission (see [pootle_translationproject/views.py#L65-L66](https://github.com/translate/pootle/blob/eeec18420cde9f1ba1d50bb4a83a44a3e0f83801/pootle/apps/pootle_translationproject/views.py#L65-L66)).
All new units are created with submission type `UNIT_CREATE` (see [pootle_store/models.py#L515](https://github.com/translate/pootle/blob/eeec18420cde9f1ba1d50bb4a83a44a3e0f83801/pootle/apps/pootle_store/models.py#L515)).  So we aren't able to differ if unit was created from upload or not. 
I'm not sure if
- we can forbid adding new units via upload or 
- we have to check user permission for creating new units in Store.update() in file upload.  

But I'm reopening this issue atm. We allow to add new units into a store via upload for all users who has translate permission (see pootle_translationproject/views.py#L65-L66).
All new units are created with submission type UNIT_CREATE (see pootle_store/models.py#L515). So we aren't able to differ if unit was created from upload or not. 
I'm not sure if

we can forbid adding new units via upload or
we have to check user permission for creating new units in Store.update() in file upload.
But I'm reopening this issue atm.

**Comment by dwaynebailey** [comment]
@ta2-1 surely what @julen mentions in https://github.com/translate/pootle/issues/3745#issuecomment-103037486 would address that?

**Comment by ta2-1** [comment]
@dwaynebailey there is a collision: when we upload we set submission type to `UPLOAD`, when we create units we set submission type to `UNIT_CREATE`. I'm wondering if it should be allowed to create new units via upload.

**Comment by dwaynebailey** [comment]
@ta2-1 this is only on upload for a new unit right?  An existing unit would get type upload?

I think the reason we allow unit creation on upload is that you want to upload terminology files that may be expanded.

In terms of upload to a project file, I'm not so sure.  I think @phlax and I did chat about this.  If your file is older then the current file then you could potentially introduce units that have already been obsoleted.

**Comment by ta2-1** [comment]
@dwaynebailey yes, an existing unit would get type upload.

**Comment by iafan** [comment]
This isn't relevant for Evernote, but I'd say that fundamentally we should only allow users to upload _translations_, not _units_. @dwaynebailey is that strictly necessary to upload terminology that way? It could probably be managed in version control and translated as any other software strings (this is what we do at Evernote).

**Comment by dwaynebailey** [comment]
@iafan we have this inherited situation that users can upload their own files to the Terminology project, thus they don't necessarily match a set term list.  I think we should revisit this or work out how to make more robust generally.

**Comment by unho** [comment]
> @dwaynebailey yes, an existing unit would get type upload.

And that is why they are not showing up on the score.

Current behavior is that if unit in Pootle is untranslated the uploaded translation is just added as new translation (despite the type being upload) and if Pootle unit is already translated the uploaded translated is converted to a suggestion for the unit (I guess the type is upload as well?), but those cases should be treated like translation and suggestion so they can be displayed on the user score.

**Comment by ta2-1** [comment]
This issue was fixed in #4605.
But we are not able to distinguish if unit was created via upload. I've created a new issue https://github.com/translate/pootle/issues/4774 for that.
