### ISSUE TITLE
nplurals check not present after running ./manage.py regenerate_checks_descriptions

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3756]
After I've run the ``./manage.py regenerate_checks_descriptions`` command the ``nplurals`` check is not present.  It is present in the StandardChecker so I'm not sure why it wouldn't be picked up.

**Comment by phlax** [comment]
im working on this one...

**Comment by phlax** [comment]
@dwaynebailey the nplurals check is not present on StandardChecker - just on StandardUnitsChecker

im just trying to get my head around the difference

**Comment by phlax** [comment]
I have changed setup.py to generate descriptions for both StandardChecker and StandardUnitsChecker.

This works although i had to add "isreview" in to pootle_misc.checks.check_names - i'm figuring this is ok

**Comment by dwaynebailey** [comment]
@phlax this sound good.  Please add isreview to the excluded checks, search if isfuzzy in the checks.py to see where.
