### ISSUE TITLE
Drop run_cherrypy wsgi server?

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3758]
We have the ``run_cherrypy`` command, does anybody use that? I'd suggest we drop it but I'd like some input from others.

**Comment by jleclanche** [comment]
+1 on dropping it

**Comment by jleclanche** [comment]
I'd be in favour of doing so for 2.7 btw.

**Comment by julen** [comment]
`pootle start` uses it, providing a default for users wanting to quickly test Pootle after installing it.

**Comment by jleclanche** [comment]
No sense using cherrypy over django's builtin server for that tbh.

**Comment by julen** [comment]
I have no objections to drop this, however the docs need to be prominent on suggesting to use a real server over the default toy server, and that's not quite the case at the moment.
