### ISSUE TITLE
Document the dump management command

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3759]
``dump`` looks like it could be useful for development.  But I'm not 100% sure what data I'm looking at when I execute it.  @ta2-1 I suspect this one might be yours.  Let me know how it works and I'll happily document it.  Or the other option is to remove it.

**Comment by ta2-1** [comment]
@dwaynebailey I used it to compare dump files after changing suggestion models and refreshing stats algorithm. Made some adjustments [here](https://github.com/ta2-1/pootle/tree/issue/3759). If you think it is worth I can create PR with it.

**Comment by dwaynebailey** [comment]
I think its useful.  But clearly only for developers.  I'd be happy if you PR'd it.
