### ISSUE TITLE
Renaming a project code doesn't update related references

### ISSUE THREAD

**Issue by julen** [translate/pootle#3764]
When a project code is renamed via the admin UI (`/admin/projects/`), any calculated stats cease to be available, because the cache keys do not match anymore.

Since the stats are effectively there, is renaming cache keys a feasible option here @ta2-1?

**Comment by julen** [comment]
The issue has wider nature since any model including a `pootle_path` that references the old project code needs to be updated.

**Comment by julen** [comment]
Consider the commit above a temporal workaround to prevent renaming project codes from the UI. Unless this functionality is considered invalid/undesired due to various reasons, admins should be able to edit project codes.

**Comment by julen** [comment]
Transcribing from #2720:

When one wants to rename a project's on-disk folder, now this requires deleting and then re-creating a project, which wipes out its history.

Renaming a project's slug/key should probably rename its underlying project folder too.

**Comment by unho** [comment]
The same problem happens if you rename a language code. See #4213 for the original report.

**Comment by phlax** [comment]
there are a lot of things that need changing if a project code is changed - this is now handled in the tp_tool api and related commands

**Comment by unho** [comment]
Furthermore, the project code cannot be changed in the UI anymore.
