### ISSUE TITLE
Improve POOTLE_META_USERS documentation

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3765]
I'm trying to document the ``POOTLE_META_USERS`` setting.  The current docs are unclear as to what the purpose of the setting is, probably because of the term "API users".  I'm not 100% sure what I would put in there and what it would do.  Its unclear from the commit 70f7d95e6faeb70bcebc0cba8ee3623a32cc88b8 and the issue evernote/pootle#234 what exactly this is about.

But based on https://translate.evernote.com/user/system/ and https://translate.evernote.com/user/nobody/ I'm guessing those are ``POOTLE_META_USERS``.  In which case should the default not be ('system', 'nobody')?

@ta2-1 you landed that feature, could you provide some guidance?

**Comment by iafan** [comment]
Meta users are essentially special non-human accounts. 'System' is a meta-user which makes changes in the system when 'update_stores' command is executed. 'Nobody' is a user not associated with anyone particular. Such users don't have a simplified public profile rendering (no social buttons, for example, and no scores).

In the future, there will be more meta-users (each meta-user being tied to a specific plugin and representing some external service, like localization provider, that sends their translations into Pootle. There's no much reason to change this setting manually, I guess.
