### ISSUE TITLE
Legal pages don't remember your acceptance of the agreemenet

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3769]
This is likely only a problem on the [LibreOffice dev server](https://translations-test.documentfoundation.org/projects/) but tracking it here so we don't forget.

**Comment by julen** [comment]
You sure? I've been able to sign in, no questions asked (accepted the agreement like two days ago).

**Comment by dwaynebailey** [comment]
@julen I unpublished the legal agreement a few days ago.  So likely you saw both sides.  Perhaps its just me?  But I've removed all cookies and such and if enabled I get asked on every page :/

**Comment by julen** [comment]
It looks like it's just you; do you have a test case?

**Comment by dwaynebailey** [comment]
1. Login as admin and enable Licence Page
2. Logout and login as a regular user
3. Get asked on every page to confirm

I've kept this disabled for now as I don't want it to distract users.

Perhaps it is only me :/  I'm not sure where and how the legal agreements are stored for me to check why I or others are being hounded.

**Comment by dwaynebailey** [comment]
Still happening.  I actually did a SQL query to look at the records:

```sql
select sa.agreed_on, sa.document_id, sa.id, au.username
from staticpages_agreement as sa join accounts_user as au
where au.id = sa.user_id and au.username like "%dwayne%";
```

I can see the ``agreed_on`` value change when I agree.  Yet I keep getting the agreement popping up in the browser.  Tested on Chrome and Firefox with the same results.

**Comment by iafan** [comment]
I don't know the implementation details, but if we're comparing dates, can it be somehow related to time zones?

**Comment by iafan** [comment]
@julen, fyi: we'll be likely updating our ToS soon (within next few weeks), so we need to make sure this legal agreement stuff works properly and there are no regressions.

**Comment by julen** [comment]
I have made some fixes and restored the skipped test we had for legal pages in 52c99455 (7a691358b4 is relevant too). Unless I'm missing something really obvious, the logic of the test makes sense, and it passes.

However, I have been able to reproduce the behavior described in this issue. Seeing that the results are not expected but the tests pass, I'll drop into raw SQL because Django seems to be playing with us (see #3506 for reference).

If someone is able to come up with a failing test for the current code, that would be great.

**Comment by dwaynebailey** [comment]
Testing on __sqlite__, I don't see the error.  I can create a legal page and it works as expected.  As admin I make the page.  When I go to the project folder I'm asked to accept the terms.  After that I'm not asked again until I make an update of the legal page.  In which case I get asked to confirm again, but only once.  So works as expected.

Testing on __mysql__, I also don't see this error.

The above are both following ``migrate`` and then ``initdb``.

I'm not sure how you managed to create the issue on your database Julen :/

**Comment by julen** [comment]
Loaded a fresh dump, couldn't reproduce the issue. Then added a new legal page, modified the previously-existing one, and I'm hitting this over and over again. I checked everything timezone-related, no change.

I'll PR the changes I have using a raw SQL query which doesn't exhibit this behavior.

**Comment by julen** [comment]
I have added tests for more scenarios (5c3a98908) and dropped into raw SQL for this one on the commit above, which doesn't exhibit the issue anymore.
