### ISSUE TITLE
Extra permissions after migration

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3771]
On new mlo and LibreOffice server after migration I now find that I have the following extra and obsolete permissions:

* Never seen before - **anybody know where these come from?**
  * Can add directory
  * Can delete directory
  * Can change directory
* Discarded features - I guess the removal of these are missing in migrations
  * Can commit to version control
* Should have been dropped with Import/Export implementation 
  * Can overwrite translation on uploading files

**Comment by julen** [comment]
directory-related permissions come from https://github.com/translate/pootle/blob/df613f7fde1fc9b8510596035263273cf92d3b4a/pootle/apps/pootle_app/management/__init__.py
I'm not really sure what it's supposed to fix, although it looks safe to drop once confirming it alters no behavior.

**Comment by unho** [comment]
The directory permissions doesn't seem to be a problem, so will keep them.

**Comment by unho** [comment]
Closing since a fix has been merged in 3d7a25cf.
