### ISSUE TITLE
Non critical checks in Pootle editor are shown in red

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3776]
We're only exposing critical errors in the overview.  And exposing all checks in the editor.  We only block submission on critical errors, we don't block on other error classes.

However, we show all errors in Red.

For non-critical errors we should choose a cooler colour from the UI so that translators will know what are the critical errors.

**Comment by jleclanche** [comment]
I already mentioned before but I agree with Evernote's philosophy that all checks should be critical. If we can get check "levels" out of the way entirely and get rid of any distinction, then this becomes a non-issue.

**Comment by dwaynebailey** [comment]
Great in theory.  But [not even Evernote](https://translate.evernote.com/projects/support_evernote/translate/ZendeskDynamicContent/#filter=checks&checks=doublequoting) actually subscribes to that as a completely hard and fast rule.
