### ISSUE TITLE
Cannot build docs due to an ImportError

### ISSUE THREAD

**Issue by julen** [translate/pootle#3781]
In a virtualenv with sphinx installed (and it's only there, no system-wide sphinx exists), the docs refuse to build due to an `ImportError`.

```bash
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.3

Exception occurred:
  File "conf.py", line 55, in <module>
    from pootle.core.utils.version import get_docs_version
ImportError: No module named pootle.core.utils.version
The full traceback has been saved in /var/folders/m9/_jv23r3j7xs26c7wx_w71_1w0000gn/T/sphinx-err-4lXaE3.log, if you want to report the issue to the developers.
```

The traceback follows:
```python
ImportError: No module named pootle.core.utils.version
...skipping...
# Sphinx version: 1.2.3
# Python version: 2.7.8
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 55, in <module>
    from pootle.core.utils.version import get_docs_version
ImportError: No module named pootle.core.utils.version
```

This is clearly due to the recent changes in versioning.

**Comment by julen** [comment]
I had to `add2virtualenv /path/to/my/repo` in order to make this work, which would be nice to avoid if possible. If there's no way to avoid that, feel free to close the issue.

**Comment by unho** [comment]
Another solution recommended by @dwaynebailey https://github.com/translate/pootle/commit/a88f5e48

**Comment by dwaynebailey** [comment]
@julen I always setup my dev env with ``pip install -e .`` so I never saw this.

I tried looking briefly at ``from importlib import import_module`` but that didn't seem to be the right solution.

I can't see a way to avoid this easily so I'm closing.

**Comment by jleclanche** [comment]
Wait, why `pip install -e .` instead of just `./setup.py install`?

**Comment by unho** [comment]
This still happens. See https://readthedocs.org/projects/pootle/builds/3328497/

Builds for 2.7 branch have been broken for nearly 3 weeks.

**Comment by unho** [comment]
It works locally, but Read The Docs seems that is not able to use our trickeries.

**Comment by julen** [comment]
No 2.7.1 docs without this, I presume.

**Comment by unho** [comment]
Yes, no 2.7.1 docs because of this.

I have thinking and perhaps the best choice here is to go back to previous conf where the version was just a variable and not something imported from another module. We go back to the duplicate version scenario, but at least the docs will work while we think of a better solution. Unless someone has a good solution now.

**Comment by phlax** [comment]
@unho sounds like a plan

**Comment by dwaynebailey** [comment]
Enabled "Use Virtualenv" on RTD, this will ``./setup.py install`` Pootle before it tries to make any docs.
