### ISSUE TITLE
Reviewing docs and current use of further settings

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3792]
There are some configs that seem to be Pootle related that need a little explanation.

Some issues including:
1. Didn't make the `POOTLE_*` migration
2. Poorly documented
3. Could be obsolete

The setting are:
`OBJECT_CACHE_TIMEOUT` - Time in seconds the Pootle’s statistics cache will last. - surely this is obsolete now?

Are the following still relevant?
`PARSE_POOL_CULL_FREQUENCY`
`PARSE_POOL_SIZE`

`POOTLE_CACHE_TIMEOUT` - no docs, not sure what this does.

Looks like these are needed and just need a `POOTLE_*` rename
`EXPORTED_DIRECTORY_MODE`
`EXPORTED_FILE_MODE`

Are these still relevant with no update_against_templates? Otherwise `POOTLE_*`
`FUZZY_MATCH_MAX_LENGTH`
`FUZZY_MATCH_MIN_SIMILARITY`

`POOTLE_*` needed
`LEGALPAGE_NOCHECK_PREFIXES`

**Comment by jleclanche** [comment]
POOTLE_CACHE_TIMEOUT is used in templates/editor/units/term_edit.html and templates/editor/units/edit.html only.

**Comment by julen** [comment]
Cache timeout was discussed in #3402, wasn't finished it seems.

**Comment by julen** [comment]
* `PARSE_POOL_*` is part of Pootle's dark matter; still relevant.
* `EXPORTED_DIRECTORY_NAME` is used by `pootle_misc.ptempfile.mkdtemp()`, which is only used in tests. IIRC this function was added for downloads, and tests could simply use `tempfile.mkdtemp()`. Safe to get rid of the function and the setting.
* `EXPORTED_FILE_MODE` is the mode (perms) in which sync'ed files will be written to the FS.
* `FUZZY_*` is used in `store.update()`'s matcher, provided the `fuzzy=True` flag is passed. Fact is no code calls `store.update()`, as this code-path was probably used by update against templates.

**Comment by julen** [comment]
Addressed:
* `POOTLE_CACHE_TIMEOUT` has already been documented as part of #3402 (and `OBJECT_CACHE_TIMEOUT` is now gone too).
* `FUZZY_*` were removed as part of #3836.
* Some missing `POOTLE_` prefixes were added in 7e7b052.
* `EXPORTED_DIRECTORY_MODE` was referenced in dead code, and has been removed in 541c6c0.

Nothing to do:
* `PARSE_POOL_*`. These are internal to how store parsing happens. They'll probably go away when we decouple models from TTK storage classes. Hence I'd say no need for action.

Remaining:
* `AMAGAMA_URL`. Not sure what to do with it.
* `EXPORTED_FILE_MODE`. This sets the FS permissions of the files sync'ed to disk. Any opinions on what to do with it? Just rename it to `POOTLE_SYNC_FILE_MODE` or similar?

**Comment by unho** [comment]
> * `AMAGAMA_URL`. Not sure what to do with it.

On my ideal world these would be replaced by a `POOTLE_TM_SERVERS` that mixes both local and remote TM sources.

> * `EXPORTED_FILE_MODE`. This sets the FS permissions of the files sync'ed to disk. Any opinions on what to do with it? Just rename it to `POOTLE_SYNC_FILE_MODE` or similar?

Yes, that sounds like and acceptable name. Less misleading than the previous one indeed.

**Comment by dwaynebailey** [comment]
> AMAGAMA_URL. Not sure what to do with it.

Leave for now and solve when it gets merged as an ``ENGINE`` in ``POOTLE_TM_SERVERS``

> EXPORTED_FILE_MODE. This sets the FS permissions of the files sync'ed to disk. Any opinions on what to do with it? Just rename it to POOTLE_SYNC_FILE_MODE or similar?

Yip I think just rename it, odd that we didn't use ``EXPORTED_DIRECTORY_MODE`` but that we do use this one.

**Comment by julen** [comment]
After further inspection, I see `EXPORTED_DIRECTORY_MODE` was only used when unzipping uploaded zips on the server :unamused:

**Comment by julen** [comment]
`POOTLE_SYNC_FILE_MODE` done in c9faaa6.

Closing as the review is fully complete albeit there are a few bits missing as outlined in previous comments.
