### ISSUE TITLE
Suggestions should always have a user

### ISSUE THREAD

**Issue by unho** [translate/pootle#3810]
It was proposed in #3651 to enforce `Suggestion.user` to be never `NULL`.

**Comment by jleclanche** [comment]
We should assign suggestions without a user to `nobody`.

**Comment by unho** [comment]
Already done in a 2.6 migration https://github.com/translate/pootle/blob/stable/2.6.0/pootle/apps/pootle_store/migrations/0022_assign_userless_suggestions_to_nobody.py This issue is about making sure a suggestion without user can be never created again.

**Comment by jleclanche** [comment]
If we did that in 2.6 why didn't we switch to null=False at the same time? :/

**Comment by julen** [comment]
Everyone seemed to be okay to add the constraint, however [you asked not to do so](https://github.com/translate/pootle/issues/3651#issuecomment-86964569) until 2.7 was released.

**Comment by jleclanche** [comment]
Rats, I should have remembered that bug when we added vfolders - I said that when we thought there would be no more db changes :(

**Comment by jleclanche** [comment]
@ta2-1 @julen The fix can land now.
