### ISSUE TITLE
Login failure on QWebKit based browser

### ISSUE THREAD

**Issue by SafaAlfulaij** [translate/pootle#3813]
As the title says. I'm using Qupzilla (Qt 4.8)

**Comment by unho** [comment]
@SafaAlfulaij Click in the login button where? In a server you setup? Which version does it use?

**Comment by SafaAlfulaij** [comment]
Latest version (2.7.0).
In the main page, there is a button named sign in (Sorry about the wrong title).
When you click it, A "window" appears that requires a username and the password.
After filling both of them, And clicking "Sign in", nothing happens.
When I check the JS console I see a "ReferenceError: Can't find variable: Promise" error.
Looks like it's with Safari (or QWebkit), I found this while searching the error: http://stackoverflow.com/questions/22462396/cant-find-variable-promise-on-safari

And "Qupzilla" is a web browser

**Comment by julen** [comment]
Hey @SafaAlfulaij, thanks for the report. This seems to be due to a missing polyfill for some browsers (pushed a fix in 197fe69b1). Could you please check if the issue still remains?

**Comment by SafaAlfulaij** [comment]
Thanks for the fix, But I can't test it as I don't even know how to make a server, I just wanted to login to lxde localization server.
If it works with you then it's ok to close this bug. I'll reopen it when the same problem happens again. :)

**Comment by dwaynebailey** [comment]
Just tested on linode2.locamotion.org with Qupzilla for Mac.  I can now loging without issue.

**Comment by SafaAlfulaij** [comment]
Yeah it worked! Thanks a lot! :)

**Comment by julen** [comment]
Good to hear that! Now, even this has been fixed (main reason being IE support) realize that Qupzilla [is not a browser we actively support](http://docs.translatehouse.org/projects/pootle/en/latest/developers/browsers.html), so in this and in any other cases YMMV.
