### ISSUE TITLE
VFolders: Do not relate new units with vfolder using Unit post_save signal

### ISSUE THREAD

**Issue by unho** [translate/pootle#3817]
Relating new units with vfolder using Unit post_save signal (https://github.com/translate/pootle/blob/d3700b78/pootle/apps/virtualfolder/models.py#L363-L385) has a major impact on `update_stores` performance.

Thus an alternative way to relate those newly added units has instead to be used. Perhaps queuing jobs to relate such units can improve the performance.

**Comment by phlax** [comment]
units are no longer associated with vfolders directly
