### ISSUE TITLE
Rename `evernote_reports` to `reports`

### ISSUE THREAD

**Issue by julen** [translate/pootle#3822]
The `evernote_` prefix doesn't make sense here anymore, let's get rid of it and adjust the references everywhere.

**Comment by jleclanche** [comment]
+

**Comment by jleclanche** [comment]
@julen Is this on your plate? We're entering release phase and this needs to land before we squash migrations.

**Comment by unho** [comment]
I wonder if a07f454 fixes this.

**Comment by julen** [comment]
As mentioned yesterday on IRC this task is not in our immediate plans.
