### ISSUE TITLE
Issues with source strings for localisation on Pootle

### ISSUE THREAD

**Issue by khagaroth** [translate/pootle#3824]
Note: line numbers are from Pootle, they don't have to correspond with the current state in the repository in some cases.

    static/js/auth/components/AccountActivation.js:33
        We have sent an email to <span>%s</span> containing the special link.

    static/js/auth/components/AccountActivation.js:38
        We have sent an email to the address you used to register this account containing the special link.
Bad sentence word order, should be **We have sent an email containing the special link to...** or something like that.

     static/js/auth/components/RequestPasswordResetSent.js:44
        Didn
This string is not extracted correctly, it balks on the ' in Didn't

    static/js/auth/components/SocialVerification.js:105
        Sign In')}REGEX
)}REGEX - this shouldn't be there

    templates/editor/units/xhr_timeline.html:30
        check
This one could use some translator comment, what is it used for?

    apps/staticpages/views.py:116
        page-%d
Is this one really supposed to be a translatable string?

*OT: Is there anywhere some demo of the new Pootle version (preferably with access to the admin UI) or some premade VM image? It would be nice to at least see it in action or preferably being able to actually test the translation on a running instance.*

**Comment by dwaynebailey** [comment]
The only issue not fixed here is:

```
templates/editor/units/xhr_timeline.html:30
    check
```

which is more an issue of really broken l10n which should be addressed as its own issue
