### ISSUE TITLE
Broken l10n in timeline

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3826]
Issue #3824 requested a comment for this unit:

```
templates/editor/units/xhr_timeline.html:30
    check
```
>This one could use some translator comment, what is it used for?

Inspection of [that code](https://github.com/translate/pootle/blob/7907606c/pootle/templates/editor/units/xhr_timeline.html#L37) shows some really damaged localisation which appears in the timeline we guess as:

'Muted Placeholder check'

I.e. we've got a constructed concatenation that many languages can't translate.  And we're not 100% sure where the first part is localisable anyway.

**Comment by julen** [comment]
The other part comes [from the view](https://github.com/translate/pootle/blob/c4d794bbfe7568b05849ccffb2f32517f9c5ac43/pootle/apps/pootle_store/views.py#L626-L627), which is as braindead as the template construct.
