### ISSUE TITLE
Stats: don't keep HTML snippets in the cache

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3835]
It's not good when we store `last_updated` and `last_action` HTML snippets in the stats cache.
Let's keep a prepared structure there which will allow us to build a proper snippet on client side.

**Comment by julen** [comment]
To elaborate a little bit more on the *why*, currently any changes affecting the markup require refreshing all stats, which is a waste of time since the actual data is there, however mixed with its visual representation.

**Comment by julen** [comment]
@ta2-1 and myself have been working on this during the last few days and we already have working code in the stats/snippets branch. There are a few missing bits though:

* Reducing the size of the response payload. There's currently some useless data being served over the wire. `unit.state` should be gone; `gravatar_url` → `email` (and we only need the md5). The components need to be adjusted accordingly.
* Flattening the response. `unit.source` → `unit_source`; `unit.url` → `unit_url`.
* Restoring the last activity in the user profile. With the current changes it's broken.

**Comment by julen** [comment]
Also I see there are still references to `snippet`, namely in `refresh_stats` — let's get rid of them.
(If putting `refresh_stats` in par with `refresh_stats_rq` functionality-wise is a non-goal, I believe it's time to drop `refresh_stats`).

**Comment by unho** [comment]
> (If putting refresh_stats in par with refresh_stats_rq functionality-wise is a non-goal, I believe it's time to drop refresh_stats).

I think that actually is the other way: `refresh_stats` hasn't been dropped yet because the new `refresh_stats_rq` still doesn't have all the functionality of the former.

**Comment by ta2-1** [comment]
we already have a separate `calculate_checks` command and we can easily create a new command for `--calculate_wordcount` as @julen mentioned  https://github.com/translate/pootle/issues/3548#issuecomment-103875453.
So the only reason, why we didn't drop it, was #3693.
Let's move away `--calculate-wordcount`, drop old `refresh_stats` and focus on optimisation.

**Comment by julen** [comment]
Ok, so let's leave any changes to (the old) `refresh_stats` away from this issue and address it in #3548.
