### ISSUE TITLE
Store.update: get rid of fuzzy matcher

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3836]
I've noticed that there is a code related to fuzzy matcher in `Store.update()` which can remove units from DB. That doesn't correspond that we don't delete units from a DB, we make them obsolete instead.
Let's change fuzzy matcher behaviour  or get rid of it.

**Comment by julen** [comment]
Actually @dwaynebailey and me were briefly commenting this on IRC the other day. This was part of the update against templates feature, which is long gone. Therefore it's dead code basically (no way to hit that code path last time I checked), and safe to be removed.
