### ISSUE TITLE
Store.sync() doesn't order units in a file

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3837]
Working on #3802 I realized that `Store.sync()` doesn't take into account default unit order. 
Try following:
- add an unit to beginning of a `.po` file
- run `update_stores` for `TP` containing this `.po` file 
- check that the unit was added
- remove just added unit from the `.po` file
- run `sync_stores`

Our unit will be added to the end of the file.

**Comment by phlax** [comment]
i believe this works and is tested now. Can you reopen if you think its still an issue @ta2-1
