### ISSUE TITLE
Terminology suggestions not being shown

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3846]
After the LO upgrade to 2.7.0 they are no longer seeing terminology suggestions.  This worked in the previous version.

Simply changing the checker style to terminology for the Terminology project resulted in the return of Terminology suggestions.

My concern however was that this somehow turned itself off in the upgrade.  So reporting this so that we can find the root cause of why Terminology forgot that it was a terminology project.

**Comment by Mixaill** [comment]
Same situation on clean install.
Setting *checkstyle* to *terminology* in *pootle_app_project* table helps me.

**Comment by phlax** [comment]
im wondering if this is resolved @dwaynebailey ?

**Comment by dwaynebailey** [comment]
On a clean install we have the checkerstyle _correctly_ set to terminology.

**Comment by dwaynebailey** [comment]
I can't replicate this on an upgrade either
