### ISSUE TITLE
'js/vendor.bundle.js' not found after first time running the server 

### ISSUE THREAD

**Issue by kamotos** [translate/pootle#3850]
After cloning, I followed the steps described in [Hacking](http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/developers/hacking.html) but I couldn't get to run the project because of some `BundleError`

    BundleError at /
    'js/vendor.bundle.js' not found (using staticfiles finders)

I also tried to do `python manage.py assets build` but I get : 

    webassets.exceptions.BundleError: 'js/editor/app.bundle.js' not found (using staticfiles finders)

Am I missing some step? What could I have done wrong in your opinion?

**Comment by dwaynebailey** [comment]
You should be on the [latest docs](http://docs.translatehouse.org/projects/pootle/en/latest/developers/hacking.html).  This points to the bits needed for [frontend development](http://docs.translatehouse.org/projects/pootle/en/latest/developers/frontend.html) which is what you are missing.

Let us know how that goes.

**Comment by kamotos** [comment]
Up and running. Thanks for the hint !
