### ISSUE TITLE
Do we need python-Levenshtein?

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3851]
Currently we test for faster levenshtein matching and justify it as needed for faster update against templates.  But we don't have update against templates anymore in Pootle.

The current need that remains is handled by a JS version client side.

So confirm if this is indeed needed, my guess is that if needed its being used via ttk lshtein magic.  If not needed remove any reference and checks for this and the package from ``requirements/deploy.txt``.

**Comment by jleclanche** [comment]
I believe we dropped the serverside levenshtein a few months ago. ttk still needs it though no?

**Comment by jleclanche** [comment]
cc @julen

**Comment by julen** [comment]
Just checked this: for terminology matching Pootle uses a custom matcher, and for calculating scores the levenshtein library is in JS. So we're free to drop the dependency for 2.7.0.
