### ISSUE TITLE
Multiple entries

### ISSUE THREAD

**Issue by DarioZ86** [translate/pootle#3853]
I've issues translating a CSV file where I have multiple locations with the same source and consequently target.

1) If I download a translated file, only the last entry is translated, all the other not.
2) If I try to upload a translated file with different locations with same translation I get error.

How can I at least workaround this?

Thanks,
Dario

**Comment by unho** [comment]
@DarioZ86 Either:

- Convert the CSV to a format that merges those equivalent units into just one (for example PO), or
- Change the CSV so all the units are different (probably not feasible).

**Comment by DarioZ86** [comment]
The first, the latter is as you say.
