### ISSUE TITLE
Editor textarea height is not adjusting when using MT or 'copy source' functions

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3854]
1. Go to https://translate.evernote.com/da/kb_evernote/translate/articles/23466441.xml.po#unit=4764237
2. Adjust your browser window width so that the source text spans three lines.
3. Click on either 'Google Translate' button or 'Copy into translation' button.

Observed: Textarea is populated with the text, but the height of the area is not automatically adjusted.

Expected: Textarea height should be adjusted on any changes done to its contents.

**Comment by julen** [comment]
FTR, the same applies to re-using TM results.
