### ISSUE TITLE
'module' object has no attribute 'json'

### ISSUE THREAD

**Issue by gjuric** [translate/pootle#3859]
Hi,

I have installed Pootle 2.5.1.3 on Debian Jessie. After installing tastypie and setting

    POOTLE_ENABLE_API = True

I had to make this tweak http://stackoverflow.com/questions/18191221/no-module-named-constants to get Pootle to start.

Now, when I open some of the API pages in a browser I get:

    Server Error
    
    An error has occurred. Thank you for your patience.
    
    'module' object has no attribute 'json'

I found a question about the same error on the mailing list and somebody suggested that they should upgrade to Python 2.6. I am running Python 2.7.

The full trace for opening /api/v1/ is:

    2015-06-23 20:22:18,612 INFO Starting CherryPy server, listening on port 8000
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
        response = callback(request, *callback_args, **callback_kwargs)
      File "/usr/lib/python2.7/dist-packages/tastypie/api.py", line 78, in wrapper
        return getattr(self, view)(request, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tastypie/api.py", line 155, in top_level
        serialized = self.serializer.serialize(available_resources, desired_format, options)
      File "/usr/lib/python2.7/dist-packages/tastypie/serializers.py", line 202, in serialize
        serialized = getattr(self, "to_%s" % desired_format)(bundle, options)
      File "/usr/lib/python2.7/dist-packages/tastypie/serializers.py", line 374, in to_json
        return djangojson.json.dumps(data, cls=djangojson.DjangoJSONEncoder, sort_keys=True, ensure_ascii=False)
    AttributeError: 'module' object has no attribute 'json'

The same thing happened a couple of months ago when 2.5.1 came out and I had the same issue on Debian Wheezy as well.

**Comment by jleclanche** [comment]
What version of django are you running?

**Comment by gjuric** [comment]
I am not sure, the one that got installed when I entered "pip install "Pootle==2.5.1.3".

I think the version is 1.4.20, at least that is what I get when I run "django-admin --version".

**Comment by jleclanche** [comment]
Try upgrading to Django 1.5, which I think the API needs.

**Comment by gjuric** [comment]
Now I am getting a new error:

     ImportError('No module named simple',)

I see that https://github.com/translate/pootle/blob/2.5.1.3/requirements/base.txt says that Django needs to be < 1.5

**Comment by gjuric** [comment]
OK; I resolved the issue by looking at the requirements file. I have uninstalled the tastypie provided by the Debian package and installed it with:

    pip install "django-tastypie==0.9.16"

Hope this will help somebody else Googling for the exact issue.
