### ISSUE TITLE
Manage command to get a list of contributors

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3867]
We need to be able to credit translators for version control commits.  For now we're not interested in more than knowing the information and leaving it to tools to use that information in commit messages.

The command should do the following:

1. Allow us to get a count ``--count`` so that we'd know if we can attribute this commit to one person or a group of people.
2. Specify a project and language - so that we can limit the information to one "domain" and commit
3. Give a range.  Which is likely either a time period of a revision count.  So ``--from-revision`` as we'll likely know what was the last revision we looked at before this commit.

Ideally data output is just text that we can use in our outside automation:

```
$ ./manage.py attribution --count --project=firefox --language=af
1
```

```
$ ./manage.py attribution --project=firefox --language=af
Dwayne Bailey <dwayne@translate.org.za>
```

Multiple contributors in a period would do the following
```
$ ./manage.py attribution --project=firefox --language=af
Dwayne Bailey <dwayne@translate.org.za>
A Nother <another@example.com>
```

We leave it to the outside scripts to use this information to make attribution,

**Comment by codeadict** [comment]
I can take this one, please @dwaynebailey let me know

**Comment by jleclanche** [comment]
@codeadict Go ahead.
