### ISSUE TITLE
Better handling of new line characters

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#3869]
Currently if a string has a new line character `\n`, Pootle will show verbatim and the user will also need to enter verbatim as well. This is cumbersome especially in RTL text as than `n` can mess the directionality.

Virtaal has a very nice way to handle this, first the `\n` is showed as pilcrow `¶` in both source and translation, and pressing Enter will insert a new line character (Pootle does this, but when re-editing the window it disappears unless it was entered manually).

**Comment by julen** [comment]
Closing as this has been handled as part of #4171.
