### ISSUE TITLE
Local TM exact matches being missed

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3872]
In Pootle with Local TM we're getting suggestions for short strings that are missing some exact matches.

E.g. Croatian for [Add](https://translations.documentfoundation.org/hr/libo_ui/translate/svtools/source/control.po#unit=93339187) we get various variants but we're not getting the exact match for 'Add' that actually does exist in another project.

So we just need to investigate how this is happening:

1. Is the data missing
2. Is Levenshtein bad on Elasticsearch
3. Is our result post processing dropping the 100% match

**Comment by julen** [comment]
Closing in favor of #3971.
