### ISSUE TITLE
project specific dictionary for translators

### ISSUE THREAD

**Issue by Matthias84** [translate/pootle#3874]
Hi, I like pootle, but miss a feature to collect the translation of common words. In a team this makes it easier to create a translation that sounds more consistent and reuse terms and keywords.

For example the Mediagobblin project has currently a [list in a wiki](https://wiki.mediagoblin.org/Translations#German). It would be nice to have this integrated or (maybe) generated out of the existing translations (ignoring stopwords per lang).

**Comment by unho** [comment]
You can get the translation files for a language and use [poterminology](http://translate-toolkit.readthedocs.org/en/latest/commands/poterminology.html) to extract a file with terminology. Once you have adjusted that file and provided the right translations you can upload it to Pootle to use as a terminology source: http://pootle.readthedocs.org/en/stable-2.5.1/features/terminology.html
