### ISSUE TITLE
Not possible to edit specific project or language, or create them, in admin

### ISSUE THREAD

**Issue by unho** [translate/pootle#3880]
@julen It seems to be some JavaScript issue: `Uncaught TypeError: Cannot read property '_currentElement' of null`. I made sure it is not some caching of old JavaScript in the browser. I tested on Chromium 43. On Firefox 38 the error returned is `TypeError: n is null`.

**Comment by julen** [comment]
I'm afraid there's no way to reproduce this — please double-check your deps. are up-to-date and the bundles are rebuilt too.

**Comment by unho** [comment]
Just run `make assets` and the problem persists.

**Comment by julen** [comment]
Can't reproduce I'm afraid, try removing your `node_modules` and starting from a clean slate.

**Comment by unho** [comment]
@julen Now worked. Thanks a lot!
