### ISSUE TITLE
Change unit revision during store.update() 

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3881]
Currently we don't change revision during update because our `sync_stores` implementation relies on the `Store.max_unit_revision()` to be higher than the `Store.last_sync_revision` even after Web UI update during `update_stores`.
But we need to increment the revision upon `store.update()` for import functionality.

Let's increment a global revision counter in the beginning of any `store.update()` and set that new value to all units changed during this update. Note that any Web UI update will be increment revision on its own.

**Comment by ta2-1** [comment]
@julen, @dwaynebailey, @jleclanche I talked with @iafan about this issue and there is a kind of problem. Current approach doesn't work if `import` is run with a `sync_stores` command at the same moment.
It can't be a problem if we run all `sync` and `update` tasks within RQ background processes (see  #3583). But it's not landed and import/export process doesn't adjusted for handling it via RQ #3786.

So I have to ask once again:  are we ok with this approach?

**Comment by jleclanche** [comment]
Yeah, it's fine.

**Comment by jleclanche** [comment]
@ta2-1 Is this

**Comment by jleclanche** [comment]
Wrong issue.

**Comment by dwaynebailey** [comment]
@ta2-1 Yeah last night I was wondering about the issue of doing a sync at the same time as an update.  There is a small possibility of an issue.  But I think combined with ``--force`` and --overwrite`` this issue could be reduced and with the sync optimisation the window is smaller.  So for now I'd say its not a critical issue since we'll eliminate it when the other RQ bits land.

**Comment by dwaynebailey** [comment]
@ta2-1 @jleclanche one concern I have which maybe we need to look at.

I use ``--modified-since`` in ```list_languages`` to protect mlo from updating languages that might be hosted on Pootle but the team is actually not translating on Pootle.  So we get a list of languages that have changed.

A concern now would be that with this change ``update_stores`` once I've done a update against templates would force a change in revision.  That change in revision could cause me then to commit everything.  I could avoid this I guess if I know the revision used for template updates and make sure that is my last flagged revision.  But this starts to sound hairy.

Thoughts?

**Comment by ta2-1** [comment]
@dwaynebailey, if I understood you right, we do the similar thing in EN `sync-update` cycle. And `store,last_sync_revision` field is used for it.
I'm not aware how update against templates works. What does it do exactly? And how should we change revision during this process?
