### ISSUE TITLE
syspath_override not on path after fresh pip install

### ISSUE THREAD

**Issue by FrITA** [translate/pootle#3886]
I just installed Pootle in a virtual environment in Debian 8 and this happens:

```
user@computer ... $ venv/bin/pootle -version
...
  File "/home/user/test_pootle2/venv/lib/python3.4/site-packages/pootle/runner.py", line 27, in <module>
    import syspath_override
ImportError: No module named 'syspath_override'
```

`syspath_override` is present but it isn't on the path.

Pootle:
Pootle 2.6.0 (Django 1.6.11, Translate Toolkit 1.13.0)

Python:
Python 3.4.3 (default, May  3 2015, 15:16:07) 
[GCC 4.9.2] on linux

pip:
pip 7.1.0 from /home/user/pootle/venv/lib/python3.4/site-packages (python 3.4)

However, this bug is really easy to fix by changing `import syspath_override` to `from pootle import syspath_override` in `runner.py`

It looks like that line is the same in 2.7 and 2.6.0.

As an aside; Does anyone else think the `syspath_override` functionality should be in `__init__`?

**Comment by unho** [comment]
Latest stable version of Pootle is 2.5.1.3. You should use that for production. Follow the instructions in http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/server/installation.html to ensure you don't have any problem.

Besides that Pootle does not support Python 3.

**Comment by julen** [comment]
As @unho says these are unsupported versions of Pootle/Python (2.6.0 is a transitional release). Besides that we have plans to get rid of `syspath_override` in #3608, so closing.

**Comment by FrITA** [comment]
I'm more interested in pootle for hacking/personal use.
Is it clearly documented somewhere that there is no Python 3 support?
A search on PyPi leads here, https://pypi.python.org/pypi/Pootle/2.5.1.2, but the link is broken.
Aside from that; are there any plans to port pootle and translate-toolkit to Python 3?

**Comment by jleclanche** [comment]
@FrITA translate-toolkit has the works of Python 3 compatibility in it. It's an ongoing project which had to take a backseat to other developments recently. Since Pootle depends on translate-toolkit currently, Pootle won't be compatible with Python 3 before TTK is.

Please feel free to contribute Python 3 fixes.

**Comment by FrITA** [comment]
That makes sense. There's some interesting stuff in TKK, maybe I'll spend some time this weekend hacking.

**Comment by tcitworld** [comment]
Translate-Toolkit is now Python 3-compatible, any news on this ?

**Comment by dwaynebailey** [comment]
@tcitworld any PRs ;)

translate-toolkit has one bug we want to close before and official release with Python 3 compatibility.

All of our deps are now py3 compatible.

There are no current plans to support Python 3, we we have enough on our plate.  But we'd welcome any PRs.  If you want to look at this my thoughts are that we won't support both versions. We'd just support Python 3.

**Comment by Nuruddinjr** [comment]
I have Pootle 2.7.6 installaed but still getting the same error in Python 3.5

**Comment by unho** [comment]
Pootle doesn't support Python 3 yet.

**Comment by karstengo** [comment]
I still get the same error with python3.8.2

```
ModuleNotFoundError: No module named 'syspath_override'

$ pootle init
Traceback (most recent call last):
  File "/home/ogak/sources/env/bin/pootle", line 33, in <module>
    sys.exit(load_entry_point('Pootle==2.9.0rc1', 'console_scripts', 'pootle')())
  File "/home/ogak/sources/env/bin/pootle", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ogak/sources/env/lib/python3.8/site-packages/pootle/runner.py", line 20, in <module>
    import syspath_override  # noqa
ModuleNotFoundError: No module named 'syspath_override'
```
