### ISSUE TITLE
For certain page content, extra wrapper HTML tags are added for no reason

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3889]
Steps to reproduce:
1) Create a new static page with the following code:
```html
 <style></style><p>test</p>
```
2) Save the page, and open it's 'view' link.
3) Look into the page source. The inserted static page content will look like this:

```html
 <html><head><style></style></head><body><p>foo</p></body></html>
```
The resulting HTML structure is totally odd and may lead to unexpected rendering issues. Note that this only seems to happen when there are `<style>...</style>` tags in the static page body.

According to quick inspection by @unho:
> As I can see the problem is in https://github.com/translate/pootle/blob/master/pootle/templates/staticpages/_body.html#L14
> And it is when calling `page.body`

**Comment by julen** [comment]
The structure is being generated by lxml:
```python
In [1]: from lxml.html import rewrite_links

In [2]: rewrite_links('<p></p>', lambda x: x)
Out[2]: '<p></p>'

In [3]: rewrite_links('<style></style><p></p>', lambda x: x)
Out[3]: '<html><head><style></style></head><body><p></p></body></html>'
```

**Comment by iafan** [comment]
Can we prevent lxml from being overly smart?

**Comment by julen** [comment]
Not that I'm aware of; we'd need to create our own custom version of `rewrite_links` here. Just wondering how big this issue in practice is though.

**Comment by julen** [comment]
FTR, passing in any string with a root node prevents lxml from generating a whole doc:
```python
In [4]: rewrite_links('<div><style></style><p></p></div>', lambda x: x)
Out[4]: '<div><style></style><p></p></div>'
```

**Comment by iafan** [comment]
This means we can do a simple workaround by wrapping the contents of the static page in `<div>...</div>` when returning it as a value of `page.body`, right?

**Comment by julen** [comment]
Yeah that should do the trick; still we better write our own wrapper around `rewrite_links` to ensure proper behavior everywhere.
