### ISSUE TITLE
TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by Leo-g** [translate/pootle#3893]
When i run pootle init i get the above error, stack trace is below. 

     site-packages/pootle/runner.py", line 61, in init_settings     output = output.replace("${default_key}",                   b64encode(os.urandom(KEY_LENGTH)))

versions python 3.4 and pootle 2.6

**Comment by jleclanche** [comment]
Pootle does not support Python 3 unfortunately. Contributions welcome.

**Comment by jleclanche** [comment]
This particular bug fixed in a4d100c

**Comment by Leo-g** [comment]
When will python 3 support be available? Is the git branch stable? Can I clone it for my live project?
I am having issues with postgres migration and as per a resolution I should use pootle 2.7 by directly cloning the repo

**Comment by jleclanche** [comment]
Yes, the current git branch is stable enough for production use.

**Comment by jleclanche** [comment]
There's no ETA on python 3 support right now, since it's a lot of work. But if you encounter more easy issues feel free to report them...
