### ISSUE TITLE
Use DirtyFields to track changes in a unit

### ISSUE THREAD

**Issue by julen** [translate/pootle#3895]
Some methods of the `Store` and `Unit` models have grown way too much (specially the `save()` methods) and they're not becoming easy to read, maintain and test.

One of the the causes of the growth in line length is that changed fields are tracked in _private_ variables of an instance as boolean values, for example `self._target_updated`, `self._state_updated`, `self._comment_updated` etc. The list grows as fields are added and checks need to be performed, and the values of these attributes need to be manually set/unset. This is terrible.

We already have a `DirtyFieldsMixin` class to handle situations like these ([example usage](https://github.com/translate/pootle/blob/51efba76835e97449e1cafb4e5c8dd9a006c947e/pootle/apps/staticpages/models.py#L81)). As far as we're constrained to a scenario where we can use signals, such a mixin will allow us to vastly simplify the existing code.

**Comment by phlax** [comment]
dirtyfields has been removed
