### ISSUE TITLE
Ensure tests affecting the FS are run from a clean slate

### ISSUE THREAD

**Issue by julen** [translate/pootle#3898]
Currently tests that deal with the FS (i.e. any tests that parse FS stores or sync them to disk) are not straightforward to reason about, since their initial state _might_ not be the same as a developer sees them in the [test data files](https://github.com/translate/pootle/tree/master/tests/data/po).

For the entire testing session [data files are copied over to a temporary directory](https://github.com/translate/pootle/blob/674a6d9110192ea68a5b3661d97736653d36c485/tests/fixtures/models/store.py#L41-L63), and setting locations are adjusted to point there. This is a session-scoped fixture, therefore it's run once for a complete test run. As a consequence of this, some tests that parse stores end up depending on the result of previous tests, which is not nice.

We definitely want to avoid this. How? There are at least two ways:
1. Make the `po_directory` fixture function-scoped.
   This would mean that for every test function. We can force devs to explicitly require this fixture or `autouse` it every time (the latter would end up doing useless work for many tests). The main concern is how this would affect the execution time of all tests, since copying to the tmp dir + removing the tmp dir would happen in the lifecycle of every test function.
2. Explicitly use separate test files for each test affecting the FS.
   The current behavior for setting up a tmp directory would be kept, so that operation would be run just once for the entire testing session. However, each test would explicitly make use of separate files ([check example](https://github.com/translate/pootle/commit/1a45bf42ff6b30498e59656dee4c5bdfa530123e)), therefore keeping files explicitly isolated to specific tests.
   The challenge with this approach is using a consistent naming scheme for test data files.

Can someone else think of any other alternatives?

**Comment by julen** [comment]
I'm currently leaning towards favoring the second option, as it keeps data files explicit to what they test. I like the first option too, but I'm worried about the impact this might have in the overall execution time.

**Comment by julen** [comment]
Would appreciate thoughts on the matter @ta2-1 @translate/house.

**Comment by unho** [comment]
I am against 1) with `autouse`.

I also don't like 1) with no `autouse` because this sounds like it can end being unmanageable as we have more tests that rely on this.

I think 2) is the best choice despite this leads to a growing size for test directory.

And I don't see any other possibility.

**Comment by dwaynebailey** [comment]
2) makes a lot of files with the same data.  But I'd prefer that as its then safe to change files and data as you know it impacts only your test.

Would an option for 1) we to explicitly tell a test that this is one that needs to start from scratch and it does that for the files.

**Comment by ta2-1** [comment]
1) seems to be very convenient but since we have difficulties let's continue with 2). 
Actually we apply 2) already. I had to add new .po files (one per test) for many tests. 
But probably we can improve a way how we add new (pre test) fixtures. Can we copy the same files from an existing fixture to a primary test directory?

**Comment by phlax** [comment]
there may still be some fs pollution in tests, but i believe the fixtures now generally handle this correctly
