### ISSUE TITLE
--modified-since is not filtering languages

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3899]
The full count for all projects on the server as reference:
```
$ ./manage.py list_languages | wc -l
218
```

The count of languages enabled for the ``firefox`` project.  The count is lower so that's good
```
$ ./manage.py list_languages --project=firefox | wc -l
197
```

Lets get a revision:
```
$ ./manage.py revision
26101
```

Now lets filter for a project ``firefox`` and a revision clost to 26101.  Notice the count is as if there is no filtering and a result of 170 would be technically impossible I would think.
```
$ ./manage.py list_languages --modified-since=26090 --project=firefox | wc -l
170
```

Choosing a revision in advance of the current revision should return zero results:
```
$ ./manage.py list_languages --modified-since=26200 --project=firefox | wc -l
170
```

General result, we're not filtering these results.

This is blocking going live on mlo as it simply doesn't do what it advertises to do.  Can we please write tests to validate this as it's a pain to go live and discover that it doesn't do what it needs to do.

**Comment by dwaynebailey** [comment]
@jleclanche can you pick this up please.

**Comment by julen** [comment]
[The code](https://github.com/translate/pootle/blob/120573fef7d7ffb43656a4d066111eab2c0bfaf1/pootle/apps/pootle_app/management/commands/list_languages.py#L42) makes no sense:
```python
    tps = tps.filter(submission__id__gt=revision)
```
It's comparing revision numbers with submission IDs. It should rather be:
```python
    tps = tps.filter(submission__unit__revision__gt=revision)
```

**Comment by jleclanche** [comment]
I am looking into it, it's not that simple, it errors out with django.core.exceptions.FieldError: Relation fields do not support nested lookups

**Comment by jleclanche** [comment]
Actually it was that simple. 45 minutes debugging something completely different :/

BTW I have no idea how the code ended up looking at IDs.

**Comment by dwaynebailey** [comment]
Confirmed that fixed it thanks.
