### ISSUE TITLE
Show email of users in Pootle

### ISSUE THREAD

**Issue by Delphine** [translate/pootle#3901]
Right now in many cases, it's impossible to know who is who on Pootle. In many occasions, I need to contact localizers in regards to an urgent project, but am unable to because people use nick names that do not correspond to any existing Mozillians profile and that do not appear on the l10n team page. Not having emails accessible prevents us from contacting these localizers in a timely manner. Requesting a fix for this :)

**Comment by unho** [comment]
@dwaynebailey If I remember correctly a patch to deal with this had been applied on the Mozilla's Pootle server, isn't it?

**Comment by dwaynebailey** [comment]
@unho we had a patch to expose the email address if a user was an admin.  We should do the same for the profile page.

**Comment by Delphine** [comment]
Thanks for looking into this. Do you have an ETA for the fix? We're trying to contact people who are working on a language that we are going to launch Firefox OS in, so it would be crucial to be able to communicate with him soon. We haven't been able to find out how to reach him yet. Thanks!

**Comment by unho** [comment]
@dwaynebailey The patch for previous mlo already was for the profile ac2b602b. Adjusted it to new codebase and created PR #3910.
