### ISSUE TITLE
[Mozilla] Unable to edit projects settings  

### ISSUE THREAD

**Issue by arky** [translate/pootle#3902]
Trying to edit the project settings results in JavaScript errors.  
```
"Uncaught TypeError: Cannot read property '_currentElement' of null
20:50:51.442 Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.1 vendor.min.091472dd.js:1:1004"
```
Test Case: 
1. Log in into Pootle as Super admin
2. Navigate to admin/projects 
3. Click a project to view to edit its settings. 

Result: You get JavaScript errors. 
Expected Result: Take the user to project settings.

**Comment by jleclanche** [comment]
cc @julen

**Comment by arky** [comment]
Looks like a deployment problem with Mozilla server. Marking this as invaild. Thanks @jleclanche !

**Comment by dwaynebailey** [comment]
Just a heads up on what I did here, for future reference.
```
cd pootle/static/js
rm -rf node_modules
npm install
cd ../../..
make assets
```

**Comment by julen** [comment]
`npm install` is unnecessary; `make assets` already takes care of that.
