### ISSUE TITLE
Unicode letter "u" appears in some strings (u"example")

### ISSUE THREAD

**Issue by SafaAlfulaij** [translate/pootle#3903]
In some strings, the u letter that indicates that a string is a unicode string (Python stuff) appears.
Example:
"Could not create u'testing.po'. Missing Project/Language? (File u'testing.po' was rejected because its X-Pootle-Revision is too old.)"

**Comment by jleclanche** [comment]
This is an artifact of using `%r` (generally a good idea for paths) on unicode strings. I guess I'll change it.
