### ISSUE TITLE
Provide users option to resend the activation email 

### ISSUE THREAD

**Issue by arky** [translate/pootle#3904]
![screenshot from 2015-07-18 13 43 30](https://cloud.githubusercontent.com/assets/808895/8760646/08bc6096-2d53-11e5-82eb-ea95abed0551.png)

Please provide a hyperlink to resend the activation email in the 'Account  Activation' dialog box.

**Comment by jleclanche** [comment]
The email is supposed to be resent automatically when you try to log in again.

**Comment by julen** [comment]
@jleclanche is right: this is a non-issue as described in https://github.com/translate/pootle/issues/3517#issuecomment-74875092.
