### ISSUE TITLE
Release PyPi 2.7

### ISSUE THREAD

**Issue by aRkadeFR** [translate/pootle#3906]
Hey there :)

Trying to deploy pootle, and the pip release right now is 2.6, though it can't be deployed cause it says on initdb: "Pootle 2.6.0 is an interim version... install Pootle 2.7" which 2.7 version is not on pypi.

Plus to rollback to a correct version, through piip, it shows that it is the 2.5.1.2 version, but can't install it anymore.

**Comment by unho** [comment]
@aRkadeFR Sorry. There is some problems with PyPI. The latest stable release is 2.5.1.3, so please try explicitly specifying it. Please let us know if that fixes the issue.

**Comment by aRkadeFR** [comment]
yeah I can instlal 2.5.1.3, I have other problems with this release then, I open an other ticket. Thanks for the answer.
