### ISSUE TITLE
Allow language managers to edit their language's special characters

### ISSUE THREAD

**Issue by gueroJeff** [translate/pootle#3908]
Essentially, it used to be that project admins could add their own special characters to the virtual keyboards for their project. There was an option for it in the project description portion of the project landing page. It appears that the field for adding special characters via that workflow has been removed.

Use case: Julio Gomes, who has been mentor for many indigenous Latin American locales, is project admin for each of these locales. After they were created in Pootle, he would do additional research into the writing systems for each locale and add those special character keys on his own within the project's description editing dialogue. Julio's request is to have it restored.

**Comment by dwaynebailey** [comment]
Some added info on this.  The ability to add a language description page also had the ability to edit the special characters.  Currently on ``master`` these changes can only be made at the global admin level.

I think we should look at exposing more of these config options on the Browse/Translate dropdown for language admin.

That would include:

1. Special characters
2. Language descriptions page (possibly)

**Comment by gueroJeff** [comment]
I think that would be a great place for them.

**Comment by unho** [comment]
Plan of action:

- Add some intermediate level of permissions between regular users and global admin, so some users can edit settings and announcements for specific TPs, Languages or Projects.
- If allowing such users to visit the admin site is deemed too dangerous or undesirable, then provide some new admin UI that just allows to edit a single TP, Language or Project.
- Consider displaying the links to access admin UIs in the actions dropdown:

![abbb](https://cloud.githubusercontent.com/assets/939880/9177109/9ee3564e-3f8f-11e5-9723-857e651ef378.png)

**Comment by iafan** [comment]
> Add some intermediate level of permissions between regular users and global admin, so some users can edit settings and announcements for specific TPs, Languages or Projects

@unho, we already have project-level admins, which could be a good fit for the purpose.

**Comment by unho** [comment]
@iafan How do you specify a user to be a project-level admin? I have been checking existing permissions and I didn't saw any that can be checked to tell that a user is a project manager (I do prefer this term over admin, which I only use for global-admin or superuser).

**Comment by iafan** [comment]
@unho, try going to e.g. https://translate.stage.evernote.com/projects/website3_evernote/admin/permissions/ — there you can add a user with 'Can administrate a translation project' permission.

**Comment by unho** [comment]
> @unho, try going to e.g. https://translate.stage.evernote.com/projects/website3_evernote/admin/permissions/ — there you can add a user with 'Can administrate a translation project' permission.

I thought that particular permission was to give some user TP manager rights. But independently of if this permission is "project manager" or "TP manager", I think we lack "language manager".

**Comment by iafan** [comment]
I think 'administering translation project' can include both adding permissions and providing descriptions. No need for another permission type, IMO. Let's keep things simple.

**Comment by unho** [comment]
Created issue #3984 to track announcements edit for users with `administrate` permission.
