### ISSUE TITLE
Unhandled Exception after changing user language

### ISSUE THREAD

**Issue by xperseguers** [translate/pootle#3909]
After changing the user language on http://translation.typo3.org/accounts/edit/ I now only get the following error on any page:

```
Unhandled Exception

An unhandled exception was thrown by the application.
```

I am not able to do anything anymore on translation.typo3.org. Logging out by removing the session cookie revives the page but logging in gives me the exception again.

## Background

* Pootle is version 2.5.1.3 installed via "pip"
* Installed in a Python virtualenv
* With debug "on", this error happens:

```
AttributeError at /about/
'NoneType' object has no attribute '_info'

Exception Location:	/path/to/django/utils/translation/trans_real.py in _fetch, line 147
```

Local vars:

<img width="321" alt="debug" src="https://cloud.githubusercontent.com/assets/646805/8795210/3ec07170-2f8b-11e5-9c5c-6e7b1832dddf.png">

This happens, e.g., with `pootle_app_pootleprofile` is set to `en` or `en-gb` but not when it is set to `en-us`.

**Comment by dwaynebailey** [comment]
I can't seem to replicate this.  Could you give some of the following info:

1. What system is this on?
2. Also could you past the full traceback please.
3. Could you try the following:
```
  file $path_to_virtualenv/./lib/python2.7/site-packages/pootle/locale/en_GB/LC_MESSAGES/django.mo 
  msgunfmt $path_to_virtualenv/./lib/python2.7/site-packages/pootle/locale/en_GB/LC_MESSAGES/django.mo | msgfmt -
  file messages.mo
```
4. I suspect something with localisation obviosly, so if you are able to recompile the MO files using msgfmt that would be helpful to validate if that is indeed the error.

**Comment by xperseguers** [comment]
1. It's a Debian wheezy although with hindsight I had previously similar problem on a Jessie (latest) but did not know how to debug.

2. forcing `en-gb` as `ui_lang` instead of (working) `en-us`:
```
Environment:


Request Method: GET
Request URL: http://translation.typo3.org/

Django Version: 1.4.21
Python Version: 2.7.3
Installed Applications:
['django.contrib.sessions',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'pootle_app',
 'pootle_misc',
 'pootle_store',
 'pootle_language',
 'pootle_project',
 'pootle_translationproject',
 'pootle_profile',
 'pootle_statistics',
 'pootle_tagging',
 'pootle_notifications',
 'pootle_autonotices',
 'pootle_terminology',
 'staticpages',
 'registration',
 'profiles',
 'djblets.siteconfig',
 'djblets.util',
 'contact_form_i18n',
 'django_assets',
 'taggit',
 'voting',
 'south']
Installed Middleware:
['pootle.middleware.baseurl.BaseUrlMiddleware',
 'django.middleware.transaction.TransactionMiddleware',
 'djblets.siteconfig.middleware.SettingsMiddleware',
 'django.middleware.cache.UpdateCacheMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'pootle.middleware.setlocale.SetLocale',
 'django.contrib.messages.middleware.MessageMiddleware',
 'pootle.middleware.errorpages.ErrorPagesMiddleware',
 'django.middleware.common.CommonMiddleware',
 'pootle.middleware.captcha.CaptchaMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware']


Traceback:
File "/opt/local/pootle/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  87.                     response = middleware_method(request)
File "/opt/local/pootle/local/lib/python2.7/site-packages/django/middleware/locale.py" in process_request
  24.         translation.activate(language)
File "/opt/local/pootle/local/lib/python2.7/site-packages/django/utils/translation/__init__.py" in activate
  105.     return _trans.activate(language)
File "/opt/local/pootle/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in activate
  194.     _active.value = translation(language)
File "/opt/local/pootle/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in translation
  184.     current_translation = _fetch(language, fallback=default_translation)
File "/opt/local/pootle/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _fetch
  147.             res._info = res._info.copy()

Exception Type: AttributeError at /
Exception Value: 'NoneType' object has no attribute '_info'
```

3.

```
 ~  file /opt/local/pootle/lib/python2.7/site-packages/pootle/locale/en_GB/LC_MESSAGES/django.mo 
/opt/local/pootle/lib/python2.7/site-packages/pootle/locale/en_GB/LC_MESSAGES/django.mo: GNU message catalog (little endian), revision 0.0, 566 messages

~  msgunfmt /opt/local/pootle/lib/python2.7/site-packages/pootle/locale/en_GB/LC_MESSAGES/django.mo | msgfmt -
(empty output)
```

**Comment by xperseguers** [comment]
ping

**Comment by jleclanche** [comment]
@xperseguers does the error remain if you set `USE_I18N = False` in your settings?

**Comment by xperseguers** [comment]
No, the error is gone but it leads to another problem, namely that users cannot choose their interface language anymore, may it be with their browser's preferences or from settings in Pootle.

What's worth mentioning: some languages in Pootle do not translate the UI: e.g. Albanian, Chinese (Hong Kong), ... but many others work: Arabic, German, French, Chinese (China), ...

Regarding English, I see 3 locales in Pootle settings for my profile:

* English (South Africa) (`en-za` in `pootle_app_pootleprofile`)
* English (United Kingdom) (`en-za` in `pootle_app_pootleprofile`)
* English (`en` in `pootle_app_pootleprofile`)

Choosing any of those leads to the exception and breaks the session and user profile until either `pootle_app_pootleprofile.ui_lang` is _cleared_ or set to `en-us` (which happens to be the default language for the Pootle install, namely setting `LANGUAGE_CODE` which is not locally overridden and default value within `10-base.conf`.

**Comment by xperseguers** [comment]
You may reproduce the bug by using my Ansible playbook to install Pootle in a Debian Wheezy or Jessie virtual machine. Debian Jessie as VM may, e.g., be downloaded here: http://www.osboxes.org/debian/.

Just follow the 4-5 super easy and quick steps in `README.rst` after cloning https://git.typo3.org/Teams/Translation.git.

**Comment by julen** [comment]
@xperseguers I'm afraid your steps to reproduce don't work (i.e. no way to even have Ansible running). You should notice the Debian images you link to lack many of the required packages (git, easy_install, and so on) — I was able to overcome that by manually editing */etc/apt/source.list* and installing the packages myself, but this is far beyond the point.

Would you be able to provide the steps to reproduce this based on the [supported installation methods](http://docs.translatehouse.org/projects/pootle/en/latest/server/installation.html)?

**Comment by xperseguers** [comment]
no way to have Ansible run? Are you using Windows, it may be the cause, it runs smoothly on both Linux and Mac OS X? I downloaded myself a basic Debian image from debian.org and really installed nothing else than ssh server before running the Ansible script. It takes care of installing git, easy_install and so on on its own.

Anyway, I'm not following the link of supported installation method (version latest) but version 2.5.1.3: http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/server/installation.html

One of the first step described is installing Pootle in a virtualenv, I suspect it to be somehow related because I was then unable to make Pootle see the isocode package...

The steps to reproduce (and in the Ansible playbook) are strictly those of your install tutorial, taking care of configuring memcached and xapian and running the whole using nginx + fast cgi: http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/server/web.html#proxying-with-nginx-fastcgi

Just tried again, plain vanilla Pootle 2.5.1.3, after initial login with admin/admin, I go to my profile and set 'english (en)' as language and bang!

**Comment by xperseguers** [comment]
Today someone reported me another configuration where the profile is kept broken. I could reproduce. Even if `en-us` is set in the profile (which, to write it again, works), as soon as I edit my browser language preferences and I put `en-gb` on top, before `en-us` or `en`, no way! the error happens so the browser has precedence over the profile. There is something inherently broken with `en-gb`...

**Comment by xperseguers** [comment]
As reported 12 days ago:

```
Django Version:	1.4.21
```

I found this (old) bug: https://code.djangoproject.com/ticket/18192. I applied the suggested patch:

```
django/utils/translation/trans_real.py

@@ -138,6 +138,12 @@ def translation(language):
 
         res = _translation(globalpath)
 
+        if res is None:
+            return gettext_module.NullTranslations()
+
         # We want to ensure that, for example,  "en-gb" and "en-us" don't share
         # the same translation object (thus, merging en-us with a local update
         # doesn't affect en-gb), even though they will both use the core "en"
```

on `/opt/local/pootle/lib/python2.7/site-packages/django/utils/translation/trans_real.py` and problem was gone. I then chowned the file to `pootle:pootle` instead of `root:root` so that the corresponding `trans_real.pyc` could be recreated on next call.

According to the aforementioned bug tracker entry, it should be fixed since the refactoring of Django localization class, this was more than 1 year ago: https://github.com/django/django/commit/a5f6cbce07b5f3ab48d931e3fd1883c757fb9b45 (version 1.8c1).

**Comment by xperseguers** [comment]
I guess the correct way of fixing this bug in Pootle, even if actually related to Django would be to use an up-to-date version of Django instead of v1.4.21, but don't know where this dependency comes from. Well, at least I hope this will help other users having the same problem since the error message is not clear at all.

I'd like to understand what (and why) is actually missing in my installation out-of-the-box from the manual.

**Comment by jleclanche** [comment]
@xperseguers We are releasing Pootle 2.7.0 today, which is compatible with Django 1.7 and 1.8.

**Comment by xperseguers** [comment]
Considering the current workaround fine enough, hopefully does not happen anymore with 2.7.0 then :)

**Comment by julen** [comment]
> We are releasing Pootle 2.7.0 today, which is compatible with Django 1.7 and 1.8.

FTR, 1.8 compatibility is not ensured or supported.
