### ISSUE TITLE
No guidelines on serving static files via web servers

### ISSUE THREAD

**Issue by julen** [translate/pootle#3913]
From #3734, it turns out there's no single mention or instructions that web servers need to be configured to serve static files.

Note that this was also affecting file downloads — I'm not sure what's the current situation there.

Some guidance needs to be provided, otherwise this ends up with confused users.

**Comment by unho** [comment]
This is partially addressed in the example configuration for Apache: http://docs.translatehouse.org/projects/pootle/en/latest/server/web.html#apache-with-mod-wsgi

Downloads (exports) are no longer served by the web server (see 097a9cfd) but instead served directly by Pootle. This was different on 2.5.1.x release.

**Comment by unho** [comment]
This is a 2.5.x issue. In 2.7.x these files are served directly by Pootle. Merged 464cc11f that fixes this.
