### ISSUE TITLE
Expanded checks are not being updated

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3923]
The expanded checks available through the + on the progress bar are heavily cached or are not updating.

I completed a review of all 'compendium conflicts' and there are now none on mlo.  But expanding the checks shows 431 failing compendium conflcts.  Clicking on 431 says that there are no units.

I suspect that this snippet is quite heavily cached.  But I'd assume if we have stats in redis we don't need to cache these results are heavily as before.

**Comment by julen** [comment]
Did you reload the page? If not this is intended to avoid unnecessary requests.

**Comment by dwaynebailey** [comment]
This pages exhibits the issue http://mozilla.locamotion.org/projects/ (you need to expand the progress bar to see the checks).  Its still cached at the time of posting this.

**Comment by julen** [comment]
We checked on IRC and this is not a protocol- or client-level caching issue.

**Comment by julen** [comment]
@dwaynebailey could you confirm this is an actual issue?

**Comment by dwaynebailey** [comment]
I'm going to close this as I can't reproduce at the moment.
