### ISSUE TITLE
'Copy into translation' button always copies English text

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3927]
Steps to reproduce:
1. Make sure you have one or more alternative source languages selected for your account (let's say it is Russian)
2. Go to any unit which has a Russian translation
3. Click the 'Copy into translation' button next to Russian translation

Expected: Russian translation will be copied into the edit area.
Observed: English source is copied.

**Comment by julen** [comment]
This is a regression introduced in 368c809.
