### ISSUE TITLE
Latest activity credits suggestors

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3928]
The latest activity indicator will use the user data for people who have provided suggestions.

This is pretty confusing when the person suggesting is not part of the team.  Either making a valid suggestion to fix something or mistakenly suggesting on the wrong project.

So this is a discussion point. Shouldn't we indicate last activity only for those activities that result in an actual translation.  That is a translation or the acceptance of a suggestion?

**Comment by iafan** [comment]
I had a brief talk with @julen about this. It seems both he and I are on the same page here: we consider suggestions the valid activity which needs to be reflected as last activity column.

My vision here is that, when we get suggestion voting implemented right, for some languages the only activity would be suggesting and voting. So if we filter that out, it will look like not much is happening in the language even if there's a healthy community of volunteers who suggest and vote for suggestions.

**Comment by unho** [comment]
Just wanted to point out that voting proved not to produce good quality translations in the past.

**Comment by iafan** [comment]
@unho, this depends on the size of the volunteer community and on the workflow that happens on top of voting.

**Comment by julen** [comment]
Closing per the invalid tag.
