### ISSUE TITLE
Remove fab files

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3929]
I loved them: easy deployment and staging.  But seems nobody uses them.  I'm sure they've painfully bitrotted.

So lets stop the pain and remove them.  Also needs removal of parts from the docs.

If you want to keep them, best test that they are still workable and/or start using them.

**Comment by julen** [comment]
These are very specific to a certain setup and IMHO they don't belong here. The bit-rotten part is worrying and misleading at the same time. If anyone wants to maintain them, these can be managed in a separate repo. For now, let's get rid of them.
