### ISSUE TITLE
Submitting translations while reviewing suggestions

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#3933]
I’m not sure if this is doable, but when in suggestions review mode I often find myself not accepting any suggestions and instead submitting my own (either completely new or based on what of the suggestions), but when I hit Submit I _want_ to stay in this unit as long as it has any pending suggestions so that I can reject them, but what happens now is that once I Submit I get moved to the next unit with suggestions which is counter productive (for my use case at least).

**Comment by iafan** [comment]
I'm pretty positive that this is doable, and that this makes perfect sense. Whenever we filter units by (`filter=suggestions`), we should stay in the same unit until it has any pending suggestions, and advance automatically when it has none.

**Comment by julen** [comment]
Notice that at the moment Pootle only has the notion of *filters* (which might map better or worse to reviewing capabilities), and there's no such thing as *review mode*.

Taking this into account, at the current state of things I believe the behavior will be surprising for users: submitting will behave differently based on the chosen *filter*.

Having made that observation, I'm totally in favor of improving the workflow for suggestions. Also consider having a look at #2596 and #2069 which already propose specific ways to improve reviewing suggestions.

**Comment by iafan** [comment]
We already happen to have a different behavior when reviewing suggestions in `filter=suggestions` mode: when one has accepted or rejected all suggestions, we automatically advance to the next unit.

I don't see such a different behavior as a problem: in the end, it can be explained that in this suggestion review mode we go through _suggestions_, and not _units_, so we only advance to the next unit if it no longer contains pending suggestions. So I'd implement this as described above, then see if we need to do anything to help people understand this mode better.

I also have some ideas on how to improve the suggestion workflow. One day I'll spec it out.

**Comment by julen** [comment]
> We already happen to have a different behavior when reviewing suggestions in filter=suggestions mode: when one has accepted or rejected all suggestions, we automatically advance to the next unit.

This is not limited by the filter, the current behavior is orthogonal to it.

**Comment by iafan** [comment]
Ok, good to know. I think we will need to fix that as well.

**Comment by khaledhosny** [comment]
I think I’m happy with the current workflow now.
