### ISSUE TITLE
Disallow TP creation if there is no template language

### ISSUE THREAD

**Issue by unho** [translate/pootle#3942]
See https://github.com/translate/pootle/pull/3918#issuecomment-127209505 for more.

Perhaps we should enforce a project having a templates language always as a way to fix this.

**Comment by julen** [comment]
> Perhaps we should enforce a project having a templates language always as a way to fix this.

-1, that's a workaround, not a fix. Also we don't want to force servers to have a templates *language*.

**Comment by unho** [comment]
I wanted to say a template language. Not necessarily `templates` or the same across projects.

**Comment by julen** [comment]
Still it refers to the same concept. In our case for instance we don't import or expose templates anywhere in Pootle.

Let's fix the issue and forget about workarounds that complicate things around.
