### ISSUE TITLE
Internal server Error (500) on new installation pootle 2.7

### ISSUE THREAD

**Issue by mitsurugi** [translate/pootle#3949]
Hi, I was trying for a week to install Pootle on a apache2 webserver.

I followed the instructions for installing via GIT

Here is my  `pootle --version`

    Pootle 2.7.0.dev0 (Django 1.7.9, Translate Toolkit 1.13.0)

I configured the pootle.conf to work with MySQL

I managed to start pootle with no warnings no errors until i acces it in the browser, there was when i recieve an error 500 and the follow errors in the terminal

    2015-08-06 13:46:46,948 INFO Starting CherryPy server, listening on port 8000
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in     get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/views/index/index.py", line 27, in view
    return render(request, 'welcome.html', ctx)
       File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),

[...]

      version = self.get_version(ctx, refresh=ctx.auto_build)
      File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
    BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x347d150>], contents=('css/style.css', 'css/actions.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder

I google trying to find solutions before comming here and tried some commands  like

    python manage.py collecstatic --clear --noinput
    python manage.py assets

Some sais that is django problem so I tried to install another version but this pootle version does not works with django != 1.7.9

Apache access logs or error does not show problems

I also configured my virtualhost with

    ProxyPass / http://localhost:8000/
    ProxyPassReverse / http://localhost:8000/
    ProxyPreserveHost On

Im on a Debian 7 wheezy

Any ideas or somebody know how to fix it? Thanks

**Comment by unho** [comment]
First of all it is recommended to use the final 2.7.0 version that we just shipped.

Please try this installation step: http://docs.translatehouse.org/projects/pootle/en/stable-2.7.0/server/installation.html#static-assets

**Comment by mitsurugi** [comment]
Yeah, that works for me and fix my the issue

    cd /usr/local/lib/python2.7/dist-packages/pootle/static/js && npm install
    cd ../../..
    make assets

Now I have to handle with other stuff, on the main projects page

   Exception: Directory matching query does not exist.

After login :)

Thanks
