### ISSUE TITLE
Sidebar gets wrong height when hidden on page load

### ISSUE THREAD

**Issue by phlax** [translate/pootle#3969]
to reproduce:

- put a lot of content in the sidebar
- load a page with the sidebar closed
- expand the sidebar and witness that the sidebar is ~2x the height of the contained elements

this is fixed by #3963 and is related to #3812

**Comment by phlax** [comment]
This issue can be seen here:

http://mozilla.locamotion.org/af/firefox/browser/defines.inc.po

...by reloading the page with the sidebar collapsed.

tested on chrome 44.0.2403.89 , iceweasel 39.0

**Comment by dwaynebailey** [comment]
@phlax nice catch, I've seen that before.  Glad to see you manage a fix also :)
