### ISSUE TITLE
Suggested AMAGAMA_URL does not work over https

### ISSUE THREAD

**Issue by xperseguers** [translate/pootle#3983]
Suggested (default) value is:

```
AMAGAMA_URL = 'http://amagama.locamotion.org/tmserver/'
```

But when an instance of Pootle is running over SSL (which is more and more a must have nowadays for any website), it leads to errors of type "Unknown error" while translating.

Debugging the AJAX requests gives that:

```
Mixed Content: The page at 'https://translation.typo3.org/da/TYPO3.core.backend/translate/locallang.1415814785.xlf#filter=incomplete&unit=3392329' was loaded over HTTPS, but requested an insecure script 'http://amagama.locamotion.org/tmserver/en/da/unit/?source=List%20topics%20only&jsoncallback=_jsonp3392329'. This request has been blocked; the content must be served over HTTPS.
jsonp @ editor.min.97cd4148.js:188
PTL.editor.getTMUnits @ editor.min.97cd4148.js:499
PTL.editor.ready @ editor.min.97cd4148.js:439
jQuery.event.dispatch @ common.min.c38521
cd.js:183elemData.handle.eventHandle @ common.min.c38521cd.js:151
jQuery.event.trigger @ common.min.c38521cd.js:174
(anonymous function) @ common.min.c38521cd.js:223
jQuery.extend.each @ common.min.c38521cd.js:35
jQuery.fn.jQuery.each @ common.min.c38521cd.js:11
jQuery.fn.extend.trigger @ common.min.c38521cd.js:223
PTL.editor.reDraw @ editor.min.97cd4148.js:464
PTL.editor.displayEditUnit @ editor.min.97cd4148.js:464
$.history.init.unescape @ editor.min.97cd4148.js:426
implementations.hashchangeEvent.check @ editor.min.97cd4148.js:5
jQuery.event.dispatch @ common.min.c38521cd.js:183
elemData.handle.eventHandle @ common.min.c38521cd.js:151
```

By trial and error with the certificate used on locamotion.org, I found this a few days ago:

The switch to https for the amagama server can be changed by overriding from `60-translation.conf`:

```
#AMAGAMA_URL = 'http://amagama.locamotion.org/tmserver/'
AMAGAMA_URL = 'https://amagama-live.translatehouse.org/api/v1/'
```

However this does not work anymore since DNS has been removed in the mean time.

Please switch to https for this server or explain how to *reliably* use https to get suggestions.

**Note:** this bug has been first reported and analyzed on https://forge.typo3.org/issues/68745

**Comment by xperseguers** [comment]
Since I reported the problem, this URL seems to be working again:

https://amagama-live.translatehouse.org/api/v1/en/da/unit/?source=Default%2C%20Subnavigation%20Right%20and%202%20Columns&jsoncallback=_jsonp3748284

Was it only a temporary problem? The API URL seems to be correct when reading the doc from http://docs.translatehouse.org/projects/amagama/en/latest/

**Comment by julen** [comment]
There have been DNS issues with TranslateHouse domains over the weekend, which are now working again.
