### ISSUE TITLE
I get pkg_resources.DistributionNotFound when running pootle

### ISSUE THREAD

**Issue by francescortiz** [translate/pootle#3986]
I get pkg_resources.DistributionNotFound when running pootle.

    $ pootle
    Traceback (most recent call last):
    File "/home/bicconfigurator/apps/pootle/.ve/bin/pootle", line 5, in <module>
        from pkg_resources import load_entry_point
    File "/home/bicconfigurator/apps/pootle/.ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
        working_set.require(__requires__)
    File "/home/bicconfigurator/apps/pootle/.ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
        needed = self.resolve(parse_requirements(requirements))
    File "/home/bicconfigurator/apps/pootle/.ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: rq>=0.5.0

rq is installed and in version 0.5.4. Installing rq version 0.5.0 does not solve the situation.

**Comment by julen** [comment]
Make sure it's installed in your virtualenv, not system-wide.

**Comment by francescortiz** [comment]
It is installed in my virtualenv:

    $ which pootle
    /home/<username>/apps/pootle/.ve/bin/pootle

**Comment by julen** [comment]
What does
```
$ workon pootle
(pootle)$ pip freeze --local | grep rq
```
return?

**Comment by francescortiz** [comment]
I installed virutalenvwrapper, run "mkvirtualenv pootle", "workon pootle" "pip install pootle".

Now pootle works correctly. I don't know what difference it makes, seems that using virtualenvwrapper was the solution. If virtualenvwrapper is mandatory then the installation documentation is outdated. If not tell me what can I do to help.

**Comment by julen** [comment]
No, virtualenvwrapper is not mandatory and it's just a handy wrapper around virtualenv, so nothing is different under the hood.

Everything points in the direction that your deps where out of Pootle's virtualenv.

**Comment by francescortiz** [comment]
Is there anything I can do in order to check/fix what was wrong?

**Comment by jleclanche** [comment]
This is probably the same as #3980

**Comment by ngkabra** [comment]
I still have this exact problem.
I did a clean install: 

    $ python2.7 -m virtualenv --no-site-packages ~/.v/pootle
    $ source ~/.v/pootle/bin/activate
    $ pip install --upgrade pip
    $ pip install Pootle

The Pootle installation goes smoothly. Does not give any error messages. No warnings either. No interruptions. But `pootle --version` gives the same error.

Here is the output of `pip freeze --local`:

    click==6.7
    cssmin==0.2.0
    diff-match-patch==20121119
    Django==1.7.11
    django-allauth==0.25.2
    django-assets==0.11
    django-contact-form==1.0
    django-overextends==0.4.1
    django-redis==4.4.3
    django-rq==0.9.0
    django-transaction-hooks==0.2
    elasticsearch==1.6.0
    lxml==3.6.0
    oauthlib==2.0.2
    Pootle==2.7.6
    python-openid==2.2.5
    redis==2.10.5
    requests==2.13.0
    requests-oauthlib==0.8.0
    rq==0.5.6
    six==1.10.0
    sphinx-me==0.3
    translate-toolkit==1.13.0
    urllib3==1.20
    webassets==0.11

As you can see, rq is installed, and it is in the virtualenv, and it is the correct version. Pootle is also installed in the virtualenv. 

And finally pootle is also the correct pootle:

    $ which pootle
    ~/.v/pootle/bin/pootle

Any ideas what's going on?

**Comment by ngkabra** [comment]
For what it's worth, I managed to get Pootle working by first downgrading virtualenv to version 1.10.1, then creating the virtualenv, installing pip, not upgrading it to the latest pip (I don't know if this step is necessary), and then installing Pootle. Worked like a charm. (But surely this is just a temporary hack...)
