### ISSUE TITLE
get_submission_message has been removed breaking refresh_stats

### ISSUE THREAD

**Issue by phlax** [translate/pootle#3987]
It seems as though `get_submission_message` has been replaced by `get_submission_info`

This breaks `refresh_stats` which still uses `get_submission_message`

**Comment by julen** [comment]
This is sort of *intentional*, as already commented by @ta2-1 (https://github.com/translate/pootle/issues/3835#issuecomment-131772621). So I wouldn't worry about fixing `refresh_stats`, but rather getting rid of the old implementation. Hence this is a non-issue I'd say.

**Comment by phlax** [comment]
yep ok - but lets get rid of old refresh_stats then as it no longer works

**Comment by julen** [comment]
Already mentioned in https://github.com/translate/pootle/issues/3548#issuecomment-131783716.
