### ISSUE TITLE
Show stats for disabled projects

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3997]
Right now, when admin disables a project and then goes to the project browser page, the stats are no longer shown (we only see dashes). There's no reason to do that. We need to display disabled projects to admins only, and show the banner telling that the project is disabled (as we do now), but otherwise we need to render disabled projects in the same way as regular ones, and allow drilling down into translation projects, folders, stores, and even open units for translation.

See my comment that explains how we should treat disabled projects: https://github.com/translate/pootle/issues/3530#issuecomment-132747404

**Comment by julen** [comment]
This is not an UI issue: if the data was there it'd be displayed. The problem is these stats are not being calculated, so it's a regression in `refresh_stats_rq`.

**Comment by iafan** [comment]
Not exactly: the project was there (as an active one), and it had all the stats. Once I marked it as a disabled, all its stats were gone. So it's not about stats not being calculated, it's rather about stats being immediately deleted or simply not displayed.

**Comment by julen** [comment]
Yes that's valid as you mentioned in the original report. My point was that missing data is the cause that leads to not displaying these stats.

So in fact, there are several issues here:
1. `refresh_stats_rq` ignoring disabled projects on its processing.
2. Disabling a project wiping out existing stats.

@ta2-1 also mentioned that when disabled projects are processed in `refresh_stats_rq`, stats from stores are not properly populated to TPs.
