### ISSUE TITLE
Issues in activation link sent by pootle

### ISSUE THREAD

**Issue by sarfrajimpinge** [translate/pootle#3998]
I have installed pootle on production server and I am starting server using `pootle start` . I have used reverse proxy to open up from `8000` to `80`. and I can access it with my domain let say `example.com` but the activation link pootle sends when ever a user signup it send it to local-host ip i.e., `127.0.0.1 `

```
A Pootle account has been created for you using this email address.
To activate your account, follow this link:
     http://127.0.0.1:8000/accounts/confirm-email/9qflyt6rnal1rvjqwoccmtquz4vxwze2p0oqqep5sziotxk8u10es0pbexjlxflr/

This message is sent to verify that the email address is in fact
correct. If you did not want to register an account, you may simply
ignore the message.
```
Now I don't know if I am able to access pootle from my domain then why it is sending activation emails from `127.0.0.1`

Any setting I need to configure ?

**Comment by phlax** [comment]
You need to configure the EMAIL_* settings.

Assuming that you are using "./pootle/settings/90-local.conf" for your custom settings, you can set them there.

**Comment by julen** [comment]
This is an issue in the **web server** configuration, as it needs to let the app-server know what the actual host is, and not use the local one.

For nginx + uWSGI the right settings are the following:
```
    uwsgi_param   Host                 $http_host;
    uwsgi_param   X-Real-IP            $remote_addr;
    uwsgi_param   X-Forwarded-For      $proxy_add_x_forwarded_for;
    uwsgi_param   X-Forwarded-Proto    $http_x_forwarded_proto;
```

You should be able to find the right configuration settings for your specific setup elsewhere on the Internet.

**Comment by sarfrajimpinge** [comment]
@julen  I am using apache as web server , below are my config file settings (pootle.conf)


```
<VirtualHost *:80>
ProxyPreserveHost On
ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / ** my domain  **

  ServerName ** my domain  **
  ServerAdmin ** my admin**

  DocumentRoot /dev/pootle

  SetEnv HOME /dev/pootle

#  WSGIDaemonProcess weblate user=pootle group=pootle processes=1 threads=15 home=/var/opt/weblate display-name=pootle python-path=/dev/pootle
 # WSGIProcessGroup weblate

  <Directory /usr/lib/python2.7/dist-packages/django/contrib/admin/static/admin/>
      Order deny,allow
      Allow from all
  </Directory>
  <Directory /dev/pootle>
      Order deny,allow
      Allow from all
  </Directory>
 # <Directory /opt/weblate/weblate/examples/>
  #    Order deny,allow
     # Allow from all
  #</Directory>

  WSGIScriptAlias / /dev/pootle/wsgi.py
  WSGIPassAuthorization On
  <Directory /dev/pootle>
      <Files wsgi.py>
      Order deny,allow
     Require all granted
      </Files>
  </Directory>
</VirtualHost>
```

**Comment by julen** [comment]
It's been a while since I have managed an Apache server, but I'd say you need to set the [`ProxyPreserveHost`](http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost) directive.

**Comment by sarfrajimpinge** [comment]
@julen yes but as you can see I have already mentioned ProxyPreserveHost directory

**Comment by julen** [comment]
Alternatively you can remove `ProxyPreserveHost On` and instead set [`USE_X_FORWARDED_HOST = True`](https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-USE_X_FORWARDED_HOST) in your Pootle/Django settings. This will instruct Django to read the actual host from the `X-Forwarded-Host` header, as opposed to the default `Host`. Note this header is set by the `ProxyPass` directive, provided you enabled the `mod_proxy_http` module.

Don't forget to reload the affected servers for any new changes to be picked up.

**Comment by neerajd-impinge** [comment]
@julen Thanks it works for me

**Comment by sarfrajimpinge** [comment]
@julen  Thanks it works for me
