### ISSUE TITLE
Add a CONTRIBUTING page to Pootle Github project

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3999]
We have the CONTRIBUTING page @jleclanche suggested and also examples such as [this](https://github.com/skidding/cosmos/blob/master/CONTRIBUTING.md)

This bug is to track the review and massage of those to build our own Pootle CONTRIBUTING page.

**Comment by unho** [comment]
Note that we already have http://docs.translatehouse.org/projects/pootle/en/latest/developers/contributing.html despite is not quite visible.

**Comment by julen** [comment]
The benefit of `CONTRIBUTING` is that [it's clearly visible](https://github.com/blog/1184-contributing-guidelines).
