### ISSUE TITLE
A cool feature to add for dual lines or more

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4001]
Is it possible to add a feature where Pootle scan each line collected in its database in order to find lines having the same exact content?? I mean i have 4 lines having "This is a test". When the user is going to translate the first one, it would appear next to "Needs work" another tickbox (named: "We found other <<NUMB>> exact lines in DB, do you want to translate them?) where the user is free to check or uncheck and then make Accept or Suggest. Is it possible?

**Comment by dwaynebailey** [comment]
We have thought of a feature like this before but have rejected it in the past for the simple reason that in most cases duplicate strings require that the translator understand the context in which the string occurs.

I think we solve it in a better way at the moment which is this. Once you have translated a string it populates the local translation memory.  If Pootle has a 100% match when editing a unit the translation is supplied by translation memory with the ability of translator to make changes as needed.

This solutions gives similar speed, but prevents population which could be risky without context.  Our feeling is that this is the safer and more reliable approach.

**Comment by JohnnyKing94** [comment]
Perfect, that's what i meant... only 100% the same... i mean

"This is a test" and "This is a test" NOT "This is a test" and "This is a test. NO comment allowed."

Only in the first case, when will i see this feature available? I really need it for my project... thx ;)

**Comment by unho** [comment]
It is already available in the latest stable version. You just need to set it up. See http://docs.translatehouse.org/projects/pootle/en/stable-2.7.0/features/translation_memory.html#elasticsearch-based-local-tm for more info.

**Comment by JohnnyKing94** [comment]
Actually i can't set it up at the moment, is there a 2.7.0 demo available where i can test this feature how works?
