### ISSUE TITLE
2.5.1.3 --> 2.7.0 migration issues

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4007]
After doing a clean install of 2.5.1.3 on debian wheezy, i followed the docs to migrate to 2.7.0

The steps i was following:
```
pip install --upgrade "Pootle>=2.6,<2.7"
pootle setup
pip install --upgrade Pootle
pootle check
pootle migrate
cd $pootle_dir/pootle/static/js/
npm install
npm update
pootle webpack
pootle collectstatic --noinput --clear -i node_modules -i *.jsx
pootle assets build
pootle createsuperuser
```

These are some of the issues that i found:

  - 2.5 expects python 2.6, but 2.7 requires python 2.7 - but there is no mention of upgrading python/virtual environment etc
  - pip prob needs to be upgraded - should be mentioned
  - installing system software only required by 2.7 is not mentioned:
    - redis-server
    - npm
  - on debian wheezy/oldstable you need redis-server and npm from backports
  - Install works until 2.6.0 install
     - warning could be more explicit "you must now upgrade to pootle 2.7.0"
  - docs should say start pootle rqworker now
  - ~~running pootle_check it fails rather than checks (touch #4006)~~
    - ~~django.core.exceptions.ImproperlyConfigured: Pootle requires a Redis-backed caching backend for 'stats' with `TIMEOUT: None`. Please review your settings.~~ fixed in #4054 
    - ~~Let's maybe add a check which says
      "...Pootle 2.7 requires a Redis caches to be set in CACHES Hint: remove or update CACHES setting in your pootle.conf" or similar~~
  - ~~running pootle migrate for 2.7 fails with~~:
      - ~~django.db.utils.OperationalError: table "accounts_user_alt_src_langs" already exists~~
    - ~~i can get past that with pootle migrate accounts --fake, but then i get~~:
       - ~~django.db.utils.OperationalError: no such column: pootle_app_translationproject.disabled~~
    - ~~which can also be gotten past with pootle migrate pootle_translationproject --fake~~
- **to migrate to 2.7.x you have to run** : 
```
    pootle migrate accounts 0002 --fake
    pootle migrate pootle_translationproject 0002 --fake
    pootle migrate
```
  - ~~starting the server i get (touch #4033 #4034)~~:
       ~~"ResponseError: wrong number of arguments for 'set' command"~~
    - ~~this was due to outdated Redis~~
    - ~~hint in checks should say what min version of redis is and be critical~~
  - ~~i then have to verify my account - this could perhaps be automated for existing accounts  (touch #4020)~~ added
  - ~~i use createsuperuser but that just creates another unverified account (touch #4035)~~
  - ~~login hangs when trying to send email (touch #3796, #3448)~~ not if debug=False
    - quote user in \#pootle this morning:
      "Hello. I'm trying to run Pootle on my laptop but I'm ending with "Connection refused" error after clicking the "Sign in" button in the "Sign in" window"
  - after logging in:
    - clicking on translationproject pages gets 404 <-- only on sqlite
    - refresh_stats needs to be run

**Comment by julen** [comment]
> * running pootle_check it fails rather than checks

The points mentioned here are #4006 basically.

> * i then have to verify my account - this could perhaps be automated for existing accounts

It really depends on the nature of your existing DB, as duplicate email addresses could slip in in the past, but not anymore.

> * login hangs when trying to send email

This is #3448.

**Comment by phlax** [comment]
@julen 

>>        i then have to verify my account - this could perhaps be automated for existing accounts

> It really depends on the nature of your existing DB, as duplicate email addresses could slip in in the past, but not anymore.

re duplicates i think the migration would fail as i believe a unique constraint has been added (ill have to check this) but ill try and test with dupe emails

re verification

if we add a ```verify_user``` command we could make that an optional step for the migrator - they could either ```verify_user admin``` or potentially ```verify_user *``` to verify all

**Comment by phlax** [comment]
@julen 

>>        i then have to verify my account - this could perhaps be automated for existing accounts

> It really depends on the nature of your existing DB, as duplicate email addresses could slip in in the past, but not anymore.

re duplicates i think the migration would fail as i believe a unique constraint has been added (ill have to check this) but ill try and test with dupe emails

re verification

if we add a ```verify_user``` command we could make that an optional step for the migrator - they could either ```verify_user admin``` or potentially ```verify_user *``` to verify all

**Comment by phlax** [comment]
>>        login hangs when trying to send email

>> This is #3448.

Yep i hadnt been able to reproduce it until now
