### ISSUE TITLE
Display errors in the auth UI for unhandled exceptions

### ISSUE THREAD

**Issue by julen** [translate/pootle#4013]
Unhandled exceptions are processed by the [`errorpages` middleware](https://github.com/translate/pootle/blob/8e58b1c10b6ef0876ef606358792cd16ae779a4c/pootle/middleware/errorpages.py), and these either return an error page for ordinary requests, or a simple JSON-serialized string describing the catched error (`{"msg": "<error-body>"}`).

When it comes to the authentication UI, this only accounts for errors returned by allauth, which have the `{"errors": {"__all__": "<generic-error>", "<field-name>": "<field-specific-error>"}}` shape. So the auth UI also needs to consider the unhandled exceptions, otherwise there will be no UI feedback under some circumstances.

**Comment by unho** [comment]
Related #3448.
