### ISSUE TITLE
No error feedback when managing suggestions

### ISSUE THREAD

**Issue by veer66** [translate/pootle#4018]
I cannot remove my own suggestion even though I click at the red-white cross. 
![Image Screen Capture](http://file.8fold.in/pic/remove_suggestion.png)

**Comment by thanyawzinmin** [comment]
Yeah I got that sometimes.

**Comment by arky** [comment]
+1 
Confirming the problem. Really hard to reproduce.

**Comment by dwaynebailey** [comment]
@veer66 do you have a link to that unit

@arky are you able to supply steps to produce?

**Comment by veer66** [comment]
Here is the ink http://mozilla.locamotion.org/th/firefox/translate/shared/#filter=untranslated&unit=18316198

**Comment by julen** [comment]
I think this is because you do not have review rights. Are you able to check the network response and its payload?

I just checked that the UI doesn't display the error to the user on the other hand..

**Comment by julen** [comment]
I can confirm this is a permissions issue (I see 403 responses on the server logs), and I can reproduce it locally. The permissions issue is on the locamotion side, so I'll hijack this issue to ensure we display a message to users.

**Comment by julen** [comment]
I was testing more after fixing the UI issue and indeed self-reviewing own suggestions when a user doesn't have `review` rights doesn't work as expected. I have filed #4021 to track that.

**Comment by thanyawzinmin** [comment]
Right you can't remove your own suggestions if you does't have a reviewer access.
