### ISSUE TITLE
Feature requests: customize sanity checks on a per-locale basis

### ISSUE THREAD

**Issue by Jobava** [translate/pootle#4031]
1. Add language-specific rules that can override some global sanity checks. For example, Romanian quotes are like „this” and „something «like» this” and sometimes we also have to put quotes around terms that are unquoted in English, this triggers the 'quotes matching' and the 'double-quote' rule.

2. Related: per-language specific regexes or parsing rules for: common mistakes, terminology violations, style and tone, common formulas etc.

**Comment by julen** [comment]
This is already implemented as part of the TTK quality checks. If you have specific requirements for a language I suggest you [file an issue in TTK](https://github.com/translate/translate/issues/new) or create a PR with the proposed improvements.
