### ISSUE TITLE
Make redis version check CRITICAL

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4033]
If the redis version is not sufficiently recent the site will fail.

Currently there is a CRITICAL check for the presence of redis, but the version check is only a WARNING - i think it should be CRITICAL

The hint should also say what the minimum redis version is

**Comment by dwaynebailey** [comment]
I think the issue is that its a little unclear on what the actual minimum would be.

But address the fact that the code still has it as a ``.Warning`` instead of ``.Critial`` and I'm lgtm.
