### ISSUE TITLE
Disabled projects overlaps sidebar

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4040]
CSS is placing disabled projects above sidebar in firefox - not in chrome - needs to have z-index reduced most likely

**Comment by dwaynebailey** [comment]
@iafan this shows the text overflowing into the sidebar http://linode2.locamotion.org:8000/ar/firefox/

**Comment by phlax** [comment]
@dwaynebailey that link isnt showing the problem for me

are there any disabled projects on that page?

when we triggered the problem it was only the disabled projects that had it

**Comment by phlax** [comment]
it also might have been caused by the fooed html in the sidebar

**Comment by unho** [comment]
It would be great to have some screenshot.

**Comment by iafan** [comment]
> http://linode2.locamotion.org:8000/ar/firefox/
The link above doesn't work
