### ISSUE TITLE
2 bugs in 2.7.0

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4043]
Since you suggested me to update Pootle to the newever version several days ago (2.7.0, no git version), so i did, but i keep having the same problem plus one more:

- Pootle keeps spamming my `error.log` in Apache with those two lines: 
```
[Wed Sep 09 10:17:33 2015] [error] 2015-09-09 10:17:33,541 INFO Loading custom settings from '/my/path/pootle.conf'...
[Wed Sep 09 10:17:33 2015] [error] 2015-09-09 08:17:33,858 INFO Using Python PO
[Wed Sep 09 10:17:46 2015] [error] 2015-09-09 10:17:46,998 INFO Loading custom settings from '/my/path/pootle.conf'...
[Wed Sep 09 08:17:47 2015] [error] 2015-09-09 08:17:47,316 INFO Using Python PO
```

It is like every web user who is trying to connect to the website, Pootle loads up every time the conf... and i don't know if it's right since all my `error.log` is full of this

- Despite I disabled the contact form, it keeps showing on the "Sign in" form, on the bottom of this form.

**Comment by unho** [comment]
Thanks for reporting. Next time please file two separate issues since it helps keeping unrelated errors separate.

I have no idea why you get the first error. Have you tried truncating the `error.log` to see if this message keeps appearing?

Can you share a screenshot for the second error. I am not sure I fully understand your description.

**Comment by JohnnyKing94** [comment]
- These errors appears only if someone access to this pootle site.. and it keeps appearing since the clean installation i did: https://dl.dropboxusercontent.com/u/89718989/ESO/Pootle/bandicam%202015-09-09%2011-10-20-829.jpg
It's like if everytime the Pootle tries to load the site
(Do not look the errors of "Exception AttributeError" these are caused forma  Redis-server problem and it's already been reported to them :) )
- This is the image you asked for: https://dl.dropboxusercontent.com/u/89718989/ESO/Pootle/bandicam%202015-09-09%2011-08-58-032.jpg
I disabled the contact form from pootle.conf and i don't know if it's a bug, the only place where it appears is in the Sign in form

**Comment by dwaynebailey** [comment]
@JohnnyKing94 and @unho I'm going to close this issue and open two individual ones as we can't handle two completely different issues in one bug, its insane.
