### ISSUE TITLE
Contact form link appearing in Sign In popup despite being disabled

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4046]
Breaking out reports from #4043 by @JohnnyKing94 into individual bugs

Despite I disabled the contact form, it keeps showing on the "Sign in" form, on the bottom of this form.

**Comment by unho** [comment]
This most likely is https://github.com/translate/pootle/blob/4c64bd58/pootle/static/js/auth/components/AuthWindow.js#L18-L24 being rendered unconditionally.
