### ISSUE TITLE
merge_user should also remove the old user

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4059]
Currently ``merge_user`` does not actually remove the old user.  You need to run ``purge_user`` following ``merge_user`` to completely remove the user.  This is dangerous and error prone, especially on older instances that have a large number of users.

**Comment by dwaynebailey** [comment]
Currently I've scripted the following to work around this problem:

```bash
#!/bin/bash

if [ $# -ne 2 ]; then
        echo "$(basename $0) from_user to_user"
        exit 1
fi

from_user=$1
to_user=$2

./manage.py merge_user $from_user $to_user && ./manage.py purge_user $from_user
```

**Comment by phlax** [comment]
@dwaynebailey i didnt add this because i can see a situation where you dont want to delete the user when merging.

How about we add a "--delete" flag to delete when merge has completed?

**Comment by dwaynebailey** [comment]
@phlax could you elaborate the situation where you don't want to delete the user?  I'd do the inverse of ``--delete``, that is by default purge the $from user and with an option, don't delete her.  I think the use case to remove the user is much more likely than the other.  Though I can't think of a reason to keep the user if you've just removed all their contributions.

**Comment by iafan** [comment]
+1 that this is an issue. By default, the merged user should be deleted. You may want to add an option *not* to delete the user, like `--leave`, but I'm not sure in which situations this will be useful. Mind elaborating?

**Comment by iafan** [comment]
Haha, wrote the same thing as @dwaynebailey )

**Comment by phlax** [comment]
hi @iafan @dwaynebailey - the use case i imagined is that you want to copy over profile info or perhaps permissions - as these are not currently dealt with.

The other use case i had in mind was in relation to an idea that @dwaynebailey mentioned of being able to set times between which you want to merge data - eg if someone had been borrowing someone elses account.

I can see the consensus is with making deletion the default option so ill add that in - and i reckon add a `--no-delete` option to keep the user object

**Comment by iafan** [comment]
I think these cases should be dealt separately: if you want to only copy permissions, I'd go for a separate explicit command for that. If you want to shift attribution from one user to another for work done within certain time range, I'd go with a separate command as well. Internally these commands might share common merging code, but the front-facing CLI syntax will be different. It's better than use just one management command with obscure options. With that approach, there's no need for --delete or --no-delete, and the merge command will always do what it was supposed to do — merge two users into one without leaving any traces of the old user.

**Comment by julen** [comment]
Funny this issue was already [raised in the review](https://github.com/translate/pootle/pull/4002#issuecomment-137703972).

> I'd go for a separate explicit command for that

In general I don't believe it's necessary to bloat Pootle with so specific once-off commands.

> the use case i imagined is that you want to copy over profile info or perhaps permissions (also maybe alt_src_languages?) - as these are not currently dealt with.

I already raised this in the review, in fact, that's what I'd expect from a `merge_user` command.
