### ISSUE TITLE
False positive in `check_duplicate_emails`

### ISSUE THREAD

**Issue by julen** [translate/pootle#4071]
The newly-introduced `check_duplicate_emails` check goes through all users without excluding users that are fine to have *empty* or invalid email addresses (*nobody* and *default*), hence resulting in a false positive test.

**Comment by phlax** [comment]
hi @julen 

The problem was that we would like to make User.email unique (see #4035) - and im not entirely sure how to handle these system users.

Perhaps for now we should just exclude them from this check.

**Comment by julen** [comment]
That's what I suggest, either use `hide_permission_users()`, or `hide_meta()` if the *system* user can be taken out as well.

**Comment by unho** [comment]
IMHO *system* user should be left out as well.
