### ISSUE TITLE
Fix translatable strings after 2.7.1 release

### ISSUE THREAD

**Issue by unho** [translate/pootle#4074]
- Reapply commit 3c87d1a0
- Make translatable this string https://github.com/translate/pootle/blob/324684b9/pootle/apps/accounts/views.py#L36-L37

**Comment by julen** [comment]
Also there's a typo in https://github.com/translate/pootle/blob/6402166018b35246d87afa1b8dba0c52e19b5552/pootle/static/js/admin/components/UserForm.js#L52: s/*eg comments*/*e.g. comments*/
