### ISSUE TITLE
Priority sorting has random file order where it should be alphabetical

### ISSUE THREAD

**Issue by julen** [translate/pootle#4079]
In a server with vfolders, when clicking on an incomplete count, it automatically sets the priority sorting to the editor view. The sorting, in turn, exposes units in a very illogical way: sorted by priority but scattered across files. This results in totally confusing surrounding units.

See an example in the following screenshot — note all units in there have *1.0* priority.
<img width="581" alt="weird_priority" src="https://cloud.githubusercontent.com/assets/16768/9954920/2d575ada-5ded-11e5-9e3d-551ffd93abcf.png">

**Comment by dwaynebailey** [comment]
Just to be clear this is what we want:

1) Sort on priority
2) Then sort on directory and files in alphabetical order.

**Comment by unho** [comment]
This can be seen live in http://mozilla.locamotion.org/eu/firefox/translate/dom/#filter=all&sort=priority&unit=8708523
