### ISSUE TITLE
Clear old failed jobs

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4080]
I made a new installation with 2.7.1 after it came out and everything works great, but as usual i remove the project "tutorial" and "terminology" from the admin panel along with the folders. For such strange reason, i keep having failed jobs which if i run `pootle retry_failed_jobs` keeps returing to failed since they respond to project they no more exist. I was reading on internet that i'm able to clear these failed jobs using the rq-dashboard, since you even mentioned in the docs: http://pootle.readthedocs.org/en/latest/server/rq.html

But with the rq-dashboard i cannot find the rq worker and none of his jobs (failed/queued). Through pootle i can see the RQ worker is running, but not through rq-dashboard, if i run "rqworker", the rqdashboard detects it, but not pootle. so i figured it out they use different code or something.

But i still need to clean OLD failed jobs that i don't need anymore. How is possible to solve this?
(I have 78 failed jobs, despite i made a new installation, they're the same number of the old installation used before of it... i tried to restart the `pootle rqworker`, redis, the system... nothing changed, always 78) :(

**Comment by dwaynebailey** [comment]
You need to point rq-dashboard to the correct queue, which is 2 on Pootle.

**Comment by JohnnyKing94** [comment]
How do i do that? this is not mentioned anywhere

**Comment by julen** [comment]
Of course that's only mentioned where it belongs, in [rq-dashboard docs](https://github.com/nvie/rq-dashboard).

**Comment by JohnnyKing94** [comment]
I read everything but there's no reference how to config/point the queue... there's a bunch of commands to use on how to point to the http server, to the port and other stuff.. but no references on how to change the queue to "2". Unless, i need to point on some http server, pls tell me which ports, which https etc

**Comment by JohnnyKing94** [comment]
Ok maybe i found out, just for having a confirmation, the queue is related to the redis DB?? if i set as integer the number "2" as the redis db value for Pootle, would it be correct? right?

**Comment by julen** [comment]
I have no experience with rq-dashboard but changing the DB number should be enough.

**Comment by JohnnyKing94** [comment]
Ok i resolved it, i just leave the answert to other users who needs to know
There are 2 options, the CLI mode (as described on Pootle docs) and via dashboard (more cool, with traceback of errors),

CLI MODE
# Run this commands on a terminal
```redis-cli -n 2 lrange rq:queue:failed 0 -1 #the first one show all your failed jobs
redis-cli -n 2 flushdb #the second one removes all the failed jobs```

RQ-DASHBOARD
# Just create a screen on the terminal and run this command if you need to point the dashboard to the right DB
```screen -dmS rq-dashboard rq-dashboard --redis-database 2```

And that's all ;)
