### ISSUE TITLE
Issue with the pot template of the language

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4081]
I was using my own version of italian language translated, then i checked the .pot template was updated, so i updated my own version with the source .pot file. After the successful edit, i found out, you removed from "pootle_js" the "All Projects" line, when the words All Projects still exist in the home of Pootle. So i inserted the line manually and boom the translation of the line on my site returned to be normal. I suggest to check the templates and see if they're totally okay :)

Keep the good work ;)

**Comment by JohnnyKing94** [comment]
Another feedback, missing the line "Entire Project", here's the image: https://dl.dropboxusercontent.com/u/89718989/Pootle/bandicam%202015-09-20%2014-38-04-559.jpg

I added manually and now it's ok :)

**Comment by unho** [comment]
Thanks for the heads up. Just confirmed that these two strings are indeed missing, but they should be there. After some research I found another string is also missing, so it is better to list all the ones that are missing:

- All Languages
- All Projects
- Entire Project

all of them come from https://github.com/translate/pootle/blob/master/pootle/static/js/browser.js#L163-L170

**Comment by JohnnyKing94** [comment]
Another feedback, missing the line "reviewed", here's the image: https://dl.dropboxusercontent.com/u/89718989/Pootle/bandicam%202015-09-21%2014-05-03-161.jpg

And i checked later, even the lines "translated", "suggested", "edited", "marked as fuzzy" and others are missing. I tried to add manually on pootle file (not the js), but nothing changed, the translation still remains in english.. i think it's changed something here

**Comment by JohnnyKing94** [comment]
I would like to translate the words of the report email, if you could integrate this kind of template on the po file, it would be amazing

```
Unit: (url_string)

Source: (source_string)

Current translation: 

Your question or comment:
```

Thx in advance ;)

**Comment by dwaynebailey** [comment]
Just a gentle please.  Don't mixup a bug with a request for a feature.  If you really really don't want me to randomly close bugs then please, one issue, one bugs.  This is now about three different issues.

**Comment by JohnnyKing94** [comment]
Ok i deleted the message and i open a new one, sorry ;)

**Comment by dwaynebailey** [comment]
Was tedious one to find.  But seems xgettext can still not extract JavaScript message.  This change should bring back the extraction 90483db307d6728f9560627e882fa5d83dc91469 and this template update 5a6bdbf9a4011b7e328d3b98130ee6a8d7dbb1fb brings back the strings originally spotted.

**Comment by JohnnyKing94** [comment]
Still not resolved... the lines "reviewed", "pre-translated" etc are not translated... i just updated the file as soon as you made this fix, i translated these lines, but still doesn't work... they're all the lines from "UserEvent.js"... i think the lines are ok, but something is blocking these lines to be translated
