### ISSUE TITLE
Last edit line on Static pages - public side

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4082]
Is it possible to integrate a "Last edit" line on static pages?? That would be great, i tried to add manually the code ```<time class="js-relative-date" title="{{ page.modified_on|dateformat }}" datetime="{{ page.modified_on.isoformat }}">&nbsp;</time>``` on the page, the output for the first seconds is correct, but then it remains stuck always to that line (a few seconds ago). It's probably cause it's called "static pages", so i'd rather bet this kind of edit needs to be made on the source code. If you add it, that would be great. Possibly leave an option to tell people on which page to activate or not.

**Comment by julen** [comment]
You'd need to ensure the JS code that re-evaluates relative times kicks in ([helpers.updateRelativeDates()](https://github.com/translate/pootle/blob/ccfbe0bead6deba1a0b90bc5f6d09728f60ff0e8/pootle/static/js/helpers.js#L28-L32)).

However use it at your own risk — we're slowly deprecating such a construct in favor of a truly encapsulated component.

**Comment by JohnnyKing94** [comment]
I'm not a big fan of javascript and i have no idea how to do such things, anyway, what kind of encapsulated component are you working on it? I'm curious :)

**Comment by julen** [comment]
The [`<TimeSince />` component](https://github.com/translate/pootle/blob/master/pootle/static/js/shared/components/TimeSince.js) takes over.
