### ISSUE TITLE
Translation of the Report Email

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4084]
I would like to translate the words of the report email, if you could integrate this kind of template on the po file, it would be amazing... naturally title of the email included, which it would be ```[(name-site)] Unit #(num) ((lang))```

```
Username: (username)
Current URL: (url)
IP address: (ip_address)
User-Agent: (user_agent)

Unit: (url_string)

Source: (source_string)

Current translation: 

Your question or comment:
```

Thx in advance ;)

**Comment by unho** [comment]
I don't think this is a good idea. I can imagine some scenario where a klingon translator sends a report, and then the manager has trouble to understand what the translator reported. But perhaps I am going too far.

**Comment by JohnnyKing94** [comment]
Why it should not to be a good idea?? The pootle adminastrator translates in the local language Username, Current URL, IP Address etc, so every admins that have access to the domain mail (eg report@domain.com) will read the report in the correct local language except for the source string :)

**Comment by iafan** [comment]
Emails should be translated in the preferred language of the receiver, not the sender. I believe the way Pootle currently works is it will use the language of the sender (and this is what Leandro is referring to and is trying to advise against).

**Comment by JohnnyKing94** [comment]
That's fine for me, but still i don't get it... the report email is different from the confirmation email sent to the private email box of the user who registered... the report email is something sent to the admin email account which needs to be in the language of the receiver??? who's the receiver in this case??? it's just a domain name not related to any users registered, how can you tell report@domain.com wants the email in the local language, if it's not the sender to tell that???

**Comment by iafan** [comment]
Receiver of the message is the admin/manager. I, as a manager, don't want to get reports in random languages from different translators, when I only understand one or two languages. Since Pootle doesn't know what language manager is capable reading in, English is the next best option.

**Comment by julen** [comment]
This is intentional, and others have already explained the reasoning behind this.

**Comment by JohnnyKing94** [comment]
Ok, i got the point, but if all the admins are from the same country and they know that specific language??? I mean, my pootle server is intended only for italian people, my admin team is composed of italians and the email box is accessible for them... so i mean, you point the logic to multi-country people, but i intend only my country... at least give us this option :(

**Comment by unho** [comment]
@JohnnyKing94 Then override https://github.com/translate/pootle/blob/285a7002d68ae05365b9036117ea050260451d54/pootle/templates/contact_form/contact_form.txt and https://github.com/translate/pootle/blob/63c5a1c0530536027d785485e39bb510a08e9beb/pootle/apps/contact/views.py#L21-L29 with your preferred translations.

**Comment by JohnnyKing94** [comment]
Ok thank you, much appreciated :)

**Comment by julen** [comment]
We could probably move https://github.com/translate/pootle/blob/63c5a1c0530536027d785485e39bb510a08e9beb/pootle/apps/contact/views.py#L21-L29 to a template file to allow easier overriding without anyone having to patch the source files.

**Comment by unho** [comment]
I agree.
