### ISSUE TITLE
.pot project file, how it works on pootle?

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4091]
I'm just trying to find some docs on your site about pot source file... with poeditor i usally update the po file with the source pot, if i do the same for pootle (uploading the pot file in the project folder) when there's a .po project already running, what happens in the case the pot file has new lines and need to update/remove others? Is it capable to do that pootle or not? If yes, how the strings already translated will be managed in the case the source string have changed?? The translations are going to be assigned to system user or not?

**Comment by julen** [comment]
As of today translation templates are only used to initialize new languages via the web interface. Other than that, you should update your localization files against the latest templates out of Pootle:

1. `sync_stores` to retrieve latest state of translations to disk,
2. Merge any new strings into existing localization files using your toolchain of choice (which depends on the file formats you intend to localize), and
3. `update_stores` to import the updated files into Pootle.

**Comment by JohnnyKing94** [comment]
But in the moment i merge, example the
- SOURCE
I'm Rob
-TARGET
Sono Rob

with the
- NEW SOURCE
I'm Rob Smith

and then i update with "update_stores", what happens to the target already translated "Sono Rob", it will be removed?? marked as fuzzy automatically??

and in the case i upload a localization file with updated targets and i merge these targets with the new ones i uploaded and then i update, what pootle does? all the lines that were before translated by users, are going to be assigned always to them with the new translations or they will be removed and assigned to system user??

This is what i'm trying to understand

**Comment by unho** [comment]
If you upload a translated file (not from disk, but using the UI) conflicts will be converted to suggestions that need to be reviewed, and new translations with no conflicts are accepted.

If you then want to update with new templates do as @julen told. `update_stores` will import the updated translations into Pootle overriding what is on Pootle.

**Comment by unho** [comment]
Sorry, `update_stores` only overwrites if you tell it to do so: http://docs.translatehouse.org/projects/pootle/en/latest/server/commands.html#update-stores
