### ISSUE TITLE
Bring back mute button for non-critical quality checks

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4098]
This request from Rhos, Welsh localisater on mlo _"Any chance of getting the mute button back on the Quality Checks? I prefer to be able to clear the deck so that I can see where I am and what's new."_

In losing the mute button for non-critical checks we made it less noisy and reduced the need to mute the non-critical checks.  But we also made it impossible for a translator to mark all false positives and address all issues in their translations.  Thus they can't actually perform a clean review of a particular issue.

I'd suggest we bring back the mute button for this instance, but ideally hide it for these tests unless the user hovers over the item.

**Comment by dwaynebailey** [comment]
@iafan need some UI input on this

**Comment by iafan** [comment]
Ok, let's try adding it back, hidden by default, shown on hover; when the non-critical check is muted, let's add .5 opacity style to it (so it will be not only gray, but semitransparent).
