### ISSUE TITLE
Revisit the supported markup formats

### ISSUE THREAD

**Issue by julen** [translate/pootle#4111]
In #3766 a flag was raised about the support of markup formats other than HTML.

As a reminder, Pootle currendly *kinda* supports the following markup flavors:

* HTML
* Markdown
* reStructuredText
* Textile

The last three are via setting + extra package + extra supporting app code.

It's very likely that HTML is the most widespread option among deployments, as it's the default and it requires zero configuration. I know some people are using Markdown as well. On the contrary, I don't know of any deployments using rST or Textile, TBH.

I'm bringing this up for discussion, as the code could potentially become simpler and it *might* be a good compromise to take based on the feedback.

**Comment by dwaynebailey** [comment]
From my perspective rST and Textile can go.  But I'm using Markdown on most of my installations as its simpler to write and less prone to errors.  But I'm not sure removing just those two makes code simpler.

One big issues is that the format is site wide, so you can't phase out support of any format on the site.  But you break all your content at once if you remove those.  Making content store both data and the chosen format would allow migration.

**Comment by julen** [comment]
Given the fact that at least HTML + Markdown is _required_, there's no extra simplification on taking rST and Textile out, so I'm closing this issue.
