### ISSUE TITLE
Switch mozilla.org translation repo from svn to github

### ISSUE THREAD

**Issue by pascalchevrel** [translate/pootle#4127]
Currently locamotion imports data from our svn repository for mozilla.org localization.

We are transitioning to GitHub and we would need Locamotion to pull data from our github repo instead as soon as you can:
https://github.com/mozilla-l10n/www.mozilla.org

Thanks

**Comment by dwaynebailey** [comment]
@pascalchevrel do you have a transition date.  Changing is relatively easy, but I just need to know when and plan some downtime for when I'm not travelling.

**Comment by pascalchevrel** [comment]
We could move to github at the end of the week if that's ok for you, basically everything is ready on our side, only locamotion is an unknown :)

**Comment by dwaynebailey** [comment]
@pascalchevrel safer for me to do this when I'm back.  Which is Thu.  So let me try to do this Fri. Its mostly just shifting my push and pull parts of scripts to Git commands instead of SVN.  Shoudn't be too much work.

**Comment by pascalchevrel** [comment]
ok sounds good, I can then tell localizers that the switch will happen over the week end and that starting next Monday we are on Github, Thanks!

**Comment by dwaynebailey** [comment]
@pascalchevrel I'm busy executing this as we speak.  Will take me a little bit of time to test, but I think you can safely announce the switch.

**Comment by pascalchevrel** [comment]
Cool thanks, I will make an announcement when all the tools and servers  are migrated (we are halfway, waiting for colleagues in the US to wake up to upgrade CI stuff and demo servers)

**Comment by dwaynebailey** [comment]
@pascalchevrel OK this is done from out side now.  I'm pulling templates from en-US in Git.  Since we aren't landing translations directly to the repo that landing part doesn't concern Pootle at this time.  So we're done.

**Comment by pascalchevrel** [comment]
awesome, thanks :)
