### ISSUE TITLE
A user can't download the terminology files from a Terminology project

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4129]
I know we switched off download of ``pootle-terminology.po`` files as they cause a number of problem mostly because there is no associated file.  But this seems to have extended to also include the 'Terminology' project.

I can't recall if at the time we decided it was an OK compromise.  But now with @phlax's work which means we can have non-existent files we should likely be able to bring this back. At the very least we shouldn't be disabling download of files within Terminology ad only restrict ``pootle-terminology.po``

**Comment by julen** [comment]
By reading #3937 it doesn't look like this is intended — the referenced commit is entirely prohibiting (or at least hiding) downloads from the terminology project.

**Comment by dwaynebailey** [comment]
The work on ``pootle_fs`` to break away from the need for a file on the filesystem should make it possible to revert the #3937 fix and get downloads of terminology back again.

**Comment by phlax** [comment]
@dwaynebailey ive re-enabled this and done a really quick ttw test to check it works ok.

Is there some special handling necessary for pootle-terminology.po?

I cant actually find that file in the default build
