### ISSUE TITLE
Ensure that searching in Pootle takes accelerators into account

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#413]
*Version: 1.0.2*

We have to test that searching in Pootle (with and without indexing) will
provide correct results in light of accelerators. The information can be
obtained for the project's checker style.

**Comment by dwaynebailey** [comment]
Marking this as the duplicate of #3805, mostly because this one still assumes indexing where new Pootle has no indexing so we don't need to consider that as part of the issue.
