### ISSUE TITLE
Drop --overwrite from update_tmserver

### ISSUE THREAD

**Issue by unho** [translate/pootle#4133]
We can just drop `--overwrite` if we hot-swap indexes using aliases. See https://groups.google.com/forum/#!topic/elasticsearch/tlmU_7kSrfg and https://www.elastic.co/blog/changing-mapping-with-zero-downtime

From https://github.com/translate/pootle/issues/4120#issuecomment-144801389

**Comment by dwaynebailey** [comment]
In all honestly I'm not sure I see the point.  We're swapping a clunky but easy to understand method with what I think is a more complex one for a tiny use case where honestly you need to be a ES expert to execute.

**Comment by unho** [comment]
Dropping this option will have several benefits:

- Will simplify usage of the command
- Will remove some hackery code with new code that will actually rely on Elasticsearch capabilities
- Will ease merge of `update_external_tmserver` and `update_tmserver`

**Comment by unho** [comment]
Closing this as I misunderstood the purpose of `-overwrite`. Will create new issues for hot-swapping indexes and reworking the `update_tmserver` command in a way it is easier to understand which is for each of the options it accepts.
