### ISSUE TITLE
Expand/collapse file/folder list in project

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#414]
*Version: 0.11*

*Originally posted by Clytie Siddall:*

Yes, here I am back trying to manage OpenOffice.org files on Pootle, this time the OpenOffice.org Pootle.

And the first thing I notice is that I'm going to spend a lot of time navigating down into directories and 
back up again, considering the heavily-embedded structure of the OpenOffice.org project.

My file browser expands and collapses listings. So does my FTP editor, my SVN interface and no doubt my 
Address Book and my dog.

Could we please have an expandable/collapsible file/folder listing on Pootle?

This could save a lot of time.

Also I hope you have time to work on that "last link visited" enhancement request I made last time I was 
wrestling with OOo on Pootle. That is needed in response to the same problem: deeply embedded files.

Thankyou for all your good work. :)

**Comment by unho** [comment]
@julen @iafan Is this fixed on core?

**Comment by julen** [comment]
Yep, the resources drop-down covers this use case.
