### ISSUE TITLE
Allow import attribution overriding

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4142]
When importing it is not possible to override the attribution given.
1. If using the UI the uploader will be attributed.  This is problematic if an admin is uploading a file on behalf of someone else.
2. When using `import` command the attribution is to the system user.  I had a case where I was resolving conflicts and wanted to attribute the author but couldn't.

This has two implementation needs:
1. Allow `--author` to be specified for the `import` command and use that for attribution.  If the user does not exist then fail.
2. If you have admin rights in the UI add a dropdown that allows you to select the user to attribute.  I'm not sure we need to track somewhat like Git with Author and Commiter.  Could be helpful for the timeline.

**Comment by dwaynebailey** [comment]
Lets aim to do the cli for 2.7.3, the UI can wait

**Comment by phlax** [comment]
i believe this is complete - @dwaynebailey ?

**Comment by dwaynebailey** [comment]
Upload from the UI will attribute correctly, and also allows admins to override attribution.
