### ISSUE TITLE
Remove warning for TM server's weight

### ISSUE THREAD

**Issue by julen** [translate/pootle#4143]
I have a single TM configured, that's all I want. Still, Pootle complains about missing weight, which is completely irrelevant and only adds noise.

```
System check identified some issues:

WARNINGS:
?: (pootle.W019) POOTLE_TM_SERVER['default'] has no WEIGHT.
	HINT: Set a WEIGHT for POOTLE_TM_SERVER['default'].
```

**Comment by unho** [comment]
Given that it defaults to `1.0` it is possible to just remove the warning. But the warning serves a purpose: let the user know that `POOTLE_TM_SERVER` is missing something, despite it is not a critical setting.

Would like to have feedback from other people before either removing the warning or closing as wontfix.

**Comment by dwaynebailey** [comment]
@unho gave the same feedback in the review.  Its pointless, we have a default and thus there is no reason even for a user to set this.  The warning is just noise here and should go.

**Comment by unho** [comment]
Removing it then.
