### ISSUE TITLE
Confirmation code page includes info on access rights

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#415]
*Originally posted by Clytie Siddall:*

I am quite alarmed by the number of supposedly interested people who have registered with Pootle for my 
language, but have never written to me for access rights. That means they have never actually been able 
to contribute, bar suggestions.

I think it is quite likely that most people _don't_ read the docs, and simply start trying to use the software.

I strongly suggest that the confirmation code page, which every registrant has to see, also contains 
something like (translated, of course):
___

Note: to protect our translations from unauthorized edits, new registrants can only _suggest_ translations. 
If you want to be able to translate via Pootle, you also need to send an email requesting access rights (and 
containing your full name and Pootle username) to:

[language admin name and address]
OR
see this URL
[general contact webpage, mailing list etc.]

Meanwhile, you can suggest translations, and get used to Pootle! Start here: [howto]
___ 

I think this will avoid a lot of people being discouraged because they can't edit translations, or because they 
have no idea what is going on.

As you have seen, there is a long list of Vietnamese translators on the Wordforge Pootle. Virtually all of 
them have never requested access rights, and have never been active. That is a critical waste of scarce 
volunteers.

I hope this is not awkward to implement.

Clytie

**Comment by julen** [comment]
Anything like this can be achieved by providing custom templates, closing.
