### ISSUE TITLE
Enable sorting by contribution in contributor command

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4153]
Currently contributors are sorted in alphabetical order.  This is great for crediting.  But it would be more helpful to allow sorting by contribution in cases where you want to use to list to make other decisions around the amount of contribution.

Thus add ``--sort-by-contribution`` and ``--sort-by-name`` options.

**Comment by unho** [comment]
What about using just `--sort-by` and passing a value to it like in `--sort-by=contributions`, `--sort-by=name`?

**Comment by dwaynebailey** [comment]
@unho yip that works and allows extension if needed.
