### ISSUE TITLE
Download for offline translation path broken

### ISSUE THREAD

**Issue by dreasvandonselaar** [translate/pootle#4155]
After upgrading from 2.5 to 2.7, the "Download for offline translation" link is broken. It points to https://mycorrecthostname.com/export/?path=/nl/project/ and returns:
```
Not Found

The requested URL /export/ was not found on this server.
```

**Comment by dreasvandonselaar** [comment]
From apache2 error.log:
```
[Wed Oct 21 10:23:30 2015] [error] [client 95.97.137.122] File does not exist: /var/www/pootle/env/lib/python2.7/site-packages/pootle/po, referer: https://mycorrecthostname.com/nl/project/
```

**Comment by dwaynebailey** [comment]
@dreasvandonselaar you need and export directory which is used to cache downloaded files.

**Comment by dreasvandonselaar** [comment]
@dwaynebailey such directory used to be part of the Apache2 installation instructions, but I cannot find it in http://docs.translatehouse.org/projects/pootle/en/stable-2.7.2/server/web.html

I guess I should set e.g.: Alias /export /var/www/pootle/env/lib/python2.7/site-packages/pootle/translations/

This "bug" can possibly be closed then.

**Comment by unho** [comment]
@dreasvandonselaar Exported resources are served directly by Pootle since 2.7.0 (included). So you must remove the Alias for exports from Apache conf.

**Comment by dreasvandonselaar** [comment]
You're right, it was left-over configuration from 2.5.
