### ISSUE TITLE
Fix Store.update --overwrite

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4157]
When we added the "use suggestions on conflicting uploads" feature we broke the overwrite mode of Store.update which expects the on-disk file to win any conflict.

The simple fix is to add a pootle_wins flag (as is done in another PR) and set that to false if overwrite=True.

The only problem with this approach is that the code import_export.utils.import_file uses the overwrite=True flag *and* expects pootle to win

Another approach would be to manually set the imported file's revision in update_stores if overwrite=True to a revision >= Store.max_unit_revision

@dwaynebailey @ta2-1 - any thoughts on this?

**Comment by dwaynebailey** [comment]
@phlax not 100% sure I understand.  Is the problem maybe that import should not use overwrite=True?  I'm wondering if there is a reason for splitting ``overwrite`` and ``pootle_wins``?  Since ``overwrite`` feels like ``pootle_wins=False``.

I know its off topic but could we maybe have some name refactoring here.  ``pootle_wins`` just seems wrongs when it is more like ``winner=pootle``

**Comment by ta2-1** [comment]
@dwaynebailey, could `overwrite=True` be set because we didn't increment revisions during `Store.update()`?

**Comment by phlax** [comment]
@dwaynebailey im not particularly committed to any particular name - although im thinking resolve_conflict=POOTLE_WINS/UPDATE_WINS might be more explicit

The functionality between overwrite and pootle_wins=False is slightly different.

- overwrite makes Store.update call update_units with all units regardless of which have been updated since the revision set in revision header
- pootle_wins decides which to turn to suggestion and which to keep in the event of changed units

I would agree that where overwrite=True we would generally want to make pootle_wins=False - but im not 100% of what the affect of making overwite=False will be in import_export.utils.import_file

**Comment by phlax** [comment]
@ta2-1 im thinking manually setting the revision might be the right approach in the case of --overwrite in update_stores - although i will still need the pootle_wins flag for conflict resolution in other cases
