### ISSUE TITLE
Email language contact about new registrants

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#416]
*Originally posted by Clytie Siddall:*

This is another attempt to make better use of people who register with Pootle but don't contact us for 
access rights. It could sort of replace or complement my previous request for more information on the 
activation page.

Please add a feature to notify the nominated language contact (if one exists) about new registrants for 
that language.

I'm reloading my admin page on the OpenOffice.org Pootle constantly at the moment, hoping to catch 
registrants who may not know they need to email me, or may not remember to email me.

So an automatic email would be very useful.

You will recall that earlier on, I talked about how useful it would be to have nominated contacts for 
languages, and possibly for projects. Pootle attracts interest, and we have to make the most effective use 
of that interest.

Thankyou

Clytie

**Comment by dwaynebailey** [comment]
We don't have language selection in 2.7.0 like we have here.  We still need to bring back the concept of language teams and language leads that can interact with and approve volunteers in 2.7.0 so closing this bug as it's the feature but built on the assumption of old Pootle.
