### ISSUE TITLE
select_related breaks order_by in UnitManager.get_queryset

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4160]
The default manager for Unit does select_related - here:

https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/models.py#L223:L224

This seems to break order_by on the model, which is used by the units property on Store, here:

https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/models.py#L1400

The problem only occurs when you try to access Store.units by index, ie:

```python
for i in range(0, store.units.count()):
    print store.units[i]
```

So the following work correctly as they iterate the units

```python
for unit in store.units:
    print unit.index

for index store.units.values_list("index", flat=True):
    print index
```

This seems to be a Django bug - but im not sure, and couldnt find anything that had been already reported

**Comment by julen** [comment]
Is this perhaps a side-effect of #3837?
