### ISSUE TITLE
Make it easier to deal with unwanted suggestions

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4166]
Pootle by default allows logged in users to make suggestions.  That causes a problem if users suggest stuff but they aren't any good at translating.  A language can set things such that by default only approved users can translate but that is not easy to discover.

We need to deal with:
- Making it easier to change the default for a language or project
- Allowing easy rejecting a users suggestions (not sure if we reject only in a language or only in a project or how we manage that)
- Allow blocking of a users - so specifically marking them as unable to contribute to a project.

**Comment by phlax** [comment]
we now have a suggestions ui for this purpose
