### ISSUE TITLE
update_tmserver: incorrect loaded translations count

### ISSUE THREAD

**Issue by julen** [translate/pootle#4168]
I just rebuilt my TM index, and it reported the following:
```bash
$ ./manage.py update_tmserver --rebuild
Last indexed revision = -1
1641057 translations to index

Expected 1641057, loaded 1641058.
```

I tested this process in different machines and since all of them are returning the same output, I'm pretty sure the counter for *loaded* is incorrect, as it always reports 1 translation more than expected.

**Comment by dwaynebailey** [comment]
@julen I can't replicate this with manual uploads or with upload for local tm.  So the counter in my cases doesn't show that message as there is no mismatch.  I think we can safely assume that the mismatch is in the data.  So unless you can replicate this can we close this.

**Comment by julen** [comment]
Wasn't able to reproduce this time; will reopen if I hit it consistently in the future.
