### ISSUE TITLE
make a quick project start doc pls

### ISSUE THREAD

**Issue by walter211** [translate/pootle#4170]
Spend too much hours on figure out how to use this...

**Comment by julen** [comment]
Thank you for sharing your impressions @walter211.

Do you have more specific or elaborate feedback? We are always happy to improve docs and instructions, however reading about the pain points you had and how you ended up proceeding would definitely help everyone. 
Also note that if you were struggling, there's always user support available on the [#pootle channel on IRC](http://webchat.freenode.net/?channels=%23pootle).

Looking forward to your small contribution, which will be valuable.

**Comment by walter211** [comment]
Yes, for my purpose to using this , is working with my team. I see all the docs is intruducing the terms and basic commands, but for a newbie. 
Here is what I want to know urgently:
How to upload a PO files to the server...(command line or web ui interface)
A basic workflow how two person translate in one project & one language.
How to import an language in an empty project(which blocks me now).
How to export the translation files out for team.
How to integrate the svn or git.

Really appreciate  your guys work, thanks!

**Comment by walter211** [comment]
I am not quite get the import and export term ,seems it is just a flow how to syc transltion between the database and the web content files, right?

**Comment by phlax** [comment]
@walter211 - it looks to me like you might have some problem with your env - we are going to look at the original bug - ie adding quick start docs.

if you can go on irc.freenode.org #pootle - someone there will be happy to track down any problems that you might have getting set up

**Comment by haf** [comment]
It is not clear from reading this issue how I contribute these docs.

**Comment by dwaynebailey** [comment]
@haf if you have a Pootle checkout the documentation is in ``docs/`` in reStructuredText.  So just writing up the docs as you see them would work.  If you are able to write them and struggle with rst I'm sure we can help get the formatting right.

**Comment by julen** [comment]
@haf you can also edit them directly in GitHub by clicking the _Edit_ link available at the top of any documentation page ([example page](http://docs.translatehouse.org/projects/pootle/en/latest/server/commands.html) which would lead to [the GH editing interface](https://github.com/translate/pootle/edit/master/docs/server/commands.rst)).

**Comment by haf** [comment]
There.

Note that if you feel like my talk about the *ancient pootle-master* is a bit rich, then help me implement this for my project and my team and I'll write the intro docs in full in return.

**Comment by unho** [comment]
> How to upload a PO files to the server...(command line or web ui interface)

See http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html#adding-a-new-project If the question is about adding new strings to translate to an already existing project see http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html#adding-new-strings-to-existing-project


> A basic workflow how two person translate in one project & one language.

Pootle is capable of handling multiple persons translating the same project and language. People don't need to care about what other people is doing. If coordination is necessary it must be done outside Pootle.


> How to import an language in an empty project (which blocks me now).

If this is enabling translation for a new language in a project see http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html#enable-translation-to-a-new-language


> How to export the translation files out for team.

Pootle allows to download translation files for offline translation: http://docs.translatehouse.org/projects/pootle/en/latest/features/offline.html


> How to integrate the svn or git.

Pootle currently doesn't handle this, so you will need to get it working with custom scripts. We expect to support this back again with the new `pootlefs` feature.
