### ISSUE TITLE
Better search function

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#418]
*Originally posted by Clytie Siddall:*

Pootle's Search function is better than nothing, but that's about all you can say for it. It's extremely basic: 
it doesn't even distinguish case.

So using it to search through a huge and complex corpus like OpenOffice.org Help is like paddling a canoe 
with a toothpick. You just don't get anywhere.

I strongly suggest enhancing the Pootle search function, with the following priorities:

1. List all results on one page or set of pages (excluding all non-resulting strings) for separate review and 
edit. 

(a) The results page(s) should also feature a Select All toggle (selects or deselects all on that page), and 

(b) an entry field with a drop-down menu containing (for example): Replace, Replace All.

2.  Regex. We use it all the time offline, why not on Pootle? It gives the search function some actual bite.

3. Case-sensitive.

4. A drop-down menu next to the Search field which allows the user to select the hierarchical point in the 
project from which s/he wants to search. 

This avoids us getting bad results when we have found one item and edited the Search field, only to find 
out (eventually) that following that one result means we are now searching inside the file containing that 
result, and nowhere else.

It also saves time in setting up searches. We should not be the victims of embedded, clunky project design 
(that's a comment about OpenOffice.org, not Pootle ;) ).

5. Recent searches (drop-down menu on other side of Search field, in interfaces usually just a magnifiying 
glass icon and small down-arrow symbol on which you click to see the recent searches)

If you can do ANY of these, it will help us a lot. If you can do more, that will be wonderful. Eventually, we 
will have a Search feature to brag about. There are further standard text-editor search features which can 
be applied.

Thankyou

(Back to my frustrating and time-wasting searching in Pootle)

Clytie

**Comment by dwaynebailey** [comment]
Some of these are great ideas, but they're tied to the old search implementation.  We'll open bugs related to these when we implement features for new Pootle.
