### ISSUE TITLE
unit_url and webpack doesn't work properly (2.7.2)

### ISSUE THREAD

**Issue by romangoward** [translate/pootle#4186]
Hi folks,
I have a pootle installation under a specific url, e.g. example.com/translations/ and everything works fine, exclude the translation unit link in the 'Last Activity' field.
Reactor returns a dictionary from json, but profile_url grows from [pootle_statistics/models.py#L283](https://github.com/translate/pootle/blob/fa961d18caa290bc34f05cee8e4169bd3261d677/pootle/apps/pootle_statistics/models.py#L283) while unit_url hardcoded in [UserEvent.js#L43](https://github.com/translate/pootle/blob/stable/2.7.2/pootle/static/js/shared/components/UserEvent.js#L43). Funny that the 'Latest activity' filed in a user's public profile contains a right url, since it grows from the model.py.

That's the first problem.
The second one is about webassest: I've tried to find a way for fixinig a bug in UserEvent.js and I've found that call with l() wrapper => [Avatar.js#L54](https://github.com/translate/pootle/blob/stable/2.7.2/pootle/static/js/shared/components/Avatar.js#L54).
So, I've tried to recreate assets and called the following commands:
* pootle webpack
* pootle collectstatic --clear
* pootle assets build

and i've got the next content in the 'Last activity' field:
**system user edited ${sourceString} 3 weeks ago**
as well as it broke the same field in the public profile:
**'Latest activity':   user1 accepted suggestion for ${sourceString} Yesterday**

I've tried to do it once again, but even without changes in a js  — I had the same result.

# virtualenv info ( pip list )
antiorm (1.2.0)
cffi (1.2.1)
click (5.1)
cryptography (1.0.1)
cssmin (0.2.0)
db (0.1.1)
db-psycopg2 (0.0.7)
diff-match-patch (20121119)
Django (1.7.10)
django-allauth (0.24.1)
django-assets (0.11)
django-contact-form (1.0)
django-overextends (0.4.0)
django-redis (4.3.0)
django-rq (0.8.0)
django-taggit (0.11.1)
django-transaction-hooks (0.2)
django-voting (0.1)
elasticsearch (1.6.0)
enum34 (1.0.4)
idna (2.0)
ipaddress (1.0.14)
lxml (3.5.0)
msgpack-python (0.4.6)
oauthlib (1.0.3)
pip (7.1.2)
Pootle (2.7.2)
psycopg2 (2.6.1)
pyasn1 (0.1.8)
pycleaner (1.1.1)
pycparser (2.14)
pyOpenSSL (0.15.1)
python-openid (2.2.5)
redis (2.10.5)
requests (2.8.1)
requests-oauthlib (0.5.0)
rq (0.5.6)
setuptools (0.9.8)
six (1.10.0)
South (1.0.2)
sphinx-me (0.3)
translate-toolkit (1.13.0)
urllib3 (1.12)
webassets (0.11)

P.S. Calling a pootle webpack with a --dev key hangs.

**Comment by dwaynebailey** [comment]
@romangoward thanks for reporting.  Please one issue in an issue, otherwise we'll all get confused as to what the issue, what is fixed, etc, etc.

I'm not 100% sure I understand your first issue. Do you mean that with a server located at ``example.com/some_path/`` that everything works correctly except the "Last Activity" which would point to the users profile page which should be ``example.com/some_path/user/xxx``

The second issue sounds very much like the one fixed in https://github.com/translate/pootle/commit/97487324be8ef45499ff6d806f62ef2502fc4eb8

**Comment by romangoward** [comment]
@dwaynebailey thanks for your attention. Yes, a server located at `example.com/some_path/`.
The 'Last Activity' field contains two links: 
![unit_url](https://cloud.githubusercontent.com/assets/1024504/11157449/7c5aa83e-8a62-11e5-8497-e8e6c0032bb0.png)

* `VM` is a link to a user profile, and it's correct  => `example.com/some_path/user/VM` .
* `@mention` is a link to a last edited unit, and there is an error: it should be like: `example.com/some_path/language/project/translate/file.po#unit=some_number`, but `/some_path/` is missed.

**Comment by dwaynebailey** [comment]
@romangoward funny none of my servers have the fully elaborated Last Activity field in the Browse page.  But looks like you've given a fair bit of info for us to look a little deeper.

*I'm out of here for the weekend.  I expect other devs will have more info on Monday.*

**Comment by julen** [comment]
Re. the first issue, do you experience the lack of the `/translations/` in URLs when you perform an action via the web? Or do you see that only after running `refresh_stats`?
All of the URL generation comes straight from Django via `reverse()` calls, so the only problematic place I can think of here is `refresh_stats`.

The second report is a dupe of #4121.

**Comment by romangoward** [comment]
@julen I've checked both actions — web and cli, and unfortunately both have the same bug.

**Comment by julen** [comment]
Do you have [`FORCE_SCRIPT_NAME = '/translations'`](https://docs.djangoproject.com/en/1.7/ref/settings/#force-script-name) in your settings? Without that the jobs that calculate stats won't be able to see the prefix.

**Comment by romangoward** [comment]
@julen nope, I didn't have this variable in a config, well.. now it works fine, thanks :-}

**Comment by julen** [comment]
Cool, thanks for confirming!
