### ISSUE TITLE
Some checks are not loaded correctly by Pootle

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4197]
Running TTK checks we get the following errors in the logs:

```
2015-11-18 14:53:32,369 ERROR Problem with check filter 'gconf': 'GnomeChecker' object has no attribute 'locations'
2015-11-18 14:53:32,370 ERROR Problem with check filter 'validxml': 'LibreOfficeChecker' object has no attribute 'locations'
2015-11-18 14:53:32,371 ERROR Problem with check filter 'credits': 'MozillaChecker' object has no attribute 'locations'
```

These fill up the log and potentially mask other issues.

**Comment by julen** [comment]
For these specific checkers I see `.locations` is already set in [`TranslationChecker.run_filters()`](https://github.com/translate/translate/blob/e597559572de32f6f0f334f2cdcd33c9a146d6a0/translate/filters/checks.py#L530), which [is run](https://github.com/translate/translate/blob/e597559572de32f6f0f334f2cdcd33c9a146d6a0/translate/filters/checks.py#L600) when Pootle wants to [update quality checks for a unit](https://github.com/translate/pootle/blob/7c55b354b2da93209662f23206454a39465bd0a9/pootle/apps/pootle_store/models.py#L828).

Seeing the three errors are logged practically at the same time, I wonder why **all** checkers are being instructed to run in the first place – Pootle has a unique checker assigned per TP (or per-site, but this is clearly not the type of setup being reported).

**Comment by Tognolo** [comment]
I have the same problem on every page.

**Comment by phlax** [comment]
i believe this was fixed in https://github.com/translate/pootle/pull/4477 - please reopen if problem persists

**Comment by kartoffelheinz** [comment]
Applying the patch linked in #4477 to Pootle 2.7.2 won't fix it for me, I still get the same errors the op described just from loading the tutorial project in the webapp. Something still is not right there.

**Comment by phlax** [comment]
hi @kartoffelheinz i have a feeling we just fixed it for the creation of new Projects - i think we probably need to add a migration to fix Projects that have been incorrectly set up - ill try and address this today

**Comment by phlax** [comment]
seems like i was wrong - and it wasnt fixed - i will look further when i get chance

**Comment by unho** [comment]
This issue comes from Translate Toolkit. Fix will be included in next Translate Toolkit release. Explanation and fix in https://github.com/translate/translate/commit/6122c4bc.
