### ISSUE TITLE
Disabled project cannot use update_stores

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4198]
If a project is 'disabled' then you cannot run `update_stores` against it.

The use case is setting up a project that you only want to make available to translators once all files are correctly synced.  Currently you have to enable to project before you can run ``update_stores`` which means that users can potentially work on it when you might not yet want them to.

**Comment by iafan** [comment]
@ta2-1, I was under impression that we have addressed this already? See https://github.com/translate/pootle/issues/3530#issuecomment-132747404 that explicitly states that the disabled projects should properly be updated.

**Comment by ta2-1** [comment]
@iafan your comment is about stats updating (as I understood it). But I wonder how can we change project and update stats if `update_stores` doesn't work. I'll check it.

**Comment by iafan** [comment]
Let me quote the relevant bit:

> [disabled project] should be hidden from anybody expect admins, but otherwise it should be a regular project

**Comment by julen** [comment]
Related question: is the stats ticker displayed while processing disabled projects? Regular users don't wanna be bothered by this while the project remains disabled, it's interesting for site-admins though.

**Comment by iafan** [comment]
@julen, I think you already answered your question. Users shouldn't see anything related to projects they don't have an access to (be it disabled projects or projects with custom permissions). Dirty stats status if on of such properties.

**Comment by ta2-1** [comment]
There is one confusing thing here.
`update_stores` behaviour: if there is no project directory we disable the entire project (Note: we don't make anything (TPs) obsolete).

How can we update a TP within a disabled project?
- if the directory for the disabled project exists then we update the TP as usual and even make it obsolete if there is no directory for this TP.
- if the directory for the disabled project doesn't exist then we can do nothing or make the TP obsolete.

I'm about to add extra option to `update_stores` command if we need to touch internal structure for disabled projects. Any thoughts?

**Comment by dwaynebailey** [comment]
@ta2-1 can you explain what the option would be?  This doesn't feel like it needs an option (unless I misunderstood something). In my mind ``update_stores`` simply works as expected on a disabled TP.

**Comment by ta2-1** [comment]
@iafan, @dwaynebailey, should `sync_stores` work with disabled projects?

**Comment by dwaynebailey** [comment]
@ta2-1 yes, ``sync_stores`` should work with disabled projects.

My use case is that I use disabled projects to hide them and prevent user working on them.  But I still want to be able to get translations from Pootle and update translations on Pootle if I'm using the command line.
