### ISSUE TITLE
Review update_stores for speed issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4199]
An `update_stores` for a new TP on larger projects such as a Firefox language, can take an hour.  With N languages we're looking at a considerable time at the moment to initialise a new set of projects.

We never took this long before, so clearly we've regressed in some way.

This task is to profile the current approach and look for any potential bottlenecks.  Things that could be blocking us now:
- Updating TM when we run `update_store` - bulk update is much faster
- Loading units one by one.
- Something really stupid that we're doing...

**Comment by phlax** [comment]
http://stackoverflow.com/questions/1687125/how-to-profile-a-django-custom-management-command-exclusively

**Comment by ta2-1** [comment]
`update_stores` command was refactored. there were a lot of optimisations applied. so I'm closing this issue.
