### ISSUE TITLE
Strange quot and double quot errors in Pootle for Persian

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4201]
This is likely a TTK issue but it has impact for mlo.  [Verbatim report](https://bugzilla.mozilla.org/show_bug.cgi?id=944858).

In Persian we see a number of false positives in strings which relate to single and double quotes.

Some are the usual suspects of `'s and s'` which should really be marked as false positives.

I'm picking up some issues e.g.
* https://mozilla.locamotion.org/fa/firefox/translate/dom/chrome/layout/css.properties.po#unit=4093460 - this is untranslated and look 100% identical yet fails the check.
* We seem to always fail double quote check if single quote fails.

The following is an [instance](https://mozilla.locamotion.org/fa/firefox/translate/dom/chrome/nsWebBrowserPersist.properties.po#unit=4093855).

```po
msgid ""
"%S could not be saved, because a file already exists with the same name as the '_files' directory.\n"
"\n"
"Try saving to a different location."
msgstr ""
"قادر به ذخیرهٔ %S نیست، زیرا پرونده‌ای با همان نام به عنوان پوشهٔ 'ـپرونده‌ها' از قبل وجود دارد.\n"
"\n"
"تلاش کنید ذخیره‌سازی را در محل دیگری انجام دهید."
```

**Comment by dwaynebailey** [comment]
This seems to be a non-issue, the singlequote error was totally correct as Persian uses << not '.  So the original reporter didn't know their languages own quote rules.  However, the real issue would be that:

1. In failure of singlequote we're getting doublequote errors also.  This of course confuses users especially in our case.
2. Failures that say why its a failure would be more useful and direct users to make the needed corrections.

This should move to TTK.

**Comment by unho** [comment]
Closed since it was moved to https://github.com/translate/translate/issues/3408
