### ISSUE TITLE
Missing migration for staticpages.AbstractPage

### ISSUE THREAD

**Issue by imankulov** [translate/pootle#4206]
When I do `pootle makemigrations`, Django detects an inconsistency and generates new migration to add fields `url` to `staticpages.legalpage` and `staticpages.staticpage`. Not sure if it's a missing migration, or a field which doesn't have to be there in the first place.

Thanks in advance for fixing this one way or another.

**Comment by unho** [comment]
Thank you for reporting.

Can you please provide some additional information, like the version you were upgrading from and the exact commands you run?

**Comment by dwaynebailey** [comment]
@unho the error occured becuase of 08ac39503a98c6b8bcd76f36565e7182e09be576 which changed the ``help_text``

**Comment by imankulov** [comment]
@unho 

```
$ git rev-parse HEAD
ed7c9f289ef753d33393d5bcf09038e9100fe876

$ pootle migrate
  ...
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

$ pootle makemigrations
...
Migrations for 'staticpages':
  0002_auto_20151123_1046.py:
    - Alter field url on legalpage
    - Alter field url on staticpage
```

@dwaynebailey: True, turned out it's not a big deal :)

**Comment by dwaynebailey** [comment]
@unho yip, luckily.  I'm busy testing something in .travis that will catch these in future.
