### ISSUE TITLE
version control: commit should show a reasonable error if the local copy is outdated

### ISSUE THREAD

**Issue by sumpfralle** [translate/pootle#421]
most revision control systems refuse to do a commit if the base local working
copy is outdated (compared to the repository).

For now pootle shows the output of a thrown exception, that was caused by the
respective command line tool (svn, git, ...).

This behaviour is hard to understand for users and should be changed to a
friendly warning like "the repository contains a newer version of this file -
please update your local copy to merge these changes before committing".

The check could be done in projects.py (Pootle) before committing. Commit should
abort with the above error message if the local working copy is outdated.

Any ideas regarding this check for the different revision control systems?

**Comment by dwaynebailey** [comment]
We've taken out VCS and will implement this in another way in future.  So closing this.
