### ISSUE TITLE
Changing language code breaks Pootle

### ISSUE THREAD

**Issue by unho** [translate/pootle#4213]
The problem is that basically changing a language code doesn't trigger the necessary changes on `pootle_path` for the related TPs and its Directories, Stores and VFolderTreeItems. Thus stats don't work, and other Pootle features don't work as expected (like syncing files to disk). There are two proposed tasks to fix this issue:

1. Forbid to change the language code for existing languages. This can be landed on its own but 2) is required to avoid losing the ability to alter the language code.
2. Add a management command to alter a given language code that would perform all the required changes:

- Disable all the language TPs so they don't get updates either from disk or from the UI,
- Sync all language stores to disk to ensure no translations are lost,
- Flush stats and caches related to this language,
- Change the language code,
- Copy files on disk from old locations to new locations (research how this might affect `update_stores` since we would like to avoid triggering any update since we just synced translations),
- Change `pootle_path` for the affected objects so the new language code is used,
- Recreate stats for the whole language (preferably TP by TP),
- Any other relevant change?
- Enable all the language TPs

The expected final outcome is that no attributions or permission assignments are lost, the language code is renamed and Pootle is still working.

**Comment by phlax** [comment]
ref #4152

**Comment by dwaynebailey** [comment]
I'd be concernd that that the command does too much, like syncing to disk.  I'd say that is the admin's task not the commands task.  I know why we want to do it, but it has unintended consequences if the admin doesn't know if will do something that actually is unrelated to the intention.

**Comment by unho** [comment]
If sync to disk is not included in the command then we need to ask the user running it to manually disable the TPs before syncing, and then enabling them back. I think it is better to include this on the command.

**Comment by dwaynebailey** [comment]
Disabling is unrelated to syncing.

**Comment by dwaynebailey** [comment]
Syncing will change files on the filesystem or make commits all of which is likely unexpected.  Disabling is not destructive, sync_stores is.

**Comment by julen** [comment]
Unless I'm missing some detail, this is no different from renaming a project — I'd consider it a dupe of #3764.

**Comment by unho** [comment]
It is indeed related. I wouldn't consider this necessarily a dupe.

I suppose that 1) can be achieved with something similar to https://github.com/translate/pootle/commit/7348f8a767efeba7e5b18552adbac803f75ef9f7 ?

**Comment by julen** [comment]
> I wouldn't consider this necessarily a dupe.

Mind elaborating why?

**Comment by unho** [comment]
Proposed a patch to prevent this from happening. It is not an actual fix for the underlying issue.

**Comment by unho** [comment]
>> I wouldn't consider this necessarily a dupe.

> Mind elaborating why?

Thought about it and basically the issue is the same: stats are no longer available because related items pootle_paths are not updated accordingly. So closing this issue as a duplicate of #3764.
