### ISSUE TITLE
update_stores logic is no longer called when TP is initialised

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4215]
This is a regression from #3877 

If this is the desired behaviour ill make the necessary changes to restore it.

The other option is explicitly calling ``update_stores`` after adding TP - and changing docs to reflect that.

In order to fix i probably need to move the last_sync_revision logic back out of the management command so it can be called from other points in the code more easily

i also think i need to check anywhere that store.update is called and make sure it doesnt expect old last_sync_revision behaviour

**Comment by dwaynebailey** [comment]
I'm trying to think of cases or instance that would have triggered:

1. When a TP was added and files are on disk IIRC that would load units into the TP
2. When a new language is created and no files are on disk it will create the TP from templates.
3. If update_store is called for a language that doesn't have a TP then the TP is created and the stores are loaded.

I think that's the previous behaviour in terms of interaction related to TPs.
