### ISSUE TITLE
Docs: Include on release notes that the ability to choose preferred language was dropped

### ISSUE THREAD

**Issue by unho** [translate/pootle#4221]
In one of the latest Pootle versions the ability to choose the UI language has been dropped. Previously users were able to select it using a dropdown or a setting on their profiles. Now it is picked from the browser preferred languages list.

This particular change wasn't included on any release notes, and it should be.

**Comment by dwaynebailey** [comment]
Or should we bringing this back? It was something Jerome landed but got reverted when we merged with EN.

**Comment by phlax** [comment]
@dwaynebailey lets update the docs and then maybe raise a ticket to bring back functionality

**Comment by unho** [comment]
I personally think it is ok to **not** get the functionality back. I mean, is there any scenario where a user can't change its browser preferred language settings?

**Comment by phlax** [comment]
well - as a localisation org maybe this is something we should document (if its not already)

**Comment by unho** [comment]
Language picker displayed all pages was added in 6eb08290 and is not present on any 2.7.x version.

**Comment by unho** [comment]
UI language User Profile field (used to specifiy preferred UI language on user settings) was removed on 17f8c450 and is not present on any 2.7.x or 2.6.x version.

**Comment by dwaynebailey** [comment]
@unho there are many reason why a user would want to override a preferred language in certain instances.  I don't want most of the web in Afrikaans, but I do want Pootle in Afrikaans.   The inverse might also be true if the sites translations are rubbish. Preferred language doesn't allow that as its a hammer that makes one size fit all.  We can't justify this at all really.  Being able to override, and the website remember that override, is actually very well documented behaviour for how Accept-Langs should work.

So I'm OK that we don't have the feature and we want it back.  But justifying it being missing in the way I'm seeing here is just very bad l10n practice and we can't justify it at all.  I'm happy to say we're not 100% sure how we want to implement the UI.  But honestly not having this is the dark ages of l10n.

**Comment by unho** [comment]
I must say I missed that. You are 100% right.

Created a PR to document this change so at least users know what happened and how to try to workaround the missing feature.

Adding back the feature should be a separate issue from this one.

**Comment by unho** [comment]
Added #4230 to track getting back the feature.
