### ISSUE TITLE
Create an InitDB class

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4225]
i think it would be cleaner to put the functions in pootle.core.initdb into a class

**Comment by julen** [comment]
FWIW there's nothing wrong with plain functions in this context. Maybe you want to elaborate on the reasons why you propose the change?

**Comment by phlax** [comment]
for a few reasons:
- these functions logically belong together
- there are better conditions that could be written and these are similar in each of the tests - so they could probably use instance properties/attributes
- imho testing for these functions would be easier looking at them as logical group
- basically the generic reasons for OOP

**Comment by phlax** [comment]
...make it easier for endusers to customise initialisation behaviour

**Comment by julen** [comment]
Initialization is a one-off thing, so there's probably something wrong if a deployment wants to customize it. And speaking of grouping, the module itself serves such a purpose.

Having said that, if you really want to make the change that's your call, however I don't see any great benefits to do so and personally I wouldn't put my time on it.

**Comment by phlax** [comment]
well there are some improvements i would like to make beyond changes in #4224 - and it would be a lot easier to do imho with these functions in a class

**Comment by unho** [comment]
Which improvements are those?

**Comment by phlax** [comment]
off the top of my head:

- being able to do InitDB().has_run_previously() in mngmt command
- being able to specify which project/s to load at init
- being able to run methods selectively
- being able to write a deployment that does specific things at init time
