### ISSUE TITLE
Upgrade Django dependency to latest stable

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4233]

**Comment by julen** [comment]
I'm +1 on upgrading to 1.**9** instead, which should be out in a short amount of time (RC2 currently).

**Comment by unho** [comment]
If by the time we get to this release 1.9 is out I am ok with skipping Pootle 2.8.x.

**Comment by julen** [comment]
FTR [Django 1.9 has been released](https://www.djangoproject.com/weblog/2015/dec/01/django-19-released/), and 1.7 reached EOL.

**Comment by unho** [comment]
@translate/house We are about to release Pootle 2.7.3, and Django 1.8 is the LTS version. Should we upgrade to Django 1.8 and release Pootle 2.8.0 instead of 2.7.3?

**Comment by phlax** [comment]
@unho - no for sure not - we can change the django dep sooner - but lets keep to our milestones

**Comment by phlax** [comment]
...im thinking next release needs to be 2.7.3b2 as we are adding/changing lots more core code

**Comment by phlax** [comment]
lets at least see what current issues are with upgrading
