### ISSUE TITLE
Pep8 cleanup

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4237]
make files more pep8-compliant and make linting possible

we need to agree some exceptions - some possible exceptions:

- E501: 80 chars
- W503: conditional operators
- E402: imports not at top of file
- ?

**Comment by phlax** [comment]
> 80 chars
i would prefer to keep to this one

> conditional operators

i have very strong feelings about this and would like to be able to put these at the beginning of conjoining clauses 8)

> imports not at top of file

sometimes it really is necessary to import in functions/methods to avoid circular imports without major refactoring

**Comment by dwaynebailey** [comment]
After major pep8 cleanup and porting Travis to tox the [pep8 config](https://github.com/translate/pootle/blob/3a39f1ebfff726fddd28225fafd0a7d79b406dfd/setup.cfg#L36-L52) summarises it as follows:
```ini
[pep8]
max-line-length=84
# migrations - autogenerated, so we don't really want to edit them
# docs/conf.py - mostly supplied by Sphinx
# .tox - exclude any tox installed files
exclude=migrations,conf.py,.tox
# E129 visually indented line with same indent as next logical line
#   - No real agreement here.  Best to disable it for now
# E226 missing whitespace around arithmetic operator
#   - This makes split[a+1:b+1] look unreadble as split[a + 1:b + 1]
# E402 module level import not at top of file
#   - There are enough cases where we want to import in a function
# W503 line break before binary operator
#   - Jury is out on what is actualy more readable
# Default ignore list for ref E121,E123,E126,E226,E24,E704
ignore=E129,E226,E402,W503
statistics=True
```

This means:
*  We're excluding things that are auto-generated.
* Line length of 84 _not_ 79.  There are **13** lines over 79 that could be cleaned up if someone wants to lower that limit
* We exclude 4 issues with reasons outlined above.
