### ISSUE TITLE
Pyflakes cleanup

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4239]
There are a lot of pyflakes issues atm

Not sure if there any exceptions that anyone would like to see:

- ?

**Comment by julen** [comment]
Can you please give some context and share which ones are these issue? TIA.

**Comment by phlax** [comment]
@julen i put up the ticket for people to add any exceptions to pyflakes that they would like to see

personally i dont want to see any - but the obvious one that comes to mind is import modules for re-import. In this case we seem to have decided to use an ``__all__`` list to express why the imports are there - so that seems to be a non-issue

**Comment by phlax** [comment]
once we have the pyflakes count to 0 ill close this ticket - which we are very close too - i just cleaned up any that were non-functional changes. There are a couple left - list comprehensions resetting local vars i think

**Comment by julen** [comment]
So are you referring to these?
```bash
$ pyflakes . | grep -v migrations
./manage.py:15: 'syspath_override' imported but unused
./setup.py:164: 'syspath_override' imported but unused
./pootle/checks.py:250: 'textile' imported but unused
./pootle/checks.py:252: 'markdown' imported but unused
./pootle/checks.py:254: 'docutils' imported but unused
./pootle/runner.py:17: 'syspath_override' imported but unused
./pootle/apps/pootle_app/apps.py:18: 'pootle_checks' imported but unused
./pootle/apps/virtualfolder/helpers.py:44: list comprehension redefines 'dir_path' from line 35
./pootle/core/helpers.py:140: list comprehension redefines 'units' from line 134
./pootle/core/markup/filters.py:76: 'textile' imported but unused
./pootle/core/markup/filters.py:78: 'markdown' imported but unused
./pootle/core/markup/filters.py:80: 'docutils' imported but unused
```

**Comment by phlax** [comment]
yep - thats them

**Comment by julen** [comment]
* `syspath_override` issues can be silenced/ignored — it's used but it only has side-effects at import time (see #3608 too).
* The import for `pootle_checks` is needed AFAIK to register the checks themselves on app init.
* The markup checks can be silenced/ignored too: they only try to determine if such packages are available. This is code that might be going away depending on the verdict of https://github.com/translate/pootle/issues/4184#issuecomment-157179358

So from my understanding the actual issues left alive are:
```
./pootle/apps/virtualfolder/helpers.py:44: list comprehension redefines 'dir_path' from line 35
./pootle/core/helpers.py:140: list comprehension redefines 'units' from line 134
```

**Comment by phlax** [comment]
> The import for pootle_checks is needed AFAIK to register the checks themselves on app init.

Lets do this with AppConfig.ready

**Comment by phlax** [comment]
> So from my understanding the actual issues left alive are:

yep - they are both easy fixes - but i was rushing when i did the other much easier fixes - and didnt have time to pdb through and confim 100% that it would have no side-effects
