### ISSUE TITLE
Remove hardcoded Evernote values in wordcount

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4242]
In https://github.com/translate/pootle/blob/7e734e14/pootle/core/utils/wordcount.py#L37-L41 we have harcoded product names.  Useful check, but not useful having it hardcoded and uncustomisable. Move this into some config.

**Comment by ta2-1** [comment]
done in 9ec0d37b5a645ff64dcaa88dfe8ac43fab317a19.
