### ISSUE TITLE
Support gd>ga machine translation

### ISSUE THREAD

**Issue by kscanne** [translate/pootle#4258]
I have a high-precision translation engine betweent these closely-related languages.  I would love to have it available through Pootle so I can try and keep up with Michael Bauer.

The translation engine is available as a web service; you'd just need to make a POST request to
http://borel.slu.edu/cgi-bin/seirbhis.cgi
with one parameter named "teacs", whose value should be the gd text to translate.

The response is a JSON object, in this format:

```json
[["Iongantach","Iontach"],[",",","],["nach eil","nach bhfuil"],["?","?"]]
```

(that is, a list of translation pairs; we do this because in many contexts we want to align the source and target - for Pootle you'd just need to grab the second element in each pair and piece them back together into a string).

**Comment by julen** [comment]
@kscanne could you please ensure the server can handle CORS requests? TIA.

**Comment by kscanne** [comment]
Hey @julen - CORS requests should work now.

**Comment by kscanne** [comment]
FYI, I'm adding a second language to the translator this week, so things will change a bit going forward.  The new URL for the web service is:
http://borel.slu.edu/cgi-bin/seirbhis2.cgi
It now takes a second POST parameter "foinse" which is the language code of the source text.  Currently supporting "gd" or "ga".

**Comment by kscanne** [comment]
I wrote some documentation (note URL has changed also):

https://github.com/kscanne/caighdean/blob/master/API.md

**Comment by phlax** [comment]
hi @kscanne - i added a python client lib for interacting with the server - https://github.com/phlax/python-caighdean
