### ISSUE TITLE
Redirect to wrong URL when not running on port 80

### ISSUE THREAD

**Issue by exzhawk** [translate/pootle#4261]
I started a pootle instance by "pootle start" command on my server and use nginx as proxy. Since 80 port is occupied, nginx is listening on 8080. The URL 'http://ip:8080/projects/' works fine. But in many cases, for example when clicking the upper right logo, it will redirect to 'http://ip:8080' and then redirect to 'http://ip/projects/' and failed. It can't redirect to the project page with port number 8080.

**Comment by julen** [comment]
Pootle uses Django's `reverse()` for backend URLs and redirects, so this is probably a misconfiguration of your server.

Make sure your nginx proxy configuration also includes the port number:
```nginx
proxy_set_header    Host $host:$server_port;
```

**Comment by exzhawk** [comment]
Thanks. My fault.
