### ISSUE TITLE
PootleCommand handles obsolete translation projects

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4269]
`update_stores` command can make obsolete TP directory many times. 
It doesn't affect us much except we get extra unnecessary log messages like this:

```
set(['get_last_updated', 'get_checks', 'get_mtime', 'get_suggestion_count', 'get_last_action', 'get_wordcount_stats']) deleted from /uk/android_announcements_evernote/ cache
```

which tells us that cache for TP has been deleted.

I think any `PootleCommand` shouldn't handle TP with obsolete directories. `update_stores` command will resurrect TP directory when it's added.

**Comment by ta2-1** [comment]
@julen, @unho, @phlax, @dwaynebailey GTM?

**Comment by unho** [comment]
You mean the issue?

**Comment by ta2-1** [comment]
sorry, PR #4270 of course
