### ISSUE TITLE
calculate_checks uses a huge amount of app memory on large sites

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4273]
It used up ~4GB before my test server ran out of mem/swap

**Comment by phlax** [comment]
@ta2-1 maybe the solution is to remove the tool - trying to rem if there is anything that calculate_checks is still needed for

**Comment by julen** [comment]
`calculate_checks` is needed when willing to (selectively) calculate checks without refreshing all stats. This usually happens when a quality check has been refined/updated.

**Comment by ta2-1** [comment]
When you add new checks or change existing one you'll need to recalculate these checks for all units:
- update `QualityCheck` objects;
- refresh stats cache;

`refresh_stats` command addresses the second only. So I'd not get rid of this.
