### ISSUE TITLE
Wrong import in `test_checks` command.

### ISSUE THREAD

**Issue by electronick1** [translate/pootle#4275]
Wrong import in `test_checks` command. (pootle/pootle/apps/pootle_app/management/commands/test_checks.py)
[Here](https://github.com/translate/pootle/blob/master/pootle/apps/pootle_app/management/commands/test_checks.py#L22) we import `utils`, but [here](https://github.com/translate/pootle/tree/master/pootle/apps/pootle_misc) we have only `util.py` (not utils.py)

**Comment by dwaynebailey** [comment]
@electronick1 thanks for reporting, the fix was pretty easy and it's on master if you want to test.

**Comment by electronick1** [comment]
@dwaynebailey Cool! Thanks for quick response.
