### ISSUE TITLE
`sync_stores` doesn't handle disabled projects

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4276]
We addressed the similar issue for `update_stores` #4198.
`sync_stores` should work for disabled projects as well https://github.com/translate/pootle/issues/4198#issuecomment-161717337.

**Comment by julen** [comment]
Would it always consider disabled projects or would there be a flag to skip these altogether? cc @iafan

**Comment by ta2-1** [comment]
@julen there is a flag `skip_missing` which is always used in EN workflow. Its behaviour won't be changed.

**Comment by julen** [comment]
:+1:

**Comment by dwaynebailey** [comment]
I'm not sure --skip-missing does what is expected, or the docs aren't clear.  That deals with files, not disabled projects.

**Comment by ta2-1** [comment]
I thought that @julen raised this question because project can be automatically disabled if its directory is ceased to exist. Then `sync_stores` would recreate directory for the project.
EN doesn't create `.po` files from pootle because `skip_missing` is always used. Then a directory for just disabled project won't be recreated.
