### ISSUE TITLE
Missing DB index on Unit table

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4278]
While reviewing this issue #4265 we have realised that there is no index (`store_id`, `index`) on `pootle_store_units` table.
This index is very important because the default order is exactly on these two fields.
I have to notice that it's absolutely safe to create such index via DB console. There are results that I got on EN database.
```
mysql> select * from pootle_store_unit order by store_id, `index` limit 100;
...
100 rows in set (7,26 sec)

mysql> alter table pootle_store_unit add index store_index (store_id, `index`);
Query OK, 0 rows affected (15,12 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> select * from pootle_store_unit order by store_id, `index` limit 100;
...

100 rows in set (0,05 sec)
```

If (`store_id`, `index`) index existed it'd not be very important to address #4265.

**Comment by ta2-1** [comment]
cc @julen @iafan

**Comment by phlax** [comment]
@ta2-1 - i added it already

https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/models.py#L365

**Comment by phlax** [comment]
> If (store_id, index) index existed it'd not be very important to address #4265.

that is not correct - it would be ~1000x more efficient - but would still be bad to have non-unique ordering - and worse multiple fields of non-unique ordering
