### ISSUE TITLE
Language admins can't see translators email addresses

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4282]
It would seem that we've regressed in that a language admin can't see the email address of a contributor.

**Comment by iafan** [comment]
@dwaynebailey, do you mean the user profile page? While someone's working on this, I'd also suggest a quick CSS improvement: since the email is supposed to be visible to admins only, let's render it in red "admin" color. This will give an indication that it is not a part of the public profile.

**Comment by dwaynebailey** [comment]
@iafan yes the profile page.  Its a quick way for anyone with TP, Lang or Proj admin rights to have direct contact with a contributor.
