### ISSUE TITLE
Communicate the timezone used in statistics/reports

### ISSUE THREAD

**Issue by julen** [translate/pootle#4288]
If users made translations in day N, they might not be displayed as such in reports, but rather in day N-1. This can happen due to the offset with respect to the server's timezone, as this is used when displaying the reports.

This is confusing (and alarming) for translators who check the reports themselves, leading them to think their contributions were not taken into account by the reporting tool.

The expected behavior is that reports adjust to the user's preferred local timezone when displaying.

**Comment by iafan** [comment]
This is not a bug. Please note that we make reports (including the ones used for money payment) in server timezone. We want to match the reports the users sees with the ones that we finally use for payment.

I admit we could probably communicate this better.

**Comment by julen** [comment]
I'm reopening so we can communicate this better, since it's clear it is confusing. Do you have any thoughts on the matter?

At the same time just wanted to raise the concern that reports are being tied to some 3rd party code (payments/invoices), and this isn't obvious for anyone looking at the core.

**Comment by iafan** [comment]
This is not about invoices. Invoices just use the same approach to calculation we use in other places. Basically, we use month boundaries to calculate and show statistics — in Top Contributors chart, in user's profile, in user's statistics, in admin user reports and detailed reports. These month boundaries are used to calculate both scores and money for paid contractors. If we will take timezones into account, month boundaries will be different for the server, for the manager and for the user, resulting in different values.

So the solution is simple — always use server timezone to calculate month (and day) boundaries. This will give you consistent numbers from everyone's point of view. In detailed reports, we already  show the server timezone in the table header (e.g. `Local server time (GMT-0800)`). We could show some disclaimer in a small font above the graph on the right hand side: `Daily/monthly statistics are caclulated using local server time (GMT-0800)`.

**Comment by dwaynebailey** [comment]
@iafan for user contributions this really doesn't make sense.  It does make everything consistent but reports that start in the middle of my day never make real sense.  We have contributors spread around the globe and this feels like broken localisation no matter what disclaimer is printed.

**Comment by iafan** [comment]
There are no 'reports that start in the middle of the day' from the UI standpoint. It's just about the numbers being consistent or not.

**Comment by ta2-1** [comment]
Reports were removed in 9b82115ca536a2ceb7ffd5b08415fcbf394051e9.
