### ISSUE TITLE
Remove/restrict access to site-wide editor views

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4289]
- calls to `/projects/translate` are by far the most expensive pages to load.
- i have tried to optimize these pages but hit performance barriers that are not easily overcome with such large datasets
- atm anon users are encouraged to make queries on this page with the 3 most prominently shown buttons
- these buttons have a huge and -ve impact on both db and servers
- its debatable whether these pages serve any purpose as language or project managers are usually interested in either a project or a language - rather than all projects and all langs

I am proposing to either remove this view altogether or to restrict to admins/managers or at very least members of the site.

This is something that could be made configurable as there is no real reason to restrict this view on a very small site

**Comment by julen** [comment]
I don't think we make any practical use of these buttons. The search might be used by our managers (@iafan please confirm), although it really has performance deficiencies as already outlined in https://github.com/evernote/pootle/issues/186.

The horizon would be implementing ES-based site-wide search — nevertheless that's pretty much an independent task on its own.

In the mean-time I'd be happy seeing `/projects/translate/` go altogether unless there's a real current use for it. If that's the case, making this configurable sounds like a good temporal compromise.

**Comment by dwaynebailey** [comment]
The only real manager views I use are either Project wide of Language wide.  The global view is not what most people will ever see and one that is unlikely to be used.  Unlikely in that it is rare that you want to review every language on every project.  The only minor use case would be going through suggestions or quality checks as these are likely smaller numbers, but again doing those across everything is unlikely.  Note that although this query is expensive it is not the default that someone will see, I think the default will be picked up by their accept-lang.  Those themselves could be expensive, but I'm not sure.

Some comments:

* I'm not sure I'm a fan of the config option, but if its what is needed to hide that I'd say its a good idea.
* Being able to enter the editor for these items only makes sense if you can do anything with them.  So it might make sense to limit that action to people who can suggest or translate based on their project or language rights.  Thus if you make your site require login to suggest then you immediately limit who can do this action.  Or if by default nobody has rights then nobody could do this action unless enabled.
* I'd remove the right from the top level page.
* We can change the buttons to inactive for user without rights.  So: <br />
    `Continue translation N Review suggestions N Fix critical errors N View all N`<br />
  becomes<br />
  `  Untranslated N Suggestions N Critical errors N All N`<br />
  This way we ensure that the UI is mostly the same and we don't convey possible action where none exists.

**Comment by iafan** [comment]
Site-wide search is definitely useful to localization managers (in our case, we don't have per-language managers, our managers — who are technically Pootle admins — work with all languages, and can make use of site-wide searches and other tasks, like fixing critical error checks. So I'd make this an admin-only feature. Admins can access all languages, so these site-wide actions also make sense in terms of permissions.

**Comment by dwaynebailey** [comment]
@iafan just to be clear.  Do these managers actually ever pull up a useful query that is looking at checks across all projects and across all languages?  My guess is that they are more likely to tackle one project and include all languages (i.e. reviewing all checks for a project), or address all checks across one language (i.e. cleaning up checks in one language across all its enabled projects).

I'm raising this because the global use case can be achieved by manually iterating through all projects one by one.  And also because I think its pretty rare in practise, certainly is for me.

**Comment by iafan** [comment]
Addressing all checks across all languages is definitely something that we regularly use. We have more that 40 projects, so blindly iterating through these just to see if there are any errors would be a pain. And filtering all the checks is actually quite fast for us (we usually keep the number of critical errors at zero level, so whenever a few of them appear in some projects, we can quickly filter them all from the `/projects/` page.

**Comment by phlax** [comment]
@iafan - cool i think the best thing then is to keep that site-wide view but make the permission configurable as to who can use it.

Ill add this in a PR - ill also have to add some logic to turn the links into text if you dont have the required permission.

With respect to this issue - we have been discussing bringing forward Elasticsearch integration - which would mitigate at least the issues of filtering/sorting large result sets

**Comment by phlax** [comment]
this was done some time ago
