### ISSUE TITLE
eslint breaks with airbnb update

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4293]
Travis is breaking and the only difference seems to be an update of the airbnb style files.

[Good build](https://travis-ci.org/translate/pootle/jobs/96697240) - eslint-config-airbnb@2.0.0 node_modules/eslint-config-airbnb
[Failed build](https://travis-ci.org/translate/pootle/jobs/96943078) - eslint-config-airbnb@2.1.0 node_modules/eslint-config-airbnb

**Comment by julen** [comment]
Yeah in 2.1+ basically they enabled a rule to enforce the [object shorthand syntax](https://github.com/eslint/eslint/blob/master/docs/rules/object-shorthand.md).

I re-adjusted *package.json* on top of your commit to ensure we upgrade across [tilde ranges](https://docs.npmjs.com/misc/semver#tilde-ranges-1-2-3-1-2-1), not major versions.

Let's treat upgrading to the 2.1+ config separately.
