### ISSUE TITLE
Upload changes appear in the timeline improperly

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4298]
#3745 has been reckoned as attribution bug and addressed in https://github.com/translate/pootle/commit/4c4451e2d93d69f9887ff850a30965d5f519ccb6

But upload changes are still shown improperly in timeline.

Types of upload changes:
- remove translation (empty row)
  ![image](https://cloud.githubusercontent.com/assets/682845/11874156/5084e506-a4ef-11e5-9e38-786c399d7f77.png)
- add translation (no information about upload)
  ![image](https://cloud.githubusercontent.com/assets/682845/11874249/b82b37f0-a4ef-11e5-8534-d3f9759cb930.png)
- create unit (should it be forbidden?)
  ![image](https://cloud.githubusercontent.com/assets/682845/11875501/00d7afdc-a4f6-11e5-9d04-d8ee9328ba00.png)

**Comment by phlax** [comment]
is this fixed @ta2-1 ?

**Comment by dwaynebailey** [comment]
Tested this.  Blanking, translating all show correct attribution and say "N seconds via file upload".  Changing user works and attributes correctly.

You can't upload a new unit though.  I think by design.
