### ISSUE TITLE
Don't allow adding/obsoleting Units through upload/import

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4302]

**Comment by julen** [comment]
Could someone please add what's the motivation behind this? Thanks in advance!

**Comment by phlax** [comment]
hi @julen i think the motivation is that someone who has only just registered on a site can currently eg upload an empty file, and obsolete all the units

**Comment by dwaynebailey** [comment]
Let me also elaborate with some of the pro's and con's.

Pro
- You can't obsolete everything as @phlax mentions
- You can't add N+ units with subsequent consequences
- You can't add units that have already been removed via a template update

Cons
- We need special handling for terminology where we do want someone to be able to add units
- As an admin you can't use upload to be able to make template updates

**Comment by phlax** [comment]
>  -  We need special handling for terminology where we do want someone to be able to add units
>  - As an admin you can't use upload to be able to make template updates

these can be pretty easily addressed
