### ISSUE TITLE
Missing Edit Profile link

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4309]
I updated to the latest version of pootle (git version), but i do not find anymore the link to edit the public profile. I checked my locale files for pootle and the line result to be translated just in case. If i check on the source code of the page, there are the tags but no link in it, is it a bug or what?

-- EDIT --
Neither with the english version of pootle the line shows. i just tested without my localized files... it doesn't change at all...

![Pootle - Missing Edit Link](https://dl.dropboxusercontent.com/u/89718989/pootle_edit.jpg)

**Comment by unho** [comment]
The link to edit the public profile is at the bottom of the public profile. Perhaps when you updated your Pootle you didn't recreate the assets. This is usually necessary when upgrading using a checkout from git.

**Comment by julen** [comment]
What you see in the screenshot is the mount point for the edit button; that's always there, nothing wrong with it. Note however the edit button is only displayed if you are logged in as the user of the profile you are visiting. If that's the case, please check the devtools console for errors.

**Comment by JohnnyKing94** [comment]
@unho since i already said in my previous issue i made the assets successfully (it only skipped one thing) here: https://github.com/translate/pootle/issues/4305#issuecomment-166344097
I don't think they are the assets

@julen i'm logged and i'm checking my personal profile, i do not see anyway my edit link... pls tell me where is this devtools console, so i will check it right now

**Comment by JohnnyKing94** [comment]
Now it appeared after I translated/made a revision of a string... WEIIIIRD...

**Comment by julen** [comment]
My assumption is you were getting a stale (cached) copy.

We haven't seen any similar reports during the time this code has been live, and taking into account there are no steps to reproduce it and it's not happening to you anymore, I'll proceed to close this. Feel free to reopen if you experience this again. Thanks for the report!
