### ISSUE TITLE
Create submissions when units are marked as obsolete

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4318]
We need to clarify all cases when submissions have to be created.
There are confusing things when we can expect submission is created but it's not.
For instance: submissions are created when units are resurrected but not when they are marked as obsolete.

**Comment by phlax** [comment]
yep, agree. maybe we can use this ticket to list the events that trigger submissions (and with what parameters etc), and which events are not currently covered

**Comment by phlax** [comment]
i believe this is now resolved
