### ISSUE TITLE
Optimisation images

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4333]
Some of our png's aren't completely optimal.  Use optipng or similar to reduce the size of the various images.

**Comment by dwaynebailey** [comment]
Also need to somehow include this in ``make sprite``

**Comment by iafan** [comment]
Side note: we've been talking with @julen recently on switching from PNG to SVG sprites. The primary reason for this is to support high-DPI displays, but this may also reduce the size of our assets.

**Comment by dwaynebailey** [comment]
@iafan that would be good, sprite.png is a big offender.
