### ISSUE TITLE
Editor templates broken in non-debug mode

### ISSUE THREAD

**Issue by julen** [translate/pootle#4348]
Since switching to Django 1.8 in master, the [scripts section of the editor templates](https://github.com/translate/pootle/blob/master/pootle/templates/editor/_scripts.html) doesn't render when `DEBUG = False`.

I might be doing something wrong, but I tried removing any template customizations we have, also clearing out caches, trying different browsers, always with the same result. I can reproduce this locally and in our staging server.

**Comment by phlax** [comment]
@julen we have the same problem on MLO - I tested against default install and it seemed to work ok

im not sure of exactly the problem, but for some reason the browser/index.html template is not being included by overextends

**Comment by iafan** [comment]
If this isn't an easy fix, can we undo switching to Django 1.8 until this is resolved? I'd prefer the related commits to be moved to a side feature branch so that master is stable.

**Comment by phlax** [comment]
@iafan leave this with me - i reckon we can resolve it one way or another

**Comment by iafan** [comment]
Thanks, @phlax! This is quite urgent for us as prevents testing and a release, so hope to hear some news from you in this soon.

**Comment by julen** [comment]
Sorry @phlax it seems we have been working on this at the same time, and no one self-assigned it — I only did it before trying to push, when I found the clash with the latest changes.

**Comment by phlax** [comment]
> @iafan leave this with me

either way - im much happier with the solution i committed

**Comment by julen** [comment]
Feel free to revert to yours if you see it necessary. As a side note, these XHR templates and its supporting code is condemned to go away in the near future.

**Comment by dwaynebailey** [comment]
@phlax @julen it would be nice to avoid such duplicate work in future.  It kinda pains me to think that you both spent Friday night coding on the same problem.  We PR to allow discussion and this commit and revert looks like it really wanted some discussion.  It might be good to recap or review our ideas of how and when we PR and how and when we land code to allow

**Comment by julen** [comment]
@dwaynebailey definitely. IMHO this is an edge case, and using the assign button right from the start should avoid similar cases in the future.
