### ISSUE TITLE
Feature request of direct download only translatable strings

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#436]
*Originally posted by Aijin Kim:*

This is a feature request from OO.o community.

Currently, Pootle user only can extract translatable -fuzzy and untranslated- strings from a downloaded file with pofilter. 
However it'd be helpful if it's also possible to directly download only translatable strings from Pootle. In the case that there is small volume to be translated in a big file, this feature must be useful.

**Comment by julen** [comment]
A lot changed in Pootle during the last few years, andwWe're thinking about some specific ways to address this (and even provide more), so we will open a separate ticket for tracking such work.
