### ISSUE TITLE
Missing on_commit attribute in psycopg2

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#4390]
Since the [check for `connection.on_commit`](https://github.com/translate/pootle/blob/afcf9d66c0cae31f57ac16f3a025202dc381aec8/pootle/checks.py#L364-L377) was added, the LXDE pootle install fails it despite being `DATABASES["default"]["engine"]` being set to use psycopg2.

Any idea why that would be?

**Comment by phlax** [comment]
@jleclanche are you using transaction_hooks?

**Comment by jleclanche** [comment]
Not anywhere in particular.

**Comment by phlax** [comment]
see here for relevant docs: 

https://pootle.readthedocs.org/en/stable/server/postgresql_installation.html#database-backend

**Comment by jleclanche** [comment]
Right. ok. you might want to make this clearer in the upgrade docs, I completely missed it.

**Comment by phlax** [comment]
its about to go away - so not point in changing i reckon - closing ticket
