### ISSUE TITLE
Issues when pootle is running in a subdirectory

### ISSUE THREAD

**Issue by sreichholf** [translate/pootle#4397]
I've recently upgraded to pootle 2.7.3b1 and stumbled upon some issues when pootle is installed in a subdirectory.

Our pootle is running on https://www.dream-multimedia-tv.de/pootle
The first Place where i came across the issue is the password reset mechanism.

The POST request is then trying to send the data to /pootle/pootle/... instead of /pootle/...

The second is that the "last action" in /projects is missing the /pootle and points to e.g. /de/... instead of /pootle/de/...

I've worked around the password reset issue using an internal rewrite rule. The second one is not pressing at all but as our pootle is accessed through a reverse proxy it's not fixable in using a simple redirect or rewrite

**Comment by julen** [comment]
Thanks for your report @sreichholf, let me reply each point separately.

> The POST request is then trying to send the data to /pootle/pootle/... instead of /pootle/...

Is this happening when submitting the form in a URL like `/pootle/accounts/password/reset/key/<36-digit-key>/`? If so, this is possibly a bug.

> The second is that the "last action" in /projects is missing the /pootle and points to e.g. /de/... instead of /pootle/de/...

Do you have `FORCE_SCRIPT_NAME = '/pootle'` set in your settings? Without this, the background processes that calculate stats can't infer that you are running under a non-root location, and the URLs it'll generate won't be correct. 
Once that is set, you will need to restart the RQ workers for the changes to take effect, and also run `refresh_stats` to fix the values for the last action columns.

**Comment by sreichholf** [comment]
First: Exactly. The "double pootle" is happening with the "password/reset/key" but only when submitting. The link in the email is correct :).

For the second: Restarting the rq workers actually did the job (i tried the refresh but without restarting the worker...)! 
As a suggestions the documentation should probably have at least a sentence or two about installating pootle in non-domain-roots :)

Thanks for your immediate reply and help.
As said the first can be fixed using a simple rewrite rule in the style of: 
> RewriteRule ^/pootle/pootle(.*)$ /pootle/$1 [PT,

**Comment by julen** [comment]
Thanks for confirming @sreichholf.

I just pushed a fix for the first one, it'd be great if you could verify that does the trick for you (will keep this issue open in the mean time).

Regarding docs, any suggestions on improving it are welcome, also in the form of PRs.

**Comment by sreichholf** [comment]
The fix looks good here. Passord changing now works as expected!
Thanks again!

I'll have a look the docs soon :)

**Comment by julen** [comment]
@sreichholf so are you willing to give this a try? No problem if you are not :wink: — just checking if anyone else should go ahead with it.

**Comment by phlax** [comment]
@sreichholf @julen is this bug fixed? can we close the ticket?

**Comment by julen** [comment]
The bug was fixed, the documentation part hasn't been addressed.

**Comment by unho** [comment]
@sreichholf @julen I would appreciate if you can review the fix proposed in #4536.
