### ISSUE TITLE
When visiting some user profile that user is displayed as the currently logged in user

### ISSUE THREAD

**Issue by unho** [translate/pootle#4402]
For example when visiting https://mozilla.locamotion.org/user/system/ (either logged in as any user other than `system` or as anonymous) the `system` user is displayed as the user currently logged in (upper corner).

**Comment by julen** [comment]
This is fixed in master (cf. #4401).

**Comment by unho** [comment]
I was using latest master and for some reason I got this. Now it works despite I didn't change anything. Anyway nice to see this scary one gone.
