### ISSUE TITLE
Ensure language/project/TP views have the same behavior

### ISSUE THREAD

**Issue by julen** [translate/pootle#4407]
The main browse, translate and export views have recently been moved to Class-Based Views (CBV), however some other views within the same scope still remain as Function-Based Views (FBV).

While this *per se* is not good or bad, behavior-wise there are some inconsistencies that could be addressed if the FBVs are converted to CBVs. 
This for example applies to using canonical language names everywhere (#4381): the permissions, special characters and terminology views expose a different behavior.

So let's aim for a consistent user experience in this regard.

**Comment by phlax** [comment]
@julen yep - intended to move some of the other views to CBVs - however some eg the new get_units with separated search backend do very little and dont really warrant the shift.

**Comment by phlax** [comment]
@julen can i close this as there is work going on on the specific view functions/classes?

**Comment by julen** [comment]
Cool, glad to hear so! Closing.
