### ISSUE TITLE
[Regression] Cross-language translation views return no results

### ISSUE THREAD

**Issue by julen** [translate/pootle#4411]
Cross-language translation views are returning no results for any operation performed in there, be it accessing them without filters, with filters or search. This can be reproduced in any URL such as `/projects/<project-code>/translate/<path/to/resource.ext>/`.

By inspecting the generated SQL I believe there's a syntax _error_ (although MySQL treats is as regular text it seems):
```sql
SELECT `pootle_store_unit`.`id`,
       `pootle_store_store`.`pootle_path`
FROM `pootle_store_unit`
INNER JOIN `pootle_store_store` ON (`pootle_store_unit`.`store_id` = `pootle_store_store`.`id`)
INNER JOIN `pootle_app_translationproject` ON (`pootle_store_store`.`translation_project_id` = `pootle_app_translationproject`.`id`)
INNER JOIN `pootle_app_project` ON (`pootle_app_translationproject`.`project_id` = `pootle_app_project`.`id`)
WHERE (`pootle_store_unit`.`state` > -100
       AND NOT (`pootle_store_store`.`pootle_path` LIKE BINARY '/templates/%')
       AND `pootle_app_project`.`code` = 'android_evernote'
       AND `pootle_store_store`.`pootle_path` REGEXP BINARY '/[^/]{,255}/project/resource.po$')
ORDER BY `pootle_store_store`.`pootle_path` ASC,
         `pootle_store_unit`.`index` ASC;
```

The regexp says `[^/]{,255}`, however according to the [MySQL docs on regular expressions](http://dev.mysql.com/doc/refman/5.7/en/regexp.html), a minimum value must be provided for the repetition operator. Setting it to `2` as in `[^/]{2,255}` does the trick for me (a language code will at least have 2 characters).

Could you please confirm the behavior @phlax?

**Comment by phlax** [comment]
hi @julen - yep i can confirm the bug and fix - apologies for this

**Comment by julen** [comment]
No problem, none of us realized as you see.
