### ISSUE TITLE
Needs docs on how to start with a new project's language

### ISSUE THREAD

**Issue by haf** [translate/pootle#4417]
In this case we're using react-intl for which we can export some file: what file sort is up to us.

http://docs.translatehouse.org/projects/pootle/en/latest/server/commands.html#commands

Doesn't seem to mention how to add languages. Again, I can't find the 'add language' button in the GUI. The links in the "Getting Started" guide talk about admin stuff: http://docs.translatehouse.org/projects/pootle/en/stable-2.7.3/server/installation.html#next-steps but I want to get cracking with my translations... How do I do that?

Optimal would be the flow of: "Now upload your XLIFF file [Browse...]" and then "This file is assumed to be your project's default language, 'en', please add more languages [Multi-select] [OK]".

This screen is "UGH!" 
<img width="1138" alt="screen shot 2016-01-22 at 17 54 49" src="https://cloud.githubusercontent.com/assets/193115/12517087/49f65a7c-c131-11e5-82d6-bfd2bf03db35.png">

**Comment by JohnnyKing94** [comment]
1) Create the project through the admin panel
2) Go to the project folder via ftp
3) Upload your xliff template file in that folder
4) Run the command "pootle update_stores --project=myprojectname"
5) Wait... and that's it

**Comment by haf** [comment]
That doesn't work; no project folders are created by pootle. Or they aren't in the working directory where pootle is started.

**Comment by unho** [comment]
Project directory must be already in place before creating the project through the admin panel. I recommend to put the files in place before creating the project if possible (translation projects would be created automatically).

**Comment by unho** [comment]
This has been fixed in d58a599a. So closing this issue.
