### ISSUE TITLE
refresh_scores does not refresh scores

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4418]
``refresh_scores`` in fact cannot refresh any scores.  The only code path allows ``--reset`` to zero. The code didn't seem to ever be able to recalculate the scores.

The initial docs seems to indicate that it will recalculate the score. However, the code in ``handle()`` only ever had a path for ``--reset`` which sets things to zero.

Some options

1. Fix the command
2. Correct the docs and rename to command to ``reset_scores``.

**Comment by dwaynebailey** [comment]
@ta2-1 are you able to shed some light on this?

**Comment by ta2-1** [comment]
@dwaynebailey, your description is very right. I think that we need to fix the command.  It'll be necessary to recalculate checks on existing installations after https://github.com/translate/pootle/issues/4299 issue is addressed.

**Comment by ta2-1** [comment]
Fixed in #4427.
