### ISSUE TITLE
Add docs on how user score is calculated

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4428]
@julen, @iafan can you put a link to the your doc and then we'll decide where it can be added to Pootle docs.
I'd suggest to create a new file in `docs/server/user_score.rst`.

**Comment by iafan** [comment]
@ta2-1 I shared the doc with you.

**Comment by ta2-1** [comment]
@iafan thanks.

**Comment by ta2-1** [comment]
There is a current version of docs [here](https://github.com/translate/pootle/wiki/User-score-calculation).

**Comment by iafan** [comment]
:+1:

**Comment by ta2-1** [comment]
Old scores were removed in 293255c423877a185db4aec51788ecd0b8e1ea3c and nearby.
