### ISSUE TITLE
Insist on having different redis DBs for (default, rq, stats) caches

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4449]
Working on #4319 I realised that if user put all data to the same redis DB (it's possible to do via custom settings now), then he can remove all cache instead of specific one.
Currently our checks check that redis backend is used for default cache and we are able to connect to redis by RQ connection.
Seems it's worth to insist on having different redis DBs for default, rq, stats. Let's adjust our checks accordingly.
Re #4319: probs it's worth to have one command like `clear_cache` that can accept different options (`--default`, `--rq`, `--stats`) instead of `clear_stats` etc. (seems that we don't have `clear_cache` at all now)?

**Comment by unho** [comment]
IMHO we should enforce to have different Redis DBs.

Regarding the command I agree that it might be better to have `clear_cache` that accepts different options, but the issue #4319 is fixing is #4219 which is only about `clear_stats`, so perhaps it is better to first land a fix for #4219 and then rework it into `clear_cache`.

**Comment by ta2-1** [comment]
Fixed in https://github.com/translate/pootle/commit/9b18a2ae479666258864ebbc29e26cf3efcec89b.
