### ISSUE TITLE
newlines should be converted to spaces when saving data in po file

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#445]
*Originally posted by anton:*

NOTE: I have a very small example here to illustrate what happens,
      it does not produce the bug, but you can easily reproduce it yourself.

Assume I translate a text in pootle which is a little bit long,
lets say:

Good morning how are you.

In the po file I would have:
msgstr "Good morning how are you."

If I break the text on 2 lines (assume we have a real big text) 
by pressing the Enter key of my keyboard like:

Good morning 
how are you.

Then the po file looks like:

msgstr "Good morning"
"how are you."

and after that (refresh page, or export po file) you will see the 2 words collated: 

Good morninghow are you.

A workaround is to add a space at the line end before doing a line break .-(

But this is a thing you will easily forget.

**Comment by dwaynebailey** [comment]
Don't think this is an issue really/anymore so closing
