### ISSUE TITLE
Uploading files fails with blank screen

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4450]
Uploading a single PO files causes Pootle to hang on a blank screen.

Steps to replicate:

1. Downloaded a zip of file
2. Edited a single unit in a single file
3. Uploaded that single file in the dir in which it appears (though that shouldn't make a difference)
4. Screen goes white and nothing uploaded.  Reload and you get to Pootle page
5. Check file and nothing has been uploaded.

**Comment by ta2-1** [comment]
Closing since everything related was addressed.
