### ISSUE TITLE
Download and upload buttons don't appear for a single file

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4451]
When you browser into a [single file](https://mozilla.locamotion.org/en_ZA/firefox/browser/branding/official/brand.dtd.po) you don't have access to any of the upload and download links.

Thus if you want a single files in a large directory you have to [download the whole directory](https://mozilla.locamotion.org/en_ZA/firefox/browser/branding/official/).

**Comment by unho** [comment]
This might be a regression from when views have been splitted https://github.com/translate/pootle/commit/02a24f71e40ec63701087bb993414c14280eb402.

**Comment by unho** [comment]
I think this can be fixed by moving `get_upload_widget` to `TPBrowseBaseView`.

**Comment by ta2-1** [comment]
@unho, yes, you were right. just created PR with the fix.
