### ISSUE TITLE
Add missed TP view tests

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4462]
Issues #4450 and #4451 were fixed but tests are still necessary.

**Comment by phlax** [comment]
nice one - i think the blocker for this is to add code to allow setting request.user in paramatrized fixture

**Comment by ta2-1** [comment]
@phlax I think you meant disabled projects here and there is an issue for this https://github.com/translate/pootle/issues/4445.

**Comment by ta2-1** [comment]
Tests were added in #4471. Closing this issue.
