### ISSUE TITLE
empty sidebar when browsing project

### ISSUE THREAD

**Issue by blake-sc** [translate/pootle#4467]
In master branch and recently updated branches/tags the sidebar appears to be empty when browsing a project - there is no content in it. In 2.7.3b1 it works fine and shows the appropriate import/export options.

**Comment by ta2-1** [comment]
is it duplication of #4451?

**Comment by phlax** [comment]
could well be - @blake-sc do you have any project/lang announcements that you were expecting or just the up/download widget?

**Comment by blake-sc** [comment]
It is undoubtably a related issue but the description in #4451 seems to imply a problem where the buttons don't appear when browsing a single file - this issue is the up/download widget does not appear at any browse depth. I checked it and project announcements do appear so it's only the up/download widget.

**Comment by phlax** [comment]
@blake-sc it seems you have the other bug we are just looking at - there is a fix that is being worked on by @ta2-1 atm - #4466

**Comment by blake-sc** [comment]
Yes, deleting those lines makes the buttons return, so that is the issue, thanks phlax.
