### ISSUE TITLE
No way to run command with `--no-rq` and no workers

### ISSUE THREAD

**Issue by julen** [translate/pootle#4493]
I gave a shot to the `--no-rq` flag and unless I'm doing something wrong, it doesn't seem to work as advertised.

With active workers running in the background, a nice warning prompt is displayed before proceeding:
```console
$ ./manage.py update_stores -v3 --project=foo --force --overwrite --no-rq

You currently have RQ workers running.

Running in synchronous mode may conflict with jobs that are dispatched to your workers.

It is safer to stop any workers before using synchronous commands.

Do you wish to proceed? [Ny]
```

After stopping the workers though:
```console
$ ./manage.py update_stores -v3 --project=foo --force --overwrite --no-rq
System check identified some issues:

WARNINGS:
?: (pootle.W001) No RQ Worker running.
	HINT: Run new workers with manage.py rqworker
```

Just in case I tried setting `DEBUG = False` but the result is the same.

**Comment by phlax** [comment]
@julen i believe that ``--no-rq`` works as expected, i use it pretty regularly. I think the warning is just that.

**Comment by julen** [comment]
I must have added that it wasn't doing anything after running the command. It turns out I had console logging turned off, and after switching it on I see it was doing nothing because of an unrelated error. I can confirm it works fine now, sorry for bothering.
