### ISSUE TITLE
User profiles are broken for anonymous users

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4512]
```
AttributeError at /user/phlax/

'AnonymousUser' object has no attribute 'has_manager_permissions'
```

i reckon the overridden anon object needs to provide this method

**Comment by julen** [comment]
This looks like a caching issue on your side — by no means you should ever get `AnonymousUser`. You can print/pdb `self.request.user` in `UserDetailView`'s `get_context_data()` to confirm.

**Comment by phlax** [comment]
@julen it was pretty easy to reproduce - but ill test again - also on our staging (where i found it) caching is switched off.

**Comment by phlax** [comment]
...in fact i know rem - i added a bit of code to fix it - so i could get on with what i was testing

**Comment by phlax** [comment]
hmm - im just wondering if its because im missing the necessary middleware

**Comment by phlax** [comment]
k - closing this - it was because i had custom middleware - and it wasnt updated
