### ISSUE TITLE
Can’t navigate to browse/translate from admin pages

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4524]
1. Go to a project
2. Go to TP admin using the dropdown.  Browse->Languages
3. Return to the Browse or Translate view.  Nothing happens
4. Move to the Permissions view, we move
5. Try move to Browse or Translate view again.  Nothing happens.

**Comment by julen** [comment]
This affects any function-based view, i.e. admin pages basically (regressed in 8fe18be59a).
