### ISSUE TITLE
Force creation of foreign key constraints on existing installations

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4525]
If you compare DB schema that can be created via `initdb` (on MySQL InnoDB) from a scratch with DB schema of existing installations there will be a lot of differences. 
Specifically there are no constraints on foreign keys.
It was caused after DB were migrated to InnoDB from MyISAM engine without creating necessary constraints.
Also I have noticed that some necessary indexes (like `pootle_store_unit.submitted_on`) can be absent.
Let's force creation of necessary constraints and indexes for existing installations.

**Comment by phlax** [comment]
we have taken a different approach to this with schema tool, so closing this
