### ISSUE TITLE
Enable new language in UI should added to RQ queue

### ISSUE THREAD

**Issue by unho** [translate/pootle#4534]
Enabling a new language for a project in UI should create a new task and run it with RQ in order to avoid blocking the user's browser in scenarios with large projects or when the server resources are heavily used.

Obviously we need to communicate in some way (perhaps with the [Django messages framework](https://docs.djangoproject.com/en/1.9/ref/contrib/messages/)) that the a new task have been created and that it will be run on the background. We probably would want to list these tasks in the admin dashboard. When the task is completed we might want to communicate that as well.

We will have to consider if it is ok to append the task to a queue that can have a lot of tasks, where probably the user would like the new language to be enabled as soon as possible.

There are related issues: #3786, #3577.

**Comment by unho** [comment]
@phlax pointed out that we would like to prevent the task from being initiated over and over. Instead communicate that the task was already created.

**Comment by unho** [comment]
For reference, the ability to enable a TP through UI was added in https://github.com/translate/pootle/pull/3918 and some subsequent commits that can be located by checking the https://github.com/translate/pootle/issues/3877 issue.

**Comment by julen** [comment]
IIRC, this also affects to creating new languages/projects via the admin UI when the files are already on disk.

**Comment by unho** [comment]
No, not the same. When a language is added we just save a new record in database (no disk I/O involved at all). When a project is added we only save it in database but you need to run `update_stores` to actually pull in the translations and calculate all the stats, see [Create a new project](http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html#creating-the-project) instructions.

**Comment by ta2-1** [comment]
@unho I'm not sure I follow. But what is the diff between:
- just save a new record in DB
- only save it in DB?

Having to say that we always trigger FS scanning stuff here https://github.com/translate/pootle/blob/master/pootle/apps/pootle_translationproject/models.py#L475-L490 in both cases.

**Comment by unho** [comment]
> @unho I'm not sure I follow. But what is the diff between:
- just save a new record in DB
- only save it in DB?

They mean the same. Reworded my comment to prevent confusion in the future.

> Having to say that we always trigger FS scanning stuff here https://github.com/translate/pootle/blob/master/pootle/apps/pootle_translationproject/models.py#L475-L490 in both cases.

If I am not wrong that only happens when those are not created. In my experience additional the translations are not automatically pulled in when creating a new project, something that we hopefully can fix once we add the ability to run such tasks in the background.

**Comment by ta2-1** [comment]
Fixed in #4580.
