### ISSUE TITLE
django.utils.log.NullHandler removed in Django 1.9

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#4537]
Pootle currently fails on Django 1.9:

```pytb
ValueError: Unable to configure handler 'null': Cannot resolve 'django.utils.log.NullHandler': No module named NullHandler
```

This is due to [this](https://github.com/translate/pootle/blob/634167af87a31220efc295626718dc1f5ca45b3b/pootle/settings/25-logging.conf#L40) logging rule. Removing it should fix it.

Also see: [SO#34348360](https://stackoverflow.com/questions/34348360/cannot-resolve-django-utils-log-nullhandler)

**Comment by julen** [comment]
Thank you for the report @jleclanche! In case you are interested, there's already a WIP PR to enable Django 1.9 support (#4349), although AFAIK that won't move forward until the next release is out.

@dwaynebailey, is this perhaps the logging issue you were hitting in your tests?

**Comment by dwaynebailey** [comment]
@julen don't think its the same logging issues.  Mine is trying to get the logging results to be testable.  @jleclanche thanks for spotting, surprised that I didn't see that one earlier.

**Comment by dwaynebailey** [comment]
@jleclanche can you use latest master as 603f02015a4f9783cc4a19211d5d5b89a8edd54f already fixes this (sadly I must have messed up the rebase on that commit)
