### ISSUE TITLE
Add Welsh MT server

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4538]

**Comment by techiaith** [comment]
Further details of API service here:

https://github.com/PorthTechnolegauIaith/moses-smt/blob/master/docs/APIArlein.md#moses_smt_machine_translation_online_api

**Comment by unho** [comment]
@phlax Is this fixed in https://github.com/translate/pootle/commit/3d4ee5e5a7f9fadd0016d05be19229d8cee3cdfb ?

**Comment by unho** [comment]
@phlax confirmed that this has been fixed in https://github.com/translate/pootle/commit/3d4ee5e5a7f9fadd0016d05be19229d8cee3cdfb so closing.
