### ISSUE TITLE
Catalan suggested for Breton translation

### ISSUE THREAD

**Issue by tornoz** [translate/pootle#4539]
Sometimes, Brazilian Portuguese suggestions show up in the translation memory for Breton language. Example : https://mozilla.locamotion.org/br/firefox/translate/browser/branding/official/brand.properties.po#unit=8517633 (Suggested from TM : Sincronitza, which is definitely not Breton.)

Issue probably comes from the locale codes (br or br_FR for Breton and pt_BR for Brazilian Portuguese) which is a very common issue on the web for those two languages.

**Comment by dwaynebailey** [comment]
@tornoz 

Found the source.  Seems to be some poluted strings imported into amaGama.  They're actually Catalan strings it would seem.

```
  sid  |    text     |    lang     
-------+-------------+-------------
 31038 | Sincronitza | ca
 31038 | Sincronitza | ca_valencia
 53977 | Sincronitza | ca_valencia
 53977 | Sincronitza | ca
 31038 | Sincronitza | br
```

We'll need to update the data in amaGama to fix this.

**Comment by phlax** [comment]
Closing this as this needs amagama to be updated rather than fix in pootle
