### ISSUE TITLE
Unable to connect to WSGI daemon process 'pootle'

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4542]
Sometimes when i browse my pootle site, i get the error below on the _error.log_ while on the page i get "**503 Service Temporarily Unavailable**"... i never had this kind of problem when i was with Ubuntu 12.04, now with Ubuntu 15.10, i don't know why, but it seems this new version of mod_wsgi is broken or i don't know... As it stated on this [guide](https://code.google.com/archive/p/modwsgi/wikis/ConfigurationIssues.wiki), i even added `WSGISocketPrefix /var/run/wsgi` but it isn't working, i keep having this error while browsing...

```
Sun Mar 06 19:38:14.145791 2016] [mpm_prefork:notice] [pid 505] AH00171: Graceful restart requested, doing restart
[Sun Mar 06 19:38:14.180806 2016] [wsgi:error] [pid 10147] (2)No such file or directory: [client 79.52.36.47:48403] mod_wsgi (pid=10147): Unable to connect to WSGI daemon process 'pootle' on '/var/run/wsgi.505.24.2.sock'., referer: http://translate.tamrielunlimited.it/admin/users/
[Sun Mar 06 19:38:14.234485 2016] [wsgi:error] [pid 10142] Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of Connection<host=127.0.0.1,port=6379,db=1>> ignored
[Sun Mar 06 19:38:14.237127 2016] [wsgi:error] [pid 10141] Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of Connection<host=127.0.0.1,port=6379,db=1>> ignored
[Sun Mar 06 19:38:14.237400 2016] [wsgi:error] [pid 10141] Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of Connection<host=127.0.0.1,port=6379,db=2>> ignored
```

**Comment by dwaynebailey** [comment]
Perhaps this helps http://stackoverflow.com/questions/29272726/2no-such-file-or-directory-mod-wsgi-pid-24507

**Comment by julen** [comment]
@JohnnyKing94 this looks like something strictly related to mod_wsgi and serving any Django application, so I'm afraid there's nothing Pootle can do for you here.

**Comment by JohnnyKing94** [comment]
This is the list applications installed under my enviroment... i do not have any other envs installed

```
arrow==0.7.0
cffi==1.5.2
click==6.3
cryptography==1.2.3
cssmin==0.2.0
diff-match-patch==20121119
Django==1.7.11
django-allauth==0.24.1
django-assets==0.11
django-contact-form==1.0
django-overextends==0.4.1
django-redis==4.3.0
django-rq==0.9.0
django-transaction-hooks==0.2
elasticsearch==1.6.0
enum34==1.1.2
Flask==0.10.1
glue==0.11.1
idna==2.0
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.7.3
lxml==3.5.0
MarkupSafe==0.23
MySQL-python==1.2.5
ndg-httpsclient==0.4.0
oauthlib==1.0.3
Pillow==3.1.1
Pootle==2.7.2
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
python-dateutil==2.5.0
python-Levenshtein==0.12.0
python-memcached==1.57
python-openid==2.2.5
redis==2.10.5
requests==2.9.1
requests-oauthlib==0.6.1
rq==0.5.6
rq-dashboard==0.3.6
six==1.10.0
sphinx-me==0.3
translate-toolkit==1.13.0
urllib3==1.14
webassets==0.11
Werkzeug==0.11.4
```

**Comment by dwaynebailey** [comment]
@JohnnyKing94 from the link provided [above](https://github.com/translate/pootle/issues/4542#issuecomment-193817810) this seems to be a Apache reload issue.  But only you can confirm that for us.  We'd really appreciate if you could give feedback related to the comments myself and other devs have made.

Please realise that other people who might get stuck like you will look here for help.  Thus we really do ask that you help us bring such issues to a close.

I'd appreciate if you could follow the advice in the above comment and give us some feedback as to whether that fixes the issue.

For now I'm assuming that it does and will be closing the bug. Please reopen if the problem persists.  But please also comment as to whether the hard reload solves the issue.
