### ISSUE TITLE
Force current revision value check

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4544]
If revision key is absent `Revision.incr()` returns 0 every time because of this [try...except](https://github.com/translate/pootle/blob/128f4275f1d31d4b82b82ed62dd947ad54c86f1d/pootle/core/models.py#L71-L74)

This can happen very likely after flushing redis DB. We need to check current global revision value before any pootle command is run.
Revision should be equal `Unit.max_unit_revision()` value.

**Comment by phlax** [comment]
@ta2-1 im not sure we want to do this on every command call. Could we add a startup check to force the user to reset the revision if required

**Comment by unho** [comment]
The real problem is that a Redis DB flush wips the Revision. Unless you do a full flush (something unlikely and that should be done on purpose), the Revision should be kept.

**Comment by julen** [comment]
How likely are admins to flush their DBs? Unless messing up with internals, one rarely sees this happening. Hence adding this check before any command for such an edge case I'd say is an excessive penalty.

**Comment by ta2-1** [comment]
@julen what about loading DB dumps?

**Comment by ta2-1** [comment]
@julen [this code]( https://github.com/translate/pootle/blob/128f4275f1d31d4b82b82ed62dd947ad54c86f1d/pootle/core/models.py#L71-L74) will not increment revision if there exists no revision key in cache. I think this is wrong.

**Comment by ta2-1** [comment]
> Could we add a startup check to force the user to reset the revision if required

@phlax do you mean to check the revision counter and correct its value implicitly if it's necessary before we start server?

**Comment by julen** [comment]
@ta2-1I'd argue loading DB dumps is not a common use-case for administrators, although it seems we are having different users in mind. Making this check for _any_ command as you suggest is still excessive for the common use cases, although _some_ commands might as well need it to ensure they can run properly.

**Comment by ta2-1** [comment]
@julen the query to get `Unit.max_revision()` takes less than 0.01 sec. And having this check will allow us to avoid unexpected errors.
Having to say that I wondered that we have a lot of data checks such as `check_duplicate_emails`.
So I don't understand why it's excessive.

**Comment by phlax** [comment]
lgtm

**Comment by julen** [comment]
Was this fixed by #4545?

**Comment by ta2-1** [comment]
Yes, it was fixed in https://github.com/translate/pootle/pull/4545.
