### ISSUE TITLE
Whitespace markers at end of source text can be confusing

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4558]
Currently Pootle does this:

1. It highlights whitespace at the end of a string.  It does this is a harsh red block and squiggle
2. Characters that are not easily typed are also highlighted with a soft surround and are clickable, e.g. end of string elllipsis.

However the two don't overlap.  Thus you can't click on the end of string whitespace marker to copy that character into the target text.

Once a translator learns that this is a space they can type it themselves.

To work around this problem we should:

1. Provide a tooltip to describe the character highlighted
2. Use the same special character copy mechanism so that a translator can simply click the marker to copy the character into the target text.

**Comment by julen** [comment]
I'm closing this based on the existing work in #4171, which makes this a non-issue.
