### ISSUE TITLE
Update from templates in Pootle 2.7.2 and various other annoyances

### ISSUE THREAD

**Issue by xperseguers** [translate/pootle#4559]
I'm using Pootle since a few years but I'm facing problems with 2.7.2. Here is an example :

![problems](https://cloud.githubusercontent.com/assets/646805/13702588/fa41f362-e78f-11e5-91f3-0a0059723937.png)

1. First problem is how to update translation from templates `update_from_templates` is gone and `update_stores` and `refresh_stats` does not help
2. Why is my templates project somehow marked as needing translations? When I go there, there is of course nothing to translate
3. Another issue is with available languages for the project:

![languages](https://cloud.githubusercontent.com/assets/646805/13702654/7b664cea-e790-11e5-82aa-0091e47e88e1.png)

4. Final problem with a hack I found is syncing db to disk. As I understand using `sync_stores` should be sufficient, but even when waiting a long (for statistics, ...) I had absolutely no translations dumped to disk until I used:

```
./pootle-manage sync_stores --project=<name-of-project> --force --overwrite
```

Not sure this is supposed to be like that.

5. As you see on previous screenshot, somehow the yellow bar "Refreshing"... is never really going away although I have no failed jobs and 1 worker is running.
6. Last hint I did not find would be to know if it is possible to get translation suggestions based on similar texts in other projects or at least similar texts in same project but in another file.

Thanks for helping me with those annoyances

**Comment by xperseguers** [comment]
I tried to upload a file in XLIFF like it was possible in previous versions of Pootle but firstly it does not seem I can choose "where" to upload it and secondly upload was cancelled because
```Unsupported filetype 'AppResources.xlf', only PO files are supported at this time``` What does it mean? Looks like feature wise stable Pootle 2.7 is many steps behind previous versions ?!?

**Comment by xperseguers** [comment]
So by reading http://docs.translatehouse.org/projects/pootle/en/stable-2.7.3/features/templates.html I had the idea to manually modify my translated XLIFF files and then use `update_stores` and it works, new labels are now visible. So at this point it looks like on of the most important benefit of using Pootle is gone since I will have (at least for some time) to manually do its job and convert my `.resx` to `.xlf` (which is fine, since `.resx` is not supported anyway) but then merge labels to existing `.xlf` which is a pain.

**Comment by phlax** [comment]
hi @xperseguers sorry to hear you are having difficulties with the newer version.

I would need to check in the case of XLIFF specifically - but the old functionality for importing/exporting files through the CLI is the same as before - only the web UI has changed (as far as i am aware anyway).

The UI was changed as Pootle now uses the concept of ``Revisions`` and only PO really supports including revision headers in the spec (and possibly XLIFF) - so the web UI was restricted to PO.

In relation to other issues - can i suggest restricting tickets to 1 issue per ticket as it will make it much easier for us to help you.

Im really keen to make sure that the newer version of Pootle supports your existing use cases so will follow up early in the week. You can get more immediate support in our gitter channel:

https://gitter.im/translate/pootle

although the channel tends to be quieter at the weekend

**Comment by unho** [comment]
>  1 . First problem is how to update translation from templates `update_from_templates` is gone and `update_stores` and `refresh_stats` does not help

This is covered by http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html#adding-new-strings-to-existing-project Please note that despite `pot2po` looks like only works for Gettext PO it actually can deal with other formats such as XLIFF.


> 2 . Why is my templates project somehow marked as needing translations? When I go there, there is of course nothing to translate

Reported as https://github.com/translate/pootle/issues/4568


> 3 . Another issue is with available languages for the project:

Please report this as a separate issue.


> 4 . Final problem with a hack I found is syncing db to disk. As I understand using `sync_stores` should be sufficient, but even when waiting a long (for statistics, ...) I had absolutely no translations dumped to disk until I used:
> 
> ```
./pootle-manage sync_stores --project=<name-of-project> --force --overwrite
```
> 
> Not sure this is supposed to be like that.

If nothing changed in DB in relation to the files already present on disk, just `sync_stores` won't do anything. If you want to make sure that it syncs in any case, it is safe to run that command, but note it might be inefficient. Anyway perhaps in your case it was enough with just `--overwrite`.


> 5 . As you see on previous screenshot, somehow the yellow bar "Refreshing"... is never really going away although I have no failed jobs and 1 worker is running.

Perhaps it is still processing pending jobs. Check http://docs.translatehouse.org/projects/pootle/en/latest/server/rq.html?highlight=pending#working-with-failed-jobs to see how list pending jobs. This issue perhaps will be easier to work out if you drop by the support channel so one of us can help you.


> 6 . Last hint I did not find would be to know if it is possible to get translation suggestions based on similar texts in other projects or at least similar texts in same project but in another file.

It is possible if you enable the new Local TM feature: http://docs.translatehouse.org/projects/pootle/en/stable-2.7.2/features/translation_memory.html#elasticsearch-based-local-tm

**Comment by xperseguers** [comment]
I basically have my answers. thanks.
