### ISSUE TITLE
updatepofile/commitpofile needs to be moved to translate toolkit

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#456]
Depends on:

* [x] #522 Version control update raises Attributerror

*Originally posted by Suresh:*

Pootle/projects.py updatepofile/commitpofile can be moved to translate toolkit for accessing the version control operations from scripts. Currently only Pootle can make use of these.

**Comment by dwaynebailey** [comment]
With the whole VCS approach being relooked let retire this
