### ISSUE TITLE
Templates TP displays need translation count despite it shouldn't be translated

### ISSUE THREAD

**Issue by unho** [translate/pootle#4568]
![pending_templates](https://cloud.githubusercontent.com/assets/939880/13739830/b2a9b0ae-e9cd-11e5-993d-1e354f69ac74.png)

Picked from #4559.

Technically this should be skipped for any template language the project is using.

**Comment by ta2-1** [comment]
There is more related information:
- `non .po` projects have non-zero stats;
- `.po` projects have zero stats;

![image](https://cloud.githubusercontent.com/assets/682845/15892750/24d8099c-2d84-11e6-8d3c-29a8a56bed59.png)

Neither `.po` or `non .po` projects don't work properly.

What do we want to get:
- Template project should have non-zero total stats;
- Template project have zero `need work`, `translated` stats;
- Template project stats should not be counted in parent (Project) level.

and 
- Probably we have to allow to list units from templates but it can be another issue.

**Comment by unho** [comment]
Getting translations for templates TPs can be prevented by setting appropriate permissions when creating those template TPs.
