### ISSUE TITLE
Priority is displayed even if no virtual folders are being used

### ISSUE THREAD

**Issue by julen** [translate/pootle#4577]
This is a regression: in a server with no virtual folders, units still display a default priority of _1.0_.

**Comment by unho** [comment]
I don't think we should consider it a problem.

**Comment by julen** [comment]
Would you mind elaborating? Because this is indeed a problem with no virtualfolders: there's no point in taking up UI space to display irrelevant and confusing information.

**Comment by unho** [comment]
We denormalized priority to Unit to avoid having extra queries to check for VirtualFolders. What you suggest will require to check if virtualfolders app is enabled and VirtualFolderTreeItems exist for any Unit in the path being translated. I don't think it is such a big problem to display the priority if thus we avoid having additional queries.

**Comment by julen** [comment]
`Unit.priority` has been around since the end of last year, and this is a recent regression. In fact, `git bisect` points to 508e4c19a, which dates back to 3 days ago.
```python
priority = self.object.priority if 'virtualfolders' in settings.INSTALLED_APPS else None
```
is all what's needed. I'll PR the change.

**Comment by phlax** [comment]
great thanks @julen - you might need to change the test - not sure
