### ISSUE TITLE
Include users' e-mail addresses in dropdown list

### ISSUE THREAD

**Issue by leuce** [translate/pootle#458]
At present, the dropdown list for granting users permissions only contain their real names and their user names.  To find their e-mail addresses, the admin user must manually cross-reference the user names against the full list of user names for the entire Pootle server.

RFE:  include the users' e-mail addresses in the dropdown list, so that an admin user can more easily make contact with those translators.

**Comment by dwaynebailey** [comment]
Closing this, the issue exists, but we'll solve the permission thing on its own and that should solve this issue together with that.
