### ISSUE TITLE
Make `PootleCommand` use `nargs` for list-like arguments

### ISSUE THREAD

**Issue by julen** [translate/pootle#4591]
[argparse](https://docs.python.org/2.7/library/argparse.html) has a straightforward support for list-like CLI parameters via [`nargs`](https://docs.python.org/2.7/library/argparse.html#nargs).

In PootleCommand currently we use [`action='append'`](https://github.com/translate/pootle/blob/cc4d16d0fa1e4e0aab9ce3a5d0a26da0ae488e86/pootle/apps/pootle_app/management/commands/__init__.py#L41-L52) for list-like `--project` and `--language` args, however these could benefit from using `nargs='*'`, so that passing multiple project and/or languages via the CLI becomes less cumbersome for the user:

``` shell
--language <foo> <bar> <baz>
```

as opposed to:

``` shell
--language <foo> --language <bar> --language <baz>
```

A warning note though, as this might break existing user scripts.

**Comment by phlax** [comment]
as this now uses append, i believe the issue is addressed
