### ISSUE TITLE
Include language and project information in user list

### ISSUE THREAD

**Issue by leuce** [translate/pootle#460]
This RFE relates to bug #437.  The current user list in Pootle displays only the real name, user name and e-mail address of a user.  It would be great if the page could also contain which languages and which projects the users are listed under.  I suspect it may slow down the page load considerably if this is included in the HTML file, but perhaps it can be included in a downloadable CSV file...?

**Comment by unho** [comment]
@julen Is this already fixed in new master?

**Comment by julen** [comment]
The original report doesn't apply anymore in the sense that the *Quick Links* feature is long gone. Besides, keeping those language/project contributor lists in the permissions page drop-downs has resulted to be super expensive (see #3430).
