### ISSUE TITLE
Api create project, upload and pull file ?

### ISSUE THREAD

**Issue by kushia** [translate/pootle#4612]
Hi everyone,
I have to use the Pootle api for create projects, push files to translate and pull files translated.
I checked all the doc API who's here : https://pootle.readthedocs.org/en/stable-2.5.1/api/api_project.html#get-a-project

But there is nothing answering my questions.
Do you know how to push and pull files ?

Thanks everyone!

**Comment by unho** [comment]
2016-03-30 11:17 GMT+02:00 kushia <notifications@github.com>:

> Hi everyone,
> I have to use the Pootle api for create projects, push files to translate
> and pull files translated.
> I checked all the doc API who's here :
> https://pootle.readthedocs.org/en/stable-2.5.1/api/api_project.html#get-a-project
>
> But there is nothing answering my questions.
> Do you know how to push and pull files ?
>
Hi,
sadly Pootle API doesn't allow to push files to translate, so you will have
to run
https://pootle.readthedocs.org/en/stable-2.5.1/server/commands.html#update-stores
which requires access to the server where Pootle is being run. You should
be able to retrieve the files translated by using the API, but probably it
is simpler to use
https://pootle.readthedocs.org/en/stable-2.5.1/server/commands.html#sync-stores
which also requires access to the server.

Note that newer Pootle versions dropped the API.


Bye

**Comment by kushia** [comment]
Hi,
Thanks to you, I'm going to look at this! Thanks again!

**Comment by unho** [comment]
Closing since Pootle API is not present in newer Pootle and will be replaced by other feature.
