### ISSUE TITLE
Redirect loop when accessing project's languages admin

### ISSUE THREAD

**Issue by julen** [translate/pootle#4623]
If users with project administration rights (i.e. non-superusers) try to access a project's languages admin page, they will be stuck in a redirect loop, making it impossible to access such page.

git bisect points to 14e2326, although it might as well be any of the surrounding commits (they don't seem to work individually).

**Comment by phlax** [comment]
hi @julen afaict here https://github.com/translate/pootle/blob/master/pootle/apps/pootle_app/views/admin/languages.py#L19 only superusers have access to this view.

Not sure if im looking at the wrong view

**Comment by unho** [comment]
That view is actually the list of all languages. I think the view @julen is talking about is https://github.com/translate/pootle/blob/master/pootle/apps/pootle_project/views.py#L179

**Comment by phlax** [comment]
thanks @unho

**Comment by phlax** [comment]
@julen after further investigation it seems there are 2 problems here. The first is that the view doesnt have the correct permisions, i will fix that and close this ticket.

The second problem is that although django expects to be able to redirect a logged in user to the login page if they request a resource for which they dont have permission, the login widget appears to automatically redirect users back to the `next` page as they are logged in. I will open a separate ticket for that issue.

**Comment by phlax** [comment]
#4832 opened re the second issue
