### ISSUE TITLE
Store.update() is very slow with virtual folders

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4638]
I got numbers (for one TP in firefox project on mlo with moving all content to another folder [all obsolete, all resurrected]) how VFs affects update_stores:
`All done for update_stores in 0:02:12.122124`
`All done for update_stores in 0:42:16.228620`

So every unit adding or making it obsolete triggers VF auto-update stuff which is not performant.

**Comment by phlax** [comment]
not sure if we need to test this further, but im thinking its a lot faster now
