### ISSUE TITLE
Wrong unit numbering while translating

### ISSUE THREAD

**Issue by julen** [translate/pootle#4640]
While translating on MLO (which I assume is running something around current master), I experienced an odd unit numbering behavior in the editor: I could go further beyond the maximum number of units reported for my current filter (_incomplete_).

![editor_total_count_bug](https://cloud.githubusercontent.com/assets/16768/14380430/a153af9c-fd7f-11e5-8014-f50d4b460de6.png)

**Comment by julen** [comment]
Just confirming that I've hit this again on MLO.

As I see when units are first fetched, it reports the correct total units, however on subsequent requests to fetch units, the total is re-adjusted, leaving the UI in an inconsistent and illogical state for the user.

**Comment by phlax** [comment]
@julen what is get_unit_rows set to on your account?

**Comment by julen** [comment]
I guess you mean the _Number of Rows_ setting, which is set to 10, but AFAICT that's irrelevant. As mentioned, fetching units overwrites the total number of results anytime, instead of setting the total only on the first request.
