### ISSUE TITLE
RemovedInDjango19Warning with new commenting code

### ISSUE THREAD

**Issue by julen** [translate/pootle#4657]
When firing up the server, Django 1.9-related warnings are printed a few times:
```
django_comments/models.py:170: RemovedInDjango19Warning: Model class django_comments.models.Comment doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Comment(CommentAbstractModel):

django_comments/models.py:176: RemovedInDjango19Warning: Model class django_comments.models.CommentFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CommentFlag(models.Model):
```

**Comment by phlax** [comment]
@julen although annoying im not sure its a bug as such, it just means that these models will not work in django1.9 - but as we are not using them, i think its not a problem.

I am going to test on dj1.9 when i get chance

**Comment by dwaynebailey** [comment]
@phlax it does unfortunately potentially mask other issues and makes migration to Django 1.9 impossible till they're resolved :(  Same errors are being generated by Pootle FS code from what I can see.

**Comment by phlax** [comment]
@dwaynebailey from my understanding these are just warnings, and like i said the only problem would be if we were using these models, but were not. I could be wrong about this.

**Comment by phlax** [comment]
re pootle_fs for sure these need to fixed, im seeing similar problems with StaticPages, but it kinda deps on your config also

**Comment by unho** [comment]
@phlax These warnings fill the logs, so any relevant error or warning will be more difficult to find. I do think that the right thing is to make these warnings go asap.
