### ISSUE TITLE
Machine Translation is broken

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4660]
This seems to be a regression caused here https://github.com/translate/pootle/commit/180e8b86acc7489fbe7a19a46d588031e76e5c97#diff-3e77ff2852738c0c73c60d86a5db096dR82

**Comment by julen** [comment]
Gosh, that's embarrassing, sorry about that and thanks for the pointer.

**Comment by phlax** [comment]
@julen would you check that there are no other similar issues created by linting, thanks
