### ISSUE TITLE
Misleading label for providing administrative permissions

### ISSUE THREAD

**Issue by julen** [translate/pootle#4673]
Administration pages where permissions can be managed include the _"can administrate a translation project"_ label. Correct me if I'm wrong, but I'm inclined to think this is misleading: if you assign such admin rights to a user, they can access the admin section(s) for the context the permissions were set. So this works site-wide and for the language, project and TP scopes, i.e. it's not limited to translation projects.

**Comment by unho** [comment]
Yes, the permission is "Can administrate this" where this can be a TP, a language or a project.

**Comment by iafan** [comment]
I suggest to rename this to something like "Can perform administrative tasks".
