### ISSUE TITLE
Show all contributor lists for Project, Language, TP

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4699]
Splitting work from #4210 into pieces I'm creating this issue to discuss a specific question more thoroughly.

As per #3932:
We need to create
> a page where you can see per locale a ranking of who has contributed, over different periods of time, and how many strings were worked on. Showing the number of suggestions made and accepted translations for each user would be very useful too

So let's expose per user stats pages which we have in Pootle (https://mozilla.locamotion.org/user/dwayne/stats/) and show such tables depending on selected location (Project, Language, TP). 

### Top contibutor list for last 30 days (Language: Acoli, Project: Firefox)
User | Suggested | Translated | Reviewed | Score change
---- | ----- | --------- | ---------- | --------
John Doe | 0 words  | 15 words | 9 words | +18
... | ... | ... | ... | ...

**Comment by unho** [comment]
@ta2-1 Wasn't this fixed by 831fe8b2 ?

**Comment by ta2-1** [comment]
@unho thanks. yes, this was fixed so I'm closing this issue.
