### ISSUE TITLE
update_stores with gnu-style fails if template basename contains "-ui" / doesn't match all locales

### ISSUE THREAD

**Issue by cloph** [translate/pootle#4729]
* setup a project to use **gnu-style**
* have a template like `something-ui.pot` and 
* corresponding translated po files `something-ui-languagecode.po`

then `update_stores` fails to import the files for single-element locales (like de, fr, gug,...) (but works for two-element locales like en_AU, zh_TW,...)

The problem lies in the regular expression that is used to filter the filenames at https://github.com/translate/pootle/blob/master/pootle/apps/pootle_app/project_tree.py#L28 

Regardless of the filename containing two or three letter chunks, (like -ui- in the example), the regular expression also ignores locales like ca-valencia or kmr-Latn (as the second element is too long)

**Comment by phlax** [comment]
hi @cloph we are currently transitioning to pootle_fs and ironically have just landed some code that provides very similar functionality.

for the time being tho, we can fix the regex

**Comment by cloph** [comment]
instead of fixing the regex (which is rather complex), I did a simple endswith match - won't work for everybody I guess, but for us it does the trick...

**Comment by ta2-1** [comment]
Hi @cloph

You have raised a very problematic question. And I see now that GNU file matching works very unpredictable in general case.
I started new PR https://github.com/translate/pootle/pull/4787 and added a bunch of unit tests for this function and tests proved possible collisions.

Good news:
We currently working on Pootle FS which provides Language and File Matchers.
And I think that setting of some explicit rules how languages and files are matched is the right solution.
But that won’t happen right now. So we have to think about possible quick fix.

We might land such quick fix but it will require our existing users to change their .po file layout. If we try to address valid concerns you have raised we may break something for other people. That’s why we can’t just land PR you created.

We have thought about providing `LANGCODE_POSTFIX_RE` customisable which will address the issue. But it’s not possible to solve it without code changes. You can check it in https://github.com/translate/pootle/pull/4787.
There is a comment with a proper `LANGCODE_POSTFIX_RE` for you which will allow to handle `ca-valencia` and `kmr-Latn` codes as well.

It would be great to hear your thoughts regarding this issue.

**Comment by phlax** [comment]
@ta2-1 @cloph im closing this as wontfix - altho pootle_fs is now available allbeit in beta - so this is in a sense fixed.

Please re-open if necessary
