### ISSUE TITLE
TypeError in sorttable.js

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4736]
d26e566c83148de52a60c997e3d056b048585a3b caused 
```
sorttable.js:38Uncaught TypeError: Cannot read property 'search' of undefined
```
and duplicated sorting arrows 
![image](https://cloud.githubusercontent.com/assets/682845/15294609/a62ba3ba-1b95-11e6-89eb-7fa4ecbb4e0f.png)
in Google Chrome Version 50.0.2661.94 (64-bit) on Mac OS 10.10.5

FF, Safary are not affected.
I cleared brower cache before reporting.

**Comment by julen** [comment]
Thanks for the report @ta2-1, and sorry about that — it seems a collection of elements means a different thing across browsers. I'll revert the conflicting piece and move on (this code should be phased out sooner than later).
