### ISSUE TITLE
Undo/redo stack is broken with placeable symbols

### ISSUE THREAD

**Issue by iafan** [translate/pootle#4739]
Steps to reproduce:

1. Go to https://translate.stage.evernote.com/af/_test_raw_font/translate/test.po#unit=5626935
2. Replace translation with "abc"
3. Press couple of placeable symbols below the editor, e.g. `ë`, `ï`.
4. Try to undo your edits

Expected: symbol insertion actions will be undone one by one.
Observed: these extra symbols will be left hanging at the end of the string.

I believe this will can be addressed while implementing custom undo/redo stack as a part of https://github.com/translate/pootle/pull/4171 PR.

**Comment by julen** [comment]
Closing because this was already taken care of in #4171.
