### ISSUE TITLE
Footer sometimes doesn't show up at bottom with Chromium

### ISSUE THREAD

**Issue by unho** [translate/pootle#4740]
I am using Chromium 50 (also happened with version 49) and footer is not showing up at the very bottom when listing a lot of entries in the statistics table, for example in https://mozilla.locamotion.org/projects/firefox/

![footer](https://cloud.githubusercontent.com/assets/939880/15399032/4ef71fa4-1de6-11e6-83dc-338fef306513.png)

This doesn't happen with Firefox 46 nor Opera 37.

The issue seems to be fixed if the `#body` element's `style` attribute setting a specific height is removed.

**Comment by iafan** [comment]
FWIW, I can't reproduce this on Chrome 50/Win.

**Comment by dwaynebailey** [comment]
Ditto, can't reproduce o Chrome 50/Mac

**Comment by unho** [comment]
Perhaps it is a Chromium/GNU/Linux issue.

**Comment by unho** [comment]
After upgrading MLO this issue seems to be gone. Closing.
