### ISSUE TITLE
TM: missing username+fullname displays bad label

### ISSUE THREAD

**Issue by julen** [translate/pootle#4751]
When a ElasticSearch TM result contains `null` in `username` and `fullname`, the label says _Translated by in "P" project_ is displayed (note no display name is shown there).

I guess we should display _someone_ in this case, as the source is unknown, i.e. _Translated by someone in "P" project_.

**Comment by julen** [comment]
Actually, after checking the code and a _faulty_ result set provided by @dwaynebailey, I believe this is caused by a non-empty fullname such as `" "`, which will end up evaluating as `true` and hence used as the display name.

**Comment by dwaynebailey** [comment]
@julen I think the correct solution around names is to say **Translated in "P" project** when we don't know who the translator actually is.

**Comment by julen** [comment]
Diving more into the issue I was able to locally find another example of this and I see it's caused by neither `null` nor `" "` strings. So the real issue is there's a bug when using the full name.
