### ISSUE TITLE
amaGama returns a 404 with same language pairs

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#4759]
Use case-Improvement of template language messages. In this case, the user is translating the template languages (in English) to English. 

When translating in the /en/ project, a [request](https://amagama-live.translatehouse.org/api/v1/en/en/unit/?source=In%20the%20context%20of%20DHIS2%2C%20aggregation%20refers%20to%20how%20data%20elements%20are%20combined%20within%20a%20particular%20hierarchical%20relationship.%20As%20an%20example%2C%20all%20the%20health%20facilities%20in%20a%20particular%20district%20would%20contribute%20to%20the%20total%20value%20for%20the%20particular%20district%20in%20question.%20Different%20aggregation%20operators%20are%20supported%20within%20DHIS2%2C%20such%20as%20SUM%2C%20AVERAGE%2C%20and%20COUNT.&jsoncallback=_jsonp759099) is issued to Amagama. 

An error message results in Pootle due to the 404

![selection_676](https://cloud.githubusercontent.com/assets/2968061/15545125/7b65531c-229b-11e6-8f04-42d59878d575.png)

Perhaps an HTTP 204 would be more appropriate?

**Comment by unho** [comment]
amaGama itself avoids handling translation from same language to same language: https://github.com/translate/amagama/blob/master/amagama/tmdb.py#L441-L443 Perhaps this is not dealt with in the best way, but the point is that Pootle should avoid sending requests for getting translation suggestion from a language to the same language.

**Comment by leonardcj** [comment]
You might ask why this matters, but the use-case is actually important.  I routinely "translate" new projects into the lang-en project as a review for i18n issues.  Pootle conveniently allows me to flag strings as "Needs Work", with the understanding that the work needed is on i18n, not L10n.

**Comment by unho** [comment]
My understanding is that in that particular use-case results from amaGama are unnecessary.

**Comment by dwaynebailey** [comment]
There are two aspects here:

1. Response code for non-results.  I think @jason-p-pickering is right here that 404 is probably wrong, but I'm not sure if 204 is better.
2. Pootle shouldn't be asking amaGama for results when the pairs are different
3. Pootle should handle 404 better as there might be other times when amaGama returns a 404.

**Comment by jason-p-pickering** [comment]
@dwaynebailey , I think maybe a 400 Bad Request is better in this case?

**Comment by dwaynebailey** [comment]
Just for reference https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

400 might be better, but I haven't looked carefully at the available options.

**Comment by unho** [comment]
Landed the fix in https://github.com/translate/pootle/commit/fa7c11854ab9987dfe4c8ef1f15bc09eb63b8c71 to prevent querying amaGama if source and target language are the same. amaGama issues still to be addressed on amaGama side.

**Comment by dwaynebailey** [comment]
Reopening this.  Pootle will still fail if it gets a 404 as far as I can understand, so this is a workaround but its not fixing the core issue that Pootle won't fail correctly if amaGama is broken in some way.

**Comment by unho** [comment]
No, it won't fail. It will catch the error and will just display the message seen in the screenshot in the first message in the issue.

**Comment by jason-p-pickering** [comment]
From a translation perspective, I think if Amagana fails for whatever
reason, Pootle should simply swallow the error (possibly logging the
occurrence in the JavaScript console) but not continually display the error
message to the translator. The memory there is to help the translator, but
if the service does not work, then I don't think we should penalize the
translator to see the error message each and every time it occurs.

I am not sure if this is what happens but from a usability standpoint, this
would seem to make sense.

On Tue, May 31, 2016 at 12:14 PM, Leandro Regueiro <notifications@github.com
> wrote:

> No, it won't fail. It will catch the error and will just display the
> message seen in the screenshot in the first message in the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/translate/pootle/issues/4759#issuecomment-222647891>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1J_X8bscuYlnaM6Yy3_HrKYrrjLPWuks5qHAnqgaJpZM4ImpRQ>
> .
>



-- 
Jason P. Pickering
email: jason.p.pickering@gmail.com
tel:+46764147049

**Comment by unho** [comment]
Created https://github.com/translate/amagama/issues/3210 to track the amaGama side of things.

**Comment by unho** [comment]
Created https://github.com/translate/pootle/issues/4771 to track the bigger issue with XHR request failures on Pootle.

As a result I will be closing this issue.
