### ISSUE TITLE
Do not display error messages on failing XHR requests

### ISSUE THREAD

**Issue by unho** [translate/pootle#4771]
Current Pootle [handling for failing XHR requests](https://github.com/translate/pootle/blob/master/pootle/static/js/editor/app.js#L1056-L1079) (for example when querying amaGama) is to display some not helpful error messages, see following screenshot:

![selection_676](https://cloud.githubusercontent.com/assets/2968061/15545125/7b65531c-229b-11e6-8f04-42d59878d575.png)

A more user friendly approach was suggested by @jason-p-pickering:

> From a translation perspective, I think if Amagama fails for whatever
reason, Pootle should simply swallow the error (possibly logging the
occurrence in the JavaScript console) but not continually display the error
message to the translator. The TM is there to help the translator, but
if the service does not work, then I don't think we should penalize the
translator to see the error message each and every time it occurs.
>
> I am not sure if this is what happens, but from a usability standpoint this
would seem to make sense.

This issue was originally reported in https://github.com/translate/pootle/issues/4759.

**Comment by julen** [comment]
I totally agree. As I see the error handler for retrieving TM units is the same as the handler used for requests done to the Pootle server, and the handler was developed only with the latter in mind.

The simplest solution would be to log such 3rd party-originating error to the console, as suggested by @jason-p-pickering.

**Comment by phlax** [comment]
@julen is it safe to just do `console.error(msg)`? 

I had this feeling that there was a reason not to use console. in production code

**Comment by julen** [comment]
There's no problem with that nowadays, as opposed to in the past where the `console()` object wasn't available in all supported browsers.

**Comment by unho** [comment]
@julen said in chat:

> The existing handler is fine for internal requests, and the error handler for external requests can just `console.log(error)`. Just change this line to `console.log` https://github.com/translate/pootle/blob/2984c1591065f34c8f2d4131bc3152504d69de88/pootle/static/js/editor/app.js#L2218

The same should be done for any query to other external resource.
