### ISSUE TITLE
Avoid HTML markup in Entire project content dropdown

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4820]
![image](https://cloud.githubusercontent.com/assets/682845/16078790/655fda0a-3309-11e6-936a-5e0c8585c9e8.png)

To reproduce:
- https://mozilla.locamotion.org/projects/firefox/
- click on Entire project
- type "va"

**Comment by dwaynebailey** [comment]
An oddity which might be related:

1. The dropdown for languages will highlight the typed text while filtering
2. The dropdown for project will filter but not highlight
3. The 'Entire Project' will create the issue reported by OP

**Comment by ta2-1** [comment]
Fixed in #4825.
