### ISSUE TITLE
Resources dropdown disappears if you select `/`

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4835]
If select the root directory in the dropdown, the entire dropdown disappears

**Comment by iafan** [comment]
Some background info: selecting `/` is supposed to have the same effect as resetting the path filter (a placeholder should show up). This works correctly on non-root paths, but when one is already in a root TP directory and selects `/`, the path is not changed, no redirect takes place, so the selector is always stuck in an incorrect state.
