### ISSUE TITLE
Hidden disabled projects are still counted in the top level stats

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4841]
The following picture shows 1 critical error, but the total is 147.  The total is boosted by the hidden projects.
![screen shot 2016-06-17 at 15 45 59](https://cloud.githubusercontent.com/assets/647438/16154431/bdb309f8-34a2-11e6-891a-732b801621dc.png)

If we can hide projects we should eliminate their contribution to the totals in the navbar to prevent confusion.

**Comment by julen** [comment]
It's worth noting this only affects admins. Since we have the raw data, I'd really go on and start rendering these pieces as components, which would make it much easier to develop and maintain such an interactive experience.

**Comment by phlax** [comment]
closing this in favour of https://github.com/translate/pootle/issues/5312
