### ISSUE TITLE
Disable downloading of  non-PO files

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4852]
This issue https://github.com/translate/pootle/issues/4790 requests upload functionality for downloaded non-PO formats.
But XLIFF files are downloaded in a broken format with changed unit ids. It'd be safer to disable download functionality for non-PO files.

**Comment by unho** [comment]
Sometimes makes sense to allow download despite upload is disabled, for example to allow people to get a backup for their translations.

But at least upload must be disabled for formats like XLIFF, where upload still doesn't properly work.

**Comment by phlax** [comment]
yep, i have a feeling that some translators might export to other formats to use the translations in other tools - not sure. Im wondering if adding a message that upload isnt (currently) supported would be better than disabling altogether

**Comment by dwaynebailey** [comment]
@phlax I think the issue would be that we aren't exporting a format that we can safely import.  Disabling upload may be a good first step.  I'm not sure how we do with other formats.  If the download was even vaguely similar to what we got out of `sync_stores` then fine.  I think serializer helps here.  My gut disable upload is minimal best for now.  Disabling all download and upload would prevent export but would prevent the idea that you can work offline in this format.

**Comment by ta2-1** [comment]
Currently when we get such message after uploading non-PO files.
![image](https://cloud.githubusercontent.com/assets/682845/16344791/1d989320-3a47-11e6-9255-a5cafc5b470f.png)
It's very likely to minimal best for now (according @dwaynebailey). If we just want to disable upload I'd do nothing.

**Comment by unho** [comment]
We know beforehand with formats we support for uploading, and which format uses the project, so we can just not display the upload link in case project format is not PO. I think this is the minimal best.
