### ISSUE TITLE
Add init pootle fs project command

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4856]
```
pootle init_fs_project --code=project_code --name="My Project Name" --fs="git+https://github.com/repo/path/" --translation-path="<language_code>/<filename>.<ext>"
```

This command should create a new project:
- project code, name are taken from `--code, --name`;
- `project.treestyle=none` (Allow pootle_fs to manage filesystems);
- pootle_fs.fs_type is calculated from `--fs` param (git, local_fs);
- default pootle_fs.translation_path is set as `--translation-path`;

**Comment by dwaynebailey** [comment]
@ta2-1 I think you might also want to add `--langmap=af:af_ZA,zu:zu_ZA` to allow mapping of Pootle codes to upstream codes if needed.

**Comment by dwaynebailey** [comment]
@ta2-1 would you need to define project filetype at all? i.e. PO, XLIFF, etc?

**Comment by ta2-1** [comment]
It was addressed in https://github.com/translate/pootle/pull/4857.
