### ISSUE TITLE
Stats: create a mechanism to detect if stats are broken

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4863]
Currently we use Redis Sorted set `pootle:dirty:treeitems` to detect if any treeitem (Store, Directory, TP, Project, Language) is dirty. If element has score greater than `0` then its stats will be recalculated.
But it is hard to detect if stats are broken or not.
It is necessary to answer to this question:
Will we get all zero scores in  `pootle:dirty:treeitems` set after all pending jobs finish?

I'm thinking about global dirty counter which will allow us to say:
If global dirty counter `> 0` and there are no pending jobs and running jobs then stats are broken.

**Comment by unho** [comment]
I am not quite familiar with the possible scenarios and implications here, but my guess is that stats are broken in any of this cases:

- dirty counts and no rqworkers running
- dirty counts and no pending jobs
- dirty counts and failed jobs

If there are dirty counts, but there are either running jobs or pending jobs, then the stats can be broken. 

If there are no dirty counts and no jobs running or pending then we can tell for sure stats are sound.

**Comment by unho** [comment]
Closed since stats infrastructure has been refactored and this no longer applies.
