### ISSUE TITLE
"Go to string number" fails to set URL properly

### ISSUE THREAD

**Issue by blake-sc** [translate/pootle#4870]
This bug seems to occur in master and to have existed for at least the past few months, I have hopefully nailed down the specific conditions to reproduce it, it requires a view across multiple po files (it wont be observed when translating the strings from only a single po file).

Enter a string number in the string number box and hit enter.

Pootle will navigate to that number, however it *if this number is in a different po file from where you started, it will fail to set the unit_id*
For example, I enter "25" and it sets the hash component as simply `#filter=all&offset=18`

Because it has failed to set the unit_id, if you refresh the page or attempt to use the URL pootle does not know what unit_id to go to and as such you end up at a different string number, for example 19.

The unit_id is set correctly when going from one string number within a po to another string number within the same po, for example if I click the string number box and hit enter again, because it is "navigating" within the same po file it correctly sets the url, for example `#filter=all&offset=18&unit=22`, browser refresh and using the URL then works as expected.

**Comment by iafan** [comment]
See the related discussion: https://github.com/translate/pootle/pull/4560#issuecomment-198023807 and below

**Comment by phlax** [comment]
hi @blake-sc i can add the unitid in the situation that you describe, but its worth explaining how it works. 

The views that span across Stores work differently to views for a single Store.

In the latter case the `unitid` will always take you to the unit you are looking for, whereas for views that span multiple Stores the offset is used in the first instance, and the unitid only if it falls within that offset.

It was necessary to implement in this way, as to find the index of unitid in an arbitrary queryset is a very expensive calculation and basically represented a denial of service vector for any large installation.
