### ISSUE TITLE
provide an official Dockerfile

### ISSUE THREAD

**Issue by dcharbonnier** [translate/pootle#4880]
It would be extremely convenient to be able to run pootle in docker.

**Comment by phlax** [comment]
hi @dcharbonnier we use docker a lot with pootle - apologies that we havent gotten round to publishing a production build. I will do so shortly.

you can see the dockerfiles that we use for testing here https://github.com/translate/translate-dockerfiles

**Comment by dcharbonnier** [comment]
No need to apologize, its an open source project if I want it I can propose
a PR ;-) thx for the link

**Comment by kordianbruck** [comment]
I'm really confused on what the offical way to setup pootle with docker is. On the one hand we have the dockerfiles linked above, on the other hand there is this whole thing in the wiki (https://github.com/translate/pootle/wiki/Docker-setup-notes) where I really don't get why I would need to setup a whole python environment just to run the image?

Is there not a way to run a single image off docker hub with set environment variables?

**Comment by phlax** [comment]
> I really don't get why I would need to setup a whole python environment just to run the image?

in order to use docker compose - https://docs.docker.com/compose/

> Is there not a way to run a single image off docker hub with set environment variables?

no, pootle requires a number of different applications (redis, database, elasticsearch, rqworker) to run

**Comment by kordianbruck** [comment]
>in order to use docker compose - https://docs.docker.com/compose/
No where in the docs I can spot the requirement to use python on the host system. All python commands are executed inside the container (I was looking at https://docs.docker.com/compose/django/ )

>no, pootle requires a number of different applications (redis, database, elasticsearch, rqworker) to run
I know, it would be great, if I could configure theses services myself / reuse them, as I already have them set up and provide configuration via ENV variables.

**Comment by phlax** [comment]
> Nowhere in the docs I can spot the requirement to use python on the host system.

To use docker-compose you need to install it somehow, and its python deps. There are obviously multiple ways you can do that - this is a guide to one of them

In this case you also need the compose files from the pootle repo - so all in all using a virtualenv is not a bad idea.

Also, people tend to default to using root to install - this discourages that - or at least makes it easier not to

> I know, it would be great, if I could configure theses services myself / reuse them, as I already have them set up and provide configuration via ENV variables.

there is nothing to stop you doing that - this is meant as a base configuration or example as you need

if the ENV vars could be better mangled to suit your needs, and it would be generally helpful, please PR any changes

**Comment by phlax** [comment]
> Setting up python venv on the host in order to build the image is circumventing one of the best features of docker containers.

not sure if i follow this point exactly - but imhe you shouldnt be building anything in production - and in dev etc i really welcome having the venv for managing the various things i need to build images

**Comment by kordianbruck** [comment]
@phlax alrighty, nevermind then. I think this issue can be closed then, as you already provide the docker composer way of doing things.

**Comment by phlax** [comment]
cool.

for reference the `Dockerfile` is here https://github.com/translate/pootle/blob/master/docker/Dockerfile

and the compose config is here https://github.com/translate/pootle/blob/master/docker-compose.yml
