### ISSUE TITLE
Empty browser table shows before the stats are rendered

### ISSUE THREAD

**Issue by iafan** [translate/pootle#4885]
Since we updated our production server, I noticed the following regression:

Previously when one would open any browser page, it would be rendered immediately with all the available stats.

Now when the page is opened, it is always rendered in two passes: 1) without stats (with dashes in place of numbers and with gray progress bar) and 2) the stats are populated. This not only looks worse than before, but is also slower.

**Comment by iafan** [comment]
I tried to do some investigation on the cause, specifically because we have [this page](https://translate.stage.evernote.com/ru/support_evernote/ZendeskDynamicContent/) with 662 table rows in it, where the rendering delay is noticeable.

Fun fact: the reason I decided to pay attention to that specific page is that due to some suboptimal Chrome extension this page would load on someone's computer for **1.5 minutes** (sic!)

So these are the results of my investigation:

- The page (both HTML and Javascript) loads at once (which is good)
- Total page size is **2.8MB**
- Page renders on my pretty capable computer **9 seconds**, of which ~**4 seconds** takes actual page loading and ~**5 seconds** — table rendering.

The most massive parts of the page are:

1. Empty table with no data. It has too much repetitive code, repeated templates for every table row, etc. It's size is **1.8MB**.
2. JSON data for the table rows and top stats. It's size is **860KB**.

Now, there are two problems with the JSON data itself:

1. It is rendered in HTML as an encoded string wrapped with `JSON.decode(...)` call. While modern browsers are pretty fast at decoding JSON (for me this call takes only ~10ms, which could probably ignored), but encoded JSON data takes on this particular page **1.8 times** the size of raw JSON. So passing the data as a raw JavaScript object would reduce its size to **480KB**.
2. This data contains a good amount of fields that are not rendered in the table or that could be derived from others in JavaScript. It also uses longish field names that are repeated many times, and it passes default values like `0` or `false` which could have been omitted.

Below is an example of the decoded JSON structure for one store (this is what actually gets rendered on the server and then additionally encoded):

![screenclip](https://cloud.githubusercontent.com/assets/1728158/18604887/5f555306-7c38-11e6-9faa-4f72b3b7111a.png)

And this is the bare minimum that is actually needed (one-letter JSON fields can easily be mapped on both sides; server can even passed them along to the client as constants for easier manipulation with the data):

![screenclip](https://cloud.githubusercontent.com/assets/1728158/18604894/7bc6feb8-7c38-11e6-8815-ea5599569319.png)

Such a change can reduce the JSON data size from **480KB** down to ~**120-130KB** for this particular page. We can cut it down even further if we provide a list of users separately, without duplicates, and referencing them by their indices.

As for the empty table, we can reduce **1.8MB** down to ~**10KB** of React code component. This number alone shows that server-side rendering of such a table will never be close in terms of page size and overall responsiveness as compared to client-side rendering.

Similar techniques can be applied to our currently suboptimal way of rendering other parts of the page, though their overall impact is quite small compared to the project browser table:

1. Drop-down navigation options (currently they take about **100KB** of the HTML code which has only **28KB** of actual data and this number could be reduced even further to mere **3KB** if we reused some data that already comes from the table rows)
2. Checks (on this page it is **23KB** of unused boilerplate code which is never displayed because of zero error counters).

Overall, we could reduce this particular page from **2.8MB** down to ~**170-200KB**, which would significantly reduce its load time. I also believe we can shave off much of the table rendering time if we optimize in-client page rendering (this requires separate tests, so no numbers at this point).

**Comment by dwaynebailey** [comment]
@iafan this rendering changes with summary stats, I'd measure after that lands.

**Comment by unho** [comment]
Closed since stats infrastructure has been refactored and this no longer applies.
