### ISSUE TITLE
Pootle fails to walk through all filtered units at once

### ISSUE THREAD

**Issue by iafan** [translate/pootle#4894]
I just experienced the following scenario:

1. There were 80 untranslated words in some project.
2. I clicked on the "(80)" pill link and started walking through all the units.
3. After going through all units without skipping any, I was redirected back to the browser page.
4. The browser page showed that I still had 16 words to translate in the same project. I clicked on these and indeed was given 3 more untranslated units.
5. After translating these I was redirected back to the browser which finally showed that I had no units left.

I wonder why `#filter=incomplete` failed to select all the units when I initially selected this filter.

Some observations:

1. These 3 units were added some time ago (not recently). In fact, no `update_stores`/`sync_stores` was happening on this project for the entire time I was working on these untranslated units.
2. These 3 units were in the same project and in the same .po file where other untranslated units where. So this is not related to some project or file boundaries.

I *think* we had similar issues in the past, but since the code to query units was recently reworked, I thought it might be necessary to emphasize that the bug is still there.

**Comment by julen** [comment]
In this context with a fixed result set and no update/sync happening at the same time, this wasn't the case for sure with the previous implementation that used a list of unit IDs, so I'm inclined to consider this to be a regression. It _might_ be related to the other set of similar issues reported back when the rework was merged (#4625, #4626, #4640).

**Comment by iafan** [comment]
I went through the production server logs and indeed, there were exactly 18 units that I was able to translate in the first batch. So it looks like #4625 strikes back. So I'm closing this as a duplicate of #4625.
