### ISSUE TITLE
Setting a domain as reference for pootle under cherrypy

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4904]
If i run pootle with `run_cherrypy` and i use a **proxy** for **apache2**, may i ask you to give us an option in the pootle config file where to set the domain used for the pootle app when cherrypy is used?
I ask this cause when pootle is running under cherrypy, all the email links (like reset password, creating new accounts, reports) are like: "hostname:port"... but i'd like to have "domain.com"
That's would be a good addition for pootle.

**Comment by unho** [comment]
`run_cherrypy` has been dropped. See http://docs.translatehouse.org/projects/pootle/en/latest/releases/2.8.0b1.html#command-changes-and-additions

Closed this as wontfix.
