### ISSUE TITLE
Strings about contributors wrongs

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4907]
I kept translating the pootle language files and i noted that the contributors strings you recently added with 2.8.0b1 version are wrong

In the pootle language file, the only string i found closer to this one is "Top contributors Last 30 days"
![Home](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-16%2019-31-25-281.jpg)

Same similarity for "No contributions in the last month" that is not like the one in the profile page
![Public Profile](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-16%2019-33-03-644.jpg)

**Comment by unho** [comment]
@JohnnyKing94 I am not sure I understand this issue. If I understand correctly you are saying that some of the strings you saw when translating Pootle are not possible to locate when you run Pootle? If yes, we have just updated the strings to translate, so this would be a non-issue anymore.

**Comment by JohnnyKing94** [comment]
What i meant that the line like "Top Contributors for the Last 30 days" can't be translated, cause there are no string of it in the pootle localization file, there is only one similar (Top contributors Last 30 days - in the words "for the") but it's not the case...

**Comment by unho** [comment]
@JohnnyKing94 It is now translatable: http://pootle.locamotion.org/it/pootle/translate/#search=Top%20Contributors%20for%20the%20Last%2030%20days&sfields=source The same goes for http://pootle.locamotion.org/it/pootle/translate/#search=No%20contributions%20in%20the%20last&sfields=source

I am closing this as no longer applies now that POT files for Pootle translation have been updated.

**Comment by unho** [comment]
Or if you prefer reference to POT:

- https://github.com/translate/pootle/blob/9c15e851/pootle/locale/templates/pootle.pot#L2044
- https://github.com/translate/pootle/blob/9c15e851/pootle/locale/templates/pootle.pot#L2681
