### ISSUE TITLE
Wrong positioning of images

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4908]
I thought it was my pootle installation after the 2.7.6 upgrade or my enviroment, so first i removed completely the enviroment and i tried to install everything again, but somehow i'm still getting this wrong positioning of all pootle images, is it a known bug or what? I have a fresh installation and enviroment.

![Pootle images 1](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-16%2019-48-30-813.jpg)
![Pootle images 2](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-16%2019-48-41-840.jpg)
![Pootle images 3](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-16%2019-49-00-031.jpg)

**Comment by hjbailey** [comment]
@JohnnyKing94 this relates to the image sprite.  This occurs when the sprite is cached in your browser or in the redis cache.   First try force refresh your browser `Ctrl-Shift-R`.  If that doesn't work then we're likely cached in the Redis server, pop onto the Pootle channel and we can try help refresh that.

**Comment by julen** [comment]
The same advice from #4312 applies here (it is the same problem being reported); please follow the instructions provided there for resolution, and feel free to [join the support channel](https://gitter.im/translate/pootle) should you need further support.
