### ISSUE TITLE
Name column is too wide

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4913]
Since we added the truncating name column, the name column is now too wide.

![name-too-wide](https://cloud.githubusercontent.com/assets/454682/16900917/8c46f64a-4c2b-11e6-8d82-35d541752a79.png)

This problem is even worse if you have the sidebar expanded is it makes most of the information invisible

![name-too-wide-expanded](https://cloud.githubusercontent.com/assets/454682/16900919/a0021e94-4c2b-11e6-8059-9d393a7fdccb.png)

**Comment by iafan** [comment]
Relevant discussion: https://github.com/translate/pootle/pull/4883#issuecomment-233073340
