### ISSUE TITLE
Non-translatable month name in user statistics

### ISSUE THREAD

**Issue by unho** [translate/pootle#4923]
Originally reported by @JohnnyKing94 in #4900:

> In Statistics page, i'd like the strings of the months and the strings of the days to be translatable
> ![algo](https://cloud.githubusercontent.com/assets/939880/16947767/20b444be-4db1-11e6-9403-d9c1b263d1ef.jpg)

**Comment by unho** [comment]
Also the detailed statistics does appear translated. Need to check the differences.

**Comment by ta2-1** [comment]
@unho this is a culprit `$('.dates .selected').html(PTL.reports.month.format('MMMM, YYYY'));`

**Comment by unho** [comment]
This view has been removed, so closing.
