### ISSUE TITLE
Stats: title of the second column is too long

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4926]
![image](https://cloud.githubusercontent.com/assets/682845/16967794/95df848a-4e13-11e6-9dca-9880c05ce891.png)

@iafan suggested to replace "Top Contributors for the Last 30 Days" with "Top Contributors, 30 Days".

**Comment by dwaynebailey** [comment]
@ta2-1 or could we do:

**Top Contributors**
*Last 30 days*

The above would allow us to, in the future, change what range we're using.

**Comment by ta2-1** [comment]
@dwaynebailey did you mean to break the title into two lines?

**Comment by dwaynebailey** [comment]
@ta2-1 yes, actually styling the second line differently

**Comment by iafan** [comment]
@dwaynebailey we initially spent quite some time to make sure all three columns don't span multiple lines and table rows below are aligned — it looks much cleaner this way. We can revisit the approach when/if we're going to have the period selector, but I believe even when we do we can do this on one line, not two. For now, it's easier to simply shorten the title to "Top Contributors, 30 Days" to make stats layout look as it was supposed to be.
