### ISSUE TITLE
Files dropdown keeps references to empty directories

### ISSUE THREAD

**Issue by unho** [translate/pootle#4932]
In https://mozilla.locamotion.org/templates/firefox/toolkit/chrome/mozapps/plugins/ there were files that have been removed a while ago, but you can still select this empty directory in the dropdown. This **plugins** directory is not displayed in the statistics table at https://mozilla.locamotion.org/templates/firefox/toolkit/chrome/mozapps/

**Comment by julen** [comment]
The project resources cache is only invalidated after a DB directory deletion via the `post_delete` signal (same for stores); obsoleting it won't invalidate it. I believe in-DB directories are obsoleted when the directories are removed from the FS, right @ta2-1? If that's the case, the cache should also be invalidated in such a scenario.

**Comment by phlax** [comment]
lgtm

**Comment by unho** [comment]
For the record the lgtm was for PR #5046.
