### ISSUE TITLE
Put user placeholder to Last activity messages

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4934]
There is a set of last activity localisable messages with missing subject:
```
removed translation for %(sourceString)s
```
instead of
```
%(user)s removed translation for %(sourceString)s
```

On low resolution screens (less than 1440px) we don't show action text in stats table on browse pages.
![image](https://cloud.githubusercontent.com/assets/682845/17020292/614390b8-4f49-11e6-87b2-79c65bb7a089.png)
If your screen is wider than 1440px you will be able to see 
![image](https://cloud.githubusercontent.com/assets/682845/17020270/4e57f4ee-4f49-11e6-8ef1-178e3d916096.png)

This is wrong from l10n PoV. We assume the strict order that we shouldn't.
Let's not hide a part of a longer variant of last activity message. 
Show/hide the full message would be a right solution here.

**Comment by ta2-1** [comment]
Actually we might want to include <timeSince/> component to localisable string. Then short action text can look like:
```
%(user)s %(timeSince)s
```
and long action will be 
```
%(user)s removed translation for %(sourceString)s %(timeSince)s
```

**Comment by julen** [comment]
> Let's not hide a part of a longer variant of last activity message.
> Show/hide the full message would be a right solution here.

I don't understand this proposal nor how this relates to putting user placeholders to last activity messages. Mind elaborating?

**Comment by julen** [comment]
Also, as far as I remember `%(timeSince)s` has been left apart on purpose to keep the UI consistent (cc @iafan).

**Comment by ta2-1** [comment]
> Mind elaborating?

@julen I created WIP PR. There are `short-action-text` and `action-text` classes. Elements with `short-action-text` class are displayed on low resotion screens (`action-text` element are hidden). And there is an opposite thing on screens wider than 1440px.

**Comment by iafan** [comment]
> Also, as far as I remember %(timeSince)s has been left apart on purpose to keep the UI consistent (cc @iafan).

I don't remember that and not sure how this helps with consistency. What I remember is that we wanted to adjust the way these %(timeSince) strings are rendered to make them look natural inside a larger message (do not use title case, e.g. `Yesterday` => `yesterday`). But this is not related to the current case.

The approach taken in this PR looks good to me.

**Comment by julen** [comment]
I believe [a previous comment from @ta2-1](https://github.com/translate/pootle/issues/4934#issuecomment-234225252) confused me entirely, as it seemed to me the proposal was to put the `timeSince` part in the localizable text too. This is the part I was referring to that it's been left apart on purpose. I now see the PR is only referring to adding the user as part of the localizable text.
