### ISSUE TITLE
Configurable logo url and favicon

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4948]
It would be nice to have a configurable logo in the config file like you did for the name of pootle site (`POOTLE_TITLE`) instead of creating a custom template or editing the css of the default one.

**Comment by JohnnyKing94** [comment]
I add the chance to edit also the favicon in the config file

**Comment by dwaynebailey** [comment]
@JohnnyKing94 is there any reason why you don't want to override `images/app-32x32.png` and `images/app-64x64.png` using [image customisation](http://docs.translatehouse.org/projects/pootle/en/latest/developers/customization.html#customizing-images)

**Comment by JohnnyKing94** [comment]
Actually i have no problem to edit manually... the only reason why i opened this, it was as a simply feedback... many cms include an user-friendly template customization for editing logos, favicons, og:images, meta descriptions and other things... sometimes if they don't have an appropriate dedicate page on CP, they use config file like you... as i said i don't have any problem to edit manually... it was just a feedback :smile:

**Comment by phlax** [comment]
this is partly done @JohnnyKing94 - you can now set `POOTLE_CUSTOM_LOGO`

**Comment by phlax** [comment]
looking at favicons - its a bit more complex, there are several and a config

```

    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/assets/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/assets/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/assets/favicon/manifest.json">
    <link rel="mask-icon" href="/assets/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/assets/favicon/favicon.ico">
    <meta name="msapplication-config" content="/assets/favicon/browserconfig.xml">
```

**Comment by phlax** [comment]
im wondering if there is some way we can use an svg and have it resize, rather than lots of diff sized bitmaps

**Comment by phlax** [comment]
looks like not on svg favicons - altho perhaps for some

http://caniuse.com/#feat=link-icon-svg
