### ISSUE TITLE
External link icon doesn't wrap with link text

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4960]
This Irish About page screenshot shows the link icon on one line and the link text on the other.  When wrapping the link icon should join with at least the first word of the link text.

![screen shot 2016-07-23 at 05 47 13](https://cloud.githubusercontent.com/assets/647438/17075854/07b81dc4-5099-11e6-9ee5-dbbc3b7d8596.png)

**Comment by unho** [comment]
As suggested in #4956 I would just remove the icon. It is not widely used and it will allow us to remove some CSS and reduce the sprite size.
