### ISSUE TITLE
Pootle refuses to run on TTK 1.13

### ISSUE THREAD

**Issue by julen** [translate/pootle#4968]
I updated our staging server moments ago and I was surprised that after restarting the RQ workers, they were not showing up on the list of processes being run. After digging up a bit I realize `manage.py rqworker` refuses to start because TTK's minimum hard dependency is set to version 2.

My understanding of #4914 was that there was a will to push TTK2 to beta users, however [not to make it a minimum hard dependency right away](https://github.com/translate/pootle/commit/c090e51070c2a06a74305bd0974dd7da72d9fdca). From a business perspective, and given the major overhauling that it went through, we have no motivation to bump up our TTK dependency and would like to remain in 1.13 for the time being because it's known to work well.

So we'd appreciate if you would consider reverting the change to the minimum dependency.

**Comment by phlax** [comment]
@julen please see this comment https://github.com/translate/pootle/pull/4914#issuecomment-233708697

afaia you dont install - so this really shouldnt be a problem for you

**Comment by unho** [comment]
> afaia you dont install - so this really shouldnt be a problem for you

But the [checks for runtime](https://github.com/translate/pootle/blob/master/pootle/checks.py#L15) force this minimum TTK to be in place. Reverting that while keeping the requirement should be enough for Evernote.

**Comment by phlax** [comment]
wfm

**Comment by julen** [comment]
Yes, my suggestion was to change the [minimum dependency check](https://github.com/translate/pootle/blob/b635565a93bfc085b70dc080ebbd06c8c43308bb/pootle/checks.py#L15) so anyone can still run Pootle along with a stable TTK version.
