### ISSUE TITLE
Keep id of last submission for User

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4975]
Querying for the last submission for an user can be expensive. 

``` python
Submission.objects.filter(submitter=self).latest()
```

We can easily denormalise this with adding `last_submission_id` field to User model. 
Although we might want to consider other ways to keep this value.

**Comment by unho** [comment]
I think the proposed way is just fine.

**Comment by phlax** [comment]
yep, sounds like a good idea to me

**Comment by phlax** [comment]
notes: this is on user profile page

**Comment by unho** [comment]
Something worth considering is that on user's profile we should only list latest activity for projects that visiting user has access to. So we need to cache per project.

**Comment by ta2-1** [comment]
Tested how we get `user.last_event()`
```
Submission.objects.select_related(
    "unit", 
    "unit__store", 
    "unit__store__parent").filter(submitter=self).last()
```
And it runs very fast. So I'm closing this issue because keeping the only submission_id in user table makes no sense.
