### ISSUE TITLE
Take robots.txt view away

### ISSUE THREAD

**Issue by julen** [translate/pootle#4979]
(Ported from evernote/pootle#24 with rewordings)

Currently Pootle ships with a view at `/robots.txt` which is generated dynamically. This shouldn't be Pootle's concern at all, and while it could facilitate the task of creating a _robots.txt_ file like the current one via e.g. a management command, I'm inclined to think `Disallow: /` is probably the best suggestion for deployments so far.

Nevertheless, the main point is that it is much more efficient to leave the web server of choice serve a static _robots.txt_ file rather than have it go through application code.

**Comment by dwaynebailey** [comment]
This is fixed in #5008

**Comment by julen** [comment]
FTR: this hasn't been fixed as-is and taking the view away, but rather removing the dynamic generation part and converting it into a static template.

**Comment by unho** [comment]
In order to prevent people deploying Pootle without any robots.txt it was decided to keep the view. Of course it is recommended to serve the robots.txt directly using the webserver.
