### ISSUE TITLE
Remove restriction of not being able to put code in pootle.core

### ISSUE THREAD

**Issue by julen** [translate/pootle#4981]
Branching from https://github.com/translate/pootle/pull/4868#issuecomment-235484913:

> > Also I need to object when it comes to placing the new URLs/views under pootle_statistics:
> 
> as i have explained many times - this stuff cannot be in pootle.core or you will break the plugin system

I might be missing some detail but besides the order they are listed, from the technical point of view `pootle.core` is no different from `pootle_statistics` as they are both apps.

If there's any specific shortcoming preventing us from using `pootle.core` as we are willing, let's fix it.

**Comment by phlax** [comment]
> as we are willing, let's fix it.

julen - im not sure that there is agreement about this and i really dont see the shortcomings of separating core definitions and delegation from implementation.

I have yet to hear **any** arguments compelling or otherwise of what benefits it would bring

**Comment by phlax** [comment]
adding models etc to pootle.core would break our plugins system
