### ISSUE TITLE
Create scorelog summary table

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4985]
Scorelog summary table may contain scorelogs aggregated by store, user and day.
It should be updated on post_save unit changing every time.

This will allow to improve performance of getting top_scorers data.

**Comment by phlax** [comment]
following from conversation around this - i think we will need to store scores on at least an hourly basis - perhaps as low a resolution as 15 mins, in order to accommodate timezones.

We would want to limit the data we hold at this resolution to eg 1 or 2 months

**Comment by phlax** [comment]
this is fixed in master
