### ISSUE TITLE
Wrong English accesskey

### ISSUE THREAD

**Issue by milupo** [translate/pootle#5004]
Hi,

it is not important for locales other than English but I want to tell it, though:

For Firefox 50 Aurora on Pootle, there is a wrong English accesskey for following string:

openLinkCmdInContainerTab.label "Open Link in New Container Tab"
openLinkCmdInContainerTab.accesskey "z"

As you see, there is no "z" in the English string.

**Comment by unho** [comment]
@milupo This is something that should be reported directly to Mozilla. We are doing it for you. Thanks a lot for reporting.

**Comment by milupo** [comment]
Leandro Regueiro schrieb:
> @milupo This is something that should be reported directly to
> Mozilla. We are doing it for you. Thanks a lot for reporting.

Thank you, Leandro.

Michael



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by unho** [comment]
@milupo This is the reply I got:

> See https://bugzilla.mozilla.org/show_bug.cgi?id=1276412#c17 and  https://bugzilla.mozilla.org/show_bug.cgi?id=1285853

> It wouldn't be the first one remaining in release though (see "Inspect element" in the main context menu).

**Comment by milupo** [comment]
Leandro Regueiro schrieb:
> @milupo This is the reply I got:
>
>> See https://bugzilla.mozilla.org/show_bug.cgi?id=1276412#c17 and  https://bugzilla.mozilla.org/show_bug.cgi?id=1285853
>
>> It wouldn't be the first one remaining in release though (see "Inspect element" in the main context menu).
>

Hi Leandro,

thank you for the information.

The "Inspect element" bug I have been knowing for a long time. Three 
weeks ago I proposed in a message on m.dev.l10n to use "Inquiry into" 
instead of "Inspect". Then the accesskey "q" can be used without causing 
an issue. I think it has the same or at least similar meaning. Anyhow it 
seems to me that some years ago "Inquiry into" was used but I'm not sure.

Michael


---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by unho** [comment]
Good to know. But please take all of this to official Mozilla channels.
