### ISSUE TITLE
Allow user to copy "Similar translations" text instead of automatically replacing on click.

### ISSUE THREAD

**Issue by jtwang** [translate/pootle#5009]
1. Go to the edit page for a unit. Eg. https://pootle.com/pootle/projects/translations/translate/#filter=suggestions&unit=3169216
2. Scroll down to the "Similar translations" section at the bottom.
3. Attempt to right click and highlight part of a translation
4. On mouse up, the entire similar translation is copied over the contents of the text box

Our translators have provided feedback that they'd like to be able to copy and paste segments into the text box. They often forget that they can't until it's too late and they'll lose their in-progress translation.

**Comment by julen** [comment]
Thanks for your feedback @jtwang. We already do this for the read-only rows in the editor table, I believe we can easily do it for similar translations too.

**Comment by jtwang** [comment]
Fantastic, thank you so much for picking this up!
