### ISSUE TITLE
Muting non-critical checks doesn't work

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#5013]
![image](https://cloud.githubusercontent.com/assets/682845/17364420/bf90e76c-5988-11e6-988d-d80eda92b636.png)

- Style of non-critical check is not changed after it is muted;
- Unmuting seems not to work;

We can go with tow options:
- block muting/unmuting of non-critical checks;
- fix it.

**Comment by unho** [comment]
Fix it please.

**Comment by ta2-1** [comment]
@unho why do you need to mute non-critical checks? they don't affect us as criticals and I'd say it's save just to hide `mute/unmute` action icon for them.

**Comment by dwaynebailey** [comment]
@ta2-1 the reason we brought back muting of those is because some translators do want to mute them.  That way they are able to complete translations and review all checks.  Thus with zero failures in critical and non-critical they feel happier.  Non-critical checks are much like PEP8 to them.
