### ISSUE TITLE
Show more stats view in admin dashboard is unperformant

### ISSUE THREAD

**Issue by unho** [translate/pootle#5016]
https://github.com/translate/pootle/blob/master/pootle/apps/pootle_app/views/admin/dashboard.py#L58-L96

**Comment by ta2-1** [comment]
refs https://github.com/translate/pootle/issues/4846

**Comment by julen** [comment]
Without further details, it's a dupe, I'd say.

**Comment by phlax** [comment]
@julen the performance on one particular view is a critical performance issue - it completely hoses our database

**Comment by julen** [comment]
Ah yeah, already reported but in the fork repository (evernote/pootle#290).

**Comment by unho** [comment]
It is not a duplicate, since the other issue is about exposing more data on that view, while this issue is about increasing performance.

**Comment by unho** [comment]
Closing this since #4846 can work as reimplement this feature now removed by #5132.
