### ISSUE TITLE
PermissionDenied in pootle_store.views:manage_suggestion

### ISSUE THREAD

**Issue by unho** [translate/pootle#5025]
We have seen several instances of this in MLO server. We are trying to figure out if it is either:

- The link is exposed to users without the required right, or
- The permissions checking in the view is flawed.

**Comment by julen** [comment]
Could you maybe share a full traceback?

**Comment by unho** [comment]
Shared traceback in private since we prefer not to publicly share details on our deployment.

**Comment by unho** [comment]
This comes from auto-accepting suggestions when translating, even if translator doesn't have review right: https://github.com/translate/pootle/blob/master/pootle/static/js/editor/app.js#L1570-L1580

**Comment by unho** [comment]
After discussion on chat the agreement is that when a translator submits a translation that is a 100% match of any suggestion of that unit, even if it is from a different user, that suggestion must be accepted instead to credit both the suggester and the translator.
