### ISSUE TITLE
Own suggestions are not counted for similarity

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#5028]
I'm not sure if this is correct behaviour. We skip own suggestions when calculate similarity.

https://github.com/translate/pootle/blob/ea7c47b6201ca5b0418c3b3bdcaf943c6f5c79bf/pootle/static/js/editor/app.js#L948-L951

@julen @iafan any ideas?

**Comment by julen** [comment]
This is intended as per the description in #3989.

**Comment by ta2-1** [comment]
@julen thanks. I'm closing the issue.
