### ISSUE TITLE
Sorting is broken for incomplete filters

### ISSUE THREAD

**Issue by julen** [translate/pootle#5035]
In #3477 the sorting field was changed from `Unit`'s `mtime` to `submitted_on`. While this fixed a particular issue, it regressed in the context of the `incomplete` filter, where units lack any data in the denormalized `submitted_on` field.

The net effect is that choosing a sort criterion while being on the incomplete filter will give the impression that nothing happens, even if a request/response cycle went through.

I'm not sure if we can rely on sorting by `mtime` in general, although from my quick tests it does indeed fix sorting for incomplete filters.

**Comment by ta2-1** [comment]
It's not clear what `Newest first`, `Oldest first` mean. We might think about sorting by 'Last updated' (when unit was added) or 'Last activity' (when any user performed any translation action... having to say that it's not clear if mutting/unmutting checks should be counted here).
IIRC there was discussion about different sorting options and the ideal solution would be to support all of them using `unit.submitted_on` and `unit.creation_time` separately.
Hence using of `mtime` doesn't look like a proper solution to me.

Speaking about #3477: I suspect we might set `unit.submitted_on` when unit was created.

**Comment by phlax** [comment]
afaict this is fixed in current master
