### ISSUE TITLE
Clean detailed stats URLs

### ISSUE THREAD

**Issue by unho** [translate/pootle#5038]
Detailed stats URLs are now like `/user/unho/stats/detailed?month=2016-07`, but it looks cleaner like `/user/unho/stats/detailed/2016/07/`.

Also defaults detailed stats URL is now like `/user/unho/stats/detailed?` (see trailing `?`) but `/user/unho/stats/detailed/` looks much nicer.

**Comment by unho** [comment]
Something similar goes for regular stats `/user/unho/stats/#month=2016-07` where `/user/unho/stats/2016/07/` looks cleaner.

Also checked a bit in the code how this works, and it seems that this way of exposing year and month is to simplify backend code, but IMHO this shouldn't come up and bring us ugly URLs.

**Comment by ta2-1** [comment]
@unho in regular stats we build URL via JS, I'm not sure that you suggestion is possible.
Also we might want to think what URLs could be done for /user/unho/stats/detailed?start=2016-07-01&end=2016-07-20. Initially we had those URL params.

**Comment by iafan** [comment]
I agree the suggested URLs look better. @ta2-1 pointed out that these are managed by JS side, but this isn't a problem — we can use `pushState()` API for this, e.g.: `history.pushState(null, '', "/user/unho/stats/detailed/2016/07/")`.

**Comment by unho** [comment]
What concerns me now is the ability to set a start and an end. Not sure how to put that into better looking URLs.

**Comment by unho** [comment]
This view has been removed, so closing.
