### ISSUE TITLE
Notify suggester about accept/reject suggestion comment

### ISSUE THREAD

**Issue by unho** [translate/pootle#5041]
Suggesters must be notified comments on accepted suggestions, and most importantly, rejected suggestions. Without this the accept/reject suggestions feature now in place (#4629) is basically useless.

Whether that notification should happen by email, or using GitHub-like notifications in Pootle UI, or both, is something that needs agreement.

Related #5040.

**Comment by phlax** [comment]
i think the priority here is more notifying of accept/reject actions than just the comments

**Comment by unho** [comment]
Suggesters can benefit much more from comments on accept/reject, so IMHO that is the priority. But I don't see why both can't be achieved at the same time.

**Comment by unho** [comment]
This is now fixed.

**Comment by eefahd** [comment]
Does reviewing's notifications by email work with the final release (2.8.2)?
Because I configured the email and tested it by (`pootle sendtestemail`) and it worker, but no email is sent after reviewings.

**Comment by qguv** [comment]
Hi all, same question as above. Did this feature ever make it into the latest 2.8.2 release? If not, is there a way to cherry-pick it? Thanks!
