### ISSUE TITLE
Deleting all visible projects doesn't remove language from dropdown

### ISSUE THREAD

**Issue by unho** [translate/pootle#5087]
https://mozilla.locamotion.org/my/ language got all of its visible TPs deleted, but any user (admin or not) can still pick Burmese in the language dropdown.

Comes from #3415.

**Comment by iafan** [comment]
(See https://github.com/translate/pootle/issues/3415#issuecomment-240169834 for the desired behavior for admins and non-admins.)

**Comment by unho** [comment]
If disabled TPs are removed as well, this behaves as expected: language is not included anymore in the dropdown for all users.

**Comment by unho** [comment]
This is fixed in 787095b3.
