### ISSUE TITLE
Auto-verify superusers created from CLI

### ISSUE THREAD

**Issue by iafan** [translate/pootle#5094]
When installing Pootle, one of the steps is to create a superuser:

```
$ pootle createsuperuser
```

However, when you try to log into Pootle for the first time under this superuser account, Pootle says that the account email needs to be verified. Of course, one can then do the following:

```
$ pootle verify_user <superuser-name>
```

But I believe this is something that should better be done automatically.

**Comment by phlax** [comment]
i dont think this is helpful
