### ISSUE TITLE
If editor filter retrieves no units, TypeError is thrown

### ISSUE THREAD

**Issue by unho** [translate/pootle#5111]
When filtering in the editor by some filter that doesn't return any unit, some JavaScript error is shown on the JavaScript console:

> Uncaught TypeError: Cannot read property 'id' of undefined

Observed in https://mozilla.locamotion.org/ach/firefox/translate/ when changing the filter to "Suggestions" (this TP has no suggestions).

The same happens if the filter is changed to "My suggestions" somewhere you never contributed.

**Comment by julen** [comment]
I was filing the same ticket hehe.

`fetchUnits()` for some reason is returning `true` when changing the filter and having no results. Presumably a regression from 7abd6963.

**Comment by julen** [comment]
After further investigation, this is a regression of e20fbf23 actually. If one opens up the editor with any filter which provides results, then tries to change the filter and there are no results, it will always break because the code is assuming there are results.
