### ISSUE TITLE
Creating project without a title causes broken select2 dropdown

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5114]
If you:

1. Create a project
2. With no human readable title
3. The project dropdown will appear with a blank line
4. When in the Project, there will be no dropdown to change Project

Either we could:
1. Prevent you creating a project without a human readable name
2. Use the project code if no human readable name is defined

I'd lean toward 2.

**Comment by julen** [comment]
How do you define a _no human readable title_? A whitespace string? FWIW the full name is already required (not null, not blank at the model level), allowing a whitespace would be an unintended consequence of lack of stripping when cleaning the form data.

**Comment by phlax** [comment]
@julen 

```
>>> foo = Project.objects.create(code="foo", source_language=bar)
>>> foo.fullname
u''
```

> FWIW the full name is already required (not null, not blank at the model level)

its not - https://github.com/translate/pootle/blob/master/pootle/apps/pootle_project/models.py#L184

**Comment by julen** [comment]
It is required so long as you use a form. If using the ORM directly, one can also create projects without code; moreover, [any `CharField` can be an empty string](https://github.com/django/django/blob/stable/1.8.x/django/db/models/fields/__init__.py#L95-L97) ([here's another reference](https://github.com/django/django/blob/stable/1.8.x/django/db/models/fields/__init__.py#L788-L799)).

Validation in forms is enforced by `blank=False`, which is the default, and disallows entering empty strings. We use forms for project creation (and I don't see why we wouldn't) so effectively `CharField`s are required to be non-empty.

**Comment by phlax** [comment]
> It is required so long as you use a form

which is not schema validation - and restricts reliable project creation to using that one form.

as it breaks the ui it would be better to either add the relevant *model* validation or allow and empty title and use the code if it is empty

**Comment by julen** [comment]
I'm all in for validation, feel free to add it in the model if ORM-level validation is really needed. As said, the same applies to the project's code and any `CharField` so long as we want them to be non-empty.

By the way, _breaking the UI_ needs to be read with a grain of salt, as no regular user is able to trigger such a scenario, since the form already validates for non-emptiness.

**Comment by unho** [comment]
Agreed plan was to:

- Add data migration to populate project fullname with project code for projects with no fullname
- Add schema migration to require project fullname
