### ISSUE TITLE
Update/sync update obsolete units every time with --force --overwrite

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5117]
While testing recent changes to the Store.sync code i noticed that on every sync units that were obsolete were being shown as `deleted`.

On further testing it appears that Store.update does something similar with the same units, effectively generating noop submission records.

In the case of Store.update it appears that this has been the case for some time.

**Comment by julen** [comment]
> On further testing it appears that Store.update does something similar with the same units, effectively generating noop submission records.

I'm not sure I follow or understand. Do you mean it creates `Submission` objects but does nothing with them? Or that it creates empty submissions?

**Comment by phlax** [comment]
> Or that it creates empty submissions?

i believe it was recording submissions - but it didnt follow that up any further - what alerted me to this was that it was saying "n units updated" on every update when nothing had changed
