### ISSUE TITLE
Keep users logged in for more than a session

### ISSUE THREAD

**Issue by flodolo** [translate/pootle#5130]
I don't know if it depends on the user's permissions, but I have to login every time I restart the browser, which means daily on Nightly (or even more frequently).

It would be great to keep user logged in for a few days.

**Comment by julen** [comment]
Thanks for reporting, Francesco. To be honest I always have my browser open so I didn't even notice 😓.

I'm convinced we lost this as a default behavior after switching to allauth: `ACCOUNT_SESSION_REMEMBER` defaults to `None`, and we don't ask users to confirm. Deployments can decide to always remember the session by setting `ACCOUNT_SESSION_REMEMBER = True`.

If we want to restore the old behavior we should set this by default. The other option is to make this a user choice upon sign in.

**Comment by flodolo** [comment]
I assume this is targeting a past milestone at this point? It would be great to fix, it's beyond annoying to login every dat, and reset the search options.

**Comment by julen** [comment]
Hi @flodolo, you can ask @translate/house to adjust their MLO server settings so that it says `ACCOUNT_SESSION_REMEMBER = True`. That should do the trick.

**Comment by unho** [comment]
This should be addressed now. Please confirm.

**Comment by flodolo** [comment]
It seems to be working now, thanks.
