### ISSUE TITLE
Pin to specific versions of dependencies

### ISSUE THREAD

**Issue by julen** [translate/pootle#5133]
We want our deployments to be predictable, hit the same bugs in dev/stage/production, and in order for that to happen there's no other way than pinning to explicit versions of packages. Leaving this up to fate can only cause trouble.

A common complaint against this approach is that users might not get bugfix releases. However, as [Vincent Driessen (author of RQ) points out](http://nvie.com/posts/better-package-management/):
_The biggest complaint from folks regarding explicit pinning is that you won’t benefit from updates that way. Well, yes, you won’t. But think of it. It’s impossible to distinguish between a new release that fixes bugs, or one that introduced them. You are leaving it up to coincidence. There is only one way to retake control: pin every dependency._

A middle-ground option would be to lock in a version range, however this doesn't guarantee safety in the point raised above. We _might_ want to add an exception with Django in case we are willing to officially support multiple series (e.g. 1.9.x and 1.10.x). But other than that, version pinning is always the safest and more predictable approach.

The same should apply to npm dependencies. Note that while [npm encourages SemVer](https://docs.npmjs.com/getting-started/semantic-versioning), and _package.json_ allows to specify rules that will obey these conventions, the same concerns apply—and it might be even more concerning given the speed JS packages are published/updated.

One might also raise the fact that pinning requires developers to be more aware of dependencies and keep an eye on bug fixes. Truth is there are automated tools that assist on keeping track of dependencies, and I'd say that being well-aware of changes and bug fixes is a good thing.

Thoughts?

**Comment by phlax** [comment]
@julen for releases i think definitely we should pin exactly, but in dev it makes sense not to if possible, so that you can be aware of changes etc. Not sure how feasible that is tho.

**Comment by unho** [comment]
I am in favor of pinning as much as possible, specifically the dependencies that we don't expect to change often, even if it takes time do the research. At least this way we are sure of what fails and what not. Of course always pin on release, with the possible exception of Django which IMHO is pretty stable.

**Comment by dwaynebailey** [comment]
The plus of hard/range pinning is that we don't get to run around fixing issues that mysteriously happen when someone releases a feature release as a bug fix release.  Stopping that is a win.  Currently we have range pinning in master.

I prefer range pinning as it's a way to document what we regard as acceptable versions.

The downside:

1. We need to make Pootle releases to ensure people are using bug fix/security releases of our dependencies.
2. It's hard to figure out of a dependency should be bumped up.  I did some work on a PR to bring our deps into sync and realised we might want to figure out how that part works on master.

**Comment by phlax** [comment]
on releases we really shouldnt range pin. As we have seen time and time again old builds stop working

**Comment by dwaynebailey** [comment]
@phlax the previous broken builds are not due to range pinning, but open ended pinning.

**Comment by phlax** [comment]
hmm - not sure if i agree - either way i can only test builds against known versions. Any other option for a release means i cant test it determinately.

Also - if the argument is that users should get bugfixes etc - that is an argument for hard pinning to a release - and monitoring changes in deps - releasing again against supported versions where this is necessary

**Comment by iafan** [comment]
I would personally always do hard pinning. Range pinning, even in dev, has the same potential of developing and testing features against slightly different versions of libraries, and pretty much discards the benefits of pinning. We could combine hard pinning with some check that would be done periodically as a test and would issue warnings if there are some new versions of the components/libraries available. This way everybody would know what's new, have a chance to bump the version of a library via an explicit commit, and this will ensure that all tests are now done for the exact version of the library, and that all devs and staging/production servers have exactly the same environment.

**Comment by dwaynebailey** [comment]
@phlax not sure I know what you mean, you seem to be rejecting range based pins by justifying it using failure scenarios we've had with open ended pins and which we definitely would not have got with range based pins that are closed.

So my reason for range based closed pins is simple.  That communicates that we expect to work with a range of versions of a dependency, while still closing the open end such that we don't break in future and that it's limited to what we know works.  My reason is that this communicates to packagers and others that what they might have will work.

The problem with a set pin is that it is then a fixed requirement that you deploy in a virtualenv and nothing else as you will not know what version of packages from your system will also be able to work.

If we're at the stage where we want to drop any other deployment besides virtualenv then that will work for us.

I think I'm in agreement though that with a fixed pin everything and everyone has exactly the same thing.  Travis, tests, deployments, everyones machine will all be at the same version and thus limits the variability.  If that's what @phlax was arguing for when he said "Any other option for a release means i cant test it determinately." then yes I'm with you on that.  I also think this is @iafan argument for fixed pins.

@iafan https://requires.io/github/translate/pootle/requirements/?branch=master pretty much does what you want in terms of versions.  The only problem is that in cases where the latest version doesn't meet our needs there isn't a way to communicate that we don't want newer versions.  I guess we could document that as !=N.M in the requirements.

**Comment by iafan** [comment]
> as you will not know what version of packages from your system will also be able to work.

@dwaynebailey I think there are two use cases here: for ones that run `pip install pootle` and for packagers that want to specify dependencies in terms of system packages.

The main problem with ranges is that we can't really guarantee the interoperability, as we don't run tests against all possible combinations of library versions and we never will. So I'd suggest we do the following:

When installing Pootle **from pip**, we can force users to use specific hard-pinned npm module versions (because they are installed locally), and we can force them to use hard-pinned pip packages (because we expect one to use Pootle in a separate virtualenv). With this, we can guarantee that they use exactly the same libraries we run tests against. This would be a recommended way (albeit a bit slower) to setup Pootle to get the most stable version that we internally test and use.

For making **system packages**, we could bundle another "relaxed" requirements file with range-based pins, to indicate what library versions are _expected_ to work (but not necessarily tested by us). However, it is up to packagers to choose the best combination of dependencies within these recommendations and verifying that their choice actually works. This would be a quickest way to setup Pootle, though not as stable as the first one.

**Comment by dwaynebailey** [comment]
@iafan I'd be dead against maintaining two requirements lists.  One will always get out of date and they're confusing to users.

I feel a bit like we're worrying about older versions that we aren't testing against.  While the problem we've actually hit in real life is not out of date version but new versions that we haven't tested against or that are not backward compatible.

Range pins can work fine if the installation for virtualenv users includes `--upgrade`

That said, considering that the change of `pytest<3.0.0` leading to running a really old version of pytest.  I'm heavily leaning towards fixed pins and trying to figure out some way of communicating ranges without another requirements file.

**Comment by dwaynebailey** [comment]
Just an update on what I've been doing from the Django side and some of the logic, some of it might not agree with what was originally discussed though.

A lot of these changes are facilitated by requires.io's [range filters](https://requires.io/features/#rq-filter).  These allow our requires.io badge to reflect the real state of our requirements and for us to quickly action looking at outdated requirements.

* `tests`, `dev`, `_lint`, `_docs` are all fixed pins.  No upgrades will mess with us again
* `base` all fixed or range based.  So any release won't break in the future, but we will need to address changes in requirements for bugfixes in upstream.
* `travis` and `deploy` have open ranges.  I'll likely revisit this.

Net result:

1. Almost everything is Python 3 compatible
2. All are now aligned with our Django version
3. They won't change without us knowing, thanks requires.io
4. They won't change in our environment unless we change then (`travis` and `deploy` being current exceptions)

**Comment by dwaynebailey** [comment]
@julen is there a requires.io equivalent for javascript?

**Comment by julen** [comment]
There is https://greenkeeper.io/ and other utilities one can decide to script such as [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

**Comment by dwaynebailey** [comment]
We've closed the Python side, opening https://github.com/translate/pootle/issues/5494 to track the Javascript side of pinning.
