### ISSUE TITLE
Add unit constraint on Submission

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5171]
atm there is unit is not required on submission although it actually is.

im also not clear whether the store field is necessary as it can be accessed through unit and not all submissions seem to have it

i propose to 
- add migration to delete submissions with no unit
- add constraint on unit
- possibly remove Submission.store and related clear up

**Comment by unho** [comment]
It is worth checking if `Submission.store` is needed.

**Comment by phlax** [comment]
need to check scorelog
