### ISSUE TITLE
Add test for a proper using of last sync revision in sync_stores

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#5182]
There is an uncovered case that was discovered in #5178.
Let's add a test which will check if we analyse last_sync_revision properly during  sync_stores.

**Comment by phlax** [comment]
overridding the `StoreSyncer` plugin will allow us to test when/which vars are being passed through withoug triggering actual syncs

**Comment by phlax** [comment]
i think this is fairly well tested - please reopen if there are specific tests that might be necessary
