### ISSUE TITLE
Namespacing problems with virtualfolders

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5217]
We recently added validation to ensure that there were not namespace clashes with root directories in translation projects. This was necessary as this type of clash has historically caused issue.

Adding the validation didnt clean up the existing vfolders with clashing names, and it also didnt deal with the possibility that the situation could still occur if a directory is added with a clashing name.

I would suggest that we put virtualfolders onto a separate namespace - perhaps prefixing with something like `++`

This would make it clearer that a virtualfolder was virtual, removing these namespace issues (mostly) and simplify the path mangling that currently happens in views

**Comment by julen** [comment]
> I would suggest that we put virtualfolders onto a separate namespace - perhaps prefixing with something like ++

If I'm not mistaken there was some discussion around this in the past, with proposals to append `-virtual` to directory names. @unho probably has a better background on the decision.

Leaving that aside, the suggestion sounds good to me as it becomes immediately clear in the URL bar a vfolder is involved. I understand the idea was to make this transparent for the user, although myself, as a user, I found it to be confusing. If it makes code simpler, that's a good benefit.

**Comment by phlax** [comment]
so after some discussion on possible url schemes and how best to avoid namespace clashes etc - we kinda settled on the following:

- ++vfolder/$vfoldername/$pootle_path
- ++vfolder/$vfoldername/translate/$pootle_path

**Comment by julen** [comment]
I might be missing something but my understanding from the original comment was something along the lines of `++<vfoldername>/<path>`, which is less verbose and allows avoiding clashes as long as folders starting with `++` are prohibited.  How are the others better and how is `++` needed in that scheme?

**Comment by phlax** [comment]
it makes it obvious that there is a special path - ie not part of the "pootle structure" - it also prevents potential namespace clashing with language codes in the current scheme

**Comment by phlax** [comment]
sorry  - i may have misunderstood the question.

using `++vfolder/$vfoldername`  allows us to use the `++` namespacing for other purposes

**Comment by unho** [comment]
Related #5218.

**Comment by iafan** [comment]
I provided my suggestions here: https://github.com/translate/pootle/issues/5218#issuecomment-245628762

**Comment by phlax** [comment]
fixed in https://github.com/translate/pootle/issues/5221
