### ISSUE TITLE
Move PTL.unitApiRoot

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5231]
as we needed a way for views to set the url used by UnitAPI dynamically - https://github.com/translate/pootle/pull/5227 was landed to allow that.

as we were not sure the best way to pass this var through - this ticket has been raised

**Comment by unho** [comment]
@phlax Is this done?

**Comment by phlax** [comment]
no, but im not sure its such an issue, closing this for now, as to remove will require quite a bit of refactoring
