### ISSUE TITLE
Add a web ui for pootle_fs

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5241]
If we create a simple admin interface to configure the plugin/translation_path its gonna make this a lot simpler to set up, and easier to support.

from there we can potentially add some further stuff to show the state and initiate fs actions etc

**Comment by unho** [comment]
As long as we don't go back to old VCS feature where Pootle exposed the ability to trigger syncs outside of admin dashboard I am not against.

**Comment by phlax** [comment]
im thinking this is v much a site or project/lang admin task

**Comment by phlax** [comment]
basic web ui added in https://github.com/translate/pootle/pull/5314
