### ISSUE TITLE
Vfolder dropdown bugs

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5255]
when you blank a dropdown while in a vfolder - it should do something similar to what the editor does when it gets incompatible menu options

**Comment by phlax** [comment]
also it throws an error if you to to x-project vfolder translate views - it should probs redirect or something

**Comment by dwaynebailey** [comment]
More specifically if I am at `/br/translate/` then I really don't want to be able to clear the `br` and hit site kill.

I think we could make this so for admin's also.

**Comment by unho** [comment]
Clearing dropdown while on a vfolder is no longer an issue after #5510 has been fixed.

**Comment by unho** [comment]
This no longer applies, so closing.
