### ISSUE TITLE
[LF] symbol-related issues in the raw editor

### ISSUE THREAD

**Issue by iafan** [translate/pootle#5261]
During testing, we've found a few edge case issues with the new editor code that are worth documenting. I don't think they deserve being filed separately, so here they are in one list:

1. Place caret immediately before `LF` symbol and press Delete. The caret will be placed incorrectly after deleting the symbol.
2. Select a row ending with `LF` and press Delete. The first symbol of the selection will not be deleted.
3. Select some text sequence ending with `LF` and drag it with the mouse to some other place. The line break (`LF`) is lost.

Having said that, we already have a fix for this (a refactored code with more consistent approach to handling caret position and selection overall that doesn't exhibit these issues), but it may take some more time till we test it and integrate with the existing code.

**Comment by dwaynebailey** [comment]
@translate/evernote do you have an ETA on a fix for this? We had planned to do a staging test server to expose to our users before live deployment.  We've decided to delay until this is fixed.  Result is a block on our deployment.

**Comment by julen** [comment]
No ETA as I am aware of although I don't believe it would take much time provided the experiments Igor is doing are successful.

**Comment by dwaynebailey** [comment]
@julen I'm still going to do some local testing to replicate these issues, I'll likely evaluate if I need to block on them based on how problematic I think they are and based on Igor's experiments.

**Comment by iafan** [comment]
@dwaynebailey we basically have the new working code here: https://github.com/julen/raw-font-alternative, and the demo you can play with is here: http://julen.io/raw-font-alternative/  (note that this demo doesn't handle undo/redo by itself, see below).

This is a rewrite of event handlers for the textarea that is more compact, less intrusive wrt IME input and feels more natural when it comes to working with caret/selection. We need to integrate it back into the main component, where it will get support for the custom undo/redo stack that we already have.

We're committed to landing this ASAP. We'll schedule this with Julen.

**Comment by julen** [comment]
Fixed by #5281.
