### ISSUE TITLE
Remove SubfieldBase from MultiStringField

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5268]
In django 1.9 SubFieldBase is deprecated, and removed in 1.10

Related Stackoverflow - http://stackoverflow.com/questions/35166085/how-to-deal-with-subfieldbase-has-been-deprecated-use-field-from-db-value-inst

https://docs.djangoproject.com/en/1.9/ref/models/fields/#field-api-reference

afaict we can just safely remove - it seems it just needs to have to/from db methods

**Comment by phlax** [comment]
on closer reading we might need to add a method:

```
  def from_db_value(self, value, expression, connection, context):
        ...
```

**Comment by julen** [comment]
I checked this out and while apparently the change is superficial and straightforward, there is more involved: when initializing a model **manually** and setting default values for fields that didn't provide any, now these do not go through `to_python()`, which means that for `MultiStringField`s such as `source_f` and `target_f`, the values will be `None`, while previously they were `multistring([''])`.

This is problematic when [adding new units to a store](https://github.com/translate/pootle/blob/05fb3865233b04b16afd0b2ac1cc944a664f3e49/pootle/apps/pootle_store/models.py#L1404), as many pieces of code following it rely on `<field>.strings` being available, which will only be the case if the field is initialized to a proper `multistring`.

As a side note, realize `from_db_value()` is invoked, as the name says, only when initializing the model via the DB data (this also applies to using `values()`, `values_list()` or other aggregate functions).

**Comment by dwaynebailey** [comment]
Save ooodles of time trying to figure this out and [just implement the magic ripped out of Django](http://stackoverflow.com/a/39471064).
