### ISSUE TITLE
Documentation not clear regarding setting up ElasticSearch as TM

### ISSUE THREAD

**Issue by smurfy** [translate/pootle#5284]
There are some points missing in the Documentation regarding using ElasticSearch as a TM.

Main Problem is, that it only works with ElasticSearch 1.7.x, which is superseded by ElasticSearch 2.x. And only downloadable via past releases (https://www.elastic.co/downloads/past-releases/elasticsearch-1-7-5)

Another problem i've encountered is the documentation states you need to run update `pootle update_tmserver` once to setup your local installation.  But this command failed for me, regardless if the index exists or not.
Running `pootle update_tmserver --rebuild` actually worked. So my suggesting is either update the documentation or probably better, do a rebuild automatically if the index does not exist.

**Comment by dwaynebailey** [comment]
Just a note on versions:

* Elasticsearch 2.4.1 is the upstream stable 
* Elasticsearch is currently limited to <2.0 as the API changes.  And thus the Python package is also similarly limited.
* Travis has Elasticsearch v1.4.0 installed, installing newer ones would hammer the test environment ito speed as we need to download and install that package.
* Ubuntu/Debian are released with 1.7.3 in 16.04LTS (Xenial).  Nothing was packaged before that.

So my current position, lets leave things on the 1.7.x range and simply improve the docs where that isn't clear to someone setting up Elasticsearch based TM.
