### ISSUE TITLE
Leading and trailing whitespaces lost when submitting a translation

### ISSUE THREAD

**Issue by alexanderlaw** [translate/pootle#5285]
When I try to submit a translation with the whitespaces at the start and the end of the string, these whitespaces not preserved in the store.
It makes impossible to translate postresql-messages, for example.
Look at https://babel.postgresql.org/po-9.6-branch/ecpg.pot
It contains messages like:
msgid "  -V, --version  output version information, then exit\n"

**Comment by alexanderlaw** [comment]
Patch proposed:
https://github.com/translate/pootle/pull/5286/commits/d428ad8e524dd5cc0ebefd10826fa9e6b1f107ec

**Comment by dwaynebailey** [comment]
Landed in d428ad8e524dd5cc0ebefd10826fa9e6b1f107ec
