### ISSUE TITLE
Review forms.CharField() occurances

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5291]
Django 1.9 introduced `strip=True` by default for CharField in forms.  Great idea except in localisation where we want to preserve exactly what the user submits.  We've fixed the main one in  d428ad8e524dd5cc0ebefd10826fa9e6b1f107ec via #5286 but this ticket is to review other occurances that would require us to specify `strip=False`, likely comments are the only ones.

**Comment by julen** [comment]
I went through all existing `CharField`s in forms and the only conflictive place I can think of is the special characters field for languages. I'll PR the change required to make that work as expected.

**Comment by dwaynebailey** [comment]
Looks like these are fixed based on @julen's review
