### ISSUE TITLE
Typo: pootle/pootle/static/js/editor/app.js:369

### ISSUE THREAD

**Issue by khagaroth** [translate/pootle#5295]
There is one `</br>` instead of `<br/>`.

And slightly OT, shouldn't all the `<br/>` tags be actually `<br>` only, it doesn't seem like pootle is using XHML, which is the only case where `<br>` should be closed.

**Comment by julen** [comment]
Thanks for the heads-up @khagaroth, this is now fixed. Note also that self-closing tags are valid HTML5.
