### ISSUE TITLE
New editor doesn't clearly show spaces when you have [sp][nbsp]

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5297]
In the new editor a string combining [sp] and [nbsp] such as `One[sp][nbsp]Two` creates a string where it is clear that you have a [nbsp] but it is not clear that there is a space before the [nbsp]. 

When we have two or more [sp] we use dotted spaces.  We should be using a dotted [sp] where there is a preceding or following WS otherwise you can't really see the [sp].

[nl] does show dotted space before and after the [nl] character

[nbsp] and [tab] are all candidates that can potentially hide a leading or trailing [sp].

**Comment by unho** [comment]
This also happens for a single space before tab (it is not highlighted):

![single_space](https://cloud.githubusercontent.com/assets/939880/18959509/b91a81da-8666-11e6-96a6-d239afbdaf05.png)

But multiple spaces are highlighted:

![multiple_spaces](https://cloud.githubusercontent.com/assets/939880/18959508/b9168346-8666-11e6-9bf8-c4e9b5b8e7bf.png)


It does work ok if the space is before `LF`. IMHO I would expect the space to be highlighted around any of these symbols.

**Comment by dwaynebailey** [comment]
A few people asked for some clarity...

First one that works.  Notes how `LF` show a dotted space before and after if one appears:
![screen shot 2016-09-29 at 16 39 48](https://cloud.githubusercontent.com/assets/647438/18960994/74414c36-8663-11e6-9c6b-f3a14fd0804f.png)

And now the two that don't work.  Both of these have a single space before and after the `TAB` or the `NBSP`, making it hard to see that there are indeed spaces around the raw font symbol.
![screen shot 2016-09-29 at 16 38 57](https://cloud.githubusercontent.com/assets/647438/18960995/7441eb32-8663-11e6-925a-81ffff415372.png)
![screen shot 2016-09-29 at 16 39 20](https://cloud.githubusercontent.com/assets/647438/18960996/74432b5a-8663-11e6-94b7-15c65ef8e8e5.png)

**Comment by iafan** [comment]
@dwaynebailey you can test the fix on https://julen.github.io/raw-font-alternative/

**Comment by unho** [comment]
For me it works.

**Comment by julen** [comment]
The changes are now integrated and the PR is up at #5302.
