### ISSUE TITLE
 No module named NullHandler means.   ValueError: Unable to configure handler 'null': Cannot resolve 'django.utils.log.NullHandler': No module named NullHandler

### ISSUE THREAD

**Issue by harishprince** [translate/pootle#5311]
ValueError: Unable to configure handler 'null': Cannot resolve 'django.utils.log.NullHandler': No module named NullHandler

**Comment by harishprince** [comment]
ValueError: Unable to configure handler 'null': Cannot resolve 'django.utils.log.NullHandler': No module named NullHandler

**Comment by dwaynebailey** [comment]
@harishprince can I assume you're running `master` on Django 1.9?

See https://github.com/translate/pootle/issues/4537, this is already fixed on master.

If you are on `master` and seeing this error then you probably still have a reference to `django.utils.log.NullHandler`, change that to `logging.NullHandler`.

If you are on an older version then likely you have the wrong Django installed.

Please reopen if this doesn't solve your issue.

**Comment by harishprince** [comment]
my running browser is django==1.9

thanku
