### ISSUE TITLE
Existing comments should be respected and kept unchanged

### ISSUE THREAD

**Issue by pfennig59** [translate/pootle#5327]
Only yesterday we upgraded from Pootle 2.5.1.1 to the current version 2.7.6. While the migration went relatively smoothly, we're now discovering some changes we're not happy with.

In our projects we've been using comments in entry headers like the following from our first days with Pootle:

```po
#: Caption "webm\1080p mit 24 Bildern_s.vwp":0
```

Now, when the file comes back from Pootle the comment is split into multiple lines, replacing spaces with linebreaks:

```po
#: Caption
#: "webm\1080p
#: mit
#: 24
#: Bildern_s.vwp":0
```

Also, all lines at the top of the file above msgid "" are removed and information like Product-Id-Version, etc. are replaced by placeholders.

It would be great if this could be changed back to a state where comments and file information were still respected.

**Comment by dwaynebailey** [comment]
@pfennig59 your `#:` comments look more like comments to translators. In PO the correct place for such comments are in `#.` comments where Pootle won't reflow them.  The `#:` locations are actually space dlimited so the output is not unexpected.

Removal of any data above the header units and setting the header unit to defaults sounds more like something going wrong in template updates.  You'll need to give us more details.  By default Pootle keeps all that info, it will only reset them if somehow its headers have been adjusted internally and that only happens though something like update_stores.  So some info on how you get files in and out would be helpful.

**Comment by pfennig59** [comment]
Thank you for your answer. This explains why these things happen. In Pootle 2.5.1 our #: comments came back unchanged, therefore this error didn't get noticed. I changed all translation files and now this part works alright.
The second part became clear now too, since we actually do an update_store during our further processing of the files.

**Comment by dwaynebailey** [comment]
@pfennig59 based on your last comment I'm going to close this.  Please reopen if you feel I've missed something.
