### ISSUE TITLE
Permission form breaks (with latest django)

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5336]
Attempting to use the permission form on current master creates the following error:

```
TypeError: object.__new__(generator) is not safe, use generator.__new__()
```

it appears to be caused by how the choices are set on PermissionSetForm

**Comment by phlax** [comment]
not entirely clear what changed - but im wondering if it was this commit that broke support https://github.com/django/django/commit/2788c46d46bc4d7afb906765ce1f484faef180c5

**Comment by julen** [comment]
This is happening on my side with an error mentioning that generator objects cannot be pickled. Converting it into an iterator should work (this is what Django does with regular `ModelChoiceField`s). I'll PR a fix.
