### ISSUE TITLE
Bulk Pootle FS operations

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5346]
In initial synchronisation of Pootle FS, especially if there are many TPs and many Stores, will have a lot of Stores to determine how they need to be initially aligned.

There are no abilities to manage these in bulk e.g. All Stores on Pootle missing on FS should be rm'd.

What we need is the ability to specify bulk operations.

**Comment by phlax** [comment]
Im going to close this as its not correct. You can currently filter using glob matches for either pootle_path or fs_path.

You should also be able to filter actions using the `-t` flag, although i need to confirm that this is working correctly #5354
