### ISSUE TITLE
Add back rtl fixes in select2 widgets

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5351]
there are some css fixes that are now missing i believe

**Comment by SafaAlfulaij** [comment]
I think https://github.com/translate/pootle/issues/4847 should be fixed, not this, as that is the right RTL support for select2 widgets.

**Comment by dwaynebailey** [comment]
@SafaAlfulaij it could be, I think @phlax's concern is that we actually upgraded select2 to the latest which meant quite a bit of refactoring CSS and in the process we likely have lost a lot of the existing RTL support.

**Comment by phlax** [comment]
yep thats correct - i need to check the PR that landed with select2 update and copy back the lost rtl css

the selectors changed - so the existing css no longer worked - i didnt get round to copying back and adusting the rtl selectors
