### ISSUE TITLE
Package Pootle using setuptools optional features

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5359]
With things like Pootle FS we want to be able to install e.g. git plugin, and with deployment we want to be able to include MySQL drivers.  Currently you need to do that manually.

If we used setuptools ability to install [extra optional features](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) then we could do things like:

`pip install Pootle[mysql]`

A [more elaborate example](https://github.com/bninja/rump/blob/3b6c4ff29974b3c04a260d8275567beebb296e5d/setup.py#L17-L36) that demonstrates that we could allow:

`pip install Pootle[dev,mysql,sentry]`

**Comment by phlax** [comment]
nice!

**Comment by dwaynebailey** [comment]
Fixed in https://github.com/translate/pootle/pull/5421
