### ISSUE TITLE
Feature request: Add non-breaking hyphen to special characters in the new editor

### ISSUE THREAD

**Issue by gunchleoc** [translate/pootle#5398]
In my language, we have a lot of `<single character>-<word>` combinations in words like "a-nuas", "a h-uile", " air an t-sitig" etc. It would be nice to have U+2011 as a clickable character in the new editor.

Great work on the new editor so far, it's greatly appreciated :)

**Comment by unho** [comment]
Special characters are specified per language, so which language are we talking about?

**Comment by gunchleoc** [comment]
gd, Scottish Gaelic

**Comment by unho** [comment]
Added this missing character to gd in MLO. Also added this on TTK config for gd. So it is now fixed.
