### ISSUE TITLE
Display hint on the special chars when hovering

### ISSUE THREAD

**Issue by unho** [translate/pootle#5400]
It would be helpful to display a hint on which special char we are hovering. This is helpful since sometimes it is not easy to distinguish some of the special chars from others, and because sometimes different chars are represented with an empty box:

![chars](https://cloud.githubusercontent.com/assets/939880/19531720/f808179a-9638-11e6-8307-99eecbee1798.png)

Insert which symbol?

**Comment by dwaynebailey** [comment]
@unho which special characters are you talking about? The image posted only has spaces and I would argue that space is the one we actually really don't want to have a tooltip for, perhaps the others make more sense.

**Comment by unho** [comment]
I was not making any difference at all on which chars the name should be shown.

**Comment by dwaynebailey** [comment]
@unho so you mean special characters as in those below the edit area? As opposed to the raw font characters? Got confused with an image lifted from a new editor bug which isn't really focused on the special chars.  Would have been nice to actually have a screenshot that was meant to focus on the special chars :(

**Comment by unho** [comment]
Fair point, changed screenshot.
