### ISSUE TITLE
Problems in updating the score in pootle after uploading zip file 

### ISSUE THREAD

**Issue by surit** [translate/pootle#5402]
I translated some strings in http://neweditor.staging.pootle.tech/ne/terminology/ and then downloaded the zip file. Then I uploaded the zip file to https://mozilla.locamotion.org/ne/terminology/

The following changes were seen. 
- The score were updated here https://mozilla.locamotion.org/user/surit/stats/
- The score didn't update here https://mozilla.locamotion.org/user/surit/

**Comment by dwaynebailey** [comment]
Replicated as follows:

1. On dev server `af/firefox/services/sync/`
2. One unit of 4 words is fuzzy
3. Downloaded zip
4. Removed fuzzy marker
5. Re-zipped
6. Uploaded

The stats still say 4 units need translation.  Click on it and you get empty result set as unit has been unfuzzied.

**Comment by phlax** [comment]
i think this may be a slightly separate issue - re stats not getting updated - i think the original ticket was re user stats

**Comment by phlax** [comment]
hi @surit i believe this issue is fixed altho there is a related issue that i just opened #5618 

@dwaynebailey i believe this is working correctly and may have been impacted by #5614
