### ISSUE TITLE
Improve Pootle FS sync to disk

### ISSUE THREAD

**Issue by unho** [translate/pootle#5406]
Syncing to disk with Pootle FS introduces more changes than desired:
- PO header comments are gone ([example](https://github.com/unho/removeme/commit/c649c914#diff-fd82407e5cdb01ffc9ff2acebcc98c85L1))
- PO header fields are not updated correctly ([example](https://github.com/unho/removeme/commit/c649c914#diff-fd82407e5cdb01ffc9ff2acebcc98c85R7))
  - Pootle POT header is updated instead of PO header line
  - Last-Translator is reset and not updated
  - PO header is set to an unset header
- Introduced extra PO header fields ([example](https://github.com/unho/removeme/commit/c649c914#diff-fd82407e5cdb01ffc9ff2acebcc98c85R14))
- Obsolete units are removed from file ([example](https://github.com/unho/removeme/commit/29b3cd5b#diff-8be577d7148ac4341611d40f2faca6b4L1409))
- Untouched units in Pootle are reflown in file ([example](https://github.com/unho/removeme/commit/29b3cd5b#diff-8be577d7148ac4341611d40f2faca6b4L1376))

All of these don't happen when using `sync_stores`, but do happen with Pootle FS either using `localfs` or `git` plugin.

The expected result is that each sync introduces the minimum necessary diff, to reduce the noise.

**Comment by phlax** [comment]
pootle fs now uses the same code path as store.sync does and i believe these issues have been addressed
