### ISSUE TITLE
Vfolder checks counts in editor list maximum not count for folder

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5415]
As you can see below the checks for Placeholders says 44 failures, but we only have 1 unit matching that in this vfolder.  44 is in fact the total number of failures for this project, not for this vfolder.

![screen shot 2016-10-20 at 16 12 49](https://cloud.githubusercontent.com/assets/647438/19565825/27e908e6-96e0-11e6-85f3-811a3360e836.png)

**Comment by unho** [comment]
This might be actually be hidden by #5496
