### ISSUE TITLE
Make comment submit_date tz aware

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5441]
atm comments generate

```
RuntimeWarning: DateTimeField Comment.submit_date received a naive datetime
```

**Comment by dwaynebailey** [comment]
I'm not sure if its possible to audit these and try globally block anything that isn't TZ aware? Feels like Pootle as a whole should just be very locale aware.

**Comment by phlax** [comment]
the problem is that its a runtime warning - we probs dont want anything to fail that late in play if it doesnt really have to

**Comment by phlax** [comment]
...i was thinking aloud there probably - i was thinking of turning the warning to error

quite a few of these are picked up in the test env actually - ive removed a few - we could make those error at least
