### ISSUE TITLE
Static page editing save HTML outcome instead of raw text

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5467]
To reproduce:

1. Server using Markdown for static pages and an existing static page written using Markdown
2. Minor edit the content of the static page (editing the title also seems to do this)
3. Saves fine
4. Edit the page again.  Static page text is now all in HTML. 
5. View static page on site.  Static page is now all garbled HTML

**Comment by julen** [comment]
This is due to an [undocumented backwards-incompatible change in Django 1.9](https://code.djangoproject.com/ticket/24677), not very fun to debug. I will PR the fix I have along with other minor staticpages'-related changes.
