### ISSUE TITLE
Visible NBSP needs to be more subtle

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#5473]
I use NBSP quite often, but the new visible glyph is quite bulky and distracting.

LibreOffice uses a gray rectangle that is the same width as the regular NBSP glyph, but I think setting color might be harder here, so what about rotating the current glyph 90 degrees and making it narrower and may be drop the NBSP string from it?

**Comment by comradekingu** [comment]
@khaledhosny Add some screenshots and a mockup
