### ISSUE TITLE
Setting direct repo URL requirements doesn't work if you install Pootle via pip

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#5481]
For instance if you have 
```
-e git://github.com/translate/translate.git#egg=translate-toolkit
```
in your `src/pootle/requirements/base.txt` file and you install `Pootle` via pip
```
cd src/pootle
pip install -e .
```
this will set up the last stable version of `translate-toolkit` which is 1.13 atm. Pootle setup mangles requirements line and uses egg title only. So if there is no PyPI package that matches egg title you will get setup error.

**Comment by dwaynebailey** [comment]
Fixed in 96d5b3ecf8304086b10d013bbe68ed87058bcfa5  and bdc30589d15385bf4ef5a456f9be3417dbf293fe
