### ISSUE TITLE
PermissionDenied when going to global translate

### ISSUE THREAD

**Issue by unho** [translate/pootle#5510]
Regular users are not allowed to go to global translate (no links presented to them) but they can trigger `PermissionDenied` while being on a language translate view (`/bs/translate/` for example) and then clearing the language in the dropdown.

**Comment by phlax** [comment]
i would suggest that we disable this dropdown altogether - as the sql it triggers is non-performant and admins can click it inadvertently

**Comment by unho** [comment]
I would freeze the dropdown only for non-admins.

**Comment by unho** [comment]
As discussed for admins it should trigger a dropdown to confirm the action since it will trigger a heavy query.

**Comment by phlax** [comment]
> it should trigger a popup to confirm

i was kinda joking - might work tho - not sure what the best way to handle this is

**Comment by dwaynebailey** [comment]
More specifically if I am at /br/translate/ then I really don't want to be able to clear the br and hit site kill.

I think we could make this so for admin's also.
