### ISSUE TITLE
Show Last Updated column only to admins

### ISSUE THREAD

**Issue by unho** [translate/pootle#5581]
The Last Updated column doesn't convey any information that non-admins really need. Hiding it will provide a less cluttered browse UI.

It was suggested that the Last Updated info be merged into the Last Activity column so it is also exposed to translators. This would increase the pace at which the Last Activity updates giving a sense of more activity going on. But it was decided instead that the Last Updated column be visible only to admins to prevent any confusion.

**Comment by comradekingu** [comment]
A screenshot would be in order here.

**Comment by ta2-1** [comment]
@unho `Last updated` was renamed to `Last created` (it's more clear now). It was used to get when new units were added to a project (likely when template was updated and files were updated from templates). I'm not sure that this info is unnecessary for non-admins.
Also `Last activity` shows translator activity only and I'd avoid to copy `Last updated` info to here.

**Comment by phlax** [comment]
@ta2-1 i dont think this data is of any use to anyone other than admins - at least in this table.

The other thing about is that it is not updated frequently - and having this displayed so prominently makes resources look inactive, even if they arent

**Comment by phlax** [comment]
this was fixed in #5600
