### ISSUE TITLE
Sort by Last Activity by default

### ISSUE THREAD

**Issue by unho** [translate/pootle#5582]
The rationale is that this way we expose first the active languages/projects/TPs. Seeing activity might encourage passive translators to join the effort.

Any user-defined sorting will override this default, but it is a good default anyway.

**Comment by dwaynebailey** [comment]
My thoughts are that default order is:

- Language/Project/Index - last activity
- TP - normal file based order
- Vfolders - priority

**Comment by ta2-1** [comment]
Fixed in #5695.
