### ISSUE TITLE
pootle migrate command crashes if you don't have en_US.utf8 locale installed on your machine

### ISSUE THREAD

**Issue by peterwake** [translate/pootle#5598]
I am based in the UK, and only had `en_GB.UTF-8` installed on my machine.

When running `pootle migrate` (for MySQL setup) I get an error that includes:

`locale.Error: unsupported locale setting`

If I add a line

`print self.default_locale`

in  `/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/local/dates.py` just after the `set_locale(self):` line, I get `en_US.UTF-8`.

My workaround was to install `sudo dpkg-reconfigure locales` and then add `en_US.UTF-8` the migrate worked fine.

I'd suggest this is covered in the install docs, or perhaps I missed some setting in the config file?

Thanks

**Comment by phlax** [comment]
hi @peterwake thanks for this - we should add this to the docs i think - its a step that we have in our test environments for this reason

**Comment by dwaynebailey** [comment]
Actually this needs the full traceback as the en-US setting sounds like it came from a user, likely we can work around missing locale on the platform if we know why/where its needing it.

**Comment by dwaynebailey** [comment]
@peterwake I've done some testing with this on a docker image with no locales installed. My findings are that:

1.  The code that you point to above has been refactor in `master`, it still does have this error with rc5.
2. With the refactored code Pootle will fallback to an empty locale (I assume using C locale). This technically allows you to run Pootle without any locale settings (not recommended) but should also ensure that your default system locale does not impact installation or running of Pootle.
