### ISSUE TITLE
pip install Pootle[git] does not work

### ISSUE THREAD

**Issue by peterwake** [translate/pootle#5602]
I have a git repository that I am trying to integrate with pootle, so using the latest version of pootle:

```
(env) $sudo pip install Pootle==2.8.0b4
...
(env) $pootle --version
Pootle 2.8.0b4 (Django 1.9.11, Translate Toolkit 2.0.0b7)
```

But then the [plugin install instructions](http://docs.translatehouse.org/projects/pootle/en/latest/features/pootle_fs_install_plugins.html#install-the-pootle-fs-plugins) don't make any sense - 

`(env) $ pip install Pootle[git]`

doesn't work (and I've tried various versions of this) and if I just add 

`INSTALLED_APPS += ['pootle_fs_git']`

to my conf file, I get an error `ImportError: No module named pootle_fs_git`

**Comment by dwaynebailey** [comment]
@peterwake please use `pip install --process-dependency-links Pootle[git]==2.8.0b4`

**Comment by dwaynebailey** [comment]
Fixed in 914ca0d6d66bffe8034ec5ee63c815bafe80caff

**Comment by peterwake** [comment]
Many thanks Dwayne - I will do this today. I certainly appreciate that that keeping docs up to date is hard when you're making a big change!

**Comment by phlax** [comment]
hi @peterwake i should add this is currently pretty experimental - we are actively developing the git hookup so its likely to change.

If you are thinking of using it you might want to pop into our gitter channel https://gitter.im/translate/pootle
