### ISSUE TITLE
Moving to next unit doesn't put the editor in the centre of the screen

### ISSUE THREAD

**Issue by unho** [translate/pootle#5603]
This is quite annoying if you have a big "Number of rows" (for example 50) in your user's settings, but even with the default setting you still have to scroll down to see the TM results.

![current](https://cloud.githubusercontent.com/assets/939880/20561769/7dfb47de-b180-11e6-90c2-f9ca9b1a31c5.png)

**Comment by phlax** [comment]
a reasonable solution has been landed to address this
