### ISSUE TITLE
Downloading store in a zip file with no revision lacks revision headers

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5617]
not sure if this is a dupe or related to other PO-headers bugs - but it seems like stores with no unit revision dont get headers - this causes re-uploading to fail

**Comment by ta2-1** [comment]
@phlax the only case when I could reproduce this issue is an empty store (without units).
As I could check it doesn't related to zip exporting. All tp stores are included when zip file is created. So there can be "no unit revisions" stores among those all tp stores.
