### ISSUE TITLE
PyPI description should include release notes

### ISSUE THREAD

**Issue by unho** [translate/pootle#5631]
It would be just a matter of appending the correct release notes in https://github.com/translate/pootle/blob/a216b159/setup.py#L310-L312

**Comment by dwaynebailey** [comment]
Reviewing this I really don't think this is a good idea:

1. We already have a very long set of release notes making it unhelpful on our pypi page
2. We have release notes in our docs, lets just make sure we link to them properly
3. If there are mistakes we can't easily correct them, while we can on RTD

DRY

**Comment by phlax** [comment]
> DRY

there is no reason for this to be repeated - simply included in the `long_description` for setup.py

im happy for a link to be used instead - but my feeling is that the pypi page is the best place for the changelog - as that is where most people would look first if they are not devs
