### ISSUE TITLE
Dont store announcement info for anon user

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5639]
we seem to store "announcement" info for anon users

im not entirely clear what this announcement info is used for - but we dont want to store it for anon, and we dont want it to acummulate for other users

**Comment by dwaynebailey** [comment]
The announcement info seems to be used to determine if the sidebar should be open or closed i.e. it remember a) if the user closed it and b) has the user seen this sidebar or not.

**Comment by unho** [comment]
This info is stored in session now, even for anonymous. The point on keeping this data for any of the anonymous users as well is to allow them to keep the sidebar closed, and force it to display on next visit if any of the announcements changed since their last visit.

Therefore closing.

**Comment by phlax** [comment]
@unho i think we want to look at this a bit further, and consider whether its actually useful for anon users to accumulate this data.

If not, there is a very strong argument for not doing so

**Comment by dwaynebailey** [comment]
I'd agree with @phlax, a simple isOpen is enough for anonymous.  We really only want to convey the fact that the sidebar info has changed to users who can action that and likely that s logged in users.
