### ISSUE TITLE
Wrong redirection after sign out and after clicking activation link

### ISSUE THREAD

**Issue by memaldi** [translate/pootle#5655]
Hi,

After signing out or after activating a user, Pootle redirects always to the server root (http://mydomain.com). This is a problem when you have Pootle under a subdirectory (http://mydomain.com/pootle).

Thank you.

**Comment by phlax** [comment]
hi @memaldi it might be we need to set something to make this work - but just wanted to check that you have `SCRIPT_NAME` set

**Comment by memaldi** [comment]
Hi, I have the following settings related to this issue:

```
USE_X_FORWARDED_HOST = True
FORCE_SCRIPT_NAME = '/pootle/'

LOGIN_URL='/pootle/login'
```


Regards

**Comment by phlax** [comment]
hi @memaldi afaict this works if you set

```
LOGIN_URL='/pootle/accounts/login'
```

that said there are a number of other issues that come up when setting `FORCE_SCRIPT_NAME` - ive raised a ticket for those separately #5923

**Comment by phlax** [comment]
@memaldi to fix the signout url - you need to set the following 

```
ACCOUNT_LOGOUT_REDIRECT_URL = '/foo/' 
```

**Comment by phlax** [comment]
the other thing you probably need to set is
```
POOTLE_CANONICAL_URL = "https://my.dom.ain/foo/"  
```

**Comment by phlax** [comment]
wow, it seems like you need to set a lot of things for allauth - here is all that i found

```
LOGIN_URL='/foo/accounts/login'
ACCOUNT_LOGOUT_REDIRECT_URL = '/foo/'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/foo/"
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/foo/"
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = "/foo/"

```
