### ISSUE TITLE
Pootle xliff output doesn't import into Xcode 

### ISSUE THREAD

**Issue by peterwake** [translate/pootle#5686]
Using Pootle version 1.10.4
When I generate an xliff file with Xcode, I get the following xml:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
      <xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 http://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd">
        <file original="MyApp/Base.lproj/LaunchScreen.xib" source-language="en" datatype="plaintext" target-language="fr">
          <header>
            <tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="8.1" build-num="8B62"/>
          </header>
          <body/>
        </file>
        <file original="MyApp/Base.lproj/MyApp.storyboard" source-language="en" datatype="plaintext" target-language="fr">
          <header>
            <tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="8.1" build-num="8B62"/>
          </header>
          <body>
            <trans-unit id="0ZR-YL-fgj.text">
              <source>Task description</source>
              <target>Task description</target>
              <note>Class = "UILabel"; text = "Task description"; ObjectID = "0ZR-YL-fgj";</note>
            </trans-unit>
(etc)
```

But when I then edit it and export back to xliff (using `pootle fs sync projectname`) it comes out like this:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">
  <file original="NoName" source-language="en" datatype="plaintext" target-language="fr">
    <body>
      <trans-unit xml:space="preserve" approved="yes" id="MyApp/Base.lproj/MyApp.storyboard__%04__0ZR-YL-fgj.text">
        <source>Task description</source>
        <target state="translated">Description de la tâche</target>
      </trans-unit>
(etc)
```

And I can't import this back into Xcode.

So:

1. it is (a) in version 1.1 of xliff not version 1.2, and 
2. the file original value is wrong, and the trans-unit id is getting a bastardised version of the file original value inside it.
3. there is an empty chunk of XML for LaunchScreen.xib that's just getting deleted

Anyone got any ideas? I have spent a whole day getting Pootle up and running so am very keen to go the final distance!

Thanks

**Comment by dwaynebailey** [comment]
@peterwake thanks for the script.  I was about to suggest the same.

We have a Pootle instance that needs to output for iOS as we essentially use a template version and inject the output XLIFF into that, just as you are doing here.

One thing worth looking at is the Pootle serialisers.  We are just starting to use them. But they essentially allow you to work on the files before they come into Pootle and before they are returned to the FS.  This is designed to work with Pootle FS, but its pretty new so completely undocumented at the moment.

As to the source of the problem.  Yip our support for XLIFF in Translate Toolkit is lacking when it comes to various flavours we're seeing these days.

**Comment by peterwake** [comment]
@dwaynebailey you are welcome.

I was thinking the same today as we have the iOS app and also a Rails app that uses .po files. So you could scour both for the strings to translate, then inject them back into the original files once they're done.

I am starting to appreciate how complex the whole thing is!
