### ISSUE TITLE
json file flattened after po2json

### ISSUE THREAD

**Issue by cgarreau** [translate/pootle#5693]
Hi, I'am using po2json with a template json file that includes UI grouping section:

```json
{
  "group": {
    "label1": "abc",
    "label2": "def"
  }
}
```

after using po2json the json result is flattened:
```json
{
  "group.label1": "abc",
  "group.label2": "def"
}
```

This is a regression since commit https://github.com/translate/translate/commit/40ab1e74a1a1b4a1472967f03b0571388ee77f82 than fixes #3249

**Comment by unho** [comment]
@cgarreau this is a Translate Toolkit error. Moved to https://github.com/translate/translate/issues/3541
