### ISSUE TITLE
POOTLE_FS_WORKING_PATH setting hint is unhelpful without the directory

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5714]
```console
?: (pootle.C021) Path pointed to by POOTLE_FS_WORKING_PATH is not writable by Pootle.
        HINT: Add the write permission to the `POOTLE_FS_WORKING_PATH` directory using 'chmod +w'
```

The hint is unhelpful without the actual path being pointed to by `POOTLE_FS_WORKING_PATH`

**Comment by phlax** [comment]
the other thing im thinking is that the advices is to chmod the dir - whereas it might make more sense to change the setting

**Comment by phlax** [comment]
and advising with chmod assumes unix-based system (iirc)
