### ISSUE TITLE
Translate scores sometimes miss the +

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5725]
The top scorer doesn't have a plus:

![image](https://cloud.githubusercontent.com/assets/647438/21398482/62fadcf8-c79f-11e6-9366-4e8252c75337.png)

This might be caused by the babel formatting.  Though in that code it does a if `score>0 show +`. Anything of 1000 is impacted.

Possible solution is to get babel to format positive with a +

See https://translations.documentfoundation.org/projects/libo_online/?details

**Comment by phlax** [comment]
+ removed as we no longer have negative scores by default
