### ISSUE TITLE
IntegrityError: (1062, "Duplicate entry 'xxx-stats' for key > 'pootle_revision_content_type_id_xxx_uniq'")

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5730]
This error has been spotted in the wild.

From code review its hard to see how its happening, and i ~~havent~~ managed to reproduce - *by clicking very fast on editor buttons*

~~It may be related to update_stores~~

**Comment by phlax** [comment]
after further investigation i believe that this may be related to how django handles m2m operations:

https://code.djangoproject.com/ticket/23576

from my reading of this and related tickets, a possible workaround may be to use the `through` manager

**Comment by phlax** [comment]
ive managed to reproduce this issue - its caused by  fast clicking combined with the way django handles bulk_delete

im thinking we need to look at the deletion side - and probs add some kind of debouncing to prevent multiple unintentional clicks.

this issue has also created a fair amount of duplication in the submissions dbs

**Comment by unho** [comment]
This error has been hit when running `update_stores` too.

**Comment by ta2-1** [comment]
It is fixed in https://github.com/translate/pootle/pull/6234.
