### ISSUE TITLE
Ensure update_stores command fails on error

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5731]
Seems like update_stores may swallow (some) errors. This is not helpful for sysadmins 8/

**Comment by dwaynebailey** [comment]
This is a Travis run without loading the timezone data to show that we actually do fail https://travis-ci.org/dwaynebailey/pootle/builds/191963138

**Comment by phlax** [comment]
With current master and `DEBUG` set to both True and False ive triggered exceptions at various points in the stack without the exception being swallowed.

I also checked through the codebase for bare `except:` s, to try and find anywhere that might swallow errors during update, but didnt find any.

This may just have been a legacy issue, so closing unless able to reproduce

**Comment by unho** [comment]
I guess that `except Exception` is not an issue?

**Comment by phlax** [comment]
which one - i didnt search on that
