### ISSUE TITLE
infinite "Some data on this page is currently being calculated"

### ISSUE THREAD

**Issue by yann-l** [translate/pootle#5745]
I just installed pootle 2.7.6 (last release)

I then cloned a git repos in the translation folder, created the project in pootle admin interface, and I can see it and translate it. But on every page, I always see "Some data on this page is currently being calculated, and the page will be refreshed automatically in XX seconds."

All lines are "greyed" like if they were inactive (but I Can click on it and link works).

And on nearly all lines, stats (string that needs to be translated, critical errors, ...) are not computed (they are all 0).

I tried to call `pootle refresh_stats`, but that didn't change anything.

**Comment by phlax** [comment]
hi @yann-l it seems like you may have failed jobs in your rq queue

you can clear the queue with

```
pootle flush_cache --rqdata
```
You could also upgrade to 2.8rc1 which removes the need for refresh_stats

**Comment by yann-l** [comment]
There were no failed jobs. I checked.

I also tried with 2.8.0-rc1, it works better, but I have a strange thing, when I click on my project, I get a blank list:

![blank list](https://cloud.githubusercontent.com/assets/17690810/21582516/2b3d558c-d05c-11e6-8819-eb9c368647b6.png)

I have to choose a po file to see (of course) one country, then click on it to begin translation. Why don't I see all available translations in this project?

**Comment by unho** [comment]
Have you run `update_stores` to import the data? In case of doubt you can follow the docs on how to add a new project http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html

**Comment by phlax** [comment]
@yann-l we can give you more immediate support over at https://gitter.im/translate/pootle

**Comment by phlax** [comment]
hi @yann-l im closing this as the title bug has been fixed in the last few beta releases and on master.

If you still have a problem with the other issue you reported please open a ticket for that, thanks
