### ISSUE TITLE
pootle_fs not expiring cache_keys

### ISSUE THREAD

**Issue by yann-l** [translate/pootle#5757]
When a project uses pootle FS, stats are not updated. We have to manually call `pootle flush_cache --lru --django-cache` to update it manually.

**Comment by unho** [comment]
Copied from #5688:

As an logged in admin user:

* Create empty Pootle FS project
* View project - all blank i.e no languages
* Do `pootle fs` magic and import project
* View project, and not languages are not present.  Log you can drill down and you will find them.

We're clearly caching the old data.  I guess the same applies to any individual store that is loaded.

**Comment by yann-l** [comment]
In rc2, problem is not fixed. When I fix some errors in a translation, the page that list all translations (/projects/PROJECTNAME/) is not updated.
and `pootle flush_cache --lru --django-cache` doesn't help. so no way to have this page updated.

**Comment by phlax** [comment]
hi @yann-l seems like the problem was with the way pootle obsolete stores. Hopefully fixed in #5826
