### ISSUE TITLE
No links to check categories in editor

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5807]
theres a link to critical, if there are failing critical checks but none to functional/cosmetic

im thinking we should

- make the category clickable in the dropdown
- make the selected category visible in the dropdown

**Comment by unho** [comment]
It turns out that categories are not `<option>` tags, but `<optgroup>` tags which are not clickable. See https://github.com/translate/pootle/blob/063aaac1d3116f6e1bd3c50716c6059b57abf086/pootle/templates/editor/_filters.html#L25

**Comment by unho** [comment]
Investigate if possible to cherry-pick https://github.com/evernote/zing/commit/2f5d2d23
