### ISSUE TITLE
RomanianChecker cosmetic checks are not correctly identified

### ISSUE THREAD

**Issue by Jobava** [translate/pootle#5808]
Test: translate a string and add a cedilla character: ş

The cosmetic violation is shown as "niciun_nicio" and not "cedillas"

I am not sure if this is a bug in TTK or Pootle itself.

**Comment by Jobava** [comment]
Also, this unit: https://mozilla.locamotion.org/ro/firefox/translate/dom/chrome/dom/dom.properties.po#unit=20986283

fails both RomanianChecker checks, even though it has neither problems

**Comment by unho** [comment]
This might come from TTK. When I was working on adding tests for Romanian checker in pofilter I got weird results quite similar to what is reported here. PR with pofilter tests in progress: https://github.com/translate/translate/pull/3547
