### ISSUE TITLE
filter=untranslated also shows fuzzy strings

### ISSUE THREAD

**Issue by cloph** [translate/pootle#5824]
There is no way to only have untranslated messages in the list of units to go through. There is a filter fuzzy that shows only stings marked as fuzzy, and there is a filter "incomplete" that (from my understanding) is meant to be fuzzy and untranslated combined. However, "untranslated" behaves the similar to "incomplete", at least it also shows fuzzy strings, which is not expected.

(incomplete and untranslated have different string counts though, so there is another difference)
In any case doesn't reflect what http://docs.translatehouse.org/projects/pootle/en/latest/developers/glossary.html claims to be...

Sample URLs:
https://translations.documentfoundation.org/te/libo_ui/translate/#filter=untranslated at the moment of writing this 8866 strings, the first being presented is a fuzzy one.
https://translations.documentfoundation.org/te/libo_ui/translate/#filter=incomplete at the moment of writing this 10699 strings

interestingly enough, the amount of fuzzy strings is 1833, the difference between the two. So the stats/count reflect what would be expected, but the units offered for translations isn't filtered properly?

**Comment by dwaynebailey** [comment]
I think we might need to check this with a very small PO file with all states.

But one question, could this be the automatic TM matching? If there is a 100% match from TM then that is automatically inserted into the target and the unit is made fuzzy.  You'll be able to tell because the TM unit is highlighted.

**Comment by cloph** [comment]
Ah, that might be it, as conveniently amagama gives no suggestions due to 500 internal server error, indeed the units don't have an actual translation, but as you say are auto-filled by the translation memory.
Cannot tell whether the TM entry is highlighted though, but at least that would be an explanation, although maybe not that straightforward unless you know what happens :-)

**Comment by dwaynebailey** [comment]
This comes up more often then needed.  It is confusing that you suddenly have a fuzzy string when it should be untranslated.

The TM unit is highlighted if its 100% but you need to know what you are looking for.

I suggest: highlight the TM more boldly and also highlight the editor to show a different colour for 100% TM match.
