### ISSUE TITLE
Unit order is not respected when a file is resurrected

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5889]
* git add a 3 unit .lang file; sync

```
;Bob
Jannie


;Open
Open {ok}


;Close
Close


```
* git rm the .lang file; sync
* Readd the same .lang file; sync

Expected: file is resurrected
Actual: file is resurrected, but units are in different order.

**Comment by phlax** [comment]
seems like the cause of this and #5919 and #5917 are all the same.

Basically store.resurrect doesnt give units any index and the diff/update/sync doesnt work correctly

**Comment by phlax** [comment]
this bug might be fixed - not sure

**Comment by dwaynebailey** [comment]
I redid this using the 3 unit .lang file above, plus a similar .po file.

The obsolete and resurrect happn smoothly, all units are in the correct order.  I assume order is now preserved as we obsolete the store not each unit when doing store level removal.
