### ISSUE TITLE
Merge with no change on fs creates empty commit

### ISSUE THREAD

**Issue by unho** [translate/pootle#5892]
These are the steps to reproduce:

- Change single unit in Pootle
- Change same unit in repository
- Synchronize with script (FS wins, thus no commit needed for no changes)

Expected: No commit. If there were other non-collision related changes from Pootle that needed to be synced it would be necessary though.

**Comment by phlax** [comment]
i think this can happen any time that pootle_fs merges but there is nothing to update on the filesystem. Ill see if i can find a way to prevent.
