### ISSUE TITLE
Resurrected units in pootle do not get resurrected in file

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5919]
I suspect this is related to #5917

**Comment by phlax** [comment]
we need to check if units can be resurrected by upload

**Comment by ta2-1** [comment]
I tried to upload store with obsolete or removed unit as admin user. Unit was not removed or marked  as obsolete in Pootle DB.

**Comment by dwaynebailey** [comment]
@ta2-1 I can't recall but wasn't that an intentional design?  As in you don't want people to obsolete all units in a file.  But perhaps that is something someone with admin rights should be able to do.

**Comment by ta2-1** [comment]
As per https://github.com/translate/pootle/issues/5919#issuecomment-309996445 there is no possibility to remove or mark unit as obsolete in Pootle. All such changes should go from a file. 
So I'm closing this issue.
