### ISSUE TITLE
More... link on score table is not localised

### ISSUE THREAD

**Issue by phlax** [translate/pootle#5921]
not sure if its created in js or templates

**Comment by dwaynebailey** [comment]
Screenshot says localised, unless this isn't the right window.

![screen shot 2017-01-29 at 23 56 51](https://cloud.githubusercontent.com/assets/647438/22409249/ae83c4fc-e67e-11e6-8c94-118014f91981.png)

**Comment by phlax** [comment]
ill see you 1 screenshot, and raise you another
![more-1](https://cloud.githubusercontent.com/assets/454682/22410751/1e995404-e694-11e6-9bb9-afb0fca439ef.png)
![more2](https://cloud.githubusercontent.com/assets/454682/22410753/20b49dac-e694-11e6-879c-fcbd6de69207.png)

**Comment by phlax** [comment]
i tried with a bunch of languages including Galician - and all appear the same as above

**Comment by unho** [comment]
Tested locally and displays correctly localized. Maybe you didn't rebuilt assets or recompiled the translations (I am assuming you had set the right language in your browser preferences)?

**Comment by phlax** [comment]
> Maybe you didn't rebuilt assets or recompiled the translations

yep, perhaps, ill see if thats the issue

> (I am assuming you had set the right language in your browser preferences)?

8/

**Comment by ta2-1** [comment]
it is localised here:
https://github.com/translate/pootle/blob/master/pootle/static/js/browser/components/Stats.js#L54

**Comment by phlax** [comment]
seems like this is an issue with the setup i was testing, altho i havent been able to get all working. Seems to work elsewhere tho, so closing
