### ISSUE TITLE
Creating new TPs can create $lang-template.po

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5931]
@pmattern reported a problem.  [Following the docs](http://docs.translatehouse.org/projects/pootle/en/latest/server/project_setup.html#adding-a-new-project) and setting up a GNU style project.  The results are that adding a new TP creates a $lang-template.po named project.

I could not replicate but the instructions where a GNU style project and following the docs.  My one suspicion is the autodetect of the layout.

**Comment by ChrSchwaer** [comment]
Our template file is named template.ts! Because we are using qt .ts file! Is there a name convention for ts files! Like template.tst or something else?

**Comment by phlax** [comment]
i have a feeling that the gnu matcher handles `templates` differently but not `template` - not sure exactly what it should do

**Comment by dwaynebailey** [comment]
@ChrSchwaer also [raised this issues](https://gitter.im/translate/pootle?at=589042695309d6b3588c4b25)

**Comment by ChrSchwaer** [comment]
--> it might be just that its only matching "templates" and not "template"
i just checked this, but is still the same! Now i got the name "templates-da_DK.ts"

**Comment by phlax** [comment]
understanding the issue a bit better - i realise that this is totally undesired behaviour - ill try and repro

**Comment by pmattern** [comment]
The exact finding is new PO files are prefixed by a string `<filename of POT file>-`.
E. g. create a directory `[..]/translations/foo`, copy some preexisting PO files like say `en.po`, `it.po` and the POT file as `templates.pot` → adding language `it` from Pootle's Web-UI yields `templates-it.po`.
Follow the same steps but name the POT file `foo.pot` → new PO file is named `foo-it.po`.
([relevant posting](https://gitter.im/translate/pootle?at=588cac91fba5bfea069bc5ac) of the discussion we've had on the Gitter channel.)

**Comment by ChrSchwaer** [comment]
We use this structure and file convention for every Project:

[..]/translations/foo
[..]/translations/foo/de_DE.ts
[..]/translations/foo/de_CH.ts
[..]/translations/foo/en_GB.ts
[..]/translations/foo/fr_FR.ts
[..]/translations/foo/templates.ts

We use language files from project and some from our library! Because of that they should have the same name. In your solution we would have "foo-de_DE.ts" and "library-de_DE.ts".
Is there a other possibility?

**Comment by dwaynebailey** [comment]
@pmattern can you confirm.  Do you have two files `.pot` in your project directory?

The only way that @phlax and I can get a prefix added to my PO files is if I have multiple `.pot` files.  This would be logical in that we don't know what `.po` is linked with what `.pot`.

So when we have `foo.pot` and `template.pot` and initial Afrikaans we get `template-af.po` and `foo-af.po`

**Comment by pmattern** [comment]
> Do you have two files .pot in your project directory?

Not, there's a single POT file only. As depicted in the CLI output linked in my previous posting.

What platform are you testing on? Maybe a problem in recent versions of some software involved as I'm testing on Arch Linux?

**Comment by phlax** [comment]
@pmattern if you can post me a link to see the project it might help us track donw the issue - you can pm on gitter if that helps

**Comment by phlax** [comment]
@ChrSchwaer we managed to repro the ~problem for a po project but not for ts. If you ping me on gitter ill try and follow up

**Comment by phlax** [comment]
i debugged this a bit more - seems like the first tp to be initted will create the correct `lang.po`, after that it prefixes all with `template`

**Comment by dwaynebailey** [comment]
We're marking this as a `2.8.x` bug which is a WONTFIX.  This issue should be addressed in `2.9.0` where we move to Pootle FS by default.
