### ISSUE TITLE
Text direction of RTL suggestions takes the source language direction

### ISSUE THREAD

**Issue by SafaAlfulaij** [translate/pootle#5951]
I found out that the text direction of suggestion text in the editor is wrong. It seems that it is taking the direction of the source language instead of the target language.
Here: https://github.com/translate/pootle/blob/master/pootle/static/js/editor/components/SuggestionValue.js#L74

It doesn't change with the UI, I tried it with the English UI as well.

How it looks now:
![screenshot_ _](http://i.imgur.com/2wJ5VIe.png)

How it should look (taken from the suggestion editor widget):
![screenshot_ _](http://i.imgur.com/UkkFfGV.png)

The example: https://mozilla.locamotion.org/ar/firefox/translate/dom/chrome/security/csp.properties.po#unit=5804319

_Really Sorry for reporting this late, I don't review suggestions most of the time._

**Comment by unho** [comment]
@SafaAlfulaij No regrets. Thanks for reporting.

**Comment by khaledhosny** [comment]
I think this is fixed now.

**Comment by unho** [comment]
@khaledhosny Thanks a lot!
