### ISSUE TITLE
Error in 'pootle calculate_checks' (seems to be ≠ character)

### ISSUE THREAD

**Issue by chazotte** [translate/pootle#5966]
The command pootle calculate_checks throws such error:

```
pootle calculate_checks
Running calculate_checks (noargs)
CommandError: (1366, "Incorrect string value: '\\xE2\\x89\\xA0 1' for column 'message' at row 1")
```

```pytb
(env) root@TAO-Pootle:/var/www/html/pootle# pootle calculate_checks --traceback
Running calculate_checks (noargs)
Traceback (most recent call last):
  File "/usr/local/bin/pootle", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 317, in main
    django_settings_module='pootle.settings')
  File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 297, in run_app
    management.execute_from_command_line(command)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 113, in handle
    raise CommandError(e)
django.core.management.base.CommandError: (1366, "Incorrect string value: '\\xE2\\x89\\xA0 1' for column 'message' at row 1")```

**Comment by dwaynebailey** [comment]
FYI:

 `U+2270	≰	\xe2\x89\xb0`

**Comment by dwaynebailey** [comment]
@chazotte please rerun with --project and --language to narrow down the failure.

**Comment by dwaynebailey** [comment]
@chazotte so the error message that creates the ≠ is one where the number of sentences between source and target are different.  I have a PO file with that which I used to test.

* I used update_stores to bring that file into Pootle, no errors
* Then made a new such error in the same file, no issues
* I ran sync_stores, no issues
* I ran calculate_checks on the same project, no issues.

So we need two things from you:

1. Pootle version
2. Database encoding

**Comment by chazotte** [comment]
1. Pootle version is 2.8.0-rc5.
2. Collation is latin1_swedish_ci. It guess it should be utf8_general_ci for all tables?

**Comment by phlax** [comment]
@chazotte some columns have specific collation - but the default should be utf8_general_ci

**Comment by chazotte** [comment]
Fixed with the following one-line command:
`DB="pootledb"; PWD_TMP="XXXX"; ( echo 'ALTER DATABASE `'"$DB"'` CHARACTER SET utf8 COLLATE utf8_general_ci;'; mysql "$DB" -p$PWD_TMP -e "SHOW TABLES" --batch --skip-column-names | xargs -I{} echo 'ALTER TABLE `'{}'` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;' ) | mysql "$DB" -p$PWD_TMP`

**Comment by phlax** [comment]
@chazotte as mentioned i think you will need to adjust some columns - `utf8_general_ci` is case insensitive so there are some columns that have `utf8_bin` collation - see this migration for example https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/migrations/0007_case_sensitive_schema.py

i can find you a list the cols with this collation...

**Comment by chazotte** [comment]
Thanks for this, @phlax, I will adjust collation accordingly.
