### ISSUE TITLE
Parsing of .po files while attempting to add a new language breaks with some target strings

### ISSUE THREAD

**Issue by chazotte** [translate/pootle#5976]
Hi,

When I try to create a language that already has translations .po files to be parsed, it breaks for some specific strings. I couldn't figure out why these strings make the parsing fails.

[taoitem.rdf.po.zip](https://github.com/translate/pootle/files/771244/taoitem.rdf.po.zip)
With the .po file above, it fails with these msgstr strings:
> msgctxt "http://www.w3.org/2000/01/rdf-schema#comment"
> msgid "Deprecated"
> msgstr "Ce modèle d'item n'est plus supporté. Nous vous suggérons d'en utiliser d'autres."

> msgctxt "http://www.w3.org/2000/01/rdf-schema#comment"
> msgid "Experimental"
> msgstr "Ce modèle d'item est expérimental et ne devrait pas être utilisé dans un contexte de production. Donnez-nous vos impressions afin de l'améliorer."

Any solution? Thank you.

**Comment by dwaynebailey** [comment]
@chazotte no traceback? Please always paste the traceback.

**Comment by dwaynebailey** [comment]
@chazotte I'm beginning to suspect the encoding on your database/files is wrong.

**Comment by dwaynebailey** [comment]
Based on https://github.com/translate/pootle/issues/5966#issuecomment-279436792 I'm prtty confident you can't import these because of encoding problems on the target text.

**Comment by chazotte** [comment]
Yes, after the collation and charset fix, it fully works.
