### ISSUE TITLE
Django contact form is not working with Django 1.10

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5981]
The current django contact form is not populating the email templates with supplied data.

**Comment by dwaynebailey** [comment]
Fix is in https://github.com/ubernostrum/django-contact-form/pull/22

I'm curious why `pytest-warning` didn't pick up the deprecation warning, possibly because we don't exercise the code in our tests.

**Comment by unho** [comment]
Fixed by https://github.com/translate/pootle/pull/5982
