### ISSUE TITLE
Other source language then 'en' will cause 'Unknown error' during translation

### ISSUE THREAD

**Issue by PawelSpoon** [translate/pootle#5992]
I am new to Pootle so please opologize if i did miss something obvious.

i have a pootle instance running in docker. i have created a new project.
now in my complany we use files like these:

"@somekey" (without the quotations, i just did not want to send a notification ..)
ENG:english translation
GER:german translation

so i have create a project with 4 languages: templates, en, de, fr.
i have now two problems

if i change source language from en to lets say en_GB, or even a newly created language i will get unknown errors during translation
each navigation to a string will bring up 'Unknow error'
it sems en as source language is the only one that does not throw errors.
i did try with en_GB etc. but nothing did help.
UPDATE: 
i am now using en as source language and have introduced a new language 'eng'.
now no errors are thrown.
but as mentioned above: if i have had used en_GB as a language in my project. translation of this language would throw errors

**Comment by ChrSchwaer** [comment]
If you switch on the developer tools in your browser you can see that the "Unknown Error" comes from GET call to the Amagama TM, is it?
If you don't use it switch them of in the pootle.conf

>You may want to disable Amagama by setting AMAGAMA_URL to '' if you are using Elasticsearch-based TMs, though both can operate together.

[http://docs.translatehouse.org/projects/pootle/en/stable-2.7.6/features/translation_memory.html?highlight=amagama](url)

**Comment by ChrSchwaer** [comment]
see:
[https://github.com/translate/pootle/issues/5275](url)

**Comment by PawelSpoon** [comment]
i would say you are correct:
evTools failed to parse SourceMap: http://atgrzsl2503:8080/eng/tfms10/translate/dist/purify.min.js.map
app.min.7d63089f.js:23 GET https://amagama-live.translatehouse.org/api/v1/en_GB/eng/unit/?source=AccountingOrder.ContactPerson&jsoncallback=_jsonp592206 
o @ app.min.7d63089f.js:23
getTMUnits @ app.min.7d63089f.js:22
ready @ app.min.7d63089f.js:21
reDraw @ app.min.7d63089f.js:21
renderUnit @ app.min.7d63089f.js:21
(anonymous) @ app.min.7d63089f.js:21
(anonymous) @ vendor.min.62a362b8.js:24
p @ vendor.min.62a362b8.js:24
fireWith @ vendor.min.62a362b8.js:24
n @ vendor.min.62a362b8.js:25
(anonymous) @ vendor.min.62a362b8.js:25
DevTools failed to parse SourceMap: http://atgrzsl2503:8080/eng/tfms10/translate/dist/purify.min.js.map

**Comment by PawelSpoon** [comment]
so what i did now as workaround:
i use en_US as source and en as one of the languages

**Comment by ta2-1** [comment]
This issue was fixed in https://github.com/translate/pootle/issues/6079.
