### ISSUE TITLE
User suggestions are always shown with LTR direction

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#6033]
See for example:
https://mozilla.locamotion.org/ar/firefox/translate/devtools/client/appcacheutils.properties.po#unit=20390999

The user suggestions are shown with LTR direction making them extremely hard to read when there are LTR words in them. When the suggestions are edited they have the correct direction. TM suggestions are fine.

![2017-02-24 21-10-23](https://cloud.githubusercontent.com/assets/93914/23317116/bdb64b82-fad5-11e6-9cb3-32ec39aeb6e8.png)

**Comment by SafaAlfulaij** [comment]
Isn't this a duplicate of #5951?
Or https://github.com/unho/pootle/commit/e4a8bed811beda6277b061effbd3637fded7f11b wasn't enough?

**Comment by khaledhosny** [comment]
Was #5951 about user or TM suggestions? I still see the issue on mozilla.locamotion.org, but it might be just an old version.

**Comment by SafaAlfulaij** [comment]
@khaledhosny It was about user suggestions. Yes I think Mozilla still uses the last beta version, not the `git` one.

**Comment by dwaynebailey** [comment]
@khaledhosny are you able to help make the needed changes?  It feels like this bug has dragged and you and @SafaAlfulaij might be the best to fix this.

**Comment by SafaAlfulaij** [comment]
@dwaynebailey I really think that this is a duplicate of #5951...

**Comment by khaledhosny** [comment]
This is fixed with the last update.
