### ISSUE TITLE
Question about Django stuff

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6042]
Hi,

while translating Pootle 2.8.0 I saw that there are some Django strings to be translated. So I assume that Pootle uses Django. I know almost nothing about Django but it is fully translated to hsb and dsb since Django 1.10. In fact, this is for you information only that Sorbian Django would be available if it is needed.

**Comment by dwaynebailey** [comment]
Thanks @milupo, we do indeed use Django.  Mostly Pootle uses its own string and doesn't need many (or any) from Django itself.  We're using Django 1.10 which means that any we might use would be from that version.  So if Sorbian is available we'll get them.

Thanks for the heads up and hope my explanation was clear.

In terms of Sorbian for Pootle itself.  We pull those translations in regularly.  So your translations will start to be available on Mozilla and LibreOffice servers relatively quickly.  Note though that we set the completion at 80% before we mark the language as being available in Pootle.  So if you can break that number Sorbian will be usable in all Pootle installations.
