### ISSUE TITLE
%N type strings should use plural rules

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6061]
Hi,

following strings should use plural rules:

 **templates/browser/_progressbar.html:3**
_<span class='value translated'>%(translated_percent_display)s</span> translated_

**templates/browser/_progressbar.html:4**
_<span class='value fuzzy'>%(fuzzy_percent_display)s</span> needs work_

**templates/browser/_progressbar.html:5**
_<span class='value untranslated'>%(untranslated_percent_display)s</span> untranslated_

**Comment by dwaynebailey** [comment]
@milupo could you maybe show me how Sorbian would need plurals in this case.  I've never seen this before and would like to see how we need to handle this in future.

**Comment by milupo** [comment]
Hi Dwayne,

I assume you want to have the gettext rule:

nplurals=4; plural=(n%100==1 ? 1 : n%100==2 ? 2 : n%100==3 || n%100==4 ? 3 : 0);

It's the same rule as for Slovenian.

CLDR is one, two, few and other.
And, finally, it's rule 10 of the Mozilla plural rules.

It looks as follows:

1 = singular
2 = dual
3, 4 = nominative/accusative plural
5 - 100 = genitive plural
101, 201, 301 ... = singular
102, 202, 302 ... = dual
103/104, 203/204, 303/304 ... = nominative/accusative plural
105 - 200 = genitive plural
and so on.

**Comment by milupo** [comment]
I will show you it taking the first string above as example:

1 = %(translated_percent_display)s přełoženy
1 procent přełoženy
2 = %(translated_percent_display)s přełoženej
2 procentaj přełoženej
3/4 = %(translated_percent_display)s přełožene
3/4 procenty přełožene
5 = %(translated_percent_display)s přełoženych
5 procentow přełoženych

**Comment by unho** [comment]
@milupo These placeholders, for example `%(translated_percent_display)s` render like `52.1%` so `%(translated_percent_display)s translated` is rendered like `52.1% translated`.  Given that the placeholder is always a float number, are the following correct?

1.0% přełoženy
2.0% přełoženej
3.0% přełožene
5.0% přełoženych

What about `52.1%`, `0.9%` and other cases with actual non-integer numbers?

**Comment by milupo** [comment]
Hi Leandro,

yes, it's right. 

Non-integer numbers use the 5 - 100 rule, 52,1 přełoženych and 0,9 přełoženych (In Sorbian a decimal comma is used). The rules are valid both for Upper Sorbian and Lower Sorbian.

**Comment by dwaynebailey** [comment]
@milupo we use CLDR rules to get the formatting so as Sorbian has those that should be formatted correctly.

However we use Gettext plurals which only does integer numbers.  So we can't pluralise those.

I had a quick look to see if we could hack that but based on the CLDR plural rules for Upper Sorbian http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#hsb the fraction part would follow some slightly different rules to the whole.

So until we move off Gettext for plurals or Gettext follows CLDR we're pretty limited in what we can do here.

**Comment by milupo** [comment]
Use CLDR for fractions. It is better. So the rules above are used for decimal fractions as well.

**Comment by milupo** [comment]
There is one string more:

**templates/includes/formtable.html:27**
_Showing %(count)s results per page_

**Comment by dwaynebailey** [comment]
@milupo I'm afraid we can't fully use CLDR rules for plural fractions, not easily at least.  We reply on Python and Django for our internationalisation support so working up our own solution here would take some time.  But we don't like these types of issues and would prefer to see them cleaned up.  So I'm going to leave this open so we can address it.

The second string is valid, but lets move that into its own issue as this issue is dealing with fractions.

**Comment by milupo** [comment]
Thank you, Dwayne.

Well, I think fractions do not often occur. But, you understood that the CLDR rules are the same as for integers here, didn't you?

BTW, Pootle 2.8.0 is fully translated into hsb and dsb now.

**Comment by dwaynebailey** [comment]
@milupo I looked at the CLDR rules on their site, the integer and fractions, although they follow a similar pattern they would need their own formula to determine the outcome.  The critical thing to remember though is that Gettext assumes integers so we're not able to use that mechanism and I'd prefer that we didn't give the idea that this could be correctly localised when we're not sure it will produce a correct result.

Thanks for the dsb/hsb work :)

**Comment by dwaynebailey** [comment]
Although I'd like to see this fix I'm going to close this for these reasons:

1. We use Gettext for plurals which operate on whole numbers only.
2. These strings have fractions i.e. 50.5% so introduce their own plural forms.
3. I'm reluctant to change rounding to whole numbers e.g. 50% as sometimes you do want this fine grained enough.
