### ISSUE TITLE
Needs work should be disabled after changing a copied string

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6074]
Hi,

there is a feature in Mozilla Pootle that disables the needs work setting after changing the copied string. In Pootle which is used e.g. for the Pootle 2.8.0 project the needs work setting remains active after changing the copied string. It would be good if you could apply the Mozilla Pootle behavior here as well..

**Comment by dwaynebailey** [comment]
@milupo as soon as we update pootle.locamotion to 2.8.0, which we expect to do shortly before release this will get fixed. Leaving this open until we deploy.

**Comment by milupo** [comment]
Fine. Thank you.

**Comment by phlax** [comment]
closing as this is an old version/deployment
