### ISSUE TITLE
Project Pootle 2.8.0 - Same string address has different English strings hsb and dsb

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6078]
Hi,

I saw that Upper Sorbian shows another English string than Lower Sorbian at address

apps/pootle_language/views.py:246

hsb: 
Accepted %s suggestion with comment. User will be notified
Accepted %s suggestions with comment. Users will be notified

dsb:
Rejected %s suggestion
Rejected %s suggestions

Which is the right one?

Thanks.
Michael

**Comment by unho** [comment]
I am not sure I understand.

These messages are used in the bulk suggestion management. There you can just accept/reject any number of suggestions, but if you do so by providing a comment (for example rejecting a group of suggestions with the same mistake) an email is sent to the users that sent those suggestions.

Please let us know if this issue can be closed or still needs some action.

**Comment by milupo** [comment]
That's not the point. The same string path **apps/pootle_language/views.py:246** has different English strings for hsb and dsb. See my screenshots:

hsb:
![apps-pootle_language-views py-246-hsb](https://cloud.githubusercontent.com/assets/1248520/23671541/ea75bb46-036b-11e7-964f-b3515056f139.png)

dsb:
![apps-pootle_language-views py-246-dsb](https://cloud.githubusercontent.com/assets/1248520/23671563/fee83a0e-036b-11e7-9504-f2a97905d5f4.png)

According to the Czech translation the dsb string is the correct one here.

**Comment by dwaynebailey** [comment]
@milupo I've spotted the error.  I'm not 100% sure how this is manifest.  When I pull the files from Pootle they are correct and in the repo they are correct.  So I resynchronised up and that seemed to correct the situation.  But still not quite sure how it got into this state.  I know we had some issues when hsb was first initialised so its likely that.

Thanks for reporting.

I'm going to close this though as the pootle.locamotion server is an old version of Pootle so we won't want to try track down this spurious error on an older platform.  If you spot this on the Mozilla server please do report as that will be more critical for us to track down and try to replicate.
