### ISSUE TITLE
Optimal size for a lang file

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#6091]
In terms of performance, i keep noticing that my huge xliff file (~108MB - 553859 strings) have a big impact to the pootle eviroment. I'm considering to split the files in multiples one, but first i need to know for sure what's the optimal size for a lang file in total size or in total strings... idk honestly...

**Comment by unho** [comment]
@JohnnyKing94 I don't know about any optimal size, but I would avoid files larger than 1 MB if possible.

**Comment by JohnnyKing94** [comment]
Jesus, that means 100 files of 1MB for the xliff 😅 Basically i have a .po file of 3MB and it works perfectly with its 6K strings...

**Comment by unho** [comment]
You can try XLIFF files of 3MB, or even larger, and see how it works. But XLIFF might not be as lightweight as PO. But 108MB is definitely a file that is best to be split into smaller ones.

**Comment by phlax** [comment]
1mb is probably pretty low - but im not sure exactly what the parameters are here - i *believe* its to do with mysql mem limits and temp tables

**Comment by phlax** [comment]
ideal is to debug mysql with a big file - and at least rule out that as being the bottleneck

**Comment by JohnnyKing94** [comment]
@phlax how you would proceed with MySQL?

**Comment by phlax** [comment]
hi @JohnnyKing94 there are too many variables to give a clear answer to this - it deps on size/shape of db, available resources and mysql/db configuration.

Closing for now, altho it would be good to have some docs around potential issues using very large files
