### ISSUE TITLE
Populating amaGama TM in realtime?

### ISSUE THREAD

**Issue by ymmd** [translate/pootle#6114]
Hi,

we are setting up Pootle in order to support translations from German into English. In the default configuration Pootle queries Translate House's public amaGama server. Sadly it only provides translations from English into other languages, so we set up our own amaGama server with German as a source language.

What's the best way to automatically populate amaGama with the translations that the users are providing? To store them in realtime would be best of course. We already saw that the docs [offer a way to import whole directories](http://docs.translatehouse.org/projects/amagama/en/latest/importing.html#importing-translations). Is this what we want to build upon? Or is there maybe a better way?

Thank you so much for your help!

**Comment by dwaynebailey** [comment]
@ymmd Pootle can use both amaGama or its built in local TM server.  The local TM server will be populated whenever a user supplies a translation or translations are imported into the server.

See http://docs.translatehouse.org/projects/pootle/en/latest/features/translation_memory.html#configuring-translation-memory

**Comment by ymmd** [comment]
This works as expected. Thanks!

Do anyone interested in this: Don't forget to disabled public access to your elasticSearch service if you decide to use this.
