### ISSUE TITLE
gettext: unit location is missing

### ISSUE THREAD

**Issue by Mixaill** [translate/pootle#6121]
Pootle 2.8.0rc5
Translate Toolkit 2.0.0
Pootle FS localfs project

In pootle
![image](https://cloud.githubusercontent.com/assets/704382/23995836/4c404fd4-0a5c-11e7-9f33-fb57a3e997ad.png)

In file
![image](https://cloud.githubusercontent.com/assets/704382/23995852/6c1ab010-0a5c-11e7-8f02-10c16d8ea943.png)

**Comment by dwaynebailey** [comment]
Validated. Using this file:

```po
#: Warning
msgctxt "Warning"
msgid "Warning"
msgstr "Waarskuwing"
```

If I use localfs then Location is missing.  If I use old style project creation with file existing in `translations` it is created with Locations.

**Comment by dwaynebailey** [comment]
Oops wrong button
