### ISSUE TITLE
POOTLE_CUSTOM_LOGO incorrect rendering

### ISSUE THREAD

**Issue by Mixaill** [translate/pootle#6123]
Pootle 2.8.0rc5

logo is 64x64 png
![image](https://cloud.githubusercontent.com/assets/704382/24005161/4ff6a214-0a79-11e7-9aa4-d2341413bc3b.png)

**Comment by phlax** [comment]
@Mixaill we have an intention to make the layout more responsive - but im afraid quite a bit of stuff is pixel-coded atm

**Comment by dwaynebailey** [comment]
@phlax sounds like all we need to do is set a height on the logo?

**Comment by phlax** [comment]
yep, good point - ill take a look

**Comment by phlax** [comment]
hi @Mixaill - kinda embarrased by initial answer - should be fixed in #6499

**Comment by Mixaill** [comment]
Fixed partly. Two logos in the same time.
![image](https://user-images.githubusercontent.com/704382/27388665-d5abdb50-56a4-11e7-866b-3026a6c38ac4.png)

**Comment by phlax** [comment]
yep @Mixaill we leave the pootle logo there - i think its reasonable to promote the software, and mostly we use a logotype rather than icon for second.

if you really must remove - you can hack the templates
