### ISSUE TITLE
Can't navigate to context units from a search

### ISSUE THREAD

**Issue by julen** [translate/pootle#6159]
Steps to reproduce:
1. Go to https://mozilla.locamotion.org/eu/firefox/translate/browser/chrome/browser/#search=konfigurazio%20okerra&sfields=source,target
2. Click on _Show_ to have context rows displayed
3. Click on any context row.

Actual: URL updates but the editor remains in the same unit.
Expected: URL updates and the clicked unit is open.

**Comment by unho** [comment]
I can reproduce. Thanks for reporting, we will try to get it fixed as soon as possible.
