### ISSUE TITLE
Fix fk issues in 2.6 migration/setup

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6177]
seems like (at least for some users) there is foreign key constraints that are not removed during migration.

we probably need to add something here https://github.com/translate/pootle/blob/stable/2.6.2/pootle/apps/accounts/migrations/0005_drop_pootle_app_pootleprofile.py

specifically, to remove fk constraints to this table on unit commented_by/submitted_by

**Comment by phlax** [comment]
this problem has been confirmed by other migrations

**Comment by unho** [comment]
This was fixed in https://github.com/unho/pootle/commit/1b4011fcdbb6af6142064914490ecdb6853bcb25.
