### ISSUE TITLE
Total number of strings incorrect when a language is missing a file

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#621]
*Version: 1.2.0*

*Originally posted by Christian Perrier:*

The current way to calculate statistics for a given project seems to be flawed for me:

- if a language is missing a file in one directory of a project (treestyle 'gnu') but is complete in all others, that language will be shown "100%"

This comes from the way to calculate the total number of strings, which is the sum of the number of strings in all files for that language.

Indeed, when POT files are present in directories, the total number of strings should be taken from them and not from individual PO files. So, for a project where all subdirectories ahev POT files, the totale number of strings would then be the same for all languages....and the stats for all languages would be calculated accordingly.

With the current method, if one wants to achieve the same result, one is forced to add an "empty" file for each language, by copying the POT file, in each directory, which is suboptimal and clutters the tree, particularly in projects where there are many subdirectories and many languages (http://pootle.debian.net/projects/debconf is a good example!)

**Comment by dwaynebailey** [comment]
We've redone the whole stats calculation approach so closing this.
