### ISSUE TITLE
Can't comment on untranslated Units

### ISSUE THREAD

**Issue by ymmd** [translate/pootle#6231]
We are starting to run Pootle 2.8 and discovered that we can't comment on **untranslated** units.

Steps:
1. Click _Continue translation_
2. Click the icon to add a comment
3. Insert text _Test_ into the textarea
4. Click _Submit_

Instead of submitting the comment, the browser just flashes a red box saying "server error". The apache logs have further information:

```pytb
Traceback (most recent call last):
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/www/pootle/pootle/apps/pootle_misc/util.py", line 53, in wrapper
    return f(request, *args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/var/www/pootle/pootle/apps/pootle_store/decorators.py", line 60, in decorated_f
    return f(request, unit, *args, **kwargs)
  File "/var/www/pootle/pootle/apps/pootle_store/views.py", line 218, in comment
    return save_comment(request, unit)
  File "/var/www/pootle/pootle/apps/pootle_store/views.py", line 246, in save_comment
    unit.change.commented_by = request.user
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 370, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: Unit has no change.
```
Can you reproduce this?

Kind regards,
Sebastian

**Comment by unho** [comment]
@ymmd Which version of Pootle 2.8 are you using? Is it latest master?

**Comment by dwaynebailey** [comment]
I've just tested this on https://mozilla.locamotion.org/en_ZA/ and I'm not able to replicate.  So not replicable post rc5, though it might be an issue for earlier RCs.

**Comment by ymmd** [comment]
Hi and thanks for your replies! We are using Pootle 2.8RC5. We just ran the tests to see if everything works. The result is: 2569 passed, 4 skipped, 51 xfailed, 3 xpassed

In order to collect more information about this issue, we tried to investigate where the Unit's properties are defined. When I submit a comment, my browser makes an HTTP POST request /xhr/units/58762/comment/ and the unit ID, the session ID, the CSRF token, the comment itself and everything else seems to be submitted correctly.

The urls.py is written to match `^xhr/units/(?P<uid>[0-9]+)/comment/?$` and then calls views.comment:

    @ajax_required
    @require_http_methods(['POST', 'DELETE'])
    @get_unit_context('translate')
    def comment(request, unit, **kwargs_):
        """Dispatches the comment action according to the HTTP verb."""
        if request.method == 'DELETE':
            return delete_comment(request, unit)
        elif request.method == 'POST':
            return save_comment(request, unit)

which then calls `save_comment`:

    def save_comment(request, unit):
        """Stores a new comment for the given ``unit``.
        :return: If the form validates, the cleaned comment is returned.
                 An error message is returned otherwise.
        """
        # Update current unit instance's attributes
        unit.change.commented_by = request.user # <-- there we get the error.
        # ...

The unit is fetched via the `@get_unit_context('translate')` decorator which loads a unit from the uid we pass:

    def get_unit_context(permission_code=None):
        def wrap_f(f):    
            @wraps(f)
            def decorated_f(request, uid, *args, **kwargs):
                unit = get_object_or_404(
                    Unit.objects.select_related("store__translation_project",
                                                "store__parent"),
                    id=uid,
                )
             #...

I can't find where the `.change` property of Unit is declared, although I already had a look at the classes that Unit inherits from. The only class I found is the `UnitChange` class which has a foreign key to identify units it belongs to.

There is only one code fragment I found that sets the `.change` property: [pootle_store/models.py](https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/models.py)

    def save(self, *args, **kwargs):
        # ...
        changed_with = kwargs.pop("changed_with", None) or SubmissionTypes.SYSTEM
        super(Unit, self).save(*args, **kwargs)
        # ...
        if self.updated and (created or not self.changed): # line 298
            self.change = UnitChange(
                unit=self,
                changed_with=changed_with)
        if self.updated:
        # ...
        self.change.save()

This should be called whenever a unit is updated, right? Can you help us to understand the if condition in line 298? Does it mean that the change property is only saved for Units when:

1. The Unit could be saved
and
2. The Unit didn't have an ID before it was saved (it was newly created) OR the Unit doesn't already have a changed attribute

I can't think of a case where this was false, so I don't understand why it doesn't work. Is it right to assume that all units always do have a change property?

Do you know a better way to investigate where the error comes from?

**Comment by phlax** [comment]
hi @ymmd the change object is added when the unit is saved - if there is any change - ie it has been translated or had state changed (iirc).

re setting the commented_by in the view - it probably is a bug in the rc code - im not able to check properly until early next week - but i figure we need to add a change object to untranslated units if it has a comment or other change.

re `get_unit_context` and setting such things as comments actually in views - these are deprecated and have mostly been moved to forms or similar in master

**Comment by ymmd** [comment]
Does a state change also take place when a comment is submitted or only when a translation is submitted?

Dwayne already checked this issue on mozilla.locamotion.org which also runs Pootle 2.8.0rc5. The problem does not seem to occur there: https://mozilla.locamotion.org/en_ZA/firefox/translate/browser/profile/bookmarks.inc.po#unit=22436098

Can you think of a reason why it works for them and not in our case?

**Comment by phlax** [comment]
not sure which version @dwaynebailey checked, or if its actually fixed. Your description of the problem does make sense tho - just need some time to check if its fixed and/or suggest a hack to make it work in older releases

**Comment by ymmd** [comment]
Hi, on which level of the call stack would we need to investigate the options for a possible fix?

**Comment by phlax** [comment]
@ymmd im pretty confident this is now working ok in master

if you are able to test against master that would be great - else we should be releasing another rc shortly
