### ISSUE TITLE
Pootle search box ignores diacritics

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6238]
Hi,

there is an (maybe already known) issue with diacritics in Pootle search box, they are ignored. If I e. g. search for the Sorbian characters č, ć, ě, ń, ó, ř, ŕ, š, ž, ź, all the words with these letters without diacritics are shown as well.  Only "ł" seems to work.

**Comment by krunose** [comment]
Problem occurs with words like 'čitati' i 'citati'.

Only difference between those two words is first letter, and 'č' is in above mentioned character set.

If searched for one of those words, result returns both of them like they were one word.

URL bar shows only 'citati' for both words, but Firebug in Firefox shows %C4%8D as what passed to GET for 'čitati'. Shouldn't URL bar show '%C4%8Ditati' when searched for 'čitati'?

It affects fair share of Slavic languages written in Latin script.

**Comment by phlax** [comment]
hi @milupo @krunose - not sure without testing, but im wondering if this has something to do with mysql collation sets. I'll do some testing as soon as i have some time

**Comment by phlax** [comment]
possibly relevant http://stackoverflow.com/questions/500826/how-to-conduct-an-accent-sensitive-search-in-mysql

**Comment by phlax** [comment]
@milupo @krunose i investigated this further - the search was always doing case insensitive search - which for utf8 means diacritic-insensitive too i think.

Ive adjusted this (in https://github.com/translate/pootle/pull/6370) so that if you set exact the search will be case (and diacritic) sensitive

**Comment by krunose** [comment]
Thanks for taking care of this so quickly. This sure puts a balance between searching for diacritics and when case insensitive search is wanted.
