### ISSUE TITLE
Broken PO files are partially loaded without error

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6341]
I mistakenly made a PO file with duplicate units.  The files are mostly like:

N/M.po where N=1 to 3 and M=1 to 20

A bug in my script meant that my files had more than 100 units and they where duplicated.

1. The files loaded but when checking only the first 100 units are actually loaded
2. No error was reported and update_stores did not abort or report any issue

Expected:
1. PO fil with duplicate units should throw and error
2. update_stores should report that error and abort update or that specific store.

**Comment by phlax** [comment]
after some discussion, it was agreed to warn rather than fail
