### ISSUE TITLE
Cant log in using Edge 

### ISSUE THREAD

**Issue by OctoNezd** [translate/pootle#6360]
## Steps to reproduce

1. Click login on main page

2. Enter your login and password

3. Click login

## Expected

Log in succesfully

## Happens

Nothing at all

**Comment by dwaynebailey** [comment]
@OctoNezd do you have a server side or client traceback for us?

**Comment by OctoNezd** [comment]
Nothing happens on server side. I think JS for handling login button just dont work in Edge

**Comment by phlax** [comment]
@OctoNezd im wondering if its an edge problem or phone ui problem - do you know if it works on desktop edge ?

**Comment by OctoNezd** [comment]
I dont know(using Linux on PC, ironic)

**Comment by phlax** [comment]
my guess is more likely phone - its something we would really like to support properly - but sadly dont yet

**Comment by OctoNezd** [comment]
My phone is Lumia 550, insider Fast Ring, version 10.0.15210.0, edge v.40.15210.0.0

**Comment by OctoNezd** [comment]
Bug happens on desktop edge too

**Comment by phlax** [comment]
thanks for report @OctoNezd we will have to get some vm or something to debug it

**Comment by dwaynebailey** [comment]
For testing for non-Windows devs https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by dwaynebailey** [comment]
I've tested this on latest master and I can login to Edge both v14 and v15 in Windows 10.

Testing on a Lumia 550 I can type my username in but can't see password entry field.

@OctoNezd if you can provide more info and more description that could help like Edge version and Windows versions as I can't replicate.

**Comment by OctoNezd** [comment]
My phone is on fast insider ring

Edge version is 40.15215.0.0

System ver is 10.0.15215.0

**Comment by OctoNezd** [comment]
I can see password input, but when I click on Login, nothing happens

**Comment by dwaynebailey** [comment]
See correction above, I can only test on Lumia 930 or on phones with Windows 8.1, thus no edge.

My testing shows Pootle master working correctly on Windows 10 Desktop with Edge 40.15063.0.0, which is slightly older (but really not much) than the version in https://github.com/translate/pootle/issues/6360#issuecomment-307179836

So @OctoNezd we're going to actually need more info to even get a hold on what this issue might be:
1. Could you please give some feedback on how you are testing, a video, anything that shows this actually happening.  If it failed on desktop as you say in https://github.com/translate/pootle/issues/6360#issuecomment-301225426 then this should be easy to replicate.
2. Also what version of Pootle are you using to test this, my fear is that I'm testing master and I'm not sure what version you are testing as its not supplied in this bug report.
3. If it fails on Desktop please supply the JavaScript console errors using F12.

For now I'm going to close this as from my testing of master Desktop Edge does work and mobile has known problems which we need to address under general Pootle mobile ticket.

Please feel free to reopen if you have further clarifying info from the list above.

**Comment by OctoNezd** [comment]
Here is video of bug: https://youtu.be/EI1rpvLciOs

Server responds forbidden when logging in

**Comment by OctoNezd** [comment]
Pootle version is Pootle 2.8.0rc5

**Comment by phlax** [comment]
hi @OctoNezd looking at video im seeing that the server is responding with `403` status

this usually means a missing or wrong CSRF token.

im wondering if hard-refreshing before attempting to log in helps, also i wanted to confirm 100% that the same site is working in other browsers.

if you are still experiencing this issue and are happy for me to, i can load a vm with edge and take look directly myself, to clarify exactly what is sent to the server

**Comment by OctoNezd** [comment]
Hardrefreshing doesnt work. 

This page was loaded first time in this VM, so seems like Edge have some problems with pootle

**Comment by phlax** [comment]
@OctoNezd if you can give me a link to try, i can kick up a vm with edge and check it then

feel free to pm me on https://gitter.im/phlax
