### ISSUE TITLE
Ensure suggestions cannot be made that match target

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6387]
this is not allowed currently in the ui, but the suggestion api should also ensure that this cant happen

**Comment by ta2-1** [comment]
Test in #6430 ensures that. Though we might want to ensure more. For instance if equal pending suggestions cannot be created.

**Comment by ta2-1** [comment]
I'm closing this issue because we can't add suggestions that match current unit target. Though it can be done better and #6493, #6494 are created.
