### ISSUE TITLE
Top scorers list includes zero score users

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6391]
The top scorer list in e.g. `/af/?details` includes a number of users with zero score.

I'm doubtful that these contributed in last 30 days.  So they shouldn't be on the list at all.

![screen shot 2017-05-17 at 10 37 08](https://cloud.githubusercontent.com/assets/647438/26147888/d6e7c214-3aec-11e7-8db8-e847a4e8335a.png)

**Comment by phlax** [comment]
we should make minimum for any score to 1

**Comment by unho** [comment]
Or round up all scores.
