### ISSUE TITLE
XLIFF unit lost comment on update against templates

### ISSUE THREAD

**Issue by unho** [translate/pootle#6412]
Check timeline for https://mozilla.locamotion.org/ca/ios/translate/firefox-ios.xliff#unit=22408560 as a comment was added and then removed by update against templates.

**Comment by unho** [comment]
This might be a consequence of the iOS XLIFF limitations.

**Comment by dwaynebailey** [comment]
I think the issue might be this is a user supplied comment, and I'm not sure if iOS XLIFF can make any distinctions between type or source of comment.  We might be able to preserve some ourselves but not sure if there is a `type=` that we could us for user comments.  Many possible reasons, I guess just testing what happens to a comment in pot2po might be a good thing to check.
