### ISSUE TITLE
Pootle 2.8.0 - Translation of "Getting Started"

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6429]
Hi,

I've just seen that Pootle supports Upper and Lower Sorbian now. Great!

But, the link "Getting Started" and the page behind it are not translated and it seems that it is not intended to let them translate. It would be fine if they could be translated.

Thanks,
Michael

**Comment by phlax** [comment]
hi @milupo wierdly there is a translated string for "Getting started" but not for that link.

The link title is taken from the page name, which is stored in the db and a bit harder to localise. We can try and think of a way to do it.

**Comment by milupo** [comment]
It would be fine if you could find a solution. Try, at least, to separate the link text from the related page behind it. But it is better to have translated the page as well.

**Comment by dwaynebailey** [comment]
@phlax I think we can make at least the link localised as that is within a custom template.  Page we can't at the moment.

**Comment by dwaynebailey** [comment]
```html
{% block nav_items_pre %}
<li><a href="/pages/getting_started">{% trans "Getting Started" %}</a></li>
{% endblock %}
```

So it is marked for translation, not sure why it isn't then getting translated.

**Comment by phlax** [comment]
@dwaynebailey not sure where you are seeing that - if `git grep "Getting Started"` i only see po files

**Comment by dwaynebailey** [comment]
@phlax this is within a custom template, I'm just flagging that it is marked as translatable and thus I'd have guessed it would get translated.

**Comment by dwaynebailey** [comment]
After some confusion I get this now.  I'd assumed "Getting Started" was in the `pootle/strings.py` file, it wasn't.  It had been, but by accident.
