### ISSUE TITLE
Fix accepting suggestion with changes for users with  "can review suggestions" only

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#6433]
A user with "can review suggestions" permission only are allowed to open review suggestion form.
But there is an error when this user accept suggestion with alterations:
```
app.js:1620 Uncaught TypeError: Cannot set property 'disabled' of null
    at Object.handleSubmit (http://127.0.0.1:8000/static/js/editor/app.bundle.js:16753:18)
    at Object.handleAcceptSuggestion (http://127.0.0.1:8000/static/js/editor/app.bundle.js:17438:13)
    at Constructor.handleAccept (http://127.0.0.1:8000/static/js/editor/app.bundle.js:18930:17)
```

Proposed:  disable textarea in `SuggestionReviewForm` similar to the main editor for such users.

**Comment by unho** [comment]
I disagree with proposed fix. Users with `review` permission should be able to do minor tweaks in the suggestions they are accepting, even if they don't have `translate` permission. Otherwise we are seriously limiting their ability to manage suggestions.

**Comment by ta2-1** [comment]
Probs you are right but it is impossible to distinct where minor tweak or big change happens.
And I feel that we are messing between `reviewer` role and `can accept/reject suggestion` permission again.
More over, I've just realised that accept suggestion with changes is handled via `UnitSubmitJSON` which has `@requires_permission("translate")` decorator.

**Comment by unho** [comment]
Then I accept the first proposed fix, if and only if, no "accept with changes" option is provided to user unless user has `translate` permission. Note plain accept/reject and accept/reject with comment should still be available to user with only `review` permission.

**Comment by ta2-1** [comment]
> no "accept with changes" option is provided to user unless user has translate permission

@unho I'm not clear what did you mean here. how can we provide such option?

**Comment by unho** [comment]
A user with both `review` and `translate` permissions, can either:

- Accept suggestion as is,
- Accept suggestion as is with some comment,
- Accept suggestion with changes,
- Accept suggestion with changes and with some comment.

But these last two options look like a bit like translating, so I propose that if the user has **only** `review` permission then that user should only be provided with:

- Accept suggestion as is,
- Accept suggestion as is with some comment.


I hope it is easier to understand now.
