### ISSUE TITLE
Fix Pootle docs theme for Sphinx 1.6.x

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6438]
Sphinx 1.6 introduces changes in how additional CSS is included in the theme.  This means our theme does not work on Sphinx 1.6.

Options:
1. Fix the theme
2. Drop our custom Translate theme

**Comment by arky** [comment]
@dwaynebailey Checked with Sphinx 1.8.3 The theme works as expected. 
![screenshot from 2019-01-29 16-49-45](https://user-images.githubusercontent.com/808895/51899665-18fa0700-23e6-11e9-8bcc-45f2f108b656.png)

**Comment by arky** [comment]
@dwaynebailey Pootle docs theme seems to work nicely in Sphinx 1.8.3. Closing this bug for now.
