### ISSUE TITLE
Check escaping in notification emails

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6453]
we had a report that email notifications may not be escaped correctly so we should check

**Comment by unho** [comment]
All emails are correctly escaped. So closing.

**Comment by unho** [comment]
Reopening since this was not strictly related to using markup in emails but unescaped HTML.

**Comment by unho** [comment]
Created https://github.com/translate/pootle/pull/6459 to address this issue.

**Comment by unho** [comment]
Landed fix in https://github.com/translate/pootle/pull/6459.
