### ISSUE TITLE
Strings Entire Project and Please enter 3 or more characters

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6461]
Hi,

these two Pootle 2.8.0 strings are displayed as untranslated. There is a translated string "Entire Project" - core/views/base.py:112 - which is shown in English but I didn't find the string "Please enter 3 or more characters". Mozilla and Libreoffice are using 2.8.0rc5. Are these two strings newer?

**Comment by unho** [comment]
"Please enter 3 or more characters" comes from a third party JavaScript library which you can translate in https://github.com/select2/select2/tree/master/src/js/select2/i18n Note that some basic JavaScript knowledge can be needed.

**Comment by milupo** [comment]
Thank you, Leandro. hsb.js and dsb.js are missing. Can I create the files copying the code from en.js, or should it be created by a Pootle l10n driver like you?

**Comment by unho** [comment]
@milupo that is a third party project, so it is you who has to contribute the *dsb.js* and *hsb.js* files with proper translations. I can assist with any doubt you have since I have previously contributed the *gl.js*.

**Comment by milupo** [comment]
hsb.js and dsb.js are created. I created them based on pl.js. Could you check them?

**Comment by milupo** [comment]
Hm. I don't find them again. :-(

**Comment by unho** [comment]
@milupo You have to contribute back those files as a PR for https://github.com/select2/select2 project.

**Comment by dwaynebailey** [comment]
@milupo @unho I think a more sensible approach is to:

1. See if string can be made internal, we only use that one AFAIKT
2. Put up a wiki for any additional things that need translation and clear instructions on steps needed.

@milupo not sure if you'd be up for curating such a wiki so that we could share that with others needing similar solutions?

**Comment by dwaynebailey** [comment]
@milupo @unho I've added https://github.com/translate/pootle/wiki/Localizing-Pootle---extras

**Comment by milupo** [comment]
I've juste created the files a third time and sent a pull request. I hope I did it right way based on en.js on master branch. Unfortunately, I forgot to change the contents first and created dsb.js on a tree with a cryptic name where the en.js is not in. I hope that I did not overwrite the en.js in that tree.

**Comment by milupo** [comment]
@dwaynebailey  I'm afraid I'm unable to cope with curating a wiki. But I¨m willing to learn.  :-)

**Comment by dwaynebailey** [comment]
@milupo if you are simply able to edit that above wiki page your already halfway there :)  It will allow you to scratch down conclusions and actions needed beyond the normal.  hsb and dsb are good barometers  of anything that might be missing.

**Comment by milupo** [comment]
@dwaynebailey Well, I know the syntax of MediaWiki because I am a Wikipedian of the Sorbian Wikipedias. I primarily translated the MediaWiki GUI and WP articles into hsb and dsb. But I'm not familiar with GitHub.

**Comment by milupo** [comment]
Unfortunately, the pull requests failed. I don't know what I go wrong, see:

https://github.com/select2/select2/pull/4945
https://github.com/select2/select2/pull/4946

**Comment by dwaynebailey** [comment]
@milupo the pull requests look fine.  None of them should have deleted en.js though, just added your new file.  Bu I'd leave it to upstream as they can use your contribution and fix your commits.

So:
```
cp en.js dsb.js
git add dsb.js
git commit dsb.js
```

Would have worked fine.

**Comment by unho** [comment]
@milupo Travis is failing in those PRs because you are removing `en.js` while you should be only adding new files for your translations. I checked the new files and they look fine, but it is for upstream developers to review your contributions. I strongly suggest you fix your PRs.

**Comment by milupo** [comment]
Sorry, but I have no notion of Github. What shall I do now? It seems that there are patches, hsb.js is on the patch-5 branch and dsb.js is on the patch-7 branch. But how can I get them into the master branch?

@unho How shall I fix my PRs? Is it still necessary? There are patches. Somebody changed the files.

**Comment by unho** [comment]
@milupo Sorry about the delay. You can either:

- Update your branch locally with the right changes and the force push so the current PRs are updated,
- or close existing PRs create a new PR with the right changes.

I suggest you the latter since it is much easier for unexperienced users.

**Comment by milupo** [comment]
Well, it should be OK now. The files are shown on master now. I don't know if other copies are lying around somewhere yet.

**Comment by milupo** [comment]
It makes me wann puke. I've just created the files with the option to send them to master and saw them in master but suddenly they are disappeared again.

**Comment by milupo** [comment]
I've just seen that I do not have access to the "main" master. Y have access to my fork only. The files are there now, see

https://github.com/milupo/select2/tree/master/src/js/select2/i18n

I'm here now:

https://github.com/select2/select2/compare/master...milupo:master

The two items below are the most current. What shall I do now? If I click "Create pull request", which item is used?

**Comment by phlax** [comment]
@milupo if you click to create a pull request, it will be created containing the changes in your branch from master (at that point)

**Comment by milupo** [comment]
It sucks. Now the last item below is marked as failed. Why the last one only? The page

https://github.com/select2/select2/compare/master...milupo:master

shows the content of both files.

https://github.com/select2/select2/pull/4949

Ah, details show that there are two lines too long. Actually, one line in each file. Why?

https://travis-ci.org/select2/select2/builds/241763133?utm_source=github_status&utm_medium=notification

**Comment by phlax** [comment]
most code bases have coding standards setting max line length - usually 80 chars

you just need to split those lines as you did in others

probably you will want to:

- edit changes
- commit
- squash commit
- force push (to your pr branch)

but im thinking you might need to squash the commits that are there already too

**Comment by milupo** [comment]
Hi phlax, thanks,

I've shortened the line in the files and committed the changes. Now I'm here:

https://github.com/select2/select2/pull/4949/files#diff-fde929763935fbc9c565c60414d62a92

What to do now?

**Comment by phlax** [comment]
probably you want to squash the commits into just 2 - one for each file i figure

easiest way is to use `git rebase -i HEAD~20` 

from there you can reorder the commits, and you can replace `pick` for the commits to be squashed with  `s` for squash

trying to find a good link - this is probs good https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history#squash-commits-together

**Comment by milupo** [comment]
> git rebase -i HEAD~20

is a Github command. I work online, I didn't install Github on my locale machine and I don't want to do it for these two files only.

**Comment by milupo** [comment]
It's terror. The last commit for dsb.js with the changed line failed, too. I don't know why.

https://github.com/select2/select2/pull/4949/commits

**Comment by phlax** [comment]
tests are passing now afaict

**Comment by milupo** [comment]
And how do I get them to the main master? It is irritating. They are in any trees but not in the master branch, commit **create dsb.js** failed, **create hsb.js** not (or does each commit contain both files?) Github is very complicated.

**Comment by phlax** [comment]
> And how do I get them to the main master?

thats up to the project to accept it

> Github is very complicated.

dont worry its not so bad when you get used to it, and its pretty powerful

**Comment by dwaynebailey** [comment]
Note: `Entire Project` is localisable, there was some issue with capitalisation that is fixed.  I've tests and both dsb and hsb already localised, when deployed to Mozilla they should then be correct.

With dropdown string that is now upstream so we'll leave that in the hands of that team.

@milupo I'm going to close this, feel free to comment here if you need help and assistance with the upstreaming to select2.

**Comment by milupo** [comment]
@dwaynebailey Thank you Dwayne, I can confirm, "Entire project" is translated now. I hope the files will be on the right place soon.
@phlax Already now thank you very much for your big patience with me.
