### ISSUE TITLE
Exact search does not return exact search results

### ISSUE THREAD

**Issue by unho** [translate/pootle#6475]
For example searching for "tab" returns results containing "table" or "database" which are partial matches.

**Comment by unho** [comment]
Check if this is a regression since latest version.

**Comment by unho** [comment]
Checked in Pootle 2.7.6 and in current PLO (2.5.1-rc1) and the behavior is the same: exact search for "tab" returns partial matches like "table", "database" or "executable". So moving to https://github.com/translate/pootle/milestone/39 milestone.

**Comment by dwaynebailey** [comment]
I think this is doing what it was intended to do but that the wording is probably bad:

It doesn't say exact search it says "Exact Match" and that is kinda what it does.

* Exact match - not selected.  Search for "Tab" and it will match "tab", "Tab", "table", etc
* Selected.  Search for "Tab" and it will find "Tab", "Table" but won't match "tab", "table" etc.

Perhaps "Exact Case" would be a more correct wording? Having said that I've always been confused myself.

**Comment by unho** [comment]
"Case sensitive" would be a better wording IMHO.

**Comment by dwaynebailey** [comment]
Just to be clear here when it comes to searching for a phrase:

1. Exact match - not selected.  Each word will be used to search.  I.e. it is an OR.  Case is ignored.
2. Selected. Only the exact phrase will be used.  I.e. same words, same order and same capitalisation
