### ISSUE TITLE
"pootle migrate" aborts with too long keys

### ISSUE THREAD

**Issue by ikedas** [translate/pootle#6482]
Pootle 2.8.0rc5

During installation according to instruction in Pootle Documentation, `pootle migrate` aborted with this message:
> Specified key was too long; max key length is 1000 bytes

I encountered with it using MyISAM and `utf8` charset on MySQL 5.1.73. I could fix it by following change:
```patch
--- pootle/apps/pootle_revision/migrations/0001_initial.py.orig	2017-01-30 22:37:44.000000000 +0900
+++ pootle/apps/pootle_revision/migrations/0001_initial.py	2017-06-09 18:24:11.818705589 +0900
@@ -19,8 +19,8 @@
             name='Revision',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
-                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'object ID')),
-                ('key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name=b'Revision key')),
+                ('object_id', models.CharField(blank=True, max_length=133, null=True, verbose_name=b'object ID')),
+                ('key', models.CharField(blank=True, db_index=True, max_length=133, null=True, verbose_name=b'Revision key')),
                 ('value', models.CharField(default=b'', max_length=255, verbose_name=b'Revision hash or numeric marker')),
                 ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_revision', to='contenttypes.ContentType', verbose_name=b'content type')),
             ],
```
The value `133` is not well-thought.

I guess, on InnoDB with ``utf8mb4`` charset, it should be `95` (767 [bytes] / 4 [bytes per character] / 2 [columns]) or lesser.

**Comment by phlax** [comment]
hi @ikedas current pootle only supports innodb, so if you are migrating from an older version, you will need to do the conversion first (iirc)

also, regarding the mysql version - 5.5 is known to work atm, but moving forward we are likely to set min mysql version to 5.6+

regarding the revision key length - the suggestion looks good, but shouldnt be necessary if you are on innodb and current version

**Comment by ikedas** [comment]
@phlax, I understand that gone version MySQL 5.1 won't be supported anymore.  If 5.5+ works well, there are no worries.   I'll close this issue.
