### ISSUE TITLE
Blank upload screen

### ISSUE THREAD

**Issue by Ntouris3** [translate/pootle#6505]
Im a new github user and today i was trying to upload some files to my repo but every time i clicked on "commit changes" button i ended up with a blank screen while nothing gets uploaded. Im using Windows 10 pro. 
(I know this issue has been solved a long time ago but i still face it!)

**Comment by phlax** [comment]
hi @Ntouris3 im assuming that this is quite an old version of pootle, as that button no longer exists.

as we dont really support bugfixes for the older versions im not sure this will get resolved

we do have beta support for vcs integration in the latest rc version, so you might want to try that

ping us on https://gitter.im/translate/pootle if we can help with that

closing this ticket as its unlikely to get fixed
