### ISSUE TITLE
Wrong count of incompletes for empty source strings

### ISSUE THREAD

**Issue by julen** [translate/pootle#6507]
In the context of https://mozilla.locamotion.org/, the statistics for incomplete counts in _Firefox 55 (Beta)_ don't look correct, as they report incomplete counts for empty source strings.

Examples:
* https://mozilla.locamotion.org/cy/firefox_beta/
* https://mozilla.locamotion.org/eu/firefox_beta/

This is not happening in the _Firefox (Nightly)_ project, which in fact was the source for the beta project.

**Comment by dwaynebailey** [comment]
@julen Nightly was cloned to Beta, so should carry all translations, check states, etc across.  Does nightly use ZWNJ for those or are they truly blank?

**Comment by julen** [comment]
No ZWNJ that I'm aware of. Note how the same strings are reported as translated in nightly.

**Comment by milupo** [comment]
How should empty strings marked that they are shown as translated? Until lately, I translated them adding a space character and I removed the space character then again. I sent a message to m.dev.l10n, too.

news://news.mozilla.org:119/Lt2dnYwk3Og9it3EnZ2dnUU7-IfNnZ2d@mozilla.org

"How to mark empty strings as translated?", from June 13th.

**Comment by julen** [comment]
Thanks for the fix 👍 Is this going to be deployed anytime soon? FWIW there are still incomplete counts being reported.

**Comment by unho** [comment]
@julen Thanks for raising it. A deployment with this fix was just carried over. Correct stats should be displayed shortly.

**Comment by ta2-1** [comment]
@julen I'd reopen this issue because of https://github.com/translate/pootle/pull/6553#issuecomment-314745123
