### ISSUE TITLE
Where does last action time come from?

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6512]
Hi,

Upper Sorbian Pootle uses the word **minuta** (and its plural forms minuće, minuty, minutow) for the **Last action:** string. The more usual word, however, is **mjeńšina** (mjeńšinje, mjeńšiny, mjeńšin). I didn't find neither English "minute" nor Upper Sorbian "minuta" in the Pootle 2.8.0 translation project. Thus, where does the word **minuta** come from?

Here is a screenshot of the LO translation project:

![lo_pootle_minuta](https://user-images.githubusercontent.com/1248520/27256652-e11e2bd6-53bc-11e7-96d6-4ca4aa63e2d0.png)

**Comment by dwaynebailey** [comment]
@milupo we're picking these up via [CLDR](http://cldr.unicode.org/).  So those are being defined there.  Would you mind having a look there.  Please feel free to reopen if you find that we're not using the correct form for this context but we'd prefer to align with CLDR then to have any customisations.

**Comment by milupo** [comment]
Thank you Dwayne. Meanwhile I have looked on CLDR as well and have found the entries.
