### ISSUE TITLE
Running `calculate_checks` without a project specified runs same checks for all projects

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#6519]
It seems that running `pootle calculate_checks` uses same checks for all projects, regardless of per-project settings.
This caused quite a headache for me by seemingly using the `standard` checks on a project with `reduced` checks specified.

**Comment by phlax** [comment]
the problem appears to be with teechecker https://github.com/translate/translate/blob/master/translate/filters/checks.py#L579
