### ISSUE TITLE
Changing source (with xliff) can create submissions with no submitter

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6521]
# Steps to reproduce:

- change source in file of existing unit
- run update_stores

# Results

- submissions have no submitter
- stuff breaks

## Expected result:

- nothing breaks

this only happens in xliff afaict - as i dont think its possible to change source of units in this way with po

**Comment by dwaynebailey** [comment]
```xml
       <trans-unit id="SomeId">
-        <source>Old source</source>
-        <note>Old note</note>
+        <source>New source</source>
+        <note>New note</note>
       </trans-unit>
```
