### ISSUE TITLE
Server Error on Mozilla Pootle

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6522]
Hi,

I wanted to translate Firefox for iOS on Mozilla Pootle but I can't save my translations. I get an Server Error message instead. On the other hand, Libreoffice Pootle works.

Regards,
Michael

**Comment by phlax** [comment]
hi @milupo there was an issue overnight thta is now fixed - is this still an issue now ?

**Comment by milupo** [comment]
Thank you Phlax but unfortunately not yet.

**Comment by dwaynebailey** [comment]
@milupo checking the main project page, both Sorbian's and all are working, also no reported errors.  Could you maybe elaborate what you mean when you say it isn't working for you?

**Comment by phlax** [comment]
hi @milupo i tracked errors on the server.

this issue has been happening on and off - altho im not certain of exact cause

i have opened a ticket to deal with that #6523 

editing should work ok now - closing this in favor of above ticket
