### ISSUE TITLE
Creating user scores sometimes causes duplicate/integrity error

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6523]
# Steps to reproduce:

- create a translation, first translation of the day
- possibly caused by v fast 2nd edit

# Results

- Integrity error thrown while adding users tp score

i had assumed that this was caused by fast editing, altho im now wondering whether it can be caused jut by making the first edit of the day, ill try harder to reproduce

**Comment by milupo** [comment]
Here is a screenshot:

![server_error_mozilla_locamotion](https://user-images.githubusercontent.com/1248520/27478433-e4746032-580f-11e7-9bdd-46c5c5868c21.png)

**Comment by dwaynebailey** [comment]
@milupo if you go to another unit are you able to proceed?

**Comment by milupo** [comment]
Unfortunately not, the same issue.

**Comment by dwaynebailey** [comment]
@milupo could you join us on https://gitter.im/translate/pootle as we try diagnose this

**Comment by milupo** [comment]
Thank you very much for your efforts. It works again now.

**Comment by phlax** [comment]
This was closed in https://github.com/translate/pootle/pull/6531
