### ISSUE TITLE
pootle.db does not exist

### ISSUE THREAD

**Issue by drashti4** [translate/pootle#6544]
# Steps to reproduce:
When I run pootle migrate It shows me 

`django.db.utils.OperationalError: FATAL:  database "/usr/local/lib/python2.7/dist-packages/pootle/dbs/pootle.db" does not exist`

even though file is exist.

` usr/local/lib/python2.7/dist-packages/pootle/dbs$ ls`
` pootle.db  README`

# Environment (i.e. 'pootle --version', DB, OS, Browser):
Ubuntu 14.04
Pootle 2.8.0rc6 (Django 1.10.7, Translate Toolkit 2.2.3)
python2.7

**Comment by dwaynebailey** [comment]
@drashti4 hi, thanks for trying out Pootle.

Could you tell me what steps you followed before you ran migrate as this doesn't look like a setup following our [installation guidelines](http://docs.translatehouse.org/projects/pootle/en/latest/server/installation.html#installation)

Also could you do `ls -l` so I can see if there are any permission errors.

So things I've tested:

1. The `pootle.db` does not need to exists, it will create it if it is missing
2. Permission: it will fail if it can't read and fail if it can't write.

So I'm currently unable to replicate this exact scenario, hence my first question about knowing how you got to this point and which steps you had run.

**Comment by drashti4** [comment]
I have followd installation guidelines.

`(env) $ pootle init` changed .conf file for 

      `ENGINE': 'django.db.backends.postgresql',
       
        'NAME': working_path('dbs/pootle.db'),
       
        'USER': 'postgres',
       
        'PASSWORD': 'admin',
       
        'HOST': 'localhost',
       
        'PORT': '5432',`

Run server `(env) $ sudo pootle rqworker`
`include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/pootle/checks.py", line 579, in check_mysql_timezones
    with connection.cursor() as cursor:
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  database "/usr/local/lib/python2.7/dist-packages/pootle/dbs/pootle.db" does not exist`

I checked path
`(env)$ cd /usr/local/lib/python2.7/dist-packages/pootle/dbs`
It works
`../dbs$ ls -l`
`-rw-r--r-- 1 root staff 353280 Jul  1 10:55 pootle.db`
`-rw-r--r-- 1 root staff    265 Jun 20 20:53 README`

**Comment by dwaynebailey** [comment]
OK, you're wanting to use PostgreSQL but you haven't refined the name of the database, it is still set to the SQLite database. Please have a look at the [PostgreSQL instructions](http://docs.translatehouse.org/projects/pootle/en/latest/server/postgresql_installation.html)

I'm going to close this as I think that sorts out the problem you had.

If you can see improvements to the docs that would prevent other people hitting this problem we'd love contributions to improve documentation.

**Comment by drashti4** [comment]
now It gives `django.db.utils.OperationalError: FATAL:  database "/usr/local/lib/python2.7/dist-packages/pootle/pootledb" does not exist` Database is successfully created in postgres

**Comment by dwaynebailey** [comment]
@drashti4 you need to tell me exactly what instructions you followed and what steps you took.  When I follow the instructions in the docs it works perfectly.  It looks to me like you still have `workingpath('pootledb')`  as can't think of any other reason why its teuing to write to a database called `/usr/local/lib/python2.7/dist-packages/pootle/pootledb`

**Comment by dwaynebailey** [comment]
@drashti4 best place for this type of help is on https://gitter.im/translate/pootle
