### ISSUE TITLE
Muted checks don't act muted in Pootle 2.8.0rc6

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#6550]
In Pootle 2.8.0rc5, after translating a string and triggering some warnings (namely, XML tag mismatch), I could mute that check and/or press Ctrl+Enter to navigate to the next string.

With rc6, even if I mute that check for that translation, Ctrl+Enter still flashes that check to me and does NOT take me to the next string, regardless of how many times I press that key combo.

**Comment by dwaynebailey** [comment]
Just validated, this did work in 2.8.0rc5 but doesn't work on master.
