### ISSUE TITLE
Install 2.7.6 conflicts

### ISSUE THREAD

**Issue by dikkeduif** [translate/pootle#6592]
I'm not really familiar with python and pip, it might be a simple issue to resolve.
I managed to install 2.7.6 in a virtualenv, but when I run pootle it throws the following error

> pkg_resources.ContextualVersionConflict: (urllib3 1.22 (/home/.../dev/pootle/env/lib/python2.7/site-packages)

I ran the following command to see what the conflict is
>pipconflictchecker 

And got the following response

>Conflicts Detected
>--------------------------------------------------
> - urllib3(1.22) requests(<1.22,>=1.21.1)
> - Django(1.7.11) django-bulk-update(>=1.8)
> - Django(1.7.11) django-statici18n(>=1.8)
> - Django(1.7.11) jsonfield(>=1.8.0)

I'm not sure how to proceed. I tried to install urllib by doing pip install urllib, which installs the package but it's still throwing the error.

**Comment by dwaynebailey** [comment]
@dikkeduif please try `pip install 'urllib3<1.22'`

Also not that you seem to have requirements installed from Pootle 2.8.0 so you might want to start a new virtualenv.

**Comment by dwaynebailey** [comment]
@dikkeduif in fact I'd start this virtualenv from scratch as I don't think the conflicts are related to 2.7.6, but rather to 2.8.0 dependencies.

**Comment by dikkeduif** [comment]
@dwaynebailey thanks, much appreciated. I did install 2.8 first but then decided to use the stable version, uninstalled it and then installed 2.7.6. I removed the environment completely now and reinstalled, but I'm still getting one conflict on urllib

> Conflicts Detected
>--------------------------------------------------
>- urllib3(1.22) requests(<1.22,>=1.21.1)

**Comment by dikkeduif** [comment]
Ok I think it's good now

I did
>pip uninstall urllib3 
and then
>pip install urllib3==1.21.1
