### ISSUE TITLE
Localization of the search form

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#6603]
These strings of the search form need to be localized

![](http://i.imgur.com/GKl31cK.jpg)
![](http://i.imgur.com/VOSBtjz.jpg)
![](http://i.imgur.com/lPH5myz.jpg)

**Comment by phlax** [comment]
@JohnnyKing94 , i think these strings are coming from select2

**Comment by unho** [comment]
Yes, these strings come from select2 javascript library. You have more info on how to translate this in https://github.com/translate/pootle/wiki/Localizing-Pootle---extras#select2-dropdowns

I am closing this ticket.
