### ISSUE TITLE
Debian 9 installation issues

### ISSUE THREAD

**Issue by avdijalink** [translate/pootle#6640]
hello,

I am having some issues installing pootle on debian 9. I have installed all necessary requirements.

# Steps to reproduce:

pip install virtualenv
Requirement already satisfied: virtualenv in /usr/lib/python2.7/dist-packages
virtualenv env
-bash: virtualenv: command not found

**Comment by phlax** [comment]
hi @avdijalink 

can you do
```
which virtualenv
```
if that doesnt yield anything try
```
ls /usr/bin/virtualenv
```
if that still shows nothing then it would seem like a bug in the debian virtualenv package

**Comment by samtuke** [comment]
Are there plans to make Pootle Debian 9 compatible?

**Comment by phlax** [comment]
@samtuke im running various installs on debian 9 without issue

**Comment by samtuke** [comment]
@phlax That's great to hear! Is Debian 9-specific documentation available for the installation procedure?

**Comment by phlax** [comment]
not exactly - although debian is our reference implementation - so the current docs are kinda debian specific - altho more tested against 8

**Comment by samtuke** [comment]
@phlax do you remember what steps you took to set up your own Debian 9 installation, e.g. workarounds for virtualenv and mariadb vs mysql ?

**Comment by phlax** [comment]
we tend to use virtualenvwrappers - so steps would be:

- install virtualenvwrappers using deb package
- create a user to run the app
- use mkvirtualenv to create the initial env

we should probably update the docs to reflect using wrappers, i think

**Comment by phlax** [comment]
having said that - i reckon it should work with straight virtualenv - so it would be good to find out the issue with virtualenv not being on the path that @avdijalink  had

**Comment by phlax** [comment]
re mariadb v mysql - ive been pushing to ditch the mysql docs for some time - in debian 9 ive been using mariadb because its properly packaged

**Comment by comradekingu** [comment]
@samtuke Is this still an issue on Debian 9.4? Write down what you do, and make a new issue if so.

**Comment by phlax** [comment]
for reference we have added docker recipes that include the required steps to install on debian 9

https://github.com/translate/pootle/tree/master/docker
