### ISSUE TITLE
Upgrade docs suggest using `--pre` for upgrade

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6674]
the docs here http://docs.translatehouse.org/projects/pootle/en/latest/server/upgrading.html#upgrading-from-version-2-6-x-or-later suggest using `--pre` but this should not be the case if you are not wanting to use beta versions

**Comment by unho** [comment]
The *latest* docs in RTD are for `master` branch which is actually a Pootle Beta, so the docs are correct. Note the docs for the latest stable are indeed correct (no `--pre`) http://docs.translatehouse.org/projects/pootle/en/stable-2.8.x/server/upgrading.html#upgrading-from-version-2-6-x-or-later

**Comment by unho** [comment]
Changed RTD config so by visiting http://docs.translatehouse.org/projects/pootle/ you get redirected to newest stable docs instead of **latest**.

**Comment by phlax** [comment]
hmm, k, we can close this ticket then
