### ISSUE TITLE
Try simpler language code as fallback before settings.LANGUAGE_CODE

### ISSUE THREAD

**Issue by unho** [translate/pootle#6678]
In https://github.com/translate/pootle/blob/10913224/pootle/i18n/override.py#L87-L101 if the language code `it-IT` (for example) is tried and eventually falls back to `settings.LANGUAGE_CODE`, but it makes sense to first try `it` (simpler version of `it-IT`) before falling back to `settings.LANGUAGE_CODE`.

**Comment by phlax** [comment]
my only concern is whether this corresponds to the language codes for which there are select2 translations

**Comment by unho** [comment]
Select2 safely defaults to English if you provide some unexistent language code in Select2 l10n.

**Comment by phlax** [comment]
not sure @unho - this was what was borking when the server lang was not recognised

**Comment by unho** [comment]
That shouldn't be the case because Pootle does not serve the Select2 l10n file if the language is not supported by Select2 l10n: https://github.com/translate/pootle/commit/5c2d72773122820d67c9436ffa2cc6fede1ecc08#diff-db6ee1857cb4184ef57b57f238915bfbR49

**Comment by phlax** [comment]
it might be just that other js was borking causing the select2 fail.

im thinking that if all else fails - ie we dont recognise the server lang or the server lang root we should fall back to `en`

**Comment by unho** [comment]
I agree. `settings.LANGUAGE_CODE` must be checked to see if it is supported https://github.com/translate/pootle/blob/10913224/pootle/i18n/override.py#L35-L38 and then fall back to `en`.

**Comment by unho** [comment]
A small correction, the fallback should be `en-us` to align with https://docs.djangoproject.com/ko/1.11/ref/settings/#language-code
