### ISSUE TITLE
BUG UI about silencing checks

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#6689]
Despite I silenced the critical errors, if I reload the page, I keep seeing the red alert on the unit.
![](https://i.imgur.com/t0Lysid.jpg)

**Comment by unho** [comment]
What are the exact steps you followed? I mean something like:

- Go to unit with critical checks
- Mute all checks
- Background is still red despite all checks silenced

**Comment by JohnnyKing94** [comment]
- I go to the unit with critical checks
-  I mute the check
- The red alert disappear
- I try to reload the page of that unit
- The red alert appears again

**Comment by JohnnyKing94** [comment]
Pootle 2.9.0b2

**Comment by phlax** [comment]
@JohnnyKing94 seems like the issue is just with the red background. I can repro, and the check stays muted, doesnt block etc, but as you said the background appears again red. I'll see if i can fix...
