### ISSUE TITLE
Public instance?

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#6709]
I’m trying to show some people how to use Pootle (among other tools), but http://mozilla.locamotion.org/ is now gone, and http://pootle.locamotion.org/ seems gone too. So do you have/know any public instances that one could show to people and do some very basic training?

**Comment by phlax** [comment]
hi @khaledhosny not public as such. Pootle locamotion should be back up asap (apologies for the downtime). In the meantime if you ping me on https://gitter.im/translate/pootle i could probably set you something up

**Comment by khaledhosny** [comment]
I won’t need it before the 24th, so if http://pootle.locamotion.org/ can be back online by then that would be ideal.

**Comment by dwaynebailey** [comment]
@khaledhosny the site is back up, would appreciate if you could give it a spin to test before we make a wider announcement.

**Comment by khaledhosny** [comment]
I did a quick test and it looks good, thanks.
