### ISSUE TITLE
GNU style with `/po/` needs user intervention to complete migration

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6717]
# Steps to reproduce:
Created project like likes on 2.8.x, the project is gnu-subdir and the based dir is gnu-subdir, i.e. `/po` is a subdirectory in the project, like most GNU style setups.

```
(poole)~/dev/pootle/pootle/translations (master)$ find gnu-subdir
gnu-subdir
gnu-subdir/po
gnu-subdir/po/af.po
gnu-subdir/po/de.po
gnu-subdir/po/simple.pot
```

Migrate to 2.9

```
(pootle)~/dev/pootle/pootle/translations (master)$ pootle fs fetch gnu-subdir
(pootle)~/dev/pootle/pootle/translations (master)$ pootle fs state gnu-subdir
Removed from filesystem (3)
---------------------------
Files that have been removed from the filesystem

  /af/gnu-subdir/po/af.po
   <-->  (/po/af.po)
  /de/gnu-subdir/po/de.po
   <-->  (/po/de.po)
  /templates/gnu-subdir/po/simple.pot
   <-->  (/po/simple.pot)
```

Checks mapping, no `/po/` prefix for the project files.  Added that, still state gives brokenness.

Now added a templates -> simple mapping to see if .pot sync can happen if we fake the language name.

Result is that it picked the lang mapping and change in file mapping up.  Seems file mapping was somehow cached until we changed the language mapping.

**Comment by phlax** [comment]
I believe this fixed on master @dwaynebailey can you confirm ?

**Comment by phlax** [comment]
closing this as im pretty confident its fixed

**Comment by dwaynebailey** [comment]
Yp fixed, I tested and subdir and template mapping now both work
