### ISSUE TITLE
[Idea]OCR based screenshot loading

### ISSUE THREAD

**Issue by martonmiklos** [translate/pootle#6775]
I an working with an iPAD application which localization is currently done through Pootle. Having screenshots for the translation could help a lot.  Manually generating screenshots is a time consuming process, so the following idea came into my mind:
Create a tool/plugin/feature/whatever which could be loaded with a bunch of screenshots from the app, and then an OCR would be run on each screenshot. If a string is found which is in the source text database then a copy of the screenshot should be generated by marking the found text with a rectangle and it would be automatically linked to the translation entity. 

I have played a bit with tesserract and it successfully identified most of the strings on our screenshots. 

I have created this Issue to have some brainstorming on this topic. Feel free to give some hints about the most proper implementation method. I was thinking about creating and external application, but if the pootle developers would welcome this feature in the future then I would start the development that way.

**Comment by phlax** [comment]
hi @martonmiklos seems like a good idea but im not sure everyone would use it, and therefore wouldnt want the dependencies etc.

If you want to host a repo for this tool, i reckon we could do that.

If you want to discuss further the best place is on https://gitter.im/translate/dev

**Comment by comradekingu** [comment]
@martonmiklos I think a better way to do it is in the IDE or similar. I know Qt has some built-in stuff for it. https://blog.codeship.com/automating-screenshots-in-documentation/ might help you.
