### ISSUE TITLE
FR: possiblity to edit two languages in the same screen

### ISSUE THREAD

**Issue by princeofnaxos** [translate/pootle#6784]
Having multiple flavours of a language, e.g. es_ES and es_MX, it would be a nice feature to be able to edit those in the same screen. Since many words are the same in these languages, our translators don't have to translate the same texts twice, but could just copy it to the other language(s).

Another solution could be to create a 'hierarchy' between languages. Here, es_ES would be defined as the parent for es_MX. This way, a missing translation in es_MX would be filled by the translation in es_ES, and not by empty.

**Comment by princeofnaxos** [comment]
No, that’s the other way around. I would like to see 2 or more textareas.

Edwin Boersma
Fasterminds
http://www.fasterminds.com

Tel.: +46709726431
Tel.: +46313011801

**Comment by comradekingu** [comment]
@princeofnaxos 
You can download the PO-files, and upload them to the requested branch.
You could use two browser windows to do it too I suppose.
However, setting up a fallback in your locale for the user should fix things if things arent completely translated. https://www.gnu.org/software/gettext/manual/gettext.html#The-LANGUAGE-variable
This won't be fixed soon unless you do it yourself. Providing a mockup is a start for someone else to build on.

**Comment by comradekingu** [comment]
@princeofnaxos I thought of a hacky way to do it
Add simular languages as suggested languages/examples
Change strings only when there are actual differences.
Download the strings of the similar language
Upload the finished strings of the main variant
Upload the strings of the similar language, (with updated timestamp) over that

It might be possible to edit suggested/example languages in the editor and merge in a better way in the future, but it is projected to happen beyond work on a few other things, closing for now.
