### ISSUE TITLE
Google Translate Service button on Pootle UI is useless....

### ISSUE THREAD

**Issue by OfficalAhmad** [translate/pootle#6799]
So i have been translating Arabic for a while on the Pootle website for the Open Source project: "OpenOffice", and have realised the Google Translate button. It can be seen below in the link below:

![image](https://user-images.githubusercontent.com/33064898/35836985-238dcd8e-0adb-11e8-8fd6-57d12d990edf.png)

So I decided to fiddle around with the button a little and came across an issue that occurs not only in the Arabic translation section, but for all other languages such as French, German, Italian and so on. So when i attempt to click the button, I expect it to either open a new window directing me to the google translate page, or maybe a mini-window on the current webpage I’m on, or at the very least, automatically translate the English string to Arabic based on Google translation. None of that happens, though, and instead I receive an error message at the bottom of the webpage saying “Google Translate Error. The request is missing a valid API key”. This can be seen in the image below:

![image](https://user-images.githubusercontent.com/33064898/35837077-be33c9ec-0adb-11e8-8689-08b70e54c8d7.png)

Since Pootle is Open Source too, I have then realised there is absolutely no point with this Google Translate button at all. This is my reason... Firstly, The Pootle documentation
http://docs.translatehouse.org/projects/pootle/en/stable-2.7.2/features/machine_translation.html
states this is a paid service, with fees listed at
https://cloud.google.com/translate/pricing

The fact that it is a paid service complicates things a lot. Not much 
for the amount (it's 20$ per million characters; still, it would be a 
large amount if you consider all strings and all languages), but for the 
paperwork needed for the ASF to an expenditure "per use" of this kind.

So, considering all this, would it not seem reasonable to remove this button for Open Source projects such as OpenOffice, who i have communicated with their translation mailing lists and they have explicitly made it clear that a paid service in Google Translate just wouldn't function in free services. If this button can be removed, it would tidy up the interface a little at the very least, and remove nonfunctional/unneeded features.

Thanks,
Ahmad

**Comment by unho** [comment]
Whether this should be shown or not is up to the people that handles each Pootle deployment.

Anyway I think that the behavior you are seeing has changed in recent Pootle versions.

**Comment by comradekingu** [comment]
https://translations.documentfoundation.org Doesn't have it, and LibreOffice it is a more feature rich office suite, which has fixed a whole lot of critical bugs that are still left behind in OpenOffice.
