### ISSUE TITLE
After last suggestion is rejected, webpage skips to next word... annoying

### ISSUE THREAD

**Issue by OfficalAhmad** [translate/pootle#6800]
Hi all,

Firstly, for those of you who have translated to any language of your preference using this service, you may or may not know what I am about to say. Basically, when there is a suggestion on a word that is untranslated, or is translated and perhaps “needs work”, if I accept or reject the last suggestion, the webpage will automatically skip to the next word, even if the current word has not been translated. This is quite annoying, as I do not want it to skip to the next word, and then I have to navigate back to the word I was on, in order to finish, either fixing up an error/s, or translating the word since it is incomplete. 

In my opinion, it is logical that if a word is untranslated, and there were suggestions, for which i reject all of them, that means the word is still untranslated, but the issue is at this point, the webpage will just move onto the next word as if i translated the word, or left it for needing work, or similar. In my opinion, when i reject all suggestions, the webpage should remain on the same current word i'm working on until I move onto the next word by clicking, searching, or submitting the current word. Please fix this...

**Comment by unho** [comment]
The handling of suggestions has been reworked in the latest Pootle versions and plenty of bugs were fixed.

I am closing this ticket. If you experience this issues with the latest Pootle version please let us know so we can reopen this ticket.
