### ISSUE TITLE
On "Top Contributors" section, the "Reviews" count is buggy... OpenOffice project on Pootle service

### ISSUE THREAD

**Issue by OfficalAhmad** [translate/pootle#6801]
SO i have been translating and reviewing words that needed to be reviewed, and have realised that whilst my "Submissions" count on the website is correct, the "reviews" count seems buggy and has been like that for 4 days now, especially considering the fact that i have reviewed and translated around 5000+ for Arabic on OpenOffice. You can see this on the picture below... that my reviews count is 122 for user "skyray1".

![image](https://user-images.githubusercontent.com/33064898/35837635-2322fc08-0adf-11e8-8fb2-fff660c0764a.png)

4 days ago, my submissions count was 492 which is now 3135 on the picture above for user "skyray1", and the reviews count was 122... 4 days ago too. I have translated & reviewed thousands of words since then, yet the review count stays the same and the submissions count goes up as i submit translations.

Please if this can be looked at and fixed, as i have discussed with the OpenOffice community and the majority point towards Pootle being responsible for this, which is why i am submitting this issue here.

**Comment by unho** [comment]
That has changed in recent Pootle versions. So I am closing it as it is already fixed.

**Comment by OfficalAhmad** [comment]
You closed this issue without having an idea of the full scope of this issue. I have reviewed around 1000+ translations, yet i am on 124? That hasn't changed on the website for Pootle: https://translate.apache.org/ar/ ............ if it was fixed i would have closed the issue myself, but it clearly isn't.

**Comment by phlax** [comment]
@OfficalAhmad if you need help upgrading the server you are working on can you ping us on https://gitter.im/translate/pootle - we will help as we can.

I think this will resolve some of the issues that you are having
