### ISSUE TITLE
Suggestion to make the UI better for Pootle Translate service whilst translating....

### ISSUE THREAD

**Issue by OfficalAhmad** [translate/pootle#6802]
So i have been translating a lot, and have felt annoyed with the limitations of the translation UI..... In the picture below, you can see the UI...

![image](https://user-images.githubusercontent.com/33064898/35837918-9ccf44de-0ae0-11e8-9fbb-97f7eb92d79a.png)

So i can see where the "previous" and "next" buttons are (in the bottom right of the screen". I want to point out that when translating for a long period of time, you want things to be consistent for efficiency. From personal use, i do not like the position of where those buttons are and would much rather prefer these to be next to the green "Submit" button. Currently it is annoying that the previous and next buttons are where they are because when translating, i did not even realise they existed due to their positioning and colour (mixed with the theme colour of the webpage), makes it harder to be clear in the eye.

As a suggestion, for instance, the previous button can have an upwards arrow indicating previous word, but can be greyed out (meaning unable to click) if the current word is the first in the list (logical as there is no word before the first). For the next button, it can be a downwards button indicating next word, as it can be seen that the list, as you submit words goes downwards. For the next button, when there is no more words after the current word, the downwards button can be greyed out. I have thought this through, and after careful consideration, believe that this would help with efficiency of translation when translating for long periods of time.

**Comment by unho** [comment]
This is the old UI. The new one has changed a bit:

![ui](https://user-images.githubusercontent.com/939880/36043784-c0863bd8-0dd0-11e8-837e-c40c74e85016.png)

**Comment by OfficalAhmad** [comment]
I see, so this reinforces the need for the ASF to release the latest version of Pootle which i assume is version 2.8.2, which has many fixes and additions in comparison to what i am using in 2.5.1.3. Thanks for the information, i will now inform the ASF about this.

**Comment by comradekingu** [comment]
@OfficalAhmad Are your issues attended in #5577 ?

**Comment by comradekingu** [comment]
@OfficalAhmad I have read your issue about 17 times. I can't understand what you mean.
Rewrite all of this, and provide some mockups. Make a new issue if the problem is present in the latest release.
