### ISSUE TITLE
GAMECHANGING SUGGESTION! A LIVE CHECKLISTER WHILST TRANSLATING!!

### ISSUE THREAD

**Issue by OfficalAhmad** [translate/pootle#6803]
So i was translating on a normal free day on Pootle, and i suddenly thought of an idea that i truly believe will make translating on Pootle so much more easier and fun, and most importantly, EFFICIENT.

So you all know that when you translate a word/phrase, you have to submit for the system to then check whether an accelerator is used when it's not meant to be used, or punctuation spacing needed, or numbers check (where wrong number/s is inserted). To check for the checklist to appear on a word, you would obviously revisit the word/phrase you translated for that, but that seems so much of a hassle when you translate and translate and translate.

SO....... I thought that what if maybe, just maybe, there could be an update to Pootle, where there is a live checklist. Let me explain. So instead of submitting and then revisiting to check for an errors from the checklist, why can it not be live, where it checks as we are typing (translating) and this makes it so much easier to check for errors, or needed changes, whilst translating. Also, some people may tend to just translate along the way, submitting and submitting, without even looking back to see if there are errors that need to be amended. With a live checklist, this would instantly inform the translator of an error/needed change and would potentially help make word translations more efficient. This could stop people from leaving words in errors because they just do not feel the urge to return back to it.

In essence, all i am saying is that when you translate, would it not be so much more easier if we just had a live checklist that checks for punctuation errors/addition, accelerators, numbers, and so on, whilst we are typing. I believe THIS would mark a significant improvement in the Pootle service, and help improve efficiency in translations.

--PLEASE CONSIDER THIS SUGGESTION, AS THIS WOULD DEFINITELY MARK A SIGNIFICANT CHANGE IN POOTLE'S TRANSLATION EFFICIENCY.

Thanks

**Comment by unho** [comment]
In the latest Pootle version when you try to submit a translation with failing critical checks Pootle will keep you in that string until you fix the errors. Of course the failing checks are displayed.

Thus I am closing this ticket.
