### ISSUE TITLE
Would like to be able to test translations on PLO website

### ISSUE THREAD

**Issue by scootergrisen** [translate/pootle#6806]
# Steps to reproduce:
Go to https://pootle.locamotion.org/da/

# Results (Expected/Actual):
Website is in english.
I want to test it in danish.

# Environment (i.e. 'pootle --version', DB, OS, Browser):
https://pootle.locamotion.org/about/ says:
Pootle 2.9.0rc1 [885ed53db] is powered by Translate Toolkit 2.2.5.

Are the translations not installed on PLO?
If not i would like them to be so its easier to see the strings i have translated in use.

**Comment by comradekingu** [comment]
Heia scootergrisen.
This is being overhauled and will be fixed.
