### ISSUE TITLE
.NET?

### ISSUE THREAD

**Issue by ShalokShalom** [translate/pootle#6807]
Your homepage got updated in 2013 the last time according to the footer, so this may have changed: Are resx files supported?

Hint: There is a link to the translate toolbox which says this one supports more formats. Zero information on this page about these other formats either.

Thanks a lot

**Comment by comradekingu** [comment]
http://docs.translatehouse.org/projects/pootle/en/stable-2.8.x/features/formats.html
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/index.html#commands-converters
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/index.html#formats

are relevant

**Comment by ShalokShalom** [comment]
This does not really answer my question yet

**Comment by phlax** [comment]
hi @ShalokShalom pootle will support anything that the translate toolkit can support - although you will need to convert your files to/from po on the way in/out of pootle.

ttk has support for resx here https://github.com/translate/translate/blob/master/translate/storage/resx.py 

i havent used it tho, so dont know how comprehensive or correct it is

**Comment by ShalokShalom** [comment]
Thanks a lot, that answers my question.
