### ISSUE TITLE
Improve support for XLIFF in Pootle

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#682]
Depends on:
* [x] translate/translate#743 oo2xliff marks all trans-units as approved
* [x] translate/translate#744 pomerge --mergecomments=yes does not work for xliff

*Version: 1.2.1*

Some issues mentioned by André Schnabel for translation OOo with XLIFF in Pootle:
(I'm dumping a copy of the URL in case it gets lost - check the URL for possible newer issues)

Feedback from the german l10n tema, using xliff-based pootle project for translating OOo 3.1. Process was:

    * merge new strings from OOo source to pootle using translate toolkit
    * download all strings from pootle (as zip)
    * filter new and updated strings using translate toolkit
    * distribute new / updted segments to translators and do translation using OTE
    * collect translations and review using OTE
    * merge translated strings back using translate toolkit 

merging new strings to pootle

    * xliff meta-info get lost (ask Aijin for more input)
    * Error: new segments get the status approved=yes (should be approved=no)
    * Error: updated segments keep the status approved=yes (should be approved=no)
    * Error/Wish: for updated segments, the old translation is moved to an alt-trans node and target content is removed from the trans-unit. Instead Old translation should be kept in the target, the transunit should be market as approved="no" and state="needs-review" (translate toolkit's xliff storage class actually supports this, but it is not used) 

    this can be considered as error, all statistics generated by translate toolkit / pootle will fail to report a correct number of fuzzy strings 

    * Wish: source file name and keyid (or par-id's) should be written to a context-group element (this is actually done when converting po-files to xliff) 

filter new / changed segments

    * Wish: there should be an option in the filter tools, so that no comment gets added to the segments. Actually all those automatic comments need to be removed by our translators, to be able to use own comments. 

merging translated strings to pootle

    * Error: notes on segments get lost during merge
    * Wish: Option to remove the "alt-trans" units from the merged file. As translation was already reviewed we don't need the alt-trans units anymore. Only way i know is to remove them manually in pootle.

**Comment by dwaynebailey** [comment]
Our model going forward is to have Pootle itself manage a set of states that make the most sense for general translation.  These should then map back to the states present in a format.  So rather than polluting Pootle with XLIFF states we'll rather have Pootle export correct states to XLIFF and allow Pootle to understand on its own terms states that might come from XLIFF.
