### ISSUE TITLE
Docker - demo credentials

### ISSUE THREAD

**Issue by dotZoki** [translate/pootle#6847]
I wanted to quickly try Pootle so I followed https://github.com/translate/pootle/wiki/Docker-setup-notes. Got it running but can not login. It doesn't create a demo user or I just can not find the credentials anywhere?

**Comment by phlax** [comment]
good point @dotZoki - ill add a user now

**Comment by dotZoki** [comment]
What would be a solution for now ? How to add default power user/admin to demo ?

**Comment by phlax** [comment]
im just fixing but the workaround would be to do

```
makey pootle createsuperuser
```

and then with the user you create

```
makey pootle verify_user $username
```

**Comment by dotZoki** [comment]
OK, I'll have to wait for fix.  Thanks for the effort! 

Running createsuperuser fails with error.

```
Starting pootle_redis_1 ... done
Starting pootle_elasticsearch_1 ... done
Building dev-sqlite
Step 1/7 : FROM translate/pootle:dev-build
ERROR: Service 'dev-sqlite' failed to build: manifest for translate/pootle:dev-build not found
```

**Comment by phlax** [comment]
@dotZoki that looks like the dev build - i edited the command above so not sure if you got the correct version there

**Comment by dotZoki** [comment]
I copied commands before you edited :) 
I can confirm that commands work as I can access the demo with the created user.

I guess you will close this issue after you done with the fix?

Thank you!
