### ISSUE TITLE
Is there a community somewhere?

### ISSUE THREAD

**Issue by erciccione** [translate/pootle#6893]
Have an answer from the developers team or the community is quite frustrating. Issues here get mostly ignored, same with the chats on gitter.

Is there a way to contact the Pootle team?

Sorry to use the issue tracker for this, but the contacts you linked to on the readme lead to desert rooms. see #6892

**Comment by phlax** [comment]
hi @erciccione there isnt a team in a day to day sense atm, but there are a few of us lurking around.

i dont have too much time for devving myself, but i will for sure help anyone willing to take up the baton

**Comment by phlax** [comment]
...which means yep the gitter channel is probs the best place

https://gitter.im/translate/pootle
