### ISSUE TITLE
Importing l10nmgr XML files?

### ISSUE THREAD

**Issue by dermatthias** [translate/pootle#6907]
The popular Typo3 extension l10nmgr ([https://extensions.typo3.org/extension/l10nmgr/](https://extensions.typo3.org/extension/l10nmgr/)) exports the content of Typo3 pages into a custom XML format that "_that can be used with all state-of-the-art localisation and translation tools_" (quoting the docs).

Is it possible to import these xml files into Pootle? 

I tried to import it but it looks like the format is not support. Neither did I find a way to convert it with Translate Toolkit. 

Any ideas or tips as how to import this (custom?) XML format?

Example l10nmgr XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TYPO3L10N [ <!ENTITY nbsp " "> ]>
<TYPO3L10N>
	<head>
		<t3_l10ncfg>6</t3_l10ncfg>
		<t3_sysLang>2</t3_sysLang>
		<t3_sourceLang></t3_sourceLang>
		<t3_targetLang>fr</t3_targetLang>
		<t3_baseURL>http://example.com/</t3_baseURL>
		<t3_workspaceId>0</t3_workspaceId>
		<t3_count>123</t3_count>
		<t3_wordCount>456</t3_wordCount>
		<t3_internal>			</t3_internal>
		<t3_formatVersion>1.2</t3_formatVersion>
		<t3_l10nmgrVersion>9.5.0</t3_l10nmgrVersion>
	</head>
	<pageGrp id="1" sourceUrl="http://example.com/index.php?id=1">
	  <data table="pages" elementUid="1" key="pages:NEW/2/1:title">Home</data>
    </pageGrp>
</TYPO3L10N>    
````

**Comment by unho** [comment]
O mér., 12 de feb. de 2020 ás 10:38, Matthias Schneider (<
notifications@github.com>) escribiu:

> The popular Typo3 extension l10nmgr (
> https://extensions.typo3.org/extension/l10nmgr/) exports the content of
> Typo3 pages into a custom XML format that "*that can be used with all
> state-of-the-art localisation and translation tools*" (quoting the docs).
>
Hi,
AFAICT this format is not supported neither by Translate Toolkit, nor by
Pootle. Of course we are open to new format contributions. Alternatively I
suggest you get in contact with Typo3 people so they can point you any of
those tools.


Greetings,
Leandro Regueiro
