### ISSUE TITLE
Status of that project?

### ISSUE THREAD

**Issue by buhtz** [translate/pootle#6920]
The last commit was in June 2022 (last year).

Is the project still maintained somehow?

**Comment by phlax** [comment]
not that im aware of - i would be happy to do some handover if there was anyone interested in taking it on

**Comment by phlax** [comment]
cc @unho

**Comment by buhtz** [comment]
> not that im aware of - i would be happy to do some handover if there was anyone interested in taking it on

You should mention that on top of your README.md file.

Let me ask: Is Pootle able to generate pot-files based on source files (e.g. py-files) on its own?

My problem with most translation platforms and tools is that I still have to generate the pot files myself.

**Comment by phlax** [comment]
pootle is essentially a web wrapper around translate tool kit (https://github.com/translate/translate) which is actively maintained

**Comment by buhtz** [comment]
> pootle is essentially a web wrapper around translate tool kit (https://github.com/translate/translate) which is actively maintained

I don't see that [Feature](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/features.html) in there.

**Comment by joanesinurrietasmartpm** [comment]
Coudn't install Pootle (2.8.2) either. Tried in Ubuntu and Debian environments and got the same error in both. Some commands from the installation instructions on the website doesn't work as expected.

I'm having this error when 'pip install Pootle' is executed.

AttributeError: 'UltraMagicString' object has no attribute 'endswith'

The error comes from django-sortedm2m package.

It looks like it doesn't have any support/updates anymore and dependency errors happen.

**Comment by TechnologyClassroom** [comment]
> pootle is essentially a web wrapper around translate tool kit (https://github.com/translate/translate) which is actively maintained

Weblate seems to be somewhat similar. [Python, Django, and Translate Toolkit are common between Pootle and Weblate](https://docs.weblate.org/en/latest/admin/install.html#python-dependencies). If Pootle does not plan to update to Python 3, directing people to Weblate might make sense.

**Comment by linghengqian** [comment]
- On the ASF side, https://translate.apache.org/ is still using Pootle 2.8.2, which ships with the old Translate Toolkit 2.2.5. It would indeed make more sense if Pootle could release a new version with Translate Toolkit 3.13.3, or point to a Pootle alternative that the Translate Toolkit community is using in their README.
- Furthermore, it would be nice if Pootle could publish a Docker Image on Docker Hub.
- update: As a follow-up, I opened https://github.com/apache/infrastructure-ideas/discussions/9 .

**Comment by linghengqian** [comment]
- I opened #6926 to fix the current issue.
