### ISSUE TITLE
Display PO/POT file headers

### ISSUE THREAD

**Issue by leuce** [translate/pootle#893]
Scenario: The POT file header contains useful information such as the version number and the POT file creation date.  The PO file header often contains useful information such as the names of translators and last update date/time.

Problem: There is no way for a user in Pootle to get the POT header and the only way to get the PO header is to download the PO file and view it in a text editor.

Solution: Have option to display POT and PO file headers somewhere.  The most obvious place for this may be as the first string (with the submission buttons deactivated so users can't change it or attempt to change it).  Alternatively it can be displayed in the position of the first string, but not with an edit box, so users won't think that there are cases in which they may be able to change its contents.

**Comment by dwaynebailey** [comment]
Closing, we don't want to tie Pootle to underlying formats which might or might not have their own meta data.  We'd rather fill in correct metadata without user intervention.
